<?php 
/* @var $request JO_Request */
$request = $this->getRequest();
$og_namespace = trim(JO_Registry::get('og_namespace'));
$og_recipe = trim(JO_Registry::get('og_recipe'));
if(!$og_recipe) {
	$og_namespace = '';
}
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="https://www.facebook.com/2008/fbml" lang="<?php echo JO_Registry::forceGet('config_language');?>" xml:lang="<?php echo JO_Registry::forceGet('config_language');?>">
	
	<?php if($og_namespace) { ?>
	<?php echo '<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# '.$og_namespace.': http://ogp.me/ns/fb/'.$og_namespace.'#">'?>
	<?php } else { ?>
	<head>
	<?php } ?>

		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=9" />
		<title><?php echo $this->placeholder('title');?></title>
		
		<?php if($this->placeholder('favicon')) { ?>
		<link rel="icon" href="<?php echo $this->placeholder('favicon');?>" type="image/x-icon" />
		<?php } ?>
	
		<?php if( in_array($request->getController(), array('pin', 'users')) ) { ?>
		<meta name="description" content="<?php echo $this->placeholder('pin_description')?$this->placeholder('pin_description'):$this->placeholder('description');?>" />
		<meta name="keywords" content="<?php echo $this->placeholder('keywords');?>" />
		<?php } ?>
		
		<?php /*?>
		<meta name="viewport" content="initial-scale=1.0,maximum-scale=1.0,user-scalable=no" />
		<?php */ ?>
		
		<?php if(JO_Registry::isRegistered('rss_feed')) { 
			$rss_feed = JO_Registry::get('rss_feed');
		?>
		<link rel="alternate" type="application/rss+xml" title="<?php echo $rss_feed['title'];?>" href="<?php echo $rss_feed['href'];?>" />
		<?php } ?>
		
		<base href="<?php echo $request->getBaseUrl();?>" />
		
		<!-- <link href="<?php //echo WM_Minify::minifyCSS('data/css/main.css');?>" rel="stylesheet" type="text/css" /> -->
		<link type='text/css' rel='stylesheet' href='data/css/mainZip.css?<?php echo rand(1,9999); ?>'></link>
		<!--<link type='text/css' rel='stylesheet' href='data/css/animate.css'></link>
         <link rel="stylesheet" type="text/css" href="data/css/bootstrap.min.css"/>
		<link rel="stylesheet" type="text/css" href="data/css/jquery-ui.css"/>-->
		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
		<script src="data/js/bootstrap.min.js" type="text/javascript"></script>

		<!-- <script type="text/javascript" src="<?php //echo WM_Minify::minifyJs('data/js/js_full.pack.js');?>"></script>  -->
		
		<script type='text/javascript' src='data/js/js_full.min.js'></script>
                
	<script type="text/javascript" src="data/js/banner/jquery-ui.js"></script>
	<script type="text/javascript" src="data/js/banner/banner.js"></script>
                
	
		<?php if($this->placeholder('pin_image')) { ?>
		<meta name="medium" content="image"/>
	    <meta http-equiv="imagetoolbar" content="no"/>
	
	    <link rel="image_src" href="<?php echo $this->placeholder('pin_image') ? $this->placeholder('pin_image') : $this->placeholder('site_logo');?>"/>
	    <link rel="canonical" href="<?php echo $this->placeholder('pin_url') ? $this->placeholder('pin_url') : $request->getBaseUrl();?>"/>
		<?php } ?>
		
		<?php if(JO_Registry::get('oauth_fb_key')) { ?>
		<meta property="fb:app_id" content="<?php echo JO_Registry::get('oauth_fb_key');?>"/>
	    <meta property="og:site_name" content="<?php echo $this->placeholder('site_name');?>"/>
	    <meta property="og:url" content="<?php echo $this->placeholder('pin_url') ? $this->placeholder('pin_url') : $request->getBaseUrl();?>"/>
	    <meta property="og:title" content="<?php echo $this->placeholder('board_title')?$this->placeholder('board_title'):$this->placeholder('title');?>"/>
	    <meta property="og:description" content="<?php echo $this->placeholder('pin_description') ? ($this->placeholder('pin_description')=='null'?'':$this->placeholder('pin_description')) : $this->placeholder('description');?>"/>
	    <meta property="og:image" content="<?php echo $this->placeholder('pin_image') ? $this->placeholder('pin_image') : $this->placeholder('site_logo');?>"/>
	    <?php if($og_namespace) { ?>
	    <meta property="og:type" content="<?php echo $og_namespace;?>:<?php echo $og_recipe;?>"/>
	    <?php } else { ?>
	    <meta property="og:type" content="website"/>
	    <?php } ?>
		<?php } ?>
		
		<?php echo $this->placeholder('inhead');?>
		
		<?php echo $this->placeholder('google_analytics');?>
		
	</head>
	
	<body<?php echo (!JO_Session::get('user[user_id]')?' id="not-login"':'');?> class="<?php echo $request->getController();?>-body">
<div id="boxes">
<div style="position:absolute;top:57px;left: 2px; display: none;font-size:14px;height:63px;width:900px" id="dialog" class="window">
<a href="#" class="close">Continuar >></a><br/><br/>
        amatteur utiliza cookies propias y de terceros para mejorar su experiencia de navegación y realizar tareas de analítica.
        <p>Si continúa navegando, entendemos que acepta nuestra <a href="http://www.amatteur.com/cookies">política de cookies</a>.</p>
</div>

<!-- Mask to cover the whole screen -->
<!--div style="width: 1478px; height: 100px; display: none; opacity: 0.8;" id="mask"></div-->
<div style="width: 1478px; height: 100px; display: none; opacity: 0;" id="mask"></div>
</div>
	
		<div id="fb-root"></div>
		<?php if(JO_Registry::get('oauth_fb_key')) { ?>
		<script type="text/javascript">
		    window.fbAsyncInit = function() {
		        FB.init({
		            appId: '<?php echo JO_Registry::get('oauth_fb_key');?>',
		            status: true,
		            cookie: true,
		            xfbml: true
		        });
		    };
		    (function() {
		        var e = document.createElement('script'); e.async = true;
		        e.src = document.location.protocol +
		        '//connect.facebook.net/en_US/all.js';
		        document.getElementById('fb-root').appendChild(e);
		    } ());
		</script>
		<?php } ?>
	
		<?php echo $this->placeholder('content');?>
        <?php if (JO_Session::get('user[user_id]'))
		{
			$user = Model_Users::getUser(JO_Session::get('user[user_id]'));
		?>
        	<div id="IntercomMask" title="<?php echo $this->translate('Envía tu feedback');?>"></div>
    		<script id="IntercomSettingsScriptTag">
		  window.intercomSettings = {
			// TODO: The current logged in user's email address.
			email: "<?php echo $user['email']; ?>",
			// TODO: The current logged in user's sign-up date as a Unix timestamp.
			created_at: <?php echo strtotime($user['date_added']); ?>,
			"Usuario": "<?php echo $user['username']; ?>",
			"Nombre": "<?php echo $user['firstname']; ?>",
			"Carpetas": "<?php echo $user['boards']; ?>",
			"Pins": "<?php echo $user['pins']; ?>",
			"Seguidores": "<?php echo $user['followers']; ?>",
			"user_hash": "<?php echo hash_hmac("sha256", $user['email'], "eDT2sTmXeXUZ-cQlR04MrTwcNIyJd_hbSPrbDG8n"); ?>",
			"widget": {"activator": "#IntercomDefaultWidget"},
			app_id: "c9edff59fbc58a1aeeb8e2eeceb3c0bf5a893259"
		  };
		</script>
<script>(function(){var w=window;var ic=w.Intercom;if(typeof ic==="function"){ic('reattach_activator');ic('update',intercomSettings);}else{var d=document;var i=function(){i.c(arguments)};i.q=[];i.c=function(args){i.q.push(args)};w.Intercom=i;function l(){var s=d.createElement('script');s.type='text/javascript';s.async=true;s.src='https://static.intercomcdn.com/intercom.v1.js';var x=d.getElementsByTagName('script')[0];x.parentNode.insertBefore(s,x);}if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}};})()</script>
		<?php } ?>
		

	</body>

<script src="data/js/jquery.cookie.js" type="text/javascript"></script>
<script type="text/javascript">
$(document).ready(function() 
{
	$("#IntercomMask").tooltip({
		position:{ my: "left+15 left", at: "right right" },
		  effect: "fade",
		  opacity: 0.7
     	 });
		 
	$("#IntercomMask").click(function (){
		$("#IntercomDefaultWidget").click();
	});
	
	
        var sesionActiva = $.cookie("sesionActiva");
	if(sesionActiva != 1) { 
                
                $.cookie("sesionActiva", 1);
                //alert("esta dentro");
                        
		var id = '#dialog';
	
		//Get the screen height and width
		var maskHeight = $(document).height();
		var maskWidth = $(window).width();
	
		//Set heigth and width to mask to fill up the whole screen
		$('#mask').css({'width':maskWidth,'height':maskHeight});
		
		//transition effect		
		$('#mask').fadeIn(1000);	
		$('#mask').fadeTo("slow",0);	
	
		//Get the window height and width
		var winH = $(window).height();
		var winW = $(window).width();
             
                winH = "58";
                winW = "2";
		//Set the popup window to center
		//$(id).css('top',  winH/2-$(id).height()/2);
                //$(id).css('left', winW/2-$(id).width()/2);
                $(id).css('top',  winH);
		$(id).css('left', winW);
	
		//transition effect
		$(id).fadeIn(2000); 	
	
                //if close button is clicked
                $('.window .close').click(function (e) {
                        //Cancel the link behavior
                        e.preventDefault();

                        $('#mask').hide();
                        $('.window').hide();
                });		

                //if mask is clicked
                $('#mask').click(function () {
                        $(this).hide();
                        $('.window').hide();
                });		
     }   
    
    
    
    });





</script>
</html>


