<span id="fader" class="mleft30" style="float: none">
	<span class="msgError"><span><?php echo $this->translate('Error 404!');?></span><i class="error_text"></i></span>
</span>
<br />

<div class="listing-holder left w981">
    <div class="clr space20"></div>
	
	
	<div class="messageBox">
		<p class="alert">
			<strong><?php echo $this->translate('URL, you are looking for can not be found');?></strong>
			<br />
			<?php echo JO_Request::getInstance()->getFullUrl();?>
		</p>
	</div>
	
	<br /><br />
	
	<p>
		<strong><?php echo $this->translate('We apologize for the inconvenience. Page can not be displayed for the following reasons:')?></strong>
	</p>
	
	<ul>
		<li><?php echo $this->translate('This page has been removed;');?></li>
		<li><?php echo $this->translate('This page has been moved or her name has been changed;');?></li>
		<li><?php echo $this->translate('If you typed the address manually, it may be a mistake in spelling it. Please check the spelling of your address correctly.');?></li>
	</ul>



	<div class="clear"></div>  	
</div>