<span id="fader" class="mleft30" style="float: none">
	<span class="msgError"><span><?php echo $this->translate('Error!');?></span><i class="error_text"><?php echo $this->translate('You have no permission');?></i></span>
</span>
<br />

<div class="listing-holder left w981">
    <div class="clr space20"></div>
	
	
	<div class="messageBox">
		<p class="alert">
			<strong><?php echo $this->translate('URL');?></strong>
			<br />
			<?php echo $this->fullUrl;?>
		</p>
	</div>
	
	<br /><br />
	
	<p>
		<strong><?php echo $this->translate('You have no permission to modify module')?>: <?php echo $this->moduleName;?></strong>
	</p>
	
	<br /><br /><br /><br />
	
	<div class="clear"></div>  	
</div>
