<div id="PinButton">
	<div id="ButtonHolder">
		<a onclick="Pins.error('<?php echo $this->translate('Drag me to the bookmarks bar');?>'); return false;" href="javascript:void((function(){var e=document.createElement('script');e.setAttribute('type','text/javascript');e.setAttribute('charset','UTF-8');e.setAttribute('src','<?php echo $this->getRequest()->getBaseUrl();?>data/pin/pinmarklet.js?r='+Math.random()*99999999);document.body.appendChild(e)})());" title="<?php echo $this->translate('Pin It');?>" id="BigPinItButton">
			<strong><?php echo $this->translate('Pin It');?></strong>
			<span></span>
		</a>
		<p id="ButtonInstructions"><?php echo $this->translate('← Add this link to your Bookmarks Bar');?></p>
	</div>
</div>