<?php if($this->successfu_edite) { ?>
<?php ob_start();?>
<script type="text/javascript">
$(document).ready(function(){
	$('#Success').slideDown();
});
</script>
<?php $this->placeholder('inhead', ob_get_clean());?>
<?php } ?>
<?php if($this->error) { ?>
<?php ob_start();?>
<script type="text/javascript">
$(document).ready(function(){
	Pins.error('<?php echo $this->error;?>');
});
</script>
<?php $this->placeholder('inhead', ob_get_clean());?>
<?php } ?>

	<div class="container">
	
	    <div id="header">
	
	        <h1 class="logo">
				<a href="<?php echo $this->baseUrl;?>">
					<img src="<?php echo $this->site_logo;?>" alt="<?php echo $this->getLayout()->placeholder('title');?>" />
				</a>
			</h1>
	
	    </div><!-- #header -->
		
		<form action="" method="post" id="invitationForm">
		
	    <div id="RequestContainer">
	
	        <div id="RequestInvitation">
	
	            <h1 style="margin-bottom:0px"><?php echo $this->translate('Sign up for an invite to join Amatteur');?></h1>
				<h3 style="text-align:center;font-weight:300;margin-bottom:20px;color:#ad9c9c"><?php echo sprintf($this->translate('or %slogin%s to your account'), '<a style="color:#a19191" href="'.$this->login.'">', '</a>');?></h3>
	            <div id="CompleteAccount">
	                <div class="Request">
	                    <ul>
	                        <li>
	                            <input type="text" class="" id="invitationBox" name="email" value="<?php echo $this->translate('Email');?>" />
	                            <label class="hide"><?php echo $this->translate('Email');?></label>
	                            <span class="fff"></span>
	                            <span style="display: none;" class="BoardNameError"></span>
	                        </li>
	                    </ul>
	                    <button type="submit" class="BigButton BlueButton"><strong><?php echo $this->translate('Request Invitation');?></strong><span></span></button>
	                	<div class="clear"></div>
					</div><!-- .Request -->
	            </div>
	
	        </div><!-- #RequestInvitation -->
	
	        <div class="hide" id="Success">
	            <p>
	            <?php echo $this->translate('Thanks! We\'ll send you an invite as soon as we can.');?>
	            <br>
	            <?php echo sprintf($this->translate('In the meantime, %s check out some pins %s.'), '<a href="'.$this->baseUrl.'">', '</a>');?>
	            </p>
	        </div><!-- #Success -->
	
	    </div><!-- #RequestContainer -->
	    
	    </form>
	
	</div>
						
	<div class="clear"></div>