<?php 
	$module = $this->getRequest()->getModule();
?>

<div class="info_line top">
	<h3 class="fleft title">
		<img alt="" src="cms/<?php echo $module;?>/images/language.png">
		<?php echo $this->translate('Languages Manager');?>
	</h3>
	
	<?php if($this->successfu_edite) { ?>
	<span id="fader" class="fleft mleft30"><span class="msgOk"><span><?php echo $this->translate('Successfully!');?></span><?php echo $this->translate('Information was successfully changed!');?></span></span>
	<script type="text/javascript"> 
	// <![CDATA[
	$(document).ready(function() {       
		setTimeout(function() {
			$("#fader").customFadeOut("slow" ,    
			function() {       
				$("#fader").remove();  
			});
		},
		4000);
	});
	// ]]>
	</script>
	<?php } ?>
	
	<div class="fright mtop3">
		<a class="button" href="<?php echo $module;?>/languages/create/"><?php echo $this->translate('Add new');?></a>
	</div>
	<div class="clear"></div>
</div>



<p class="info">
	<?php echo $this->translate('Languages Manager');?>.<br>
	<strong><?php echo $this->translate('Note: If you delete an entry, information will be lost.');?></strong>
</p>

<table cellspacing="0" cellpadding="0" class="display dragable_table" id="sort_order">
	<thead>
		<tr class="nodrop nodrag">
			<th width="20" class="left">#</th>
			<th class="left"><?php echo $this->translate('Name');?></th>
			<th width="50"><?php echo $this->translate('Status');?></th>
			<th width="50"><?php echo $this->translate('Edit');?></th>
			<th width="50"><?php echo $this->translate('Delete');?></th>
		</tr>
	</thead>
	<tbody>
	<?php if($this->languages) { ?>
	<?php foreach($this->languages AS $language) { ?>
		<tr id="<?php echo $language['language_id'];?>">
			<td><?php echo $language['language_id'];?>.</td>
			<td>
				<?php echo $language['name'];?> 
				<?php if($language['is_set']) { ?>
				<span class="is_set"><strong>( <?php echo $language['is_set'];?> )</strong></span>
				<?php } ?>
			</td>
			<td align="center">
				<?php if($language['is_set'] && $language['status']) { ?>
				<a href="javascript:void(0);" onclick="alert('<?php echo $this->translate('You can not disable this language. It is the default language!');?>');">
					<img src="cms/<?php echo $module;?>/images/<?php echo ($language['status'] ? 'yes.png' : 'no.png');?>" class="tooltip"  alt="" title="<?php echo ($language['status'] ? $this->translate('Active') : $this->translate('Inactive'));?>" />
				</a>
				<?php } else { ?>
				<a href="javascript:void(0);" onclick="changeStatus(<?php echo $language['language_id'];?>);">
					<img src="cms/<?php echo $module;?>/images/<?php echo ($language['status'] ? 'yes.png' : 'no.png');?>" class="tooltip"  alt="" title="<?php echo ($language['status'] ? $this->translate('Active') : $this->translate('Inactive'));?>" />
				</a>
				<?php } ?>
			</td>
			<td align="center"><a href="<?php echo $module;?>/languages/edit/?id=<?php echo $language['language_id'];?>"><img title="<?php echo $this->translate('Edit');?>" alt="" class="tooltip" src="cms/<?php echo $module;?>/images/edit.png"></a></td>
			<td align="center">
				<?php if($language['is_set']) { ?>
				<a onclick="alert('<?php echo $this->translate('You can not delete that language. It is the default language!');?>');" href="javascript:void(0);"><img title="<?php echo $this->translate('Delete');?>" alt="" class="tooltip" src="cms/<?php echo $module;?>/images/delete.png"></a>
				<?php } else { ?>
				<a id="item_<?php echo $language['language_id'];?>" class="delete" href="javascript:void(0);"><img title="<?php echo $this->translate('Delete');?>" alt="" class="tooltip" src="cms/<?php echo $module;?>/images/delete.png"></a>
				<?php } ?>
			</td>
		</tr>
	<?php } ?>
	<?php } else { ?>
		<tr class="nodrop nodrag">
			<td colspan="5">
				<div class="msgAlert"><span><?php echo $this->translate('Attention!');?></span><?php echo $this->translate('No records found ...');?></div>
			</td>
		</tr>
	<?php } ?>
	</tbody>
</table>

<script type="text/javascript"> 
// <![CDATA[
$(document).ready(function() {       
	$('.dragable_table').tableDnD({
        onDrop: function(table, row) {
	        $.post('<?php echo $module;?>/languages/sort_order/', $.tableDnD.serialize(), function(data){
				if(data) {
					if($("#fader").size()) {
						$("#fader").remove();  
					}
					$('.info_line.top .title').after('<div id="fader" class="fleft mleft30"><div class="msgOk"><span><?php echo $this->translate('Successful!');?></span><?php echo $this->translate('Information was successfully changed!');?></div></div>');
					setTimeout(function() {
						$("#fader").customFadeOut("slow" ,    
						function() {       
							$("#fader").remove();  
						});
					},
					2000);
				}
		    });
	    }
	});

	$('a.delete').click(function (e) {
        if (confirm(lang.confirm)) {
            e.preventDefault();
            var parent = $(this).parents('tr');
            $.ajax({
                type: 'post',
                url: "<?php echo $module;?>/languages/delete/",
                data: 'id=' + $(this).attr('id').replace('item_', ''),
                beforeSend: function () {
                    parent.animate({
                        'backgroundColor': '#FFBFBF'
                    }, 400);
                },
                success: function () {
                    parent.fadeOut(400, function () {
                        parent.remove();
                    });
                }
            });
        }
    });
});

changeStatus = function(id) {
	if(id == <?php echo JO_Registry::get('config_language_id');?>) {
		alert('<?php echo $this->translate('You can not disable this language. It is the default language!');?>');
		return;
	}
	$.ajax({
        type: 'post',
        url: "<?php echo $module;?>/languages/changeStatus",
        data: 'id=' + id,
        beforeSend: function () {
			$('#'+id).animate({
                'backgroundColor': '#FFBFBF'
            }, 400);
        },
        success: function () {
        	$.get(window.location.href, function(data){
        		$('#'+id).html($(data).find('#'+id).html());
        		setTimeout(function(){
        			$("#"+id+"").animate({'backgroundColor': 'transparent'}, 400).find('.tooltip').simpletooltip();
        		}, 500);
        	});
        }
	});
};

// ]]>
</script>