<?php 
	$module = $this->getRequest()->getModule();
?>

<form name="admin_form" id="admin_form" method="post" action="">

	<div class="info_line top">
		<h3 class="fleft title">
			<img alt="" src="cms/<?php echo $module;?>/images/language.png">
			<?php echo $this->translate('Languages Manager');?>
		</h3>
		
		<span id="fader" class="fleft mleft30" style="display:none;">
			<span class="msgError"><span><?php echo $this->translate('Error!');?></span><i class="error_text"></i></span>
		</span>
		
		<div class="fright mtop3">
			<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<a class="button" href="<?php echo $module;?>/languages/"><?php echo $this->translate('Cancel');?></a>
		</div>
		<div class="clear"></div>
	</div>

	<div class="clear"></div>
	
	<table cellspacing="0" cellpadding="0" class="formtable">
		<tbody>
			<tr>
				<td width="150"><?php echo $this->translate('Name');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
				<td>
					<input type="text" title="<?php echo $this->translate('Please enter a name');?>" size="15" value="<?php echo $this->name;?>" class="inputbox required"  name="name" />
        			&nbsp;&nbsp; <img title="<?php echo $this->translate('Name the language');?>" class="tooltip" alt="Tip" src="cms/<?php echo $module;?>/images/sinfo.gif">
        		</td>
			</tr>
			<tr>
				<td width="150"><?php echo $this->translate('Code');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
				<td>
					<input type="text" title="<?php echo $this->translate('Please enter a code');?>" size="15" value="<?php echo $this->code;?>" class="inputbox required"  name="code" />
        			&nbsp;&nbsp; <img title="<?php echo $this->translate('eg: en. Do not change if this is your default language.');?>" class="tooltip" alt="Tip" src="cms/<?php echo $module;?>/images/sinfo.gif">
        		</td>
			</tr>
			<tr>
				<td width="150"><?php echo $this->translate('Locale');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
				<td>
					<input type="text" title="<?php echo $this->translate('Please enter the local value');?>" size="55" value="<?php echo $this->locale;?>" class="inputbox required"  name="locale" />
        			&nbsp;&nbsp; <img title="<?php echo $this->translate('Local values ​​of the language. Used to automatically identify the language of the user.');?>" class="tooltip" alt="Tip" src="cms/<?php echo $module;?>/images/sinfo.gif">
        		</td>
			</tr>
			<tr>
				<td width="150"><?php echo $this->translate('Local area');?>:</td>
				<td>
					<select name="locale_territory" class="select">
						<?php foreach($this->locale_territories AS $locale) { ?>
						<?php if($this->locale_territory == $locale['code']) { ?>
						<option selected="selected" value="<?php echo $locale['code'];?>"><?php echo $locale['name'];?></option>
						<?php } else { ?>
						<option value="<?php echo $locale['code'];?>"><?php echo $locale['name'];?></option>
						<?php } ?>
						<?php } ?>
					</select>
					&nbsp;&nbsp; <img title="<?php echo $this->translate('Local area. Serves to determine the Region');?>" class="tooltip" alt="Tip" src="cms/<?php echo $module;?>/images/sinfo.gif">
        		</td>
			</tr>
			<tr>
				<td width="150"><?php echo $this->translate('Flag');?>:</td>
				<td>
					<select name="image" class="select" onchange="changeFlag(this.value);" onkeyup="changeFlag(this.value);">
						<?php foreach($this->flags AS $flags) { ?>
						<?php if($this->image == $flags) { ?>
						<option selected="selected" value="<?php echo $flags;?>"><?php echo $flags;?></option>
						<?php } else { ?>
						<option value="<?php echo $flags;?>"><?php echo $flags;?></option>
						<?php } ?>
						<?php } ?>
					</select>
					<?php if($this->image) { ?>
					&nbsp;&nbsp; <img id="flag_select" src="cms/images/flags/<?php echo $this->image;?>">
					<?php } else { ?>
					&nbsp;&nbsp; <img id="flag_select" src="cms/<?php echo $module;?>/images/sinfo.gif">
					<?php } ?>
        		</td>
			</tr>
			<tr>
				<td width="150"><?php echo $this->translate('Status');?>:</td>
				<td>
					<select name="status" class="select">
						<?php if($this->status) { ?>
						<option selected="selected" value="1"><?php echo $this->translate('Active');?></option>
						<option value="0"><?php echo $this->translate('Inactive');?></option>
						<?php } else { ?>
						<option value="1"><?php echo $this->translate('Active');?></option>
						<option selected="selected" value="0"><?php echo $this->translate('Inactive');?></option>
						<?php } ?>
					</select>
        		</td>
			</tr>
		</tbody>
	</table>
		
	<div class="info_line bottom">
		<div class="fright mtop3">
			<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<a class="button" href="<?php echo $module;?>/languages/"><?php echo $this->translate('Cancel');?></a>
		</div>
		<div class="clear"></div>
	</div>
		
</form>

<script type="text/javascript">
function changeFlag(flag) {
	$('#flag_select').attr('src', 'cms/images/flags/' + flag);
}
</script>