<?php 
	$module = $this->getRequest()->getModule();
?>
<form name="admin_form" id="admin_form" method="post" action="">

<div class="info_line top">
	<h3 class="fleft title">
		<img alt="" src="cms/<?php echo $module;?>/images/page_white_link.png">
		<?php echo $this->translate('Information & pages Manager');?> <?php echo ($this->parent_title ? '» ' . $this->parent_title : '');?>
	</h3>
	
	<span id="fader" class="fleft mleft30" style="display:none;">
		<span class="msgError"><span><?php echo $this->translate('Error!');?></span><i class="error_text"></i></span>
	</span>
	
	<div class="fright mtop3">
		<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
		<a class="button" href="<?php echo $this->cancel_url;?>"><?php echo $this->translate('Cancel');?></a>
		<span id="swf_upload" style="display:none;">
			<a class="button"><span id="swf_btn" ><?php echo $this->translate('Upload images');?></span></a>
		</span>
	</div>
	<div class="clear"></div>
</div>

<div class="clear"></div>

	<div class="tabs mtop3">
		<ul>
			<li><a href="#tab_data"><?php echo $this->translate('General');?></a></li> 
			<li><a href="#tab_general"><?php echo $this->translate('Data');?></a></li>
			<li><a href="#tab_seo"><?php echo $this->translate('SEO');?></a></li>
			<?php /* ?>
			<li><a href="#tab_images"><?php echo $this->translate('Images');?></a></li>
			<?php */ ?>
		</ul> 
		<div class="clear"></div>
	</div>
	
	
		<div id="tab_data">
			<table cellspacing="0" cellpadding="0" class="formtable">
				<tbody>
					<tr>
						<td width="150"><?php echo $this->translate('Title');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
						<td>
							<input type="text" size="55" title="<?php echo $this->translate('Please enter a title');?>" value="<?php echo $this->title;?>" class="inputbox required" name="title" />
	        				&nbsp;&nbsp; <img title="<?php echo $this->translate('Page Title');?>" class="tooltip" alt="Tip" src="cms/<?php echo $module;?>/images/sinfo.gif">
	        			</td>
					</tr>
					<tr>
						<td><?php echo $this->translate('Description');?>:</td>
						<td>
							<textarea rows="4" cols="53" name="description" class="valid ckeditor_replace"><?php echo $this->description;?></textarea>
	        			</td>
					</tr>
					<tr>
						<td colspan="2">
							<p class="info">
								<?php echo $this->translate('Note:');?><br>
								<strong><?php echo $this->translate('To display the pinit button on page write: {pinit_button}');?></strong>
								<br />
								<strong><?php echo $this->translate('To display the pinit button wor web on page write: {pinit_button_for_web}');?></strong>
							</p>
	        			</td>
					</tr>
				</tbody>
			</table>
		</div>
		<div id="tab_general">
			<table cellspacing="0" cellpadding="0" class="formtable">
				<tbody>
					<tr>
						<td width="150"><?php echo $this->translate('Status');?>:</td>
						<td>
							<input type="hidden" name="in_footer" value="0" />
							<select name="status" class="select">
								<?php if($this->status) { ?>
								<option selected="selected" value="1"><?php echo $this->translate('Active');?></option>
								<option value="0"><?php echo $this->translate('Inactive');?></option>
								<?php } else { ?>
								<option value="1"><?php echo $this->translate('Active');?></option>
								<option selected="selected" value="0"><?php echo $this->translate('Inactive');?></option>
								<?php } ?>
							</select>
	        			</td>
					</tr>
					<?php /* ?>
					<tr>
						<td><?php echo $this->translate('Show in the footer');?>:</td>
						<td>
							<select name="in_footer" class="select">
								<?php if($this->in_footer) { ?>
								<option selected="selected" value="1"><?php echo $this->translate('Yes');?></option>
								<option value="0"><?php echo $this->translate('No');?></option>
								<?php } else { ?>
								<option value="1"><?php echo $this->translate('Yes');?></option>
								<option selected="selected" value="0"><?php echo $this->translate('No');?></option>
								<?php } ?>
							</select>
	        			</td>
					</tr>
					<?php */ ?>
				</tbody>
			</table>
		</div>
		<div id="tab_seo">
			<table cellspacing="0" cellpadding="0" class="formtable">
				<tbody>
					<tr>
						<td width="150"><?php echo $this->translate('Meta title');?>:</td>
						<td>
							<input type="text" size="55" value="<?php echo $this->meta_title;?>" class="inputbox" name="meta_title" />
	        			</td>
					</tr>
					<tr>
						<td><?php echo $this->translate('Meta description');?>:</td>
						<td>
							<textarea rows="4" cols="53" name="meta_description" class="valid"><?php echo $this->meta_description;?></textarea>
	        			</td>
					</tr>
					<tr>
						<td><?php echo $this->translate('Meta keywords');?>:</td>
						<td>
							<textarea rows="4" cols="53" name="meta_keywords" class="valid"><?php echo $this->meta_keywords;?></textarea>
	        			</td>
					</tr>
					<tr>
						<td><?php echo $this->translate('SEO query');?>: </td>
						<td>
							<input type="text" size="55" value="<?php echo $this->keyword;?>" class="inputbox" name="keyword" />
			        		&nbsp;&nbsp; <img title="<?php echo $this->translate('Link to be used for navigation');?>" class="tooltip" alt="Tip" src="cms/<?php echo $module;?>/images/sinfo.gif">
			        	</td>
					</tr>
				</tbody>
			</table>
		</div>
		
		<?php /* ?>
		<div id="tab_images">
		
			<div id="gallery" title="<?php echo $this->translate('Upload images');?>">
				<div id="flash_interface">
					<ul id="flash_files_list"></ul>
				</div>
			</div>
		
			<ul id="galleryrow">
				<?php if($this->images) { ?>
				<?php foreach($this->images AS $image) { ?>
				<li id="item_<?php echo $image['image_id'];?>">
					<div class="controller">
						<img class="image_src" src="<?php echo $image['thumb'];?>" alt="<?php echo $image['title'];?>" />
						<span class="control">
							<a href="javascript:void(0);" class="sort">
								<img src="cms/<?php echo $module;?>/images/drag.png" alt="" title="<?php echo $this->translate('Sort');?>" class="tooltip" />
							</a>
							<a href="javascript:void(0);" onclick="imageEdit(<?php echo $image['image_id'];?>);">
								<img src="cms/<?php echo $module;?>/images/edit.png" alt="" title="<?php echo $this->translate('Edit');?>" class="tooltip"/>
							</a>
							<a href="<?php echo $image['image'];?>" title="<?php echo $this->translate('View');?>" rel="prettyPhoto[pp_gal]">
								<img src="cms/<?php echo $module;?>/images/search.png" alt="<?php echo $image['title'];?>" title="<?php echo $this->translate('View');?>" class="tooltip view" />
							</a>
							<a href="javascript:void(0);" class="delete" onclick="geleteImage('<?php echo $image['image_id'];?>');">
								<img src="cms/<?php echo $module;?>/images/delete.png" alt="" title="<?php echo $this->translate('Delete');?>" class="tooltip" />
							</a>
						</span>
					</div>
				</li>
				<?php } ?>
				<?php } ?>
			</ul>
			
			<div class="clear"></div>
			
		</div>
		<?php */ ?>
		
		<div class="info_line bottom">
			<div class="fright mtop3">
				<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
				<a class="button" href="<?php echo $this->cancel_url;?>"><?php echo $this->translate('Cancel');?></a>
			</div>
			<div class="clear"></div>
		</div>
		
		<div class="clear"></div>
		
	</form>
	
<script type="text/javascript"> 
	$(document).ready(function(){
		$(".tabs ul").idTabs(); 
		$(".tabs ul li a").click(function(){
			if($(this).attr('href') == '#tab_images') {
				$('#swf_upload').show();
			} else {
				$('#swf_upload').hide();
			}
		});
	});
</script>


<script type="text/javascript"> 
// <![CDATA[
$(document).ready(function () {

    imagesUploadOptions();
    dragPictireStart();

    window.upload_errors = 0;
    
    $("#gallery").dialog({
		bgiframe: true, 
		autoOpen: false, 
		width:715, 
		height:250,  
		zindex:9998, 
		modal: true,
		close: function() {
			$('#flash_files_list li').remove();
			window.upload_errors = 0;
    	}
	});
    
});

function imagesUploadOptions() {
	$("ul#galleryrow li").unbind('hover').hover(function () {
        $(this).find("span.control").fadeIn(400);
    }, function () {
        $(this).find("span.control").fadeOut(600);
    });

	$("a[rel^='prettyPhoto']").prettyPhoto({theme: 'facebook'});
}

function dragPictireStart() {
	$("#galleryrow").dragsort({ dragSelector: "div.controller .sort", dragEnd: saveOrder, placeHolderTemplate: "<li class='placeHolder'><div></div></li>" });
}

function saveOrder() {
	var data = $("#galleryrow li").map(function() { return $(this).attr("id").replace('item_', ''); }).get();
    $.post("<?php echo $module;?>/pages/sortImage?id=<?php echo $this->page_id;?>", { "ids[]": data }, function(data){
    	$('.message_holder').html('');
		$('.message_holder').html('<div id="fader"><div class="msgOk"><span><?php echo $this->translate('Successfully!');?></span>'+data+'</div></div>');
		setTimeout(function() {
			$("#fader").customFadeOut("slow" ,    
			function() {       
				$("#fader").remove();  
			});
		},
		2000);
    });
}

function geleteImage(id) {
	if (confirm(lang.confirm)) {
		$.ajax({
            type: 'post',
            url: "<?php echo $module;?>/pages/deleteImage?id=<?php echo $this->page_id;?>",
            data: 'id=' + id,
            beforeSend: function () {
				$('#item_'+id).animate({
                    'backgroundColor': '#FFBFBF'
                }, 400);
            },
            success: function (data) {
                if(data == 'ok') {
            		$('#item_'+id).animate({width: 0}, 1000, function(){ $(this).remove(); });
                } else {
					alert(data);
                }
            }
        });
	}
}

function imageEdit(id) {
	$('#dialog_edite').remove();
	$('#content').prepend('<div id="dialog_edite" style="padding: 3px 0px 0px 0px;"><iframe id="frameee" src="<?php echo $module;?>/pages/editeImageInfo/?id=' + encodeURIComponent(id) + '" style="padding:0; margin: 0; display: block; width: 100%; height: 100%;" frameborder="no" scrolling="auto"></iframe></div>');
	$('#dialog_edite').dialog({
		title: '<?php echo $this->translate('Edit');?>',
		close: function (event, ui) {},	
		bgiframe: false,
		width: 700,
		height: 400,
		resizable: false,
		modal: true,
		buttons: {
			"Запис": function() {
				var data = $('#frameee').contents().find('#image_info').serialize();
				var dial = this;
				$.post('<?php echo $module;?>/pages/editeImageInfo/?id='+id, data, function(result) {
					if(result == 'ok') {
						$( dial ).dialog( "close" );
					} else {
						alert('<?php echo $this->translate('An unknown error!');?>');
					}
				});
			},			
			"Отказ": function() {
				$( this ).dialog( "close" );
			}
		}
	});
}
// ]]>
</script>

<link href="cms/assets/prettyPhoto.css" rel="stylesheet" type="text/css" />

<script type="text/javascript" src="cms/assets/jquery.prettyPhoto.js"></script>
<script type="text/javascript" src="cms/<?php echo $module;?>/assets/jquery.dragsort.js"></script>
<script type="text/javascript" src="cms/<?php echo $module;?>/assets/swfupload/swfupload.js"></script>
<script type="text/javascript" src="cms/<?php echo $module;?>/assets/jquery.swfupload.js"></script>
<script type="text/javascript" src="<?php echo $module;?>/pages/swfConfig?id=<?php echo $this->page_id;?>"></script>