<div id="wrapper">
	<p class="e404">
		<a href="<?php echo $this->getRequest()->getBaseUrl();?>">
			<img src="data/images/error_406_icon.png" class="fade">
		</a>
	</p>
	<div class="textbox">
		<h1>Error with licence!</h1>
		<p>The link "Powered by" was removed from the header! Please restore the link</p>
		<p>or</p>
		<p><a href="http://pintastic.com/" onclick="target='_blank'" class="link">Contact Pintastic.com support</a></p>
	</div>
</div>