<p>
	<strong><?php echo $this->translate('New delete account request from user: ');?></strong>
</p>
<p>
	<?php echo $this->translate('User id');?>: <?php echo JO_Session::get('user[user_id]')?>
</p>
<p>
	<?php echo $this->translate('Username');?>: <?php echo JO_Session::get('user[username]')?>
</p>
<p>
	<?php echo $this->translate('Firstname');?>: <?php echo JO_Session::get('user[firstname]')?>
</p>
<p>
	<?php echo $this->translate('Lastname');?>: <?php echo JO_Session::get('user[lastname]')?>
</p>