<p><?php echo sprintf($this->translate('Hi %s'), $this->user_info['firstname']);?>,</p>

<p>
	<?php 
	echo sprintf(
		$this->translate('Got request for forgotten password in %s.'), 
		'<a href="'.$this->base_href.'" target="_blank">'.$this->header_title . '</a>');
	?>
</p>
<p>
	<?php 
	echo sprintf(
		$this->translate('If you make this request, follow %s this link %s.'),
		'<a href="'.$this->forgot_password_href.'" target="_blank">', 
		'</a>');
	?>
</p>
<p>
	<?php 
	echo sprintf(
		$this->translate('Your new password is %s'),
		'<b>'.$this->new_password.'</b>');
	?>
</p>
<p>
	<?php 
	echo $this->translate('If you have not made an inquiry just ignore this letter.');
	?>
</p>

<div>
	<?php echo html_entity_decode(JO_Registry::get('mail_footer'), ENT_QUOTES, 'utf-8');?>
</div>