<div class="short" id="footer">
            
        	<div id='floader' style="display:none">
        		<img src='data/images/ajax-loader.gif' style="margin-top:30px;height:30px;float:left;"/>
        	</div>
	<p class="scrolltotop"><a href="#body" class="easyscroll" title="<?php echo $this->translate('Scroll to Top');?>"><?php //echo $this->translate('Scroll to Top');?></a></p>    
               
        </div>