<div class="boxeswrapper">
	<div id="boxes" class="boxes-absolute">
		<div class="box">
			<div class="left-corner">
				<div class="bottom-corner">
					<div class="right-corner">
						<div class="apps">
							<h4 class="title">App-tastick</h4>
							<ul class="list">
								<li><a href="#"><img src="data/images/thumb-10.jpg" alt="App" /></a></li>
								<li><a href="#"><img src="data/images/thumb-10.jpg" alt="App" /></a></li>
								<li class="last"><a href="#"><img src="data/images/thumb-10.jpg" alt="App" /></a></li>
								<li><a href="#"><img src="data/images/thumb-10.jpg" alt="App" /></a></li>
								<li><a href="#"><img src="data/images/thumb-10.jpg" alt="App" /></a></li>
								<li class="last"><a href="#"><img src="data/images/thumb-10.jpg" alt="App" /></a></li>
								<li><a href="#"><img src="data/images/thumb-10.jpg" alt="App" /></a></li>
								<li><a href="#"><img src="data/images/thumb-10.jpg" alt="App" /></a></li>
								<li class="last"><a href="#"><img src="data/images/thumb-10.jpg" alt="App" /></a></li>
							</ul>
							<div class="clear"></div>
							<p class="follow"><a href="#">Follow</a></p>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="box">
			<div class="left-corner">
				<div class="bottom-corner">
					<div class="right-corner">
						<div class="apps">
							<h4 class="title">Also from</h4>
							<h5 class="subtitle">livlifetoo.blogspot.com</h5>
							<ul class="list">
								<li><a href="#"><img src="data/images/thumb-10.jpg" alt="App" /></a></li>
								<li><a href="#"><img src="data/images/thumb-10.jpg" alt="App" /></a></li>
								<li class="last"><a href="#"><img src="data/images/thumb-10.jpg" alt="App" /></a></li>
								<li><a href="#"><img src="data/images/thumb-10.jpg" alt="App" /></a></li>
								<li><a href="#"><img src="data/images/thumb-10.jpg" alt="App" /></a></li>
								<li class="last"><a href="#"><img src="data/images/thumb-10.jpg" alt="App" /></a></li>
							</ul>
							<div class="clear"></div>
						</div>
					</div>
				</div>
			</div>
		</div>	
	</div>
</div>