<div class="ranking">
    <div class='rankingPosition'>
        <h3><span><?php echo $this->position; ?>º Puesto </span></h3>
    </div>
    <div class='rankingImageText'>  
        <div class='rankingImage'>            
            <!--a style="background-image: url(<?php echo $this->pin['thumb']; ?>); filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='<?php echo $this->pin['thumb']; ?>',sizingMethod='scale');-ms-filter: \"progid:DXImageTransform.Microsoft.AlphaImageLoader(src='<?php echo $this->pin['thumb']; ?>',sizingMethod='scale')\";" class="PersonImage ImgLink" href="<?php echo $this->pin['href']; ?>"></a-->
            <a href="<?php echo $this->pin['href']; ?>"><img src="<?php echo $this->pin['thumb']; ?>" /></a>
        </div>

        <div class="rankingInfo">
            <h3><a href="<?php echo $this->pin['href']; ?>"><?php echo Helper_Pin::descriptionFix($this->pin['description']); ?></a> - por <a href="<?php echo $this->author['profile']; ?>"><?php echo $this->author['fullname']; ?></a> </h3>
            <br/>
            <div class="stats">
                
                <h1><?php echo $this->pin['likes']; ?> MeGusta</h1>
            </div>

        </div>
    </div>
</div>
