


<div id="create_new_pin">
	<div id="content-holder">
		<div id="emailpin">
			<form action="<?php echo $this->from_url;?>" method="post">
				
				<div class="hide">
					<input type="hidden" name="price" value="<?php echo $this->price;?>">
				</div>
				
				<div class="imageholder image-carousel">
					<img src="data/images/ajax-loader.gif" alt="" />
					<span class="price"></span>
				</div>
				<div class="left w335px">
					<p class="ntp">
						<label for="board_id" class="hide"><?php echo $this->translate('Board');?>:<br></label>
						
						<select name="board_id" id="board_id">
							<?php foreach($this->boards AS $board) { ?>
							<option value="<?php echo $board['board_id'];?>"><?php echo $board['title'];?></option>
							<?php } ?>
						</select>
					</p>
					<p>
						<label for="message" class="hide"><?php echo $this->translate('Message');?>:<br></label>
						<textarea name="message" id="message" rows="5" cols="30"><?php echo $this->description;?></textarea>
					</p>
					<p class="text_counter"></p>
					<p class="submit"><input type="submit" value="<?php echo $this->translate('Pinit');?>"></p>
					<div class="clear"></div>
				</div>
				<div class="clear"></div>
			</form>
		</div>
	</div>
</div>


<?php $key = str_replace('.','',microtime(true));?>
<script type="text/javascript">
$(document).ready(function(){

	regExPrice.addExpresionLine($('#message').html(), true);
	
	$('#message').jqEasyCounter({
		holder: 'p.text_counter',
		maxChars: 500,
		maxCharsWarning: 470,
		template: '{count}'
	}).bind("keydown keyup keypress focus paste",function() {
		regExPrice.addExpresionLine(this.value);
		if($.trim(this.value)) {
			$('#emailpin .submit input').removeClass('disabled').attr('disabled', false);
		} else {
			$('#emailpin .submit input').addClass('disabled').attr('disabled', true);
		}
		regExPrice.addExpresionLine(this.value, false);
	});

	if($.trim($('#message').val())) {
		$('#emailpin .submit input').removeClass('disabled').attr('disabled', false);
	} else {
		$('#emailpin .submit input').addClass('disabled').attr('disabled', true);
	}

	$('#board_id').selectBox().selectBox('onReady', selectBoxCallback);

	function selectBoxCallback(){

		if($('#newBoardCreate<?php echo $key;?>').size() > 0) return;
		
		newbord = $('<p><input name="newboard" value="<?php echo $this->translate('Create New Board')?>" class="newboardcreator" id="newboardcreator<?php echo $key;?>" /></p>').unbind('keydown').bind('keydown', function(e){
			if (e.keyCode == 13) { // enter key
                return false
            }
		});
		button = $('<input type="button" class="newboardcreator2">').attr('id','newboardcreator2<?php echo $key;?>').val('<?php echo $this->translate('Create')?>').unbind('click').bind('click',function(){
			$.post('<?php echo $this->createBoard;?>', $('#newBoardCreate<?php echo $key;?>').serialize(),function(data){
				if(data.data) {
					board_id_h = $('#board_id');
					board_id_h.find('option').attr('selected', false);
					board_id_h.append('<option value="'+data.data.board_id+'" selected="selected">'+data.data.title+'</option>')
					.selectBox('destroy').selectBox().selectBox('onReady', selectBoxCallback);
				} else if(data.error) {
					alert(data.error);
				} else {
					alert(data);
				}			

			}, 'json');
			return false;
		});
		newsubmit = $('<p>').addClass('submit').append(button)
		bform = $('<form action="" method="post" id="newBoardCreate<?php echo $key;?>">').append(newbord).append(newsubmit);
		new_board = $('<li>').addClass('createBoard').append(bform).append('<div class="clear"></div>');
		$('.selectBox-dropdown-menu.selectBox-options').append(new_board).find('#newboardcreator<?php echo $key;?>').clearOnFocus();
		$('#newBoardCreate<?php echo $key;?>').submit(function(){ return false; });
	}

	$('#emailpin form').unbind('submit').submit(function(){
		$('#emailpin form .submit input').after('<img src="data/images/loading_2.gif" id="loading_button" />');
		$.post('<?php echo $this->from_url;?>', $('#emailpin form').serialize(), function(data){
			if(data.indexOf('http://') === 0) {
				window.location = data;
			} else {
				$.fancybox(data, {
					'titleFormat': function(){
			        	return '<div id="fancybox-title-over"><?php echo $this->translate('Repin');?></div>';
			        },
			        titlePosition: 'over'
				});
			}
		});
		return false;
	});
		
});


</script>
<script type="text/javascript">
$(document).ready(function(){
	var image = new Image();
	image.src = '<?php echo $this->media;?>';
	$(image).load(function(){
		$('#content-holder .imageholder img').replaceWith( $(image).addClass('thumbShow') );
	});

	regExPrice.addExpresionLine($('#message').html(), true);
	$('#message').bind("keydown keyup keypress focus paste",function() {
		regExPrice.addExpresionLine(this.value);
	});
	
});
</script>