<div id="addpin">
	<p class="text"><strong><?php echo $this->pin_text;?></strong></p>
	<ul class="buttons">
		<li>
			<a href="<?php echo $this->from_url;?>" class="add silverbox" title="<?php echo $this->translate('Add a Pin');?>"><?php echo $this->translate('Add a Pin');?></a>
		</li>
		<li>
			<a href="<?php echo $this->from_file;?>" class="upload silverbox" title="<?php echo $this->translate('Upload a Pin');?>"><?php echo $this->translate('Upload a Pin');?></a>
		</li>
		<li class="last">
			<a href="<?php echo $this->add_board;?>" class="create silverbox" title="<?php echo $this->translate('Create a Board');?>"><?php echo $this->translate('Create a Board');?></a>
		</li>
	</ul>
	<div class="clear"></div>
</div>