<?php //var_dump($this);exit;?>
<div id="create-mail">
		<form name="CreateMail" method="post" action="<?php echo $this->form_action;?>" class="Form StaticForm" id="CreateMail">
            <ul>
                <li>
                    <label for="id_website"><?php echo $this->translate('Destinatario/s');?></label>
                    <div class="Right">
					<div class="add_collaborators Right">
                        
        
                        <div class="clearfix">
                            <span id="invite_response<?php echo ($this->is_edit?'-edit':'');?>">
                            <?php if($this->another_users) { ?>
                            	<?php foreach($this->another_users AS $u) { ?>
                            	<input id="hidden_user_fr_<?php echo $u['user_id']?><?php echo ($this->is_edit?'-edit':'');?>" type="hidden" name="friends[<?php echo $u['user_id']?>]" value="<?php echo $u['user_id']?>" />
                            	<?php } ?>
                            <?php } ?>
                            </span>
                            <input type="text" class="collaborator_name ui-autocomplete-input" value="<?php echo $this->translate('Add another pinner');?>" name="collaborator_name" autocomplete="off" role="textbox" aria-autocomplete="list" aria-haspopup="true">
                            
                            <ul id="CurrentCollaborators<?php echo ($this->is_edit?'-edit':'');?>">
                            	<?php if($this->another_users) { ?>
                            	<?php foreach($this->another_users AS $u) { ?>
                            	<li class="collaborator invite" id="user_fr_<?php echo $u['user_id']?><?php echo ($this->is_edit?'-edit':'');?>">
									<a href="<?php echo $u['href']?>">
										<img alt="<?php echo $this->translate('Collaborator Photo');?>" src="<?php echo $u['avatar']?>" class="collaborator_image">
									</a>
									<a href="<?php echo $u['href']?>" class="collaborator_name"><?php echo $u['fullname']?></a>
									<a class="delete_collaborator invite" href="javascript:void(0);" onclick="deleteFriend('<?php echo $u['user_id']?>');"><?php echo $this->translate('Remove');?></a>
								</li>
                            	<?php } ?>
                            	<?php } ?>
                            </ul>
                        </div>
                    </div>
                        
                    </div>
                </li>
			
				<li>
                	<label for="id_website"><?php echo $this->translate('Mensaje');?></label>
                    <div class="Right">
                		<textarea style="width: 400px; height: 100px;" title="<?php echo $this->translate('Please enter a code');?>" class="inputbox required" name="text" id="text"></textarea>
                    </div>
                </li>

            </ul>

            <!-- Button -->
            <div class="Submit">
                <a class="Button WhiteButton RedButton create-board" href="javascript:void(0);" onclick="saveMailData();">
                	<strong><?php echo $this->translate('Enviar');?></strong>
                	<span></span>
                </a>
            </div>
        </form>

    <input type="hidden" value='<?php echo $this->user_activate;?>' id="fullname" class="fullname" />
    </div>
    
    <div class="clear"></div>
    
<script type="text/javascript">
$(document).ready(function(){
	
        
	$('input.collaborator_name').clearOnFocus();

 
  	var cache = {};
 
        if ($("#fullname").val() != "")
        {
            var val = $("#fullname").val();
            var act = 1;
            $.post('<?php echo $this->friends_href;?>', {term: val, act: act}, function(data){
                    cache[val] = data.users;
                    autocompleteResults(data.users);
                    $('.option_friends').trigger("click");
            }, 'json');
        }


	

	$('.collaborator_name.ui-autocomplete-input').live('keyup', function(){
		var val = this.value;
		if(cache[val]) {
			autocompleteResults(cache[val]);
		} else {
			$.post('<?php echo $this->friends_href;?>', {term: val}, function(data){
				cache[val] = data.users;
				autocompleteResults(data.users);
			}, 'json');
		}
	}).after('<div class="menu_friends" style="position: absolute; display: none;z-index:2147483647;">');
	
	function autocompleteResults(data) {

		var holder = $('.menu_friends').empty();
		if($(data).objectSize() < 1) {
			holder.hide();
			return;
		}
		holder.show(function(){
			$(document).unbind('.joauto').bind('click.joauto',function(e){
				holder.hide();
			});
		});
		$(data).each(function(i, item){
			user = $('<div class="option_friends"><img alt="'+item.label+'" src="'+item.image+'"><span>'+item.label+'</span></div>').click(function(){
				holder.hide();
				if( $('#user_fr_'+item.value+'<?php echo ($this->is_edit?'-edit':'');?>').size() > 0 ) { return; }
				$('input.collaborator_name').val('');
				$('#invite_response<?php echo ($this->is_edit?'-edit':'');?>').append('<input id="hidden_user_fr_'+item.value+'<?php echo ($this->is_edit?'-edit':'');?>" type="hidden" name="friends['+item.value+']" value="'+item.value+'" />');
				template = $('#friend-template<?php echo ($this->is_edit?'-edit':'');?>').html();
				for(e in item) {
					template = template.replace(new RegExp(RegExp.quote('{'+e+'}'), 'g'), item[e]);
				}
				
				$('#CurrentCollaborators<?php echo ($this->is_edit?'-edit':'');?>').append(template);
			}).css({'cursor': 'pointer'});
			
			holder.append(user);
		});
	}

	RegExp.quote = function(str) {
	    return (str+'').replace(/([.?*+^$[\]\\(){}|-])/g, "\\$1");
	};
		
	
});

function saveMailData() {
	if ($("#text").val()=="")
	{
		alert("<?php echo $this->translate('Debe indicar un texto para el mensaje');?>");
		$("#text").focus();
		return false;
	}
	$.post('<?php echo $this->form_action;?>', $('#CreateMail').serialize(), function(data){
		if(data.error) {
			Pins.error(data.error);
		} else if(data.data) {
			$("#fancybox-close").click();
		}
	}, 'json');
	return false;
}

function deleteFriend(id) {
	$('#user_fr_'+id+'<?php echo ($this->is_edit?'-edit':'');?>').remove();
	$('#hidden_user_fr_'+id+'<?php echo ($this->is_edit?'-edit':'');?>').remove();
}


$(document).ready(function(){
	$(".selectBox.selectBox-dropdown").bind('click',function(event){
		$('ul.hidden').hide();
		event.preventDefault();
		$(".selectBox.selectBox-dropdown").hide();
		$(".selectBox-dropdown-menu.selectBox-options").show();

		$(".master").unbind('click').bind('click',function(event){
			event.preventDefault();

			
			var children  = $(this).find($('ul'));
			if(children.hasClass('opened')){
				children.hide().removeClass('opened');
			
				
			}else{

			$(".hidden").hide();
			var self  = $(this);
			children.addClass('opened');


			if($(children).hasClass('hidden')){
				try
                                {
                                    console.log("OK");
                                }
                                catch(e)
                                {
                                    if (window.console // check for window.console not console
                                        && window.console.log)
                                    {
                                        window.console.log("OK");
                                    }

                                }
				children.show();
				children.find('li a').click(function(event){
						event.preventDefault();
						appendElementInMain($(this));
						$(".hidden").hide();
				});
			}else{
				
				appendElementInMain(self.find($('a')));
				
			}

			}
		});
	

		function appendElementInMain(element){
			$(".selectBox-dropdown-menu.selectBox-options").hide();
			$(".selectBox.selectBox-dropdown").show();
			$(".selectBox-label").text(element.text());
			$("#catId").val(element.data("id"));
			
			}

		
	});

	return;
	
	
});

</script>

<script type="text/template" id="friend-template<?php echo ($this->is_edit?'-edit':'');?>">
<li class="collaborator invite" id="user_fr_{value}<?php echo ($this->is_edit?'-edit':'');?>">
	<a href="{href}">
		<img alt="<?php echo $this->translate('Collaborator Photo');?>" src="{image}" class="collaborator_image">
	</a>
	<a href="{href}" class="collaborator_name">{label}</a>
	<a class="delete_collaborator invite" href="javascript:void(0);" onclick="deleteFriend('{value}');"><?php echo $this->translate('Remove');?></a>
</li>
</script>