<?php //if (!isset($_SESSION['token'])) //<?php if(!JO_Session::get('token')) 
{
    echo $this->header_part; 
}    
?>

	<div class='banner'>
			<h2 class='category'><?php echo $this->translate('Gifts'); ?></h2>
		
			<div class="stitching">
             	<div class="stitch"></div>
                <div class="stitch white"></div>
           </div>
		</div>
		<?php echo $this->pins;?>
		
		

<?php //if (!isset($_SESSION['token'])) //<?php if(!JO_Session::get('token')) 
{
    echo $this->footer_part;
}    
?>
