<?php 
	$module = $this->getRequest()->getModule();
?>

<form name="admin_form" id="admin_form" method="post" action="">

	<div class="info_line top">
		<h3 class="fleft title">
			<img alt="" src="cms/<?php echo $module;?>/images/gallery-sml.png">
			<?php echo $this->translate('Boards');?>
		</h3>
		
		<span id="fader" class="fleft mleft30" style="display:none;">
			<span class="msgError"><span><?php echo $this->translate('Error!');?></span><i class="error_text"></i></span>
		</span>
		
		<div class="fright mtop3">
			<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<a class="button" href="<?php echo $module;?>/boards/"><?php echo $this->translate('Cancel');?></a>
		</div>
		<div class="clear"></div>
	</div>
	
	<div class="clear"></div>

	
	<table cellspacing="0" cellpadding="0" class="formtable">
		<tbody>
			<tr>
				<td width="150"><?php echo $this->translate('Title');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
				<td>
					<input type="text" size="55" title="<?php echo $this->translate('Please enter a title');?>" value="<?php echo $this->title;?>" class="inputbox required" name="title" />
        		</td>
			</tr>
			<?php if($this->categories) { ?>
			<tr>
				<td width="150"><?php echo $this->translate('Category');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
				<td>
				<select name="category_id"> 
						<?php foreach($this->categories as $cat): ?>
						<option value="<?php echo $cat['category_id']; ?>" <?php if($this->category_id == $cat['category_id']): ?>selected="selected"<?php endif; ?>><?php echo $cat['title'];?></option>
						<?php endforeach; ?>
					</select>	
				</td>
			</tr>
			<?php } ?>
			<tr>
				<td width="150"><?php echo $this->translate('SEO Query');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
				<td>
					<input type="text" size="55" title="<?php echo $this->translate('Please enter a query');?>" value="<?php echo $this->keyword;?>" class="inputbox required" name="keyword" />
        		</td>
			</tr>
			
		</tbody>
	</table>
	
	
	<div class="info_line bottom">
		<div class="fright mtop3">
			<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<a class="button" href="<?php echo $module;?>/boards/"><?php echo $this->translate('Cancel');?></a>
		</div>
		<div class="clear"></div>
	</div>
	
</form>