<?php 
	$module = $this->getRequest()->getModule();
?>

<div class="info_line top">
	<h3 class="fleft title">
		<img alt="" src="cms/<?php echo $module;?>/images/push_pin.png">
		<?php echo $this->translate('Boards');?>
	</h3>
	
	<?php if($this->successfu_edite || $this->error_permision) { ?>
	<?php if($this->successfu_edite) { ?>
	<span id="fader" class="fleft mleft30"><span class="msgOk"><span><?php echo $this->translate('Successfully!');?></span><?php echo $this->translate('Information was successfully changed!');?></span></span>
	<?php } else if($this->error_permision) { ?>
	<span id="fader" class="fleft mleft30"><span class="msgError"><span><?php echo $this->translate('Error!');?></span><?php echo $this->error_permision;?></span></span>
	<?php } ?>
	<script type="text/javascript"> 
	// <![CDATA[
	$(document).ready(function() {       
		setTimeout(function() {
			$("#fader").customFadeOut("slow" ,    
			function() {       
				$("#fader").remove();  
			});
		},
		4000);
	});
	// ]]>
	</script>
	<?php } ?>
	
	<div class="fright mtop3">
		<a class="button" href="javascript:void(0);" onclick="multiActionSelected('deleteMulti');"><?php echo $this->translate('Delete selected');?></a>
	</div>
	<div class="clear"></div>
</div>



<p class="info">
	<?php echo $this->translate('Pins Manager');?>.<br>
	<strong><?php echo $this->translate('Note: If you delete an entry, information will be lost.');?></strong>
</p>

<form action="<?php echo $module;?>/boards/" method="get" id="testtt">
<table cellspacing="0" cellpadding="0" class="display">
	<thead>
		<tr class="nodrop nodrag">
			<th width="20"></th>	
			<th width="20" class="left">
				<a href="<?php echo $this->sort_board_id;?>" <?php if($this->order == 'p.board_id') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>>#</a>
			</th>
			<th class="left">
				<?php echo $this->translate('Board');?>
			</th>
			<th class="left">
				<?php echo $this->translate('User/Username');?>
			</th>
			<th class="left">
				<a href="<?php echo $this->sort_followers;?>" <?php if($this->order == 'p.followers') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Followers');?></a>
			</th>
			<th class="left">
				<a href="<?php echo $this->sort_pins;?>" <?php if($this->order == 'p.pins') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Pins');?></a>
			</th>
			<th class="left">
				<a href="<?php echo $this->sort_total_views;?>" <?php if($this->order == 'p.total_views') { ?>class="sort-<?php echo $this->sort;?>"<?php }?>><?php echo $this->translate('Views');?></a>
			</th>
			<th class="left">
				<?php echo $this->translate('Is shared');?>
			</th>

			<th width="20"><?php echo $this->translate('Edit');?></th>
			<th width="20"><?php echo $this->translate('Delete');?></th>
		</tr>
		<tr class="search">
			<th width="20">
				<input type="checkbox" class="check_all_list" />
			</th>	
			<th class="left">
				<input class="inputbox" type="text" name="filter_board_id" value="<?php echo $this->filter_dic_id;?>" size="4" />
			</th>
			<th class="left"><input class="inputbox filter_board_name" type="text" name="filter_board_name" value="<?php echo $this->filter_board_name;?>" size="8" /></th>
			<th class="left"><input class="inputbox filter_username" type="text" name="filter_username" value="<?php echo $this->filter_username;?>" size="8" /> </th>
			<th class="left"> </th>
			<th class="left"> </th>
			<th class="left"> </th>
			<th class="left"> </th>
            
			<th colspan="2">
				<input type="submit" value="<?php echo $this->translate('Filter');?>" class="button">
				&nbsp; <a href="<?php echo $module;?>/boards/"><img src="cms/<?php echo $module;?>/images/reload.png" class="tooltip"  alt="" title="<?php echo $this->translate('Reset');?>" /></a>
			</th>
		</tr>
	</thead>
	<tbody>
	<?php if($this->boards) { ?>
	<?php foreach($this->boards AS $board) { ?>
		<tr id="<?php echo $board['board_id'];?>">
			<td>
				<input type="checkbox" class="check_list" name="action_check[]" value="<?php echo $board['board_id'];?>" />
			</td>
			<td>
				<a href="<?php echo $board['board_href'];?>" target="_blank">
					<?php echo $board['board_id'];?>.
				</a>
			</td>
			<td>
				<a href="<?php echo $board['board_href']; ?>" target="_blank">
					<?php echo $board['title'];?>
				</a>
			</td>
			<td>
			<a href="<?php echo $board['user_href'];?>" target="_blank">	<?php echo $board['fullname'];?> </a><br />
				<a href="<?php echo $module;?>/users/?filter_id=<?php echo $board['user_id'];?>" target="_blank">
					<?php echo $board['username'];?>
				
				</a>
			</td>
			<td>
					<?php echo $board['followers'];?>
			</td>
			<td>
				<?php echo $board['pins'];?>
			</td>
			<td>
					<?php echo $board['views'];?>
				
			</td>
			<td>
				<?php echo ($board['shared']>0.0000?$this->translate('Yes'):$this->translate('No'));?>
			</td>
			
			<td align="center"><a href="<?php echo $module;?>/boards/edit/?id=<?php echo $board['board_id'];?>"><img title="<?php echo $this->translate('Edit');?>" alt="" class="tooltip" src="cms/<?php echo $module;?>/images/edit.png"></a></td>
           	<td align="center">
				<a id="item_<?php echo $board['board_id'];?>" class="delete" href="javascript:void(0);"><img title="<?php echo $this->translate('Delete');?>" alt="" class="tooltip" src="cms/<?php echo $module;?>/images/delete.png"></a>
			</td>
		</tr>
	<?php } ?>
	<?php } else { ?>
		<tr class="nodrop nodrag">
			<td colspan="5">
				<div class="msgAlert"><span><?php echo $this->translate('Attention!');?></span><?php echo $this->translate('No records found ...');?></div>
			</td>
		</tr>
	<?php } ?>
	</tbody>
</table>
</form>
<?php if($this->pagination) { ?>
<br />
<div class="fleft">
<?php echo $this->translate('Page');?> <b><?php echo $this->page_num;?></b> <?php echo $this->translate('from');?> <b><?php echo $this->total_pages;?></b> (<b><?php echo $this->total_rows;?></b> <?php echo $this->translate('records');?>)
</div>
<div class="pagination fright">
	<?php echo $this->pagination;?>
</div>
<div class="clear"></div>
<?php } ?>

<script type="text/javascript"> 
// <![CDATA[
$(document).ready(function() {       
	$('a.delete').click(function (e) {
        if (confirm(lang.confirm)) {
            e.preventDefault();
            var parent = $(this).parents('tr');
            $.ajax({
                type: 'post',
                url: "<?php echo $module;?>/boards/delete/",
                data: 'id=' + $(this).attr('id').replace('item_', ''),
                beforeSend: function () {
                    parent.animate({
                        'backgroundColor': '#FFBFBF'
                    }, 400);
                },
                success: function (result) {
	            	if(result == 'ok') {
		                parent.fadeOut(400, function () {
		                    parent.remove();
		                });
	            	} else {
	            		alert(result);
	            		parent.animate({'backgroundColor': 'transparent'}, 400);
		            }
	            }
            });
        }
    });
});
// ]]>
</script>
