<body onload="scrollComment();"> 

<?php if($this->popup) { ?>

<div id="fb-root"></div>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/es_ES/all.js#xfbml=1";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


<script type="text/javascript">
window.___gcfg = {
    lang: 'es-ES'
};

(function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
})();
</script>


<!--div class="buttonswrapper">
	<div id="buttons">
                <ul>
                    <li>
                        <div class="fb-like" data-href="http://www.amatteur.com" data-layout="button-count" data-action="like" data-show-faces="true" data-share="false"></div>
                    </li>
                    <li>
                        <div class="fb-share-button" data-href="<?php echo $this->pin_url; ?>" data-type="button_count"></div>                                    
                    </li>

                    <li>
                        <div class="g-plusone" data-size="tall" data-annotation="none" ></div>
                    </li>
                    <li>
                        <a href="<?php echo $this->pin_url; ?>" class="tweet" title="<?php echo $this->translate('Tweet'); ?>"><span><?php echo $this->translate('Tweet'); ?></span></a>
                    </li>
                    <!--li>
                        <a href="<?php echo $this->url_embed; ?>" class="embed" title="<?php echo $this->translate('Embed'); ?>"><span><?php echo $this->translate('Embed'); ?></span></a>
                    </li>
                    <?php if (!$this->pin['pinIsReported'])
                    { ?>
                        <li>
                            <a href="<?php echo $this->url_report; ?>" class="report" title="<?php echo $this->translate('Report Pin'); ?>"><span><?php echo $this->translate('Report Pin'); ?></span></a>
                        </li>
                    <?php } ?>
                    <?php if ($this->loged)
                    { ?>
                        <li>
                            <a href="<?php echo $this->url_email; ?>" class="email" title="<?php echo $this->translate('Email'); ?>"><span><?php echo $this->translate('Email'); ?></span></a>
                        </li>
                        <?php } ?>

                    <li>

                        <?php /* if($this->follow_event) { ?>
                          <div class="action">
                          <a class="Button13 Button WhiteButton Tab following follow-red<?php echo ($this->eventIsFollow?' gray':'');?>" href="<?php echo $this->follow_event;?>"><strong><?php echo ($this->eventIsFollow ? $this->translate('Ya no me apunto') : $this->translate('Me apunto!') );?></strong>
                          </a>
                          </div>
                          <?php } */ ?>


                        <div id="contenedor" >     
                            <?php if ($this->history)
                            { ?>
                                <div class="feed box">
                                    <div class="left-corner">
                                        <div class="bottom-corner">
                                            <div class="right-corner">
                                                <div class="preview" style="overflow: auto;height: 300px">
                                                    
                                                    <label style="font-size: 0.8em;font-weight: 300;line-height: 1em;color:#0061A5;"> <?php echo $this->translate('¿Piensas asistir?') ?></span>

                                                    <div class="action">
                                                            <a class="Button13 Button WhiteButton Tab following follow-red<?php echo ($this->eventIsFollow?' gray':'');?>" href="<?php echo $this->follow_event;?>"><strong><?php echo ($this->eventIsFollow ? $this->translate('Ya no me apunto') : $this->translate('Me apunto!') );?></strong><span></span>
                                                            </a>
                                                    </div>

                                                    <label for="black" style="color:#0061A5;float:left;"><h2><?php echo $this->translate('Se han apuntado'); ?></h2></label>

                                                    <?php foreach ($this->history AS $history)
                                                    { ?>
                                                        <a href="<?php echo $history['href']; ?>" class="story" style="height: 40px;width: 180px;padding-left: 15px;white-space: normal">
                                                            <span class="profile">
                                                                <img src="<?php echo $history['user']['avatar']; ?>" alt="<?php echo $history['user']['fullname']; ?>">
                                                            </span>
                                                            <strong><?php echo $history['user']['fullname']; ?></strong> <?php echo $history['text_type']; ?>
                                                            <span class="colorlight" title="<?php echo $history['date_added']; ?>">
                                                            <?php echo sprintf($this->translate('%d %s ago'), $history['date_dif']['value'], $this->translate($history['date_dif']['key'])); ?>
                                                            </span>
                                                        </a>
                                                    <?php } ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php } ?>

                        </div>                       
                    </li>
                </ul>     
	</div>
</div-->

<div id="pin" class="popuppin">
	<div class="box boxlarge">
    	<a class="closePop"></a>
            
		<?php } ?>
        
		<div class="info">
			<div class="title" style="height:100px">
                            <p>
                                                <label style="font-size: 2.8em;font-weight: 300;line-height: 1em;color:#0061A5;float:left;"> 
                    <image src="data/images/event_calendar.png" >&nbsp;<strong><?php echo $this->translate('Evento Deportivo ');?> </strong></label>		
                            

                            </p>

                            			
                            <div class="box2" style="margin-left:70%;padding: 4px;margin-top:-16px">
                                <?php if ($this->loged) { ?>    
                                    <div class="action">                                
                                    <?php if ($this->owner) { ?>                                                    
                                        <span class="selected"><a id="editEvent" href="<?php echo $this->editEvent_url ?>" class="Button RedButton addEvent" style="margin-top:0px;  text-decoration:none;color: white;text-shadow: 0px 1px black;" ><?php echo $this->translate('Editar');?></a></span>
                                    <?php } ?>                    

                                        <a id="comparto" class="Button13 Button WhiteButton Tab following follow-red<?php echo ($this->eventIsLike?' gray':'');?>" href="<?php echo $this->like_event;?>"><strong><?php echo ($this->eventIsLike ? $this->translate('Ya no comparto') : $this->translate('Compartir') );?></strong><span></span>
                                        </a>
                                    </div>
                                        

                                <?php } ?>                    
                            </div>

                            
				<div class="left" style="float:right;border-top:10px;padding: 7px;border-color: #e2e2e2;border-style: solid;border-width: 1px">
					<h3>
                                            <label style="font-size: 0.8em;font-weight: 300;line-height: 1em;color:#0061A5;"> <?php echo $this->translate('¿Piensas asistir?') ?></span>
					</h3>
                                    
                                        <div class="action">
                                                <a id="apunto" class="Button13 Button WhiteButton Tab following follow-red<?php echo ($this->eventIsFollow?' gray':'');?>" href="<?php echo $this->follow_event;?>"><strong><?php echo ($this->eventIsFollow ? $this->translate('Ya no me apunto') : $this->translate('Me apunto!') );?></strong><span></span>
                                                </a>
                                        </div>

				</div>
			</div>

			<div class="view">
			
                                <div class="photo">
					<p>
                                                <img width="<?php echo $this->event['popup_width'];?>" height="<?php echo $this->event['popup_height'];?>" data-original="<?php echo $this->event['popup'];?>" src="<?php echo $this->event['thumb'];?>" alt="Image" />
					</p>
				</div>
				
                            <p><p></p>
                            
                            <div id="panel" style="width: 540px">
                                <div style="display:table;padding: 0px">
				<span class="desc"><?php //echo Helper_Events::descriptionFix($this->event['description']);?></p>
                                <div style="display:table-row;padding: 0px">
                                    <div style="display:table-cell;padding: 15px"><label for="email"><span class="location colorless"><?php echo $this->translate('Descripción del evento: ');?>  <br class="hide" /></label></span></div>
                                    <div style="display:table-cell;padding: 15px"><span class="field" style="font-size: 1.8em;font-weight: 300;line-height: 1em;color:#0061A5;"><?php echo $this->event['eventname'];?></span></div>
                                </div>
                                <div style="display:table-row;padding: 0px">
                                    <div style="display:table-cell;padding: 15px"><span class="location colorless"><?php echo $this->translate('Deporte: ');?></span> </div>
                                    <div style="display:table-cell;padding: 15px"><span class="field" style="font-size: 1.8em;font-weight: 300;line-height: 1em;color:#0061A5;"><?php echo $this->event['sport_category'];?></span></div>
                                </div>
                                <div style="display:table-row;padding: 0px">
                                    <div style="display:table-cell;padding: 15px"><span class="location colorless"><?php echo $this->translate('Organiza: ');?> </span></div>
                                    <div style="display:table-cell;padding: 15px"><span class="field" style="font-size: 1.8em;font-weight: 300;line-height: 1em;color:#0061A5;"><?php echo $this->event['organiza'];?></span></div>
                                </div>
                                <div style="display:table-row;padding: 0px">
                                    <div style="display:table-cell;padding: 15px"><span class="location colorless"><?php echo $this->translate('Ubicación: ');?> </span></div>
                                    <div style="display:table-cell;padding: 15px"><span class="field" style="font-size: 1.8em;font-weight: 300;line-height: 1em;color:#0061A5;"><?php echo $this->event['location'];?></span></div>
                                </div>
                                <div style="display:table-row;padding: 0px">
                                    <div style="display:table-cell;padding: 15px"><span class="location colorless"><?php echo $this->translate('Fecha: ');?> </span></div>
                                    <div style="display:table-cell;padding: 15px"><span class="field" style="font-size: 1.8em;font-weight: 300;line-height: 1em;color:#0061A5;"><?php echo $this->event['date_event'];?></span></div>
                                </div>
                                <div style="display:table-row;padding: 0px">
                                     <div style="display:table-cell;padding: 15px"><span class="location colorless"><?php echo $this->translate('Página web del evento: ');?></span></div>
                                     <div style="display:table-cell;padding: 15px"><span class="field" style="font-size: 1.8em;font-weight: 300;line-height: 1em;color:#0061A5;"><?php echo $this->event['website'];?></span></div>
                                </div>
                                <div style="display:table-row;padding: 0px">
                                    <div style="display:table-cell;padding: 15px"><span class="location colorless"><?php echo $this->translate('Detalles: ');?></span> </div>
                                    <div style="display:table-cell;padding: 15px" id="divComentarios"><span class="field" style="font-size: 1.8em;font-weight: 300;line-height: 1em;color:#0061A5"><?php echo $this->event['description'];?></span></div>
                                </div>
                                <div style="display:table-row;padding: 0px">
                                    <div style="display:table-cell;padding: 15px"><span class="location colorless"><?php echo $this->translate('Evento publicado por: ');?> </span> </div>
                                    <div style="display:table-cell;padding: 15px">
                                        <a href="<?php echo $this->event['userHref'];?>">
                                            <img style="height:110px;width:110px;" src="<?php echo $this->event['avataruser'];?>" alt="<?php echo $this->event['fullname'];?>"/>
                                            <div style="display:table-cell;padding: 0px">
                                            <?php echo $this->event['fullname'];?>
                                        </a>    
                                    </div>
                                </div>
                                <div style="display:table-row;padding: 0px">
                                </div>
			</div>
                                    <div class="commentslist">
					<form action="<?php echo $this->event['href'];?>" method="post" id="pin_commentt_form">
						<p class="hide">
							<input name="av2" />
						</p>
						<ul>
							<?php if($this->comments) { ?>
							<?php foreach($this->comments AS $crow => $comment) { ?>
							<li>
								<p class="avatar">
									<a href="<?php echo $comment['user']['profile'];?>">
										<img src="<?php echo $comment['user']['avatar'];?>" alt="<?php echo $comment['user']['fullname'];?>" />
									</a>
								</p>
								<h4><a href="<?php echo $comment['user']['profile'];?>"><?php echo $comment['user']['fullname'];?></a></h4>
								<p class="text"><?php echo $comment['comment'];?></p>
								<div class="clear"></div>
								
								<?php if($comment['delete']) { ?>
								<a href="<?php echo $comment['delete'];?>" class="delete" title="<?php echo $this->translate('Delete Comment');?>">X</a>
								<?php } elseif($comment['report']) { ?>
								<a href="<?php echo $comment['report'];?>" class="report silverbox" title="<?php echo $this->translate('Report Comment');?>">Denunciar comentario</a>
								<?php } ?>
							</li>
							<?php } ?>
							<?php } ?>
							
							<?php if($this->loged) { ?>
							<li class="addComments">
								<p class="avatar">
									<a href="<?php echo $this->self_profile;?>">
										<img src="<?php echo $this->self_avatar;?>" alt="<?php echo $this->self_fullname;?>" />
									</a>
								</p>
								<div class="form">
									<div id="friends_in_comment" class="hide"></div>
									<div class="posrelat">
										<label for="comment" class="hide"><?php echo $this->translate('Comment:');?><br /></label>
										<textarea name="write_comment" id="comment" rows="5" cols="30"><?php echo $this->translate('Add a comment...');?></textarea>
									</div>
									<p class="submit"><input type="submit" value="<?php echo $this->translate('Post comment');?>" /> <?php echo $this->translate('Type @ to recommend this pin to another Pinner');?> </p>
								</div>
								<div class="clear"></div>
							</li>
							<?php } else { ?>
							<li>
								<h4 class="login-link"><a href="<?php echo $this->login_href;?>"><?php echo $this->translate('Login to Comment')?></a></h4>
								<div class="clear"></div>
							</li>
							<?php } ?>
						</ul>
						<div class="clear"></div>
					</form>
				</div>	

                </div>			
			
			<div class="columns">
				<div class="clear"></div>
			</div>
			
		</div>
		
		<?php if($this->popup) { ?>
	</div>
</div>
<?php } ?>

</body>        
        
<script type="text/javascript">

function scrollComment() {
    $(document).ready(function(){


        <?php if($this->comment) { ?>

        var target_offset = $('#comment').offset();
        $('html, body').animate({scrollTop:target_offset.top}, 1000);

        <?php } ?>
            
            
        $("#apunto").click(function(){
            window.location.reload();
            //totallikesearch();
        });

	function totallikesearch() {
                val = '<?php echo $this->event['event_id']; ?>';
		$.post('<?php echo $this->totallike_url;?>', {event_id: val}, function(data){
                    alert(data);
                    $("#contenedor").html(data);
		},'json');
	}
            

    });
    
}


$(document).ready(function(){

//share


	<?php if($this->popup) { ?>
                
                
        $("#fancybox-wrap").wrap('<div class="pin-overlay" />');

	$('#pin .prev_next a').click(function(){
		$.fancybox.close();
		var element = this;
		var timer = setInterval(function(){
			if( !$('#fancybox-overlay').is(':visible') ) {
				Pins.initPopupOpener( $(element) );
				clearInterval(timer);
			}
		}, 50);
		return false;
	});
        
        $('#pin .closePop').click(function(){
		$.fancybox.close();
                $(".pin-overlay").remove();
	});
	<?php } ?>
	
	<?php if($this->pin['originally_pinned']) { ?>
	Pins.initFollow('.box .info .pinned .titlebar .follow a', function(element){ 
		if(!$(element).hasClass('gray')) {
			if(!$(element).hasClass('boardF')) {
				if($(element).attr('href') == $('.box .info .title .follow a').attr('href')) {
					$('.box .info .pinned .titlebar .follow a.boardF').removeClass('gray').html('<?php echo $this->translate('Me apunto!');?>');
					$('.box .info .title .follow a').removeClass('gray').html('<?php echo $this->translate('Me apunto!');?>');
				}
			} else {
				$('.box .info .pinned .titlebar .follow a.boardF').removeClass('gray').html('<?php echo $this->translate('Me apunto!');?>');
			}
		} else {
			if(!$(element).hasClass('boardF')) {
				if($(element).attr('href') == $('.box .info .title .follow a').attr('href')) {
					$('.box .info .pinned .titlebar .follow a.boardF').addClass('gray').html('<?php echo $this->translate('Ya no me apunto');?>');
					$('.box .info .title .follow a').addClass('gray').html('<?php echo $this->translate('Ya no me apunto');?>');
				}
			} else {
				$('.box .info .pinned .titlebar .follow a.boardF').addClass('gray').html('<?php echo $this->translate('Ya no me apunto');?>');
			}
		}
	});
	<?php } else { ?>
	Pins.initFollow('.box .info .pinned .titlebar .follow a');
	<?php } ?>
	Pins.initFollow('.box .info .title .follow a', function(element){
		if(!$(element).hasClass('gray')) {
			$('.box .info .pinned .titlebar .follow a.boardF').removeClass('gray').html('<?php echo $this->translate('Me apunto!');?>');
			if($(element).attr('href') == $('.box .info .pinned .titlebar .follow a:not(.boardF)').attr('href')) {
				$('.box .info .pinned .titlebar .follow a').removeClass('gray').html('<?php echo $this->translate('Me apunto!');?>');
			}
		} else {
			$('.box .info .pinned .titlebar .follow a.boardF').addClass('gray').html('<?php echo $this->translate('Ya no me apunto');?>');
			if($(element).attr('href') == $('.box .info .pinned .titlebar .follow a:not(.boardF)').attr('href')) {
				$('.box .info .pinned .titlebar .follow a').addClass('gray').html('<?php echo $this->translate('Ya no me apunto');?>');
			}
		}
	});

	

	$('#comment').tagmate({
	    exprs: {
		    "@": "([a-zA-Zа-яА-Я\ ]{1,})+(?: ([a-zA-Zа-яА-Я\ ]{1,}))*"
		},
		sources: {
		    "@": function(request, response) {
		    	if(request.term) {
					$.post('<?php echo $this->get_user_friends;?>', {term: request.term}, function(data){
						response(data.users);
					}, 'json');
		    	}
		    }
		},
		highlight_tags: true,
		highlight_class: "hilite_friends",
		menu_class: "menu_friends",
		menu_option_class: "option_friends",
		menu_option_active_class: "active_friends"
	}).bind('keyup', function(){
		var tags = $('#comment').getTags();
		if($(tags['@']).objectSize() > 0) {
			$('friends_in_comment').empty();
			for(i in tags['@']) {
				if( $('#friends_in_comment input[name="friends['+i+']"]').size() == 0 ) {
					$('#friends_in_comment').append('<input type="hidden" name="friends['+i+']" value="'+tags['@'][i]+'" />');
				}
			}
		} else {
			$('#friends_in_comment').empty();
		}
	}).autoResize().clearOnFocus();

	$('.fb-like-button').html('<iframe src="//www.facebook.com/plugins/like.php?href=<?php echo urlencode($this->pin_url);?>&amp;send=false&amp;layout=button_count&amp;width=120&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:120px; height:21px;" allowTransparency="true"></iframe>');
		
	
});


<?php /* ?>
$('#share-fb').click(function(e){
    e.preventDefault();
    FB.ui({
        method: 'feed',
        name: 'This is the content of the "name" field.',
        link: ' <?php echo $this->pin_url;?>',
        picture: '<?php echo $this->pin['thumb'];?>',
        caption: 'This is the content of the "caption" field.',
        description: $('.info .view .desc').html(),
        message: ''
        });

    FB.ui({ 
    	method:'fbml.dialog', 
    	fbml:'<fb:fbml><fb:like width="200" stream="false" header="false" /></fb:fbml>', 
    	width:200, 
    	height:150 
    	}); 
    
    return false;
});
<?php */ ?>

</script>
