<?php echo $this->header_part; ?>

<div id="fb-root"></div>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/es_ES/all.js#xfbml=1";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


<script type="text/javascript">
window.___gcfg = {
    lang: 'es-ES'
};

(function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
})();
</script>
<script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>


<div id="detail" class="pindetail">
    <?php if ($this->show_buttonswrapper)
    { ?>
        <div class="buttonswrapper" style="right:230px">
        <?php if ($this->loged) { ?>
            <div id="buttons" class="buttons-absolute" style="padding-top:60px">
        <?php } else { ?>
            <div id="buttons" class="buttons-absolute" style="padding-top:0px">
        <?php } ?>        
                <ul>
                    <li>
                    <?php if ($this->loged) { ?>                                                                    
                        <div id="contenedor">
                            <div class="feed box">
                                <div class="left-corner">
                                    <div class="bottom-corner">
                                        <div class="right-corner">
                                            <div class="preview" style="overflow: auto;height: 300px;padding-top: 0px">

                                                <div class="info">
                                                        <div class="title" style="height:100px;padding-left: 15px">

                                                                <?php if ($this->loged) { ?>                                                                    
                                                                <div class="left" style="border-top:10px;padding: 7px;border-color: #e2e2e2;border-style: none;border-width: 1px">

                                                                        <h3>
                                                                            <label style="font-size: 0.8em;font-weight: 300;line-height: 1em;color:#0061A5;"> <?php echo $this->translate('¿Piensas asistir?') ?></span>
                                                                        </h3>

                                                                        <div class="action">
                                                                            <a id="apunto-follow" style="margin-left:15%;width:100px;height:15px;padding-top: 8px;background: no-repeat;background-color:#0070BF !important;color:white;text-shadow:none;border-color: white;border-style: solid;border-width: 1px;border-radius: 5px" class="Button13 Button WhiteButton Tab following <?php echo ($this->eventIsFollow?' gray':'');?>" href="<?php echo $this->follow_event;?>"><center><strong><?php echo ($this->eventIsFollow ? $this->translate('Ya no me apunto') : $this->translate('Me apunto!') );?></strong></center>
                                                                                </a>
                                                                        </div>

                                                                </div>
                                                                <?php } ?>                                                
                                                        </div>
                                                </div>

                                                <?php if ($this->history)
                                                { ?>
                                                    <label for="black" style="color:#0061A5;float:left;"><h2><?php echo $this->translate('Personas que ya se han apuntado'); ?></h2></label>

                                                    <?php foreach ($this->history AS $history)
                                                    { ?>
                                                        <a href="<?php echo $history['href']; ?>" class="story" style="height: 40px;width: 182px;padding-left: 15px;white-space: normal">
                                                            <span class="profile">
                                                                <img src="<?php echo $history['user']['avatar']; ?>" alt="<?php echo $history['user']['fullname']; ?>">
                                                            </span>
                                                            <p><strong style="float:left"><?php echo $history['user']['fullname']; ?></strong> <?php //echo $this->translate("Se ha apuntado"); ?></p>  
                                                            <span class="colorlight" title="<?php echo $history['date_added']; ?>">
                                                            <?php echo sprintf($this->translate('%d %s ago'), $history['date_dif']['value'], $this->translate($history['date_dif']['key'])); ?>
                                                            </span>
                                                        </a>
                                                    <?php } ?>
                                                <?php } ?>                                                    
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>  
                       <?php } ?>
                    </li>                    
                    <!--li>
                        <div class="fb-like" data-href="http://www.amatteur.com" data-layout="button-count" data-action="like" data-show-faces="true" data-share="false"></div>
                    </li>
                    <!--li>
                        <div class="fb-share-button" data-href="<?php echo $this->event_url; ?>" data-type="button_count"></div>                                    
                    </li>
                    <li>
                        <div class="g-plusone" data-size="tall" data-annotation="none" ></div>
                    </li-->
                    <li>
                                <iframe src="http://www.facebook.com/plugins/like.php?href=http://www.amatteur.com&layout=button_count&show_faces=false&width=450&action=like&font&colorscheme=light&height=20" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:120px; height:20px;" allowTransparency="true"></iframe>
                    </li>
                    <li>                    
                                <a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal" hashtags="<?php echo $this->pin_url; ?>" data-via="amatteur" data-lang="es">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
                    </li>
                    <li>
                                <g:plusone size="medium"></g:plusone>
                    </li>
<!--a class="tweet" href="javascript:(function(){window.twttr=window.twttr||{};var D=550,A=450,C=screen.height,B=screen.width,H=Math.round((B/2)-(D/2)),G=0,F=document,E;if(C&gt;A){G=Math.round((C/2)-(A/2))}window.twttr.shareWin=window.open('http://twitter.com/share','','left='+H+',top='+G+',width='+D+',height='+A+',personalbar=0,toolbar=0,scrollbars=1,resizable=1');E=F.createElement('script');E.src='http://platform.twitter.com/bookmarklets/share.js?v=1';F.getElementsByTagName('head')[0].appendChild(E)}());"><span><?php echo $this->translate('Tweet'); ?></span></a>
<a href="javascript:(function(){window.twttr=window.twttr||{};var D=550,A=450,C=screen.height,B=screen.width,H=Math.round((B/2)-(D/2)),G=0,F=document,E;if(C&gt;A){G=Math.round((C/2)-(A/2))}window.twttr.shareWin=window.open('http://twitter.com/share','','left='+H+',top='+G+',width='+D+',height='+A+',personalbar=0,toolbar=0,scrollbars=1,resizable=1');E=F.createElement('script');E.src='http://platform.twitter.com/bookmarklets/share.js?v=1';F.getElementsByTagName('head')[0].appendChild(E)}());"></a-->
<!--a href="http://twitter.com/home?status=<?php echo $this->event_url; ?>">Compartir en Twitter</a>                         
                    <a title="Enviar a Twitter" href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal">Tuitear</a>
                        <a href="<?php echo $this->event_url; ?>" class="tweet" title="<?php echo $this->translate('Tweet'); ?>"><span><?php echo $this->translate('Tweet'); ?></span></a>
                    </li>
                    <!--li>
                        <a href="<?php echo $this->url_embed; ?>" class="embed" title="<?php echo $this->translate('Embed'); ?>"><span><?php echo $this->translate('Embed'); ?></span></a>
                    </li-->
                    <?php if (!$this->pin['pinIsReported'])
                    { ?>
                        <li>
                            <a href="<?php echo $this->url_report; ?>" class="report" title="<?php echo $this->translate('Report Pin'); ?>"><span><?php echo $this->translate('Report Pin'); ?></span></a>
                        </li>
                    <?php } ?>
                    <?php if ($this->loged)
                    { ?>
                        <li>
                            <a href="<?php echo $this->url_email; ?>" class="email" title="<?php echo $this->translate('Email'); ?>"><span><?php echo $this->translate('Email'); ?></span></a>
                        </li>
                    <?php } ?>


                </ul>                

            </div>

        </div>
    <?php } ?>

    <?php echo $this->left_part; ?>		
<?php if ($this->loged) { ?>
    <div class="pin"  style="margin-left:0px;padding-top: 60px">
<?php } else { ?>        
    <div class="pin"  style="margin-left:0px;padding-top: 0px">
<?php }  ?>
        <div class="box boxlarge-2">
            <div class="left-corner">
                <div class="bottom-corner">
                    <div class="right-corner">

                        <?php 
                        echo $this->events_details; ?>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="clear"></div>	
</div>

<?php echo $this->footer_part; ?>