<?php echo $this->header_part; ?>

    <?php /* if (!$this->user_data) { ?>                    
	<div id="container" style="margin-top:-50px;margin-left: 0px;" >
    <?php } else { ?>                    
	<div id="container" style="margin-top:10px;margin-left: 0px;" >
    <?php } */ ?>

<div style="margin-left: 0%;float: left;margin-top: 10%; margin-bottom: 10%" >            
<div id="containedor1" style="margin-bottom:20px;margin-right:5%;margin-left:2%;float: left;width: 20%" >    
        <img src="data/images/eventtos_1.png"  height="350px" width="300px"  >
</div>
<div id="containedor2" style="margin-bottom:20px;margin-right:3%;float: left;width: 38%" >    
	            	<span class="greyselected eventsLetras" style="float:left;"> 
                            <label>
                                <div style="width:740px;float:left;margin-left: 20%;margin-bottom: 5%">
                                    <img src="data/images/eventtos_deportivos.png" height="53px" width="235px" >&nbsp;
                                </div>    
                                <div style="width:560px;margin-left: 10px;padding-bottom: 30px">
                                    <strong><span style="margin-left: 20%;font-size: 1.4em;"><?php echo $this->translate('Busca, comparte, promociona ');?></span></strong><br/><br/>
                                    <span style="font-size: 1.1em;"><?php echo $this->translate('cualquier tipo de evento deportivo; cualquier deporte, en cualquier lugar, lo podrás encontrar aquí. Una base de datos creada y moderada por la comunidad amatteur');?></span>
                                </div>
                            </label>
                        </span>

		<div id="" class="box" style="margin-left: 10px;min-width: 300px;width:100px;min-height: 24px;height: 35px;padding: 10px 10px 12px 170px;text-shadow: 0 1px rgba(255,255,255,0.9);margin-top:10px;clear: both;min-width: 345px;white-space: nowrap;box-shadow: 0;font-size: 1.6em;font-weight: 300;line-height: 1em;font-weight: bold">
			<div class="box2">
                            <strong>
                                <span class="selected"><a id="search" href="<?php echo $this->search_url ?>" class="Button RedButton search " style="margin-top:0px;  text-decoration:none;color: white;text-shadow: 0px 1px black;" ><?php echo $this->translate('Buscar');?></a></span>
                                <?php if ($this->user_data) { ?>                    
                                <span class="selected"><a id="addEvent" href="<?php echo $this->addEvent_url ?>" class="Button RedButton addEvent " style="margin-top:0px;  text-decoration:none;color: white;text-shadow: 0px 1px black;" ><?php echo $this->translate('Añadir');?></a></span>
                                <?php } else { ?> 
                                <span><a id="addEvent" onclick="addEvent()"  class="Button RedButton addEvent " style="background-color:gray;margin-top:0px;  text-decoration:none;color: white;text-shadow: 0px 1px black;" ><?php echo $this->translate('Añadir');?></a></span>
                                <?php } ?>
                            </strong>    
                        </div>
                    
                </div>
    <div class="" style="min-width: 300px;width:100px;min-height: 24px;height: 25px;padding: 40px 0 12px;text-shadow: 0 1px rgba(255,255,255,0.9);margin-top:160px;clear: both;margin-left: 4%;white-space: nowrap;box-shadow: 0;">
                                <?php  if (!$this->user_data) { ?>                    

                    <p class="input">                            
                                <span class="addtext" style="font-size: 1.3em;font-weight: 300;line-height: 1em;">
                                    <?php echo $this->translate('Para añadir un evento tienes que estar registrado. ');?><a id="register" href="<?php echo $this->register_url ?>" class="Button RedButton register " style="margin-top:0px;  text-decoration:none;color: white;text-shadow: 0px 1px black;font-weight: bold" ><?php echo $this->translate('Regístrate Aquí');?></a>
                                </span>
                    </p>            	
                                <?php } ?>
            </div>

		<?php echo $this->pins;?>
		
		<div class="clear"></div>
    </div>        

<div id="containedor3" style="margin-bottom:20px;margin-right:5%;float: left;width: 20%" >                
            <img src="data/images/eventtos_2.png"  height="330px" width="390px"  >
</div>            


	<?php if($this->follow_user) { ?>
	<script type="text/javascript">
	$(document).ready(function(){
		Pins.initFollow('#container .box.user .follow a');
	});
	</script>
	<?php } ?>
	
<script type="text/javascript">

    function addEvent(){
        $(document).ready(function(){

            $("#input").css({'background-color': '#ccc'});
            $('span.addtext', this).css({'color': 'red'});
            //$('span.addtext', this).css({'color': 'inherit'}).delay(2800);

        });
        
    }
    
function pausecomp(ms) {
        ms += new Date().getTime();
        while (new Date() < ms){}
    }    

</script>
<?php echo $this->footer_part; ?>