<?php 
	$module = $this->getRequest()->getModule();
?>
<form name="admin_form" id="admin_form" method="post" action="">

<div class="info_line top">
	<h3 class="fleft title">
		<img alt="" src="cms/<?php echo $module;?>/images/page_white_link.png">
		<?php echo $this->translate('Mass email');?>
	</h3>
	
	<span id="fader" class="fleft mleft30" style="display:none;">
		<span class="msgError"><span><?php echo $this->translate('Error!');?></span><i class="error_text"></i></span>
	</span>
	
	<?php if($this->errors) { ?>
	<span id="fader" class="fleft mleft30 fdsfsdfsd1"><span class="msgError"><span><?php echo $this->translate('Error!'); ?></span><?php echo implode('<br />', $this->errors);?></span></span>
	<script type="text/javascript"> 
	// <![CDATA[
	$(document).ready(function() {       
		setTimeout(function() {
			$(".fdsfsdfsd1").customFadeOut("slow" ,    
			function() {       
				$(".fdsfsdfsd1").remove();  
			});
		},
		4000);
	});
	// ]]>
	</script>
	<?php } ?>
	
	<?php if($this->successfu_edite) { ?>
	<span id="fader" class="fleft mleft30 fdsfsdfsd"><span class="msgOk"><span><?php echo $this->translate('Success!'); ?></span><?php echo $this->translate('The message was send successfully!'); ?></span></span>
	<script type="text/javascript"> 
	// <![CDATA[
	$(document).ready(function() {       
		setTimeout(function() {
			$(".fdsfsdfsd").customFadeOut("slow" ,    
			function() {       
				$(".fdsfsdfsd").remove();  
			});
		},
		4000);
	});
	// ]]>
	</script>
	<?php } ?>
	
	<div class="fright mtop3">
		<input type="submit" value="<?php echo $this->translate('Save'); ?>" class="button" name="submit">
		<a class="button" href="<?php echo $module;?>/massmail/"><?php echo $this->translate('Cancel'); ?></a>
	</div>
	<div class="clear"></div>
</div>

<div class="clear"></div>

	
	
	
			<table cellspacing="0" cellpadding="0" class="formtable">
				<tbody>
				<tr>
						<td width="150"><?php echo $this->translate('User'); ?>: <img title="<?php echo $this->translate('This field is required'); ?>" class="tooltip" alt="<?php echo $this->translate('This field is required'); ?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
						<td>
							<select name="user">
								<option value="all"><?php echo $this->translate('All users'); ?></option>
								<?php foreach($this->users as $user): ?>
								<option value="<?php echo $user['email']; ?>" <?php if($this->user == $user['email']): ?>selected="selected"<?php endif; ?>><?php echo $user['firstname']; ?> <?php echo $user['lastname']; ?></option>
								<?php endforeach;?>
							</select>
	        			</td>
					</tr>
					<tr>
						<td width="150"><?php echo $this->translate('Title'); ?>: <img title="<?php echo $this->translate('This field is required'); ?>" class="tooltip" alt="<?php echo $this->translate('This field is required'); ?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
						<td>
							<input type="text" size="55" title="<?php echo $this->translate('Please enter a title'); ?>" value="<?php echo $this->title;?>" class="inputbox required" name="title" />
	        				&nbsp;&nbsp; <img title="<?php echo $this->translate('This field is required'); ?>" class="tooltip" alt="Tip" src="cms/<?php echo $module;?>/images/sinfo.gif">
	        			</td>
					</tr>
					<tr>
						<td width="150"><?php echo $this->translate('Message'); ?>: </td>
						<td class="input-textarea">
							<textarea rows="4" cols="53" name="description" title="<?php echo $this->translate('Please enter text'); ?>" class="valid ckeditor_replace"><?php echo $this->description;?></textarea>
	        			</td>
					</tr>
					
				</tbody>
			</table>
		
		<div class="info_line bottom">
			<div class="fright mtop3">
				<input type="submit" value="<?php echo $this->translate('Save'); ?>" class="button" name="submit">
				<a class="button" href="<?php echo $module;?>/massmail/"><?php echo $this->translate('Cancel'); ?></a>
			</div>
			<div class="clear"></div>
		</div>
		
		<div class="clear"></div>
		
	</form>
	
<script type="text/javascript"> 
	$(document).ready(function(){
		$(".tabs ul").idTabs(); 
	});
</script>