<?php if (!isset($_SESSION['token'])) //<?php if(!JO_Session::get('token')) 
{
    echo $this->header_part; 
}    
?>
<script type='text/javascript' src='data/js/js_full.js'></script>
<div id='profile'>
	<div class='banner'>
        <div class="infoBody">    
                        	<div class="tituloCaja">
                            	<h3><?php echo $this->translate('Diary & News');?></h3>
                                <div id="btnCreaMensaje">    
                                	<?php if($this->enable_edit) { ?>                       
                                	<a id="crearAgenda" href="<?php echo $this->popup_agenda;?>" class="Button RedButton message silverboxMessage" ><?php echo $this->translate('Create an Event');?></a>
                                    <?php } ?>
                                </div> 
                            </div>    
                            <div class="noAgenda">
                            	<?php if($this->has_agendas) { ?>
									<?php echo $this->agendas_users ?>
                                <?php } else { ?>
                                    <em><?php echo $this->translate('You have no calendar right now. Write a little bit about your calendar!');?></em>
                                <?php } ?>
                            </div>
                        </div>
</div></div>
<script type="text/javascript">
$(document).ready(function(){
	<?php if($this->enable_edit) { ?>
		var controlSpan="";
		$(".agenda .cuerpoMensaje").click(function(){
			controlSpan=$(this).find(".textoOriginal");
			controlSpan.hide();
			$(this).find(".editaAgenda").show();
			$(this).find(".editaAgenda").focus();
		});
		$(".agenda .cuerpoMensaje .editaAgenda").live('focusout',function() {
			$.post('<?php echo $this->edit_agenda;?>', {texto: $(this).val(),agenda_id:$(this).attr("id")}, function(data){
			}, 'json');
			controlSpan.html(replaceURLWithHTMLLinks($(this).val()));
			$(this).hide();
			controlSpan.show();
		});
	<?php } ?>
	$(".cuerpoMensaje .textoOriginal").each(function(){
		var text = $(this).html();
    	$(this).html(replaceURLWithHTMLLinks(text));
	});
	
	function replaceURLWithHTMLLinks(text) {
		var exp = /(\b(https?|ftp|file):\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/ig;
		return text.replace(exp,"<a class='linkHover' target='_blank' href='$1' title='Seguir vínculo'>$1</a>"); 
	  }
});
</script>

