<div style="width:100%;float:left">
<div class="agenda">
	<div class="chinchetaAzul"></div>
	<?php if($this->enable_edit) { ?>
		<a class="btnBorrar silverboxMessage" href="<?php echo $this->agenda['hrefDelete'];?>" title="<?php  echo $this->translate('Borrar'); ?>"></a>
    <?php } ?>
	<div class="cuerpoMensaje">   
    	<textarea id="<?php echo $this->agenda['agenda_id'];?>" class="editaAgenda" style="display:none"  maxlength="250"><?php echo strip_tags($this->agenda['texto']);?></textarea>
    	<span class="textoOriginal"><?php echo $this->agenda['texto'];?></span>
	</div>
</div>     
</div>