<div id="create_new_pin">
	<div id="content-holder">
		<div id="emailpin">
			<form action="<?php echo $this->agendaPopupDelete;?>" method="post">
				<div class="hide">
					<input type="hidden" name="agenda_id" id="agenda_id" value="<?php echo $this->agenda_id;?>">
				</div>
				
				<div class="left w335px">
					<p>
                                            <div id="dialog-confirm" title="<?php echo $this->translate('Delete');?>">
                                                <p><span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;"></span><label for="message"><?php echo $this->translate('These items will be permanently deleted and cannot be recovered. Are you sure?');?></label></p>
                                            </div>
					</p>
					<p class="submit"><input type="submit" value="<?php echo $this->translate('Delete');?>"></p>
					<div class="clear"></div>
				</div>
				<div class="clear"></div>
			</form>
		</div>
	</div>
</div>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<?php $key = str_replace('.','',microtime(true));?>
<script type="text/javascript">
$(document).ready(function(){

$('html, body').animate({ scrollTop: $('#create_new_pin').offset().top }, 'slow');

	$('#emailpin form').unbind('submit').submit(function(){
		$('#emailpin form .submit input').after('<img src="data/images/loading_2.gif" id="loading_button" />');
		$('#emailpin form .submit input').attr('disabled', true).addClass('disabled');
                var agenda_id = $('#agenda_id').val();
		$.post('<?php echo $this->from_url;?>', {agenda_id:agenda_id}, function(data,status){
			$('#loading_button').remove();
                        var urlagenda = '<?php echo $this->urlagenda ;?>';
			window.location.href = urlagenda;//document.referrer;
                        $.fancybox.close();
			
			
                });
		return false;
	});
		
});


</script>