<script type='text/javascript' src='data/js/js_full.js'></script>
<div id="ProfileHeader">
    <div class="FixedContainer row clearfix">
        <div class="infoBody">    
                        	<div class="tituloCaja">
                            	<h3><?php echo $this->translate('Diary & News');?></h3>
                                <div id="btnCreaMensaje">    
                                	<?php if($this->enable_edit) { ?>                       
                                	<a id="crearAgenda" href="<?php echo $this->popup_agenda;?>" class="Button RedButton message silverboxMessage" ><?php echo $this->translate('Create an Event');?></a>
                                    <?php } ?>
                                </div> 
                            </div>    
                            <div class="noAgenda">
                            	<?php if($this->has_agendas) { ?>
									<?php echo $this->agendas_users ?>                                     
                                <?php } else { ?>
                                    <em><?php echo $this->translate('You have no calendar right now. Write a little bit about your calendar!');?></em>
                                <?php } ?>
                            </div>
                        </div>
    </div>

       
</div>

