<div class="box person <?php echo ($this->key ? 'odd' : '');?>" id="<?php echo $this->user['user_id'];?>" style="padding-bottom: 48px">
    <img src="<?php echo $this->user['avatar'] ?>" class="profile user_image" alt="Profile picture of <?php echo $this->user['fullname'] ?>">
    <!--a style="background-image: url(<?php echo $this->user['avatar'];?>); filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='<?php echo $this->user['avatar'];?>',sizingMethod='scale');-ms-filter: \"progid:DXImageTransform.Microsoft.AlphaImageLoader(src='<?php echo $this->user['avatar'];?>',sizingMethod='scale')\";" class="PersonImage ImgLink" href="<?php echo $this->user['href'];?>"></a-->
			<!--p class="thumb">
				<a class="PersonImage" href="<?php echo $this->user['href'];?>">
					<img style="height:110px;width:110px;" data-original="<?php echo $this->user['avatar'];?>" src="data/images/grey.gif" alt="<?php echo $this->user['fullname'];?>" />
				</a>
			</p-->

		<div class="PersonInfo">
                        <div style="display:table">
                            <div style="display:table-row">
                                <div style="display:table-cell">
                                    <h2><?php echo $this->user['fullname'];?></h2>
                                </div><div style="display:table-cell">
                                    <div class="follow">
<!--------------------------------------------------------------->


    <?php if ($this->loged) { ?>
    <?php 
			echo '<div id="divMailsHeader" style="border-bottom:0px">';
				echo '<a id="newMail" href="'.$this->addMail.'?user_fullname='.$this->user['fullname'].'" class="silverbox" title="'.$this->translate('Enviar mensaje').'">'.$this->translate('Nuevo mensaje').'</a>';
			echo '</div>';
	}
	?>
    <script type="text/javascript">
			$(document).ready(function() 
				{
                                    /*
					$("#newMail").click(function (){
						$("#divMails").fadeOut();
					});
					$(".messagesContent").click(function (){
						$("#divMails").fadeOut();
					});
        */
					$("._5c9q").click(function (){
						if ($(this).hasClass("NOleido"))
						{
							$.post('<?php echo $this->stateMail;?>', {id:$(this).attr("id"),read:1}, function(data){
								if (data.data.unread==0)
								{
									$("#avisoMensajes").hide();
								}else
								{
									$("#avisoMensajes").html(data.data.unread);
									$("#avisoMensajes").show();
								}
							}, 'json');
							$("#mail" + $(this).attr("id")).removeClass("NOleido");
							$(this).removeClass("NOleido");
							$(this).attr("title","<?php echo $this->translate('Marcar la conversación como no leída'); ?>");
						}else
						{
							$.post('<?php echo $this->stateMail;?>', {id:$(this).attr("id"),read:0}, function(data){
								$("#avisoMensajes").html(data.data.unread);
								$("#avisoMensajes").show();
							}, 'json');
							$("#mail" + $(this).attr("id")).addClass("NOleido");
							$(this).addClass("NOleido");	
							$(this).attr("title","<?php echo $this->translate('Marcar la conversación como leída'); ?>");
											
						}
						return false;
					});
                                        /*
					$("#muestraMensajes .ados").click(function (){
						if ($("#divMails").is(":visible"))
						{
							$("#divMails").fadeOut();
						}else
						{
							$("#divMails").fadeIn();
						}
						return false;
					});
					$("#avisoMensajes").click(function (){
						if ($("#divMails").is(":visible"))
						{
							$("#divMails").fadeOut();
						}else
						{
							$("#divMails").fadeIn();
						}
						return false;
					});
                                        */
				});
	</script>


<!--------------------------------------------------------------->
			</div>
                        </div>
                        </div>
                        </div>
                        <div style="display:table">
                            <div style="display:table-row">
                                <div style="display:table-cell">
                                    <p class="location colorless"><?php echo $this->translate('Ubicación activate:');?> </div>
                                <div style="display:table-cell">
                                    <?php echo $this->user['location'];?></p>
                                </div>
                            </div><div style="display:table-row">
                                <div style="display:table-cell">
                                    <p class="location colorless"><?php echo $this->translate('Deporte:');?> </div>
                                <div style="display:table-cell">
                                    <?php echo $this->user['sport_category_1'];?></p>
                                </div>
                            </div><div style="display:table-row">
                                <div style="display:table-cell">
                                    <p class="location colorless"><?php echo $this->translate('Nivel:');?> </div>
                                <div style="display:table-cell">
                                    <?php echo $this->user['level'];?></p>
                                </div>
                            </div><div style="display:table-row">                                
                                <div style="display:table-cell">
                                    <p class="location colorless"><?php echo $this->translate('Opciones:');?> </div>
                                <div style="display:table-cell">
                                    <?php echo ($this->user['option1'] == '1' ? sprintf($this->translate("Practice sports together")) : ''); ?>
                                    <?php echo ($this->user['option2'] == '1' ? sprintf($this->translate("Organize match / tournament")) : ''); ?> 
                                    <?php echo ($this->user['option3'] == '1' ? sprintf($this->translate("Team look for sportman")) : ''); ?> 
                                    <?php echo ($this->user['option4'] == '1' ? sprintf($this->translate("Sportman look for team")) : ''); ?> 
                                    <?php echo ($this->user['option5'] == '1' ? sprintf($this->translate("Look for sponsor")) : ''); ?> 
                                    <?php echo ($this->user['option6'] == '1' ? sprintf($this->translate("Volunteer helps paraolimpics")) : ''); ?> 
                                    <?php echo ($this->user['option7'] == '1' ? sprintf($this->translate("Trainee look for tutor")) : ''); ?> 
                                    <?php echo ($this->user['option8'] == '1' ? sprintf($this->translate("Tutor begins trainee"))  : ''); ?> 
                                    </p>
                                </div>
                            </div><div style="display:table-row">
                                <div style="display:table-cell;height:98px">
                                    <p class="location colorless"><?php echo $this->translate('Comentarios:');?> </div>
                                <div style="display:table-cell" id="divComentarios">
                                    <?php echo $this->user['comment'];?></p>
                                </div>
                            </div></div>
			
		</div>

</div>