<div class="box person <?php echo ($this->key ? 'odd' : '');?>" id="<?php echo $this->user['user_id'];?>" style="padding-bottom: 48px;border-color: #cccaca;border-width: 1px;border-style: solid; padding: 5px;margin-top: 10px" >
    <img style="padding-top: 10px;" src="<?php echo $this->user['avatar'] ?>" class="profile user_image" alt="Profile picture of <?php echo $this->user['fullname'] ?>">
    <!--a style="background-image: url(<?php echo $this->user['avatar'];?>); filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='<?php echo $this->user['avatar'];?>',sizingMethod='scale');-ms-filter: \"progid:DXImageTransform.Microsoft.AlphaImageLoader(src='<?php echo $this->user['avatar'];?>',sizingMethod='scale')\";" class="PersonImage ImgLink" href="<?php echo $this->user['href'];?>"></a-->
			<!--p class="thumb">
				<a class="PersonImage" href="<?php echo $this->user['href'];?>">
					<img style="height:110px;width:110px;" data-original="<?php echo $this->user['avatar'];?>" src="data/images/grey.gif" alt="<?php echo $this->user['fullname'];?>" />
				</a>
			</p-->
                        
		<div class="PersonInfo">
                        <div style="display:table;width: 100%">
                            <div style="display:table-row">
                                <div style="display:table-cell">
                                    <h2><?php echo $this->user['fullname'];?></h2>
                                </div><div style="display:table-cell">
                                    <div class="follow" style="margin-left:10px;float: right">
<!--------------------------------------------------------------->
    <?php if (!$this->loged) { ?>
                        <a class="red mbtn" href="users/register" style="width:95px !important;height:48px !important"><?php echo $this->translate('Regístrate para contactar'); ?></a>
    <?php } ?>


    <?php if ($this->loged) { ?>
    <?php 
			echo '<div id="divMailsHeader" style="border-bottom:0px">';
                        echo '<a class="red mbtn" id="newMail" href="'.$this->addMail.'?user_voluntario_name='.$this->user['fullname'].'" class="silverbox" title="'.$this->translate('Enviar mensaje').'">'.$this->translate('Nuevo mensaje').'</a>';
			echo '</div>';
    } ?>

    <script type="text/javascript">
			$(document).ready(function() 
				{
                                    /*
					$("#newMail").click(function (){
						$("#divMails").fadeOut();
					});
					$(".messagesContent").click(function (){
						$("#divMails").fadeOut();
					});
        */
					$("._5c9q").click(function (){
						if ($(this).hasClass("NOleido"))
						{
							$.post('<?php echo $this->stateMail;?>', {id:$(this).attr("id"),read:1}, function(data){
								if (data.data.unread==0)
								{
									$("#avisoMensajes").hide();
								}else
								{
									$("#avisoMensajes").html(data.data.unread);
									$("#avisoMensajes").show();
								}
							}, 'json');
							$("#mail" + $(this).attr("id")).removeClass("NOleido");
							$(this).removeClass("NOleido");
							$(this).attr("title","<?php echo $this->translate('Marcar la conversación como no leída'); ?>");
						}else
						{
							$.post('<?php echo $this->stateMail;?>', {id:$(this).attr("id"),read:0}, function(data){
								$("#avisoMensajes").html(data.data.unread);
								$("#avisoMensajes").show();
							}, 'json');
							$("#mail" + $(this).attr("id")).addClass("NOleido");
							$(this).addClass("NOleido");	
							$(this).attr("title","<?php echo $this->translate('Marcar la conversación como leída'); ?>");
											
						}
						return false;
					});
                                        /*
					$("#muestraMensajes .ados").click(function (){
						if ($("#divMails").is(":visible"))
						{
							$("#divMails").fadeOut();
						}else
						{
							$("#divMails").fadeIn();
						}
						return false;
					});
					$("#avisoMensajes").click(function (){
						if ($("#divMails").is(":visible"))
						{
							$("#divMails").fadeOut();
						}else
						{
							$("#divMails").fadeIn();
						}
						return false;
					});
                                        */
				});
	</script>


<!--------------------------------------------------------------->
			</div>
                        </div>
                        </div>
                        </div>
                        <div style="display:table">
                            <div style="display:table-row">                                
                                <div style="display:table-cell">
                                    <p class="location colorless"><?php echo $this->translate('Opciones:');?> </div>
                                <div style="display:table-cell">
                                    <?php echo ($this->user['option1'] == '1' ? sprintf($this->translate("Deportista, individual o club, da charlas a grupos, colegios...")) : ''); ?>
                                    <?php echo ($this->user['option2'] == '1' ? sprintf($this->translate("Comparto mi experiencia de superación, charlas para grupos, colegios...")) : ''); ?> 
                                    <?php echo ($this->user['option3'] == '1' ? sprintf($this->translate("Apoyo a rehabilitación")) : ''); ?> 
                                    <?php echo ($this->user['option4'] == '1' ? sprintf($this->translate("Ayuda o entrenamiento a paralímpicos")) : ''); ?> 
                                    <?php echo ($this->user['option5'] == '1' ? sprintf($this->translate("Entrenamiento a deportista o equipo")) : ''); ?> 
                                    <?php echo ($this->user['option6'] == '1' ? sprintf($this->translate("Agrupación con otros volunttarios")) : ''); ?> 
                                    <?php echo ($this->user['option7'] == '1' ? sprintf($this->translate("Colaboración con ONG como volunttario")) : ''); ?> 
                                    <?php echo ($this->user['option8'] == '1' ? sprintf($this->translate("Participación o colaboración en eventos deportivos solidarios"))  : ''); ?> 
                                    <?php echo ($this->user['option9'] == '1' ? sprintf($this->translate("Donación material usado o nuevo"))  : ''); ?>                                     
                                    <?php echo ($this->user['option10'] == '1' ? sprintf($this->translate("Coaching, motivación, apoyo psicológico")) : ''); ?>
                                    <?php echo ($this->user['option11'] == '1' ? sprintf($this->translate("Asesoría sobre salud, lesiones y nutrición en el deporte")) : ''); ?>
                                    <?php echo ($this->user['option12'] == '1' ? sprintf($this->translate("Presto instalaciones deportivas")) : ''); ?> 
                                    <?php echo ($this->user['option13'] == '1' ? sprintf($this->translate("Patrocinio o copatrocinio equipo o deportista")) : ''); ?> 
                                    <?php echo ($this->user['option14'] == '1' ? sprintf($this->translate("Entradas o abonos para eventos deportivos")) : ''); ?> 
                                    <?php echo ($this->user['option15'] == '1' ? sprintf($this->translate("ONG ayuda a superar problemas para tomar la salida")) : ''); ?> 
                                    <?php echo ($this->user['option16'] == '1' ? sprintf($this->translate("Árbitros o jueces deportivos")) : ''); ?> 
                                    <?php echo ($this->user['option17'] == '1' ? sprintf($this->translate("Ayudo a personas mayores a hacer ejercicio")) : ''); ?> 
                                    <?php echo ($this->user['option18'] == '1' ? sprintf($this->translate("Otros (descripción en los comentarios)"))  : ''); ?> 
                                    
                                    </p>
                                </div>
                            </div>                            
                            <div style="display:table-row">
                                <div style="display:table-cell">
                                    <p class="location colorless"><?php echo $this->translate('Zona geográfica:');?> </div>
                                <div style="display:table-cell;vertical-align: bottom">
                                    <?php echo $this->user['location'];?></p>
                                </div>
                            </div>
                            <div style="display:table-row">
                                <div style="display:table-cell">
                                    <p class="location colorless"><?php echo $this->translate('Deporte:');?> </div>
                                <div style="display:table-cell">
                                    <?php echo $this->user['sport_category'];?></p>
                                </div>
                            </div>
                            <div style="display:table-row">
                                <div style="display:table-cell;height:98px">
                                    <p class="location colorless"><?php echo $this->translate('Comentarios:');?> </div>
                                <div style="display:table-cell" id="divComentarios">
                                    <?php echo $this->user['comment'];?></p>
                                </div>
                            </div>
                        </div>
		</div>
</div>