
<script>
	var emptyValidationMsg = "<?php echo $this->translate('This field is required.') ?>";
	var error = false;
	
	function clearMsg(){
		$(".loginErrMsg").empty();
	}
	
	function validate(error){
			clearMsg();
			if($('#user').val() == ''){
				$("#user").next().append(emptyValidationMsg)
                                try
                                {
                                    console.log("BN")
                                }
                                catch(e)
                                {
                                    if (window.console // check for window.console not console
                                        && window.console.log)
                                    {
                                        window.console.log("BN")
                                    }
                                }
				error = true;
			
			
			}
			
			if($('#password').val() == ''){
				
				if(document.getElementById('password').style.display == 'none')
                                {
                                    try
                                    {
                                        console.log("NOSD")
                                    }
                                    catch(e)
                                    {
                                        if (window.console // check for window.console not console
                                            && window.console.log)
                                        {
                                            window.console.log("NOSD")
                                        }
                                    }
				}
				else{
					$("#password").next().append(emptyValidationMsg)
                                        try
                                        {
                                            console.log("BN")
                                        }
                                        catch(e)
                                        {
                                            if (window.console // check for window.console not console
                                                && window.console.log)
                                            {
                                                window.console.log("BN")
                                            }
                                        }
					error = true;
				}
				
			}
			
			
			submit(error);
		
	}	
	
	
	function forgottenPassValidate(){
		clearMsg();
			if($('#user').val() == ''){
				$("#user").next().append(emptyValidationMsg)
                                try
                                {
                                    console.log("BN")
                                }
                                catch(e)
                                {
                                    if (window.console // check for window.console not console
                                        && window.console.log)
                                    {
                                        window.console.log("BN")
                                    }
                                }
				error = true;
			
			
			}
	}
	
	
	function submit(error){
                try
                {
                    console.log(error)
                }
                catch(e)
                {
                    if (window.console // check for window.console not console
                        && window.console.log)
                    {
                        window.console.log(error)
                    }
                }
		if(error == false){
			$('form').submit();
		}
		
		else{
			error = false;
		}
	}
	
	

	function forgottenPass(param){
		if(param == 'show'){
			$("#password").hide();
			$("#resetPassword").hide();
			$("#backToLogin").show();
			$("#forgotPass").val('1');
			$("#login").val('1');
			
		}
		
		else{
			$("#password").show();
			$("#backToLogin").hide();
			$("#resetPassword").show();
			$("#forgotPass").val('0');
			$("#login").val('0');
		}
                try
                {
                    console.log($("#forgotPass").val());
                }
                catch(e)
                {
                    if (window.console // check for window.console not console
                        && window.console.log)
                    {
                        window.console.log($("#forgotPass").val());
                    }
                }
	}
	

	$(document).ready(function(){
	
		$('.user').focus(function(){
                try
                {
                    console.log("co")
                }
                catch(e)
                {
                    if (window.console // check for window.console not console
                        && window.console.log)
                    {
                        window.console.log("co")
                    }
                }
		$(this).next().empty();
		$("#resetPassword").live("tap",function(){
			$(".loginErrMsg").empty();
		})
		$("#backToLogin").live("tap",function(){
			$(".loginErrMsg").empty();
		})
	})
	
	$(".submit").live('tap',function(){
                try
                {
                    console.log("submit")
                }
                catch(e)
                {
                    if (window.console // check for window.console not console
                        && window.console.log)
                    {
                        window.console.log("submit")
                    }
                }
		validate(error);
	})
	
	

	//$('#loginForm').submit()
})

</script>
	<?php $base_url=JO_Request::getInstance()->getBaseUrl();?>
    <body class="hdpi">
        <div class="page short" id="wrapper">
            <div id="logo_wrapper">
                <div id="logo">
                    <a href="<?php echo $base_url?>" ontouchstart="">
                       
                        	<img src='<?php echo "uploads".JO_Registry::get('site_logo'); ?>' style='height:30px'/>
                        
                    </a>
                </div>
            </div>

            <div class="divider"></div>

            <div class="middle_cont" id="login">
                <h2><?php echo $this->translate('Login and start pinning.') ?></h2>

                <div id="social">
                    <a href="<?php echo $this->login_facebook?>">
                        <div class="facebook"></div>
                    </a>

                    <a href="<?php echo $this->login_twitter; ?>" ontouchstart="">
                        <div class="twitter"></div>
                    </a>
                </div>
            </div> <!-- End Middle container -->

            <div class="divider bottom"></div>

            <div class="last_cont" id="connect">
                

            <div id='loginResultError' style="width: 100%; text-align: center; color: red;margin-top:20px">
            	<?php if($this->error !== 0){
            		echo $this->translate($this->error); 
            	} ?>
            </div>
            
            <div id='success' style="width: 100%; text-align: center; color: green ;margin-top:20px">
            	<?php if($this->successful !== 0){
            		
					echo $this->translate($this->successful);
            	} ?>
            </div>

                
                 
                

                <form action="" method="POST" accept-charset="utf-8" id='loginForm'>
             		<input type="hidden" id='login' name='login' value="1">
             		<input type="hidden" id='forgotPass' name='forgot_password' value='0' />
                    <input class="user" id='user' name="email" placeholder="<?php echo $this->translate('Your Email Address'); ?>" type="text">
                    <div class='loginErrMsg' style='color:red;text-align:center;padding-bottom:5px '>
                    	
                    </div>


                    <input class="user password" id='password' name="password" placeholder="<?php echo $this->translate('Your Password') ?>" type="password">
                      <div class='loginErrMsg' style='color:red;text-align:center;padding-bottom:5px '>
                    	
                    </div>

                    <div class="non_inputs">
                        <a class="red mbtn" type="submit" class="submit">
                            <strong class="submit"><?php echo $this->translate('Login')?></strong>
                            <span class="submit"></span>
                        </a>
                        <a class="loginLink" id="resetPassword" ontouchstart="forgottenPass('show')" href="#"><?php echo $this->translate('Forgot your password?'); ?></a>
                        <a class="loginLink" id="backToLogin" ontouchstart="forgottenPass('hide')" href="#"><?php echo $this->translate('Back to login?'); ?></a>
                    </div>
                </form>

            </div> <!-- End Bottom container -->

            <div class="push"></div>
        </div> <!-- End Wrapper -->
