<script type='text/javascript' src='data/js/js_full.js'></script>
<div id="ProfileHeader">
                <div class="FixedContainer row clearfix">
                        <div class="infoMessage"> 
                            <?php if($this->has_messages || !$this->enable_edit) { ?>
                            <h5><?php echo $this->translate('Conversation');?></h5>
                            <?php if($this->loged) { ?> 
                            	 <div id="btnCreaMensaje"> 
                                    <a href="<?php echo $this->popup_messages;?>" class="Button  noMessage  " title="<?php echo $this->translate('Create a Message');?>"><?php echo $this->translate('Create a Message');?></a>
                                 </div>
                                    <?php } ?>
                            <p class="colorless noMessage">
                                <?php echo $this->messages_users ?>&nbsp;
                            </p>
                            <?php } else { ?>
                            <h5><?php echo $this->translate('Conversation');?></h5>
                            <?php if($this->loged) { ?> 
                            	 <div id="btnCreaMensaje"> 
                                    <a href="<?php echo $this->popup_messages;?>" class="Button  noMessage  " title="<?php echo $this->translate('Create a Message');?>"><?php echo $this->translate('Create a Message');?></a>
                                 </div>
                                    <?php } ?>
                            <p class="colorless noMessage">
                                    <em><?php echo $this->translate('You have no messages right now. Write one!');?></em>
                                    
                            </p>
                            <?php } ?>
                        </div>
                    
                </div>

        </div>
<script type="text/javascript">
$(document).ready(function(){    
	$(".cuerpoMensaje").each(function(){
		var text = $(this).html();
    	$(this).html(replaceURLWithHTMLLinks(text));
	});
	
	function replaceURLWithHTMLLinks(text) {
		var exp = /(\b(https?|ftp|file):\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/ig;
		return text.replace(exp,"<a class='linkHover' target='_blank' href='$1' title='Seguir vínculo'>$1</a>"); 
	  }
});
</script>     

