    <?php if($this->enable_edit) { ?>
        <div class="mensaje <?php if ($this->message['message_from_id']>0){echo "hijo";} ?>">
        	<div class="cabeceraMensaje">
            	<div class="imagen">
            		<a style="background-image: url(<?php echo $this->message['avatar'];?>)" class="PersonImageLittle ImgLink" href="<?php echo $this->message['href'];?>" title="Ver perfil"></a> 
                </div>
                <div class="nombreUsu">
                	<?php echo $this->message['fullname'];?>:
                </div>
            </div>
            <div class="cuerpoMensaje">
                <?php echo $this->message['text_message'];?>
            </div>
                  
        <?php if($this->userdata["user_id"]>0) { ?> 
        	 
        	<a class="btnBorrar silverboxMessage" href="<?php echo $this->message['hrefDelete'];?>" title="<?php  echo $this->translate('Borrar'); ?>"></a> 
            <?php if($this->message['message_from_id']==0)
				//Sólo pintamos el reply si es un mensaje principal
			{ ?>
            	<a class="btnReply silverboxMessage" href="<?php echo $this->message['hrefResponder'];?>" title="<?php  echo $this->translate('Responder'); ?>"></a>
            <?php } ?> 
            
    	<?php } ?>   
        </div>          
    <?php } else { ?>	
    	 <?php if(($this->message['private_message'] == 0) || ($this->message['from_user_id']==JO_Session::get('user[user_id]'))) { ?>  
            <div class="mensaje <?php if ($this->message['message_from_id']>0){echo "hijo";} ?>">
                <div class="cabeceraMensaje">
                    <div class="imagen">
                        <a style="background-image: url(<?php echo $this->message['avatar'];?>)" class="PersonImageLittle ImgLink" href="<?php echo $this->message['href'];?>" title="Ver perfil"></a> 
                    </div>
                    <div class="nombreUsu">
                        <?php echo $this->message['fullname'];?>:
                    </div>
                </div>
                <div class="cuerpoMensaje">
                    <?php echo $this->message['text_message'];?>
                </div>
                      
            <?php if($this->userdata["user_id"]>0) { ?>  
                 <?php if ($this->message['from_user_id']==JO_Session::get('user[user_id]')) { ?>
                <a class="btnBorrar silverboxMessage" href="<?php echo $this->message['hrefDelete'];?>" title="<?php  echo $this->translate('Borrar'); ?>"></a>   
                <?php } ?>
                <?php if($this->message['message_from_id']==0)
                    //Sólo pintamos el reply si es un mensaje principal
                { ?>
                    <a class="btnReply silverboxMessage" href="<?php echo $this->message['hrefResponder'];?>" title="<?php  echo $this->translate('Responder'); ?>"></a>
                <?php } ?>
                
            <?php } ?>   
            </div>
         <?php } ?> 
    <?php } ?>   
 
    
    
<script type="text/javascript">
$(document).ready(function(){    
	$('#borrar').click(function(){    
                    $('<div></div>').appendTo('body')
                    .html('<div><h6>Are you sure?</h6></div>')
                    .dialog({
                        modal: true, title: 'Delete message', zIndex: 10000, autoOpen: true,
                        width: 'auto', resizable: false,
                        buttons: {
                            Yes: function () {
                                // $(obj).removeAttr('onclick');                                
                                // $(obj).parents('.Parent').remove();

                                $(this).dialog("close");
                            },
                            No: function () {
                                $(this).dialog("close");
                            }
                        },
                        close: function (event, ui) {
                            $(this).remove();
                        }
                    }); 
        }); 
	$(".cuerpoMensaje").each(function(){
		var text = $(this).html();
    	$(this).html(replaceURLWithHTMLLinks(text));
	});
	
	function replaceURLWithHTMLLinks(text) {
		var exp = /(\b(https?|ftp|file):\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/ig;
		return text.replace(exp,"<a class='linkHover' target='_blank' href='$1' title='Seguir vínculo'>$1</a>"); 
	  }
});
</script>        



