<?php //if (!isset($_SESSION['token'])) //<?php if(!JO_Session::get('token')) 
{
    echo $this->header_part; 
}    
?>


<div id='profile'>
	<div class='banner'>
	
		<table class='pinner'>
			<tbody>
				<tr>
					<td class='pinner_image'>
						<img src='<?php echo $this->userdata['avatar'] ?>'  class="profile user_image" alt="Profile picture of <?php echo $this->userdata['fullname'] ?>"/>
					</td>
                                        
					<td>
                                            <span class="name" style="font-weight: bold;"><a href= '<?php echo $this->getRequest()->getBaseUrl().$this->userdata['username'];?>'><?php echo $this->userdata['fullname'] ?></a></span><br>
                                        </td>

                                        <td class="right button_wrapper">
	                
	                	
	                	<?php if(!$this->enable_edit && $this->loged == 1 ): ?>
	                		<?php if($this->userFollowIgnore == 0 ): ?>
                                            <?php if($this->userIsFollow== 1): ?>
                                             <a class="mbtn user red follow" id='follow'  style="float:right;display:none" data-link='<?php echo $this->follow_user ?>'>
                                                     <strong><?php echo $this->translate('Follow') ?></strong><span></span>
                                                             </a>

                                                             <a class="mbtn user unfollow disabled pressed" id='unfollow'  data-link='<?php echo $this->follow_user ; ?>' style="float:right;margin-top:7px;" >
                                                     <strong><?php echo  $this->translate('Unfollow') ?></strong><span></span>
                                                             </a>
                                                              <?php else: ?>
                                                              <a class="mbtn user red follow" id='follow'  style="float:right;" data-link='<?php echo $this->follow_user ?>'>
                                                     <strong><?php echo $this->translate('Follow') ?></strong><span></span>
                                                             </a>

                                                             <a class="mbtn user unfollow disabled pressed" id='unfollow'  data-link='<?php echo $this->follow_user ; ?>' style="float:right;margin-top:7px;display:none" >
                                                     <strong><?php echo  $this->translate('Unfollow') ?></strong><span></span>
                                                             </a>
                                                             <?php endif; ?>
                                                             <?php endif; ?>
	                	<?php endif; ?>
	                </td>
				</tr>
			</tbody>
		</table>
		<div class="stitching">
	                    <div class="stitch"></div>
	                    <div class="stitch white"></div>
	    </div>
	 </div>
	 <?php if($this->active == 'boards'): ?>
	 <!-- profile text -->
	 	<div id="profile_bio"><?php echo $this->userdata['description']; ?></div>
                
	 <ul id='profile_links'>
	 	
	 	
		<!-- user has facebook ? -->	 	
	 	<?php if($this->userdata['facebook_id'] > 0): ?>
	 		<li id='facebook'>
	 			<a class='obtn' href='http://www.facebook.com/<?php echo $this->userdata['facebook_id']; ?>' target='_blank'>
	 				<span>Twitter</span>
	 			</a>
	 		</li>
	 	<?php endif; ?>
	 	
	 	<!-- user has twitter? -->
	 	<?php if($this->userdata['twitter_id']> 0): ?>
	 		<li id='twitter'>
	 			<a class='obtn' href='http://twitter.com/<?php echo $this->userdata['twitter_username']; ?>' target='_blank'>
	 				<span>Twitter</span>
	 			</a>
	 		</li>
	 	<?php endif; ?>
	 	
	 	<!-- user has website ? -->
	 	<?php if($this->userdata['website'] > 0): ?>
	 		<a class="obtn" href="<?php echo $this->userdata['website'] ?>" target="_blank">
                 <span>Website</span>
            </a>
	 	<?php endif; ?>
	 </ul>

	<div class="profile_header likes" style="display: inline-block">
                                        <div style='float:left;'>
                                                <p class="colorless "><?php echo $this->userdata['imageLikes']?> <img src="data/images/meGustaAz.png"> en mis imagenes </p>
                                                <p class="colorless "><?php echo $this->userdata['likers']?> <img src="data/images/meGustaAz.png"> en mi perfil </p>
                                        </div>
            
            <div style='float:right;'>
                
                                                <?php if($this->like_user) { ?>      
                                                      <?php if ($this->userIsLike) { ?>
                                                <a class="Button13 Button WhiteButton Tab liking follow-red<?php echo ($this->userIsLike?' gray':'');?>" href="<?php echo $this->like_user;?>">
                                                        Ya no me gusta <img src="data/images/noMeGustaAz.png">
                                                </a>
                                                      <?php } else { ?>      
                                                <a class="Button13 Button WhiteButton Tab liking follow-red<?php echo ($this->userIsLike?' gray':'');?>" href="<?php echo $this->like_user;?>">
                                                        Me gusta este perfil <img src="data/images/meGustaAz.png">
                                                </a>

                                                      <?php }  ?>   
                                                <?php }  ?>  
            </div>

            
    <?php /* if ($this->enable_edit)
    { 
		//Sacamos el total de mails sin leer del usuario
		$totalmails=Model_Mails::getTotalMails(array('user_id' => JO_Session::get('user[user_id]')));
	?>
<div id="muestraMensajes" style="margin-top: 0px;margin-left: 0px;width: 100px;height: 0px;float: right;right:50px"><a href="#" class="ados" ><img src="data/images/ico_sobre.png" height="18px" alt="<?php echo $this->translate('Mensajes'); ?>"/>&nbsp;<span style="color:#8C7E7E;font-weight: bold"><?php echo $this->translate('Mensajes'); ?></span></a></div>
    <?php
		if ($totalmails>0)
		{
			echo '<div id="avisoMensajes" style="right:-24px !important;top:0px;left:24px;margin-top:0px;">'.$totalmails.'</div>';
		}else
		{
			echo '<div id="avisoMensajes" style="right:-24px !important;top:0px;left:24px;margin-top:0px;display:none">0</div>';
		}
		echo '<div id="divMails" style="display:none;top:95px;left:65px;height:120px;overflow:auto">';
			echo '<div id="cabeceraCajaMails"></div>';
			echo '<div id="divMailsHeader">';
				echo '<a id="newMail" href="'.$this->addMail.'" class="silverbox" title="'.$this->translate('Nuevo mensaje').'">'.$this->translate('Nuevo mensaje').'</a>';
			echo '</div>';
                $totalmailssinleer=Model_Mails::getTotalMailsSinLeer(array('user_id' => JO_Session::get('user[user_id]')));
		if ($totalmailssinleer>0)
		{
			function cambiafyh_espanol($fechaH)
			{
				$traducir_fecha = explode("-",$fechaH);
				$separaHoras=explode(" ",$traducir_fecha[2]);
				$fecha_espana = $separaHoras[0]."/".$traducir_fecha[1]."/".$traducir_fecha[0]." ".$separaHoras[1]; 
				return $fecha_espana;
			}
				echo '<div id="divMailsScroll">';
					//Vamos a sacar el total de mails del usuario
					$mails=Model_Mails::getMails(array('user_id' => JO_Session::get('user[user_id]')));
					echo '<ul>';
					foreach($mails AS $mail) {
						if ($mail["store"]=="amazons3")
						{
							$host='http://' . JO_Registry::get('bucklet') . '.' . trim(JO_Registry::get('awsDomain'),'.') . '/';
							$sufijo="_A.";
						}else
						{
							$host="/uploads";
							$sufijo=".";
						}
						if($mail["avatar"]=="")
						{
							$imageUser="uploads/cache/data/amatteur/amatteur_azul-50x50-crop.jpg";
						}else
						{
							//cogemos la extensión del fichero
							$extension= substr(strrchr($mail["avatar"], '.'), 1);
							//ahora la quitamos
							$nombreSextension=substr($mail["avatar"], 0,strlen($mail["avatar"])-strlen($extension)-1);
							$imageUser=$host.$nombreSextension.$sufijo.$extension;
						}
						$textLeido="";
						$textToolTip=$this->translate('Marcar la conversación como no leída');
						if ($mail["read_mail"]==0)
						{
							$textLeido="NOleido";
							$textToolTip=$this->translate('Marcar la conversación como leída');
						}
						if ($mail["parent_mail_id"]==0)
						{
							$id=$mail["mail_id"];
						}else
						{
							$id=$mail["parent_mail_id"];
						}
						echo '<li>
								<a class="silverbox messagesContent '.$textLeido.'" href="'.$this->viewMail.'?id='.$id.'" role="button" id="mail'.$mail["mail_id"].'" title="'.$this->translate('Mensajería').'">
								<div class="clearfix">
									<div class="imagenMails">
										<div class="_55lt" style="width:50px;height:50px;" size="50" data-reactid=".r[33odf]">
											<img class="img" src="'.$imageUser.'" width="50" height="50" data-reactid=".r[33odf].[0]">
										</div>
									</div>
									<div class="textoMails">
										<div class="content fsm fwn fcg" style="margin-left:0px">
											<div class="author">
												<strong>'.$mail["fullname"].'</strong>
											</div>
											<div class="prwText">
												<span>'.str_replace("<br/>"," ",$mail["text_mail"]).'</span>
											</div>
											<div class="time">
												<abbr title="" class="timestamp">'.cambiafyh_espanol($mail["date_mail"]).'</abbr>
											</div>
										</div>
									</div>
									<div class="x_div"><div class="_5c9q '.$textLeido.'" id="'.$mail["mail_id"].'" title="'.$textToolTip.'"></div></div>
								</div>
								</a>
							</li>';
					}
					echo '</ul>';
				echo '</div>';
				echo '<div id="divMailsFooter">';
				echo '</div>';
			
		}
		echo '</div>';
	}
*/	?>
    <!--script type="text/javascript">
			$(document).ready(function() 
				{
					$("#newMail").click(function (){
						$("#divMails").fadeOut();
					});
					$(".messagesContent").click(function (){
						$("#divMails").fadeOut();
					});
					$("._5c9q").click(function (){
						if ($(this).hasClass("NOleido"))
						{
							$.post('<?php echo $this->stateMail;?>', {id:$(this).attr("id"),read:1}, function(data){
								if (data.data.unread==0)
								{
									$("#avisoMensajes").hide();
								}else
								{
									$("#avisoMensajes").html(data.data.unread);
									$("#avisoMensajes").show();
								}
							}, 'json');
							$("#mail" + $(this).attr("id")).removeClass("NOleido");
							$(this).removeClass("NOleido");
							$(this).attr("title","<?php echo $this->translate('Marcar la conversación como no leída'); ?>");
						}else
						{
							$.post('<?php echo $this->stateMail;?>', {id:$(this).attr("id"),read:0}, function(data){
								$("#avisoMensajes").html(data.data.unread);
								$("#avisoMensajes").show();
							}, 'json');
							$("#mail" + $(this).attr("id")).addClass("NOleido");
							$(this).addClass("NOleido");	
							$(this).attr("title","<?php echo $this->translate('Marcar la conversación como leída'); ?>");
											
						}
						return false;
					});
					$("#muestraMensajes .ados").click(function (){
						if ($("#divMails").is(":visible"))
						{
							$("#divMails").fadeOut();
						}else
						{
							$("#divMails").fadeIn();
						}
						return false;
					});
					$("#avisoMensajes").click(function (){
						if ($("#divMails").is(":visible"))
						{
							$("#divMails").fadeOut();
						}else
						{
							$("#divMails").fadeIn();
						}
						return false;
					});
                                        
                                       $(document).live("click", function() { 
						if ($("#divMails").is(":visible"))
						{
							$("#divMails").fadeOut();
						}                                           
                                       });
                                     
				});
	</script-->

            
            
            
                                    <br>
                                <div style='width:100%;clear:none;overflow:none'>

                                 <div style='clear:both'>

                                  <div style='float:left;width:50%;'>
                                 <div style='clear:both'>

                                  <div style='float:left;width:100%;'>

                                    <span style="padding-bottom:15px;color: #8C7E7E;font-weight: 600;">
                                     <?php  $users_sports = Model_Users::getUserSports($this->userdata['user_id']); ?>
                                    <?php if  ($users_sports) { ?>

                                        <?php  $i = 0; ?>
                                     <?php  foreach ($users_sports as $user_sports){ $i++; ?>
                                    <?php if (!Model_Boards::isCategoryParent($user_sports['sport_category'])) ?>
                                    <?php   { ?>
                                    <?php       echo Model_Boards::getCategoryTitle($user_sports['sport_category']);?>
                                    <?php    } ?>
                                    <?php if  ($i > 2 || count($users_sports) == $i) { break; } else { echo ", " ;} ?>                                        
                                    <?php } ?>                                        

                                    <?php } else { ?>
                                        &nbsp;
                                    <?php }  ?>    
                                    </span>                                        

                                    <?php /*if($this->userdata['sport_category_1']) { ?>
                                    <span style="padding-bottom:15px;color: #8C7E7E;font-weight: 600;"><?php echo $this->translate("Sports: "). " " . Model_Boards::getCategoryTitle($this->userdata['sport_category_1']). ", ". Model_Boards::getCategoryTitle($this->userdata['sport_category_2']) . ", ". Model_Boards::getCategoryTitle($this->userdata['sport_category_3']);?></span>
                                    <?php } */ ?>
                                    </div>
                                    </div>                                    

                                 <div style='clear:both'>

                                  <div style='float:left;width:100%'>
                                    
                                    <?php if($this->userdata['type_user']) { ?>
                                    <span style="padding-bottom:5px;color: #8C7E7E;font-weight: 600;"><?php echo  Model_Users::getUserTypeTitle($this->userdata['type_user']);?></span>
                                    <?php } ?>
                                    </div>
                                    </div>                                    

                                </div>
                                <div style='float:left;width:50%'> 

                                                <?php if($this->enable_edit && !$this->userCanActivate) { ?>
                                                      <?php if (!$this->userIsActivate) { ?>
                                                    <img src="data_mobile/images/activateNo.png">
                                                    <a id="activate" href="<?php echo $this->popup_activate;?>" class="red mbtn " style="margin-top:0px;" ><?php echo $this->translate('Activate');?></a>
                                                      <?php } else { ?>
                                                    <img src="data_mobile/images/activateSi.png">
                                                    <a id="activate" href="<?php echo $this->popup_activate;?>" class="red mbtn " style="margin-top:0px;" ><?php echo $this->translate('Activate');?></a>
                                                      <?php } ?>

                                                <?php } ?>
                                                    

                                    </div>
                                    </div>
                                    </div>                                                
        </div>
        <div>
                    
	<ul class='taplist'>
		<li class="tappable">
					
                    <a class="tappable_link" href="<?php echo $this->user_pins ?>">
                      <?php echo $this->userdata['pins']; ?> <?php  echo $this->translate('pins'); ?>
                   <div class="touch_arrow"></div>
             </a>
        </li>
        
        <li class="tappable">
                    <a class="tappable_link" href="<?php echo $this->user_pins_likes?>">
                       <?php echo $this->userdata['likes']; ?> <?php  echo $this->translate('likes'); ?>
                    <div class="touch_arrow"></div>
             </a>
        </li>
        
        <li class="tappable">
                    <a class="tappable_link" href="<?php echo $this->user_followers ?>">
                        <?php echo $this->userdata['followers']; ?> <?php  echo $this->translate('followers'); ?>
                    	<div class="touch_arrow"></div>
             </a>
        </li>
        
        <li class="tappable">
                    <a class="tappable_link" href="<?php echo $this->user_following?>">
                        <?php echo $this->userdata['following']; ?> <?php  echo $this->translate('following'); ?>
                  <div class="touch_arrow"></div>
             </a>
        </li>
        <li class="tappable">
            <a class="tappable_link" href="<?php echo $this->user_likers;?>" >
                        <strong><?php echo $this->userdata['likers'];?></strong> <?php echo $this->translate('likers');?>
                        <div class="touch_arrow"></div>
            </a>
        </li>
        <li class="tappable">
            <a class="tappable_link" href="<?php echo $this->user_liking;?>" >
                        <strong><?php echo $this->userdata['liking'];?></strong> <?php echo $this->translate('liking');?>
                        <div class="touch_arrow"></div>
            </a>
        </li>
        
        <li class="tappable">
            <a class="tappable_link"  href="<?php echo $this->user_activity;?>" >
                        <?php echo $this->translate('Activity');?>
                <div class="touch_arrow"></div>
            </a>
        </li>
        <li class="tappable">
                    <a class="tappable_link" href="<?php echo $this->urlagenda?>">
                         <?php  echo $this->translate('agenda'); ?>
                  <div class="touch_arrow"></div>
             </a>
        </li>
        <li class="tappable">
                    <a class="tappable_link" href="<?php echo $this->urlmensajes?>">
                         <?php  echo $this->translate('mensajes'); ?>
                  <div class="touch_arrow"></div>
             </a>
        </li>

        
	</ul>
        </div>                    
	<div class="profile_header bottom"></div>
	
	
	<!--userboards start here -->
	
	<div class='user_boards'>
		<ul>
                    
			<?php echo $this->boards ?>

		</ul>
        <?php /*if ($this->active == 'boards') { ?>
        <div id="ProfileHeader">
                <div class="FixedContainer row clearfix">
                        <div class="infoBody">        
                            <?php if($this->userdata['agenda'] || !$this->enable_edit) { ?>
                            <h5>Agenda y Actualidad</h5>
                            <p class="colorless noAgenda">
                                    <?php echo nl2br($this->userdata['agenda']);?>&nbsp;
                                    <!--img src="data/images/ProfileEditIcon.png"-->
                            </p>
                            <?php } /*else { ?>
                            <h5>Agenda y Actualidad</h5>
                            <p class="colorless noAgenda">
                                    <em><?php echo $this->translate('You have no calendar right now. Write a little bit about your calendar!');?></em>
                                    <img src="data/images/ProfileEditIcon.png">
                            </p>
                            <?php }*//* ?>
                        </div>
                    
                        <div class="infoMessage">        
                            <?php if($this->has_messages || !$this->enable_edit) { ?>
                            <h5>Conversación</h5>
                            <p class="colorless noMessage">
                                    <?php echo $this->messages ?>&nbsp;
                                    <!--img src="data/images/ProfileEditIcon.png"-->
                            </p>
                            <?php } /*else { ?>
                            <p class="colorless noMessage">
                                    <em><?php echo $this->translate('You have no calendar right now. Write a little bit about your calendar!');?></em>
                                    <img src="data/images/ProfileEditIcon.png">
                            </p>
                            <?php } *//* ?>
                        </div>
                    
                </div>

        </div>
        <?php }*/ ?>
            
	</div>
	
</div>
	<?php endif; ?>
	
	<?php if($this->active == 'followers'): ?>
			<ul class='list_view'>
				<?php echo $this->boards; ?>
			</ul>
	<?php endif; ?>
	
	
	<?php if($this->active == 'following'): ?>
			<ul class='list_view'>
				<?php echo $this->boards; ?>
			</ul>
	<?php endif; ?>

	<?php if($this->active == 'liking'): ?>
			<ul class='list_view'>
				<?php echo $this->boards; ?>
			</ul>
	<?php endif; ?>

	<?php if($this->active == 'likers'): ?>
			<ul class='list_view'>
				<?php echo $this->boards; ?>
			</ul>
	<?php endif; ?>

	<?php if($this->active == 'activity'): ?>
			<ul class='list_view'>
				<?php echo $this->boards; ?>
			</ul>
	<?php endif; ?>



	<?php if($this->active == 'pins' || isset($_GET['filter'])): ?>
		<script type="text/javascript" src='data_mobile/js/jquery.masonry.min.js'></script>
	
		<script type="text/javascript"> 
			
		$(document).ready(function(){
			var contaner_width = $('#ColumnContainer .pinboard').width();
			var item_width = (Math.round(contaner_width / 4)-3);
			$('#ColumnContainer .pinboard .pin').css({width:Math.round(contaner_width / 4)});
			var total_images = $('#ColumnContainer .pinboard .pin img').size();
			$("#ColumnContainer").css('margin-left','13%');
			var start_masonry = false;
			$('#ColumnContainer .pinboard .pin img').each(function(i, item){
				var image = new Image(); 
				image.src = $(item).data('original');
				image.onload = function(){
					$(item).css({
						"width": item_width,
						"height": Math.ceil(item_width / (this.width/this.height))
					}).attr('src', this.src).removeAttr('width').removeAttr('height');
					if( (i+1) == total_images) { start_masonry = true; }
				};
				image.onerror = function() {
					if( (i+1) == total_images) { start_masonry = true; }
				};
			});
			
			var masonry_load = setInterval(function(){
				if(start_masonry) {
					load_masonry();
					clearInterval(masonry_load);
				}
			}, 50);
			function load_masonry() {
				$('#ColumnContainer .pinboard').masonry({
					itemSelector : '.pin',
					columnWidth: (item_width+3),
					isAnimated:false,
					isResizable:false,
					gutterWidth: 1,
					animate:false
				  });
				  
				$(window).bind('deviceorientation', function() { $('#ColumnContainer .pinboard').masonry('reload'); });
				$(window).bind('MozOrientation', function() { $('#ColumnContainer .pinboard').masonry('reload'); });
				$(window).bind('load', function() { $('#ColumnContainer .pinboard').masonry('reload'); }); 
				$(window).bind('resize', function() { $('#ColumnContainer .pinboard').masonry('reload'); }); 

			  }
			  
		
		});
		
			 
		</script>
			<div id='ColumnContainer'>
				
				<div class='pinboard'>
				
						<?php echo $this->boards; ?>
				
				</div>
                            
			</div>
	<?php endif; ?>

<?php //if (!isset($_SESSION['token'])) //<?php if(!JO_Session::get('token')) 
{
    echo $this->footer_part;
}    
?>



<script>
			
	
				
		

		
	</script>


