
 <script type='text/javascript'>
 	
 </script>

  <body class="hdpi">

  	   <?php 
		/*  	   
  	   		if($this->fb_register){
  	   		 	//echo $this->fb_register;
  	   			$this->fb_register = str_replace('page','touch',$this->fb_register);
			//	echo $this->fb_register;
			
  	   		}
			*/
			
  	   		
  	   ?> 
  	
        <div class="page short" id="wrapper">
            <div id="logo_wrapper">
                <div id="logo" style="">
                    <a href="/" ontouchstart="">
                       
                        	<!--img src='<?php //echo "uploads".JO_Registry::get('site_logo'); ?>' style='max-width:180px; max-height: 60px;margin-left: -35px;margin-top:-10px'/-->
                        <img src='<?php echo $this->site_logo; ?>' style='max-width:180px; max-height: 60px;margin-left: -35px;margin-top:-10px'/>
                    </a>
                </div>
            </div>
			
            <div class="divider"></div>
            
          
       	<div class="middle_cont" id="invitation" >
       			
     
      			<?php if($this->error): ?>
      				
      					<p class='error' style="margin-top: 20px;font-size:12px; ">
      						<?php echo $this->error; ?>
      					</p>
      				
      			<?php endif; ?>
       		
       		      <div id="invite_form" >
       					
                    <form id="invite_me" action='' method='POST' style='width:none !important;'>
                    		<div class="social_buttons register" style="z-index: 993; padding-left:5%">
				      			  <div class="inset" style="z-index: 992; margin-bottom:10px	 ">
				            			<a class="fb login_button" href="<?php echo $this->fb_register; ?>">
				               				 <span class="logo_wrapper"><span class="logo_or"></span></span>
				                			 <span><?php echo $this->translate('Register with Facebook') ?></span>
				           				 </a>
	        					</div>
	       		       	 		<div class="clear" style="z-index: 991; "></div>
	    					</div>
	    					<h2 style="margin-bottom:20px"><?php echo $this->translate('or enter your credentials:') ?></h2>
                      	<div id='personal_details' style="border-bottom: solid 1px #E2E2E2;padding-left:5%">
	                     	<input name='email' class="user email" id="registration_box" value="<?php echo $this->email;?>" placeholder="<?php echo $this->translate('Your Email'); ?>" type="email" style='width: 250px !important' autocomplete='off'>
	                       	<input name='firstname' class="user firstname" id="registration_box" value="<?php echo $this->firstname;?>" placeholder="<?php echo $this->translate('Your First Name') ?>" type="text" style='width: 250px !important' autocomplete='off'>
	                       	<!--input name='lastname' class="user" id="registration_box" placeholder="<?php echo $this->translate('Your Last Name') ?>" type="text" style='width: 250px !important' autocomplete='off'-->
                                <input type="hidden" name="lastname" id="lastname" value="" />
	                       	<input name='username' class="user username" id="registration_box" value="<?php echo $this->username;?>" placeholder="<?php echo $this->translate('Your Username') ?>" type="text" style='width: 250px !important' autocomplete='off'>
			</div> 
                                                
                                                
    <!--div id="create-board" class="Form " style="padding-left:0px;" -->
            <!--ul style="margin:0px;"-->
                
                <!-- Tipo Usuario -->
                <!--li style="border:0px"-->
                      	<div id='other_details' style="border-bottom: solid 1px #E2E2E2;padding-left:5%">                
                    <div class="Right" id='catList'>
                         
                         <a href="" class='selectBox selectBox-dropdown' id='selectBox-TypeUser' style='width: 212px; display: inline-block;'>
                         	<?php if(!$this->usertype_title){?>
                                        <span class='selectBox-label' id='selectBox-label-TypeUser' style="width: 345px;margin-right: 10px"><?php echo  $this->translate('Please choose user type');?></span>
                         	<?php }else{?>
                         		<span class='selectBox-label' id='selectBox-label-TypeUser' style="width: 345px;margin-right: 10px"><?php echo  $this->usertype_title;?></span>
                         	<?php } ?>
                         	 <span class="selectBox-arrow" style=""></span>
                         </a>
                         
                         <ul class='selectBox-dropdown-menu selectBox-options' id='selectBox-TypeUser-dropdown-menu' style='display:none;overflow-x: hidden;width: 370px;'>
                         
                        	<?php foreach($this->user_types as $user_type) { ?>
                        		<li  class = 'master typeuser' style='border:none !important' >
                        			<a data-id='<?php echo $user_type['user_type_id'];?>' href="" class='cats-typeuser' style='color:#AAA;' ><?php echo $user_type['title']?></a>
                        			<?php if($user_type['subuser_types']){?>
                        				<ul class='subcats hidden'>
                        					<?php foreach($user_type['subuser_types'] as $subuser_type){?>
	                        					<li style='border:none !important;padding-left:0px'>
	                        						<a data-id='<?php echo $subuser_type['user_type_id']; ?>' class='' href=""><?php echo $subuser_type['title']; ?></a>
	                        					</li>
                        					<?php }?>
                        				</ul>
                        			<?php }?>
                        		</li>
                        	<?php }?>
                        </ul>
                        
                        <input type='hidden' id='user_typeId' name='type_user' value = '<?php echo $this->type_user;?>'/>

                    </div>
                <!--/li-->
                
                <!-- Deportes -->
                
                    <label for="category_id-select<?php echo ($this->is_edit?'-edit':'');?>"><?php echo $this->translate('My Sports');?></label>
                    <div class="Right" id='catList'>
                        <a id="moresports" onclick="deportes()"  class="red mbtn moresports " style="margin-top:0px;" ><?php echo $this->translate('Seleccionar ...');?></a>
                        <br/><br/>
                        <div id="divSports" name="divSports" >
                        	<?php foreach($this->user_sports as $user_sport) {  ?>
                                <?php  echo trim($user_sport); ?><br/>
                                <?php     } ?>
                            
                            <input id="sports" class="sports" name="sports" type="hidden" value="<?php foreach($this->user_sports as $user_sport) {  echo trim($user_sport); break; } ?>" />
                        </div>
                    </div>
		
			<input type="text" name="location" class="location" id="searchTextField" value="<?php echo $this->location;?>" placeholder="<?php echo $this->translate('Location');?>" style='width: 250px !important' autocomplete='off'/>
                        
                            <input type="hidden" name="lat" class="lat" id="lat" />
                            <input type="hidden" name="len" class="len" id="len" />
                        
                        <div id="map-canvas" style="display:none !important"></div>
                <!-- More Location -->
                
                    <input type='hidden' id="locationcounter" name="locationcounter"  class="locationcounter" value="<?php echo $this->locationcounter; ?>"/>
                    <?php echo $this->translate('Añadir ubicación');?>&nbsp;<a id="morelocations" href="" class="red mbtn morelocations" style="margin-top:0px;" ><?php echo $this->translate('Añadir');?></a>
                    
                    <input type="text" id="searchTextField2" value="" name="locationAux" class="locationAux" placeholder="<?php echo $this->translate('Pulsa añadir después de buscar la ubicación');?>" style='width: 250px !important' autocomplete='off' />
                    <input type="hidden" name="latAux" class="latAux" id="latAux" />
                    <input type="hidden" name="lenAux" class="lenAux" id="lenAux" />
                    
                    <span class="locations ">
                        <?php $i=0; foreach($this->user_location as $users_location) { ?>
                        <?php $i++; ?>
                            <p class="input"><label></label><span class="field"><input type='text' value='<?php echo $users_location; ?>' name='<?php echo "location".$i; ?>'></span></p>
                        <?php } ?>
                    </span>
                        </div>                       
                    	
                    	<div id='pass_details' style="border-bottom: solid 1px #E2E2E2;padding-left:5%;margin-top:5px;">
	                       	<input name='password' class="user" id="registration_box" placeholder="<?php echo $this->translate('Your Password') ?>" type="password" style='width: 250px !important' autocomplete='off'>
	                       	<input name='password2' class="user" id="registration_box" placeholder="<?php echo $this->translate('Repeat Password') ?>" type="password" style='width: 250px !important' autocomplete='off'>
			</div>                    
                    	
                    	<div id='sign_up' style="padding-left:5%;margin-top:5px;text-align: center">
			 <a class="red mbtn" type="submit" ontouchstart="" onclick="$('#invite_me').submit()" style='margin-left:-5%;padding-bottom:10px'>
                          <strong><?php echo  $this->translate('Sign Up') ?></strong>
                          <span></span>
        						</a>
						</div>
                    	
                    </form>
   					
                <div id="invite_success">
                    <h2><?php echo $this->translate('Thanks!'); ?></h2>
                    <p><?php echo $this->translate("We'll send you an invite very soon!"); ?></p>
                </div>
            </div>
            
          
          
   </div>
  <div class='divider bottom'></div>
   </body>
   
<script type='text/javascript'>
	$(document).ready(function(){

                $("#moresports").click(function(){
                    var locationcounter = $('#locationcounter').val();
                    var locations = '&locationcounter='+ $('#locationcounter').val();
                    var k = 0;
                    for(var i = 1; i <= locationcounter; i++)
                    {
                        if ($.trim($('#location' + i).val()) != "")
                        {
                            k++;
                            locations += '&location'+ k + '='+ $('#location' + i).val();
                        }
                    }                    
                    window.location.href = '<?php echo $this->deportes;?>?email=' + $('.email').val() + 
                        '&firstname=' + $('.firstname').val() + '&username=' + $('.username').val() + 
                        /*'&password=' + $('#password').val() + '&password2=' + $('#password2').val() + */
                        '&location=' + $('.location').val() + '&type_user=' + $('#user_typeId').val() + 
                        locations;
                });
	
	});
</script>   
<script type='text/javascript'>   
$(document).ready(function(){
    /*
	$(".selectBox.selectBox-dropdown").bind('click',function(event){
		$('ul.hidden').hide();
		event.preventDefault();
		$(".selectBox.selectBox-dropdown").hide();
		$(".selectBox-dropdown-menu.selectBox-options").show();

		$(".master").unbind('click').bind('click',function(event){
			event.preventDefault();

			
			var children  = $(this).find($('ul'));
			if(children.hasClass('opened')){
				children.hide().removeClass('opened');
			
				
			}else{

			$(".hidden").hide();
			var self  = $(this);
			children.addClass('opened');


			if($(children).hasClass('hidden')){
				try
                                {
                                    console.log("OK");
                                }
                                catch(e)
                                {
                                    if (window.console // check for window.console not console
                                        && window.console.log)
                                    {
                                        window.console.log("OK");
                                    }

                                }
				children.show();
				children.find('li a').click(function(event){
						event.preventDefault();
						appendElementInMain($(this));
						$(".hidden").hide();
				});
			}else{
				
				appendElementInMain(self.find($('a')));
				
			}

			}
		});
	

		function appendElementInMain(element){
			$(".selectBox-dropdown-menu.selectBox-options").hide();
			$(".selectBox.selectBox-dropdown").show();
			$(".selectBox-label").text(element.text());
			$("#catId").val(element.data("id"));
			
			}

		
	});

	$("#selectBox-Category1").bind('click',function(event){
		$('ul.hidden').hide();
		event.preventDefault();
		$("#selectBox-Category1").hide();
		$("#selectBox-dropdown-menu-Category1").show();

		$(".master").unbind('click').bind('click',function(event){
			event.preventDefault();

			
			var children  = $(this).find($('ul'));
			if(children.hasClass('opened')){
				children.hide().removeClass('opened');
			
				
			}else{

			$(".hidden").hide();
			var self  = $(this);
			children.addClass('opened');


			if($(children).hasClass('hidden')){
				try
                                {
                                    console.log("OK");
                                }
                                catch(e)
                                {
                                    if (window.console // check for window.console not console
                                        && window.console.log)
                                    {
                                        window.console.log("OK");
                                    }

                                }
				children.show();
				children.find('li a').click(function(event){
						event.preventDefault();
						appendElementInMain($(this));
						$(".hidden").hide();
				});
			}else{
				
				appendElementInMain(self.find($('a')));
				
			}

			}
		});
	

		function appendElementInMain(element){
			$("#selectBox-dropdown-menu-Category1").hide();
			$("#selectBox-Category1").show();
			$("#selectBox-label-Category1").text(element.text());
			$("#catId1").val(element.data("id"));
			
			}
	});

	$("#selectBox-Category2").bind('click',function(event){
		$('ul.hidden').hide();
		event.preventDefault();
		$("#selectBox-Category2").hide();
		$("#selectBox-dropdown-menu-Category2").show();

		$(".master").unbind('click').bind('click',function(event){
			event.preventDefault();

			
			var children  = $(this).find($('ul'));
			if(children.hasClass('opened')){
				children.hide().removeClass('opened');
			
				
			}else{

			$(".hidden").hide();
			var self  = $(this);
			children.addClass('opened');


			if($(children).hasClass('hidden')){
				try
                                {
                                    console.log("OK");
                                }
                                catch(e)
                                {
                                    if (window.console // check for window.console not console
                                        && window.console.log)
                                    {
                                        window.console.log("OK");
                                    }

                                }
				children.show();
				children.find('li a').click(function(event){
						event.preventDefault();
						appendElementInMain($(this));
						$(".hidden").hide();
				});
			}else{
				
				appendElementInMain(self.find($('a')));
				
			}

			}
		});
	

		function appendElementInMain(element){
			$("#selectBox-dropdown-menu-Category2").hide();
			$("#selectBox-Category2").show();
			$("#selectBox-label-Category2").text(element.text());
			$("#catId2").val(element.data("id"));
			
			}
        });	
        
        $("#selectBox-Category3").bind('click',function(event){
		$('ul.hidden').hide();
		event.preventDefault();
		$("#selectBox-Category3").hide();
		$("#selectBox-dropdown-menu-Category3").show();

		$(".master").unbind('click').bind('click',function(event){
			event.preventDefault();

			
			var children  = $(this).find($('ul'));
			if(children.hasClass('opened')){
				children.hide().removeClass('opened');
			
				
			}else{

			$(".hidden").hide();
			var self  = $(this);
			children.addClass('opened');


			if($(children).hasClass('hidden')){
				try
                                {
                                    console.log("OK");
                                }
                                catch(e)
                                {
                                    if (window.console // check for window.console not console
                                        && window.console.log)
                                    {
                                        window.console.log("OK");
                                    }

                                }
				children.show();
				children.find('li a').click(function(event){
						event.preventDefault();
						appendElementInMain($(this));
						$(".hidden").hide();
				});
			}else{
				
				appendElementInMain(self.find($('a')));
				
			}

			}
		});
	

		function appendElementInMain(element){
			$("#selectBox-dropdown-menu-Category3").hide();
			$("#selectBox-Category3").show();
			$("#selectBox-label-Category3").text(element.text());
			$("#catId3").val(element.data("id"));
			
			}
	});

	$("#selectBox-TypeUser").bind('click',function(event){
		$('ul.hidden').hide();
		event.preventDefault();
		$("#selectBox-TypeUser").hide();
		$("#selectBox-TypeUser-dropdown-menu").show();

		$(".master").unbind('click').bind('click',function(event){
			event.preventDefault();

			
			var children  = $(this).find($('ul'));
			if(children.hasClass('opened')){
				children.hide().removeClass('opened');
			
				
			}else{

			$(".hidden").hide();
			var self  = $(this);
			children.addClass('opened');


			if($(children).hasClass('hidden')){
				try
                                {
                                    console.log("OK");
                                }
                                catch(e)
                                {
                                    if (window.console // check for window.console not console
                                        && window.console.log)
                                    {
                                        window.console.log("OK");
                                    }

                                }
				children.show();
				children.find('li a').click(function(event){
						event.preventDefault();
						appendElementInMain($(this));
						$(".hidden").hide();
				});
			}else{
				
				appendElementInMain(self.find($('a')));
				
			}

			}
		});
	

		function appendElementInMain(element){
			$("#selectBox-TypeUser-dropdown-menu").hide();
			$("#selectBox-TypeUser").show();
			$("#selectBox-label-TypeUser").text(element.text());
			$("#user_typeId").val(element.data("id"));
			
			}

		
	});
        */
	$("#selectBox-dropdown-menu-Category1").bind('mouseleave',function(event){
        		$("#selectBox-Category1").show();
                	$("#selectBox-dropdown-menu-Category1").hide();

        });


	$("#selectBox-Category1").bind('click',function(event){
		$('ul.hidden').hide();
		event.preventDefault();
		$("#selectBox-Category1").hide();
		$("#selectBox-dropdown-menu-Category1").show();
                
                if (!$("#selectBox-Category2").is(":visible"))  
                    {
        		$("#selectBox-Category2").show();
                	$("#selectBox-dropdown-menu-Category2").hide();
                    }
                if (!$("#selectBox-Category3").is(":visible"))  
                    {
        		$("#selectBox-Category3").show();
                	$("#selectBox-dropdown-menu-Category3").hide();
                    }
                if (!$("#selectBox-TypeUser").is(":visible"))  
                    {
                        $("#selectBox-TypeUser").show();
                        $("#selectBox-TypeUser-dropdown-menu").hide();
                    }
                
                /*
		$(".master").bind('click',function(event){
                    alert("o");
                            event.preventDefault();
                            var self  = $(this);
            		appendElementInMain(self.find($('a')));
				
		});
*/
		$(".cats-category1").bind('click',function(event){
                            event.preventDefault();
                            var self  = $(this);
               		appendElementInMain(self);
		});

                
		//$(".master").unbind('click').bind('click',function(event){
                $(".master.cat1").bind('mouseenter',function(event){

                        event.preventDefault();

			
			var children  = $(this).find($('ul'));
			if(children.hasClass('opened')){
				children.hide().removeClass('opened');
			
				
			}else{

			$(".hidden").hide();
			var self  = $(this);
			children.addClass('opened');


			if($(children).hasClass('hidden')){
				try
                                {
                                    console.log("OK");
                                }
                                catch(e)
                                {
                                    if (window.console // check for window.console not console
                                        && window.console.log)
                                    {
                                        window.console.log("OK");
                                    }

                                }
				children.show();
				children.find('li a').click(function(event){
						event.preventDefault();
						appendElementInMain($(this));
						$(".hidden").hide();
				});
			}else{
				
				appendElementInMain(self.find($('a')));
				
			}

			}
		});
	

		function appendElementInMain(element){
			$("#selectBox-dropdown-menu-Category1").hide();
			$("#selectBox-Category1").show();
			$("#selectBox-label-Category1").text(element.text());
			$("#catId1").val(element.data("id"));
			
			}
	});
        
	$("#selectBox-dropdown-menu-Category2").bind('mouseleave',function(event){
        		$("#selectBox-Category2").show();
                	$("#selectBox-dropdown-menu-Category2").hide();

        });
       

	$("#selectBox-Category2").bind('click',function(event){
		$('ul.hidden').hide();
		event.preventDefault();
		$("#selectBox-Category2").hide();
		$("#selectBox-dropdown-menu-Category2").show();
                
                if (!$("#selectBox-Category1").is(":visible"))  
                    {
        		$("#selectBox-Category1").show();
                	$("#selectBox-dropdown-menu-Category1").hide();
                    }
                if (!$("#selectBox-Category3").is(":visible"))  
                    {
        		$("#selectBox-Category3").show();
                	$("#selectBox-dropdown-menu-Category3").hide();
                    }
                if (!$("#selectBox-TypeUser").is(":visible"))  
                    {
                        $("#selectBox-TypeUser").show();
                        $("#selectBox-TypeUser-dropdown-menu").hide();
                    }

		$(".cats-category2").bind('click',function(event){
                            event.preventDefault();
                            var self  = $(this);
               		appendElementInMain(self);
		});

		//$(".master").unbind('click').bind('click',function(event){
                $(".master.cat2").bind('mouseenter',function(event){

			event.preventDefault();

			
			var children  = $(this).find($('ul'));
			if(children.hasClass('opened')){
				children.hide().removeClass('opened');
			
				
			}else{

			$(".hidden").hide();
			var self  = $(this);
			children.addClass('opened');


			if($(children).hasClass('hidden')){
				try
                                {
                                    console.log("OK");
                                }
                                catch(e)
                                {
                                    if (window.console // check for window.console not console
                                        && window.console.log)
                                    {
                                        window.console.log("OK");
                                    }

                                }
				children.show();
				children.find('li a').click(function(event){
						event.preventDefault();
						appendElementInMain($(this));
						$(".hidden").hide();
				});
			}else{
				
				appendElementInMain(self.find($('a')));
				
			}

			}
		});
	

		function appendElementInMain(element){
			$("#selectBox-dropdown-menu-Category2").hide();
			$("#selectBox-Category2").show();
			$("#selectBox-label-Category2").text(element.text());
			$("#catId2").val(element.data("id"));
			
			}
        });	
        
        
	$("#selectBox-dropdown-menu-Category3").bind('mouseleave',function(event){
        		$("#selectBox-Category3").show();
                	$("#selectBox-dropdown-menu-Category3").hide();

        });
        
        
        $("#selectBox-Category3").bind('click',function(event){
		$('ul.hidden').hide();
		event.preventDefault();
		$("#selectBox-Category3").hide();
		$("#selectBox-dropdown-menu-Category3").show();
                
                if (!$("#selectBox-Category2").is(":visible"))  
                    {
        		$("#selectBox-Category2").show();
                	$("#selectBox-dropdown-menu-Category2").hide();
                    }
                if (!$("#selectBox-Category1").is(":visible"))  
                    {
        		$("#selectBox-Category1").show();
                	$("#selectBox-dropdown-menu-Category1").hide();
                    }
                
                if (!$("#selectBox-TypeUser").is(":visible"))  
                    {
                        $("#selectBox-TypeUser").show();
                        $("#selectBox-TypeUser-dropdown-menu").hide();
                    }
                    
                
		$(".cats-category3").bind('click',function(event){
                            event.preventDefault();
                            var self  = $(this);
               		appendElementInMain(self);
		});

		//$(".master").unbind('click').bind('click',function(event){
                $(".master.cat3").bind('mouseenter',function(event){

			event.preventDefault();
                        

			var children  = $(this).find($('ul'));
			if(children.hasClass('opened')){
				children.hide().removeClass('opened');
				
			}else{
                            
                            

                            $(".hidden").hide();
                            var self  = $(this);
                            children.addClass('opened');

                            if($(children).hasClass('hidden')){
                                    try
                                    {
                                        console.log("Tiene hidden");
                                    }
                                    catch(e)
                                    {
                                        if (window.console // check for window.console not console
                                            && window.console.log)
                                        {
                                            window.console.log("Tiene hidden2");
                                        }

                                    }
                                    children.show();
                                    children.find('li a').click(function(event){
                                                    event.preventDefault();
                                                    appendElementInMain($(this));
                                                    $(".hidden").hide();
                                    });
                            }else{

                                    appendElementInMain(self.find($('a')));
                                    console.log("ADD");

                            }

			}
		});

		function appendElementInMain(element){
			$("#selectBox-dropdown-menu-Category3").hide();
			$("#selectBox-Category3").show();
			$("#selectBox-label-Category3").text(element.text());
			$("#catId3").val(element.data("id"));
			
			}
	});

	$("#selectBox-TypeUser-dropdown-menu").bind('mouseleave',function(event){
                        $("#selectBox-TypeUser").show();
                        $("#selectBox-TypeUser-dropdown-menu").hide();

        });

	$("#selectBox-TypeUser").bind('click',function(event){
		$('ul.hidden').hide();
		event.preventDefault();
		$("#selectBox-TypeUser").hide();
		$("#selectBox-TypeUser-dropdown-menu").show();

                if (!$("#selectBox-Category1").is(":visible"))  
                    {
        		$("#selectBox-Category1").show();
                	$("#selectBox-dropdown-menu-Category1").hide();
                    }
                if (!$("#selectBox-Category2").is(":visible"))  
                    {
        		$("#selectBox-Category2").show();
                	$("#selectBox-dropdown-menu-Category2").hide();
                    }
                if (!$("#selectBox-Category3").is(":visible"))  
                    {
        		$("#selectBox-Category3").show();
                	$("#selectBox-dropdown-menu-Category3").hide();
                    }
                    
		$(".cats-typeuser").bind('click',function(event){
                            event.preventDefault();
                            var self  = $(this);
               		appendElementInMain(self);
		});
                    
                    
		//$(".master").unbind('click').bind('click',function(event){
                $(".master.typeuser").bind('mouseenter',function(event){
			event.preventDefault();

			var children  = $(this).find($('ul'));
			if(children.hasClass('opened')){
                            
				children.hide().removeClass('opened');
				
			}else{

                            $(".hidden").hide();
                            var self  = $(this);
                            children.addClass('opened');

                            if($(children).hasClass('hidden')){
                                    try
                                    {
                                        console.log("OK");
                                    }
                                    catch(e)
                                    {
                                        if (window.console // check for window.console not console
                                            && window.console.log)
                                        {
                                            window.console.log("OK");
                                        }

                                    }
                                    children.show();
                                    children.find('li a').click(function(event){
                                                    event.preventDefault();
                                                    appendElementInMain($(this));
                                                    $(".hidden").hide();
                                    });
                            }else{
        //console.log("ADD");
                                    appendElementInMain(self.find($('a')));

                            }

			}
		});
                
		function appendElementInMain(element){
			$("#selectBox-TypeUser-dropdown-menu").hide();
			$("#selectBox-TypeUser").show();
			$("#selectBox-label-TypeUser").text(element.text());
			$("#user_typeId").val(element.data("id"));
			
			}


		
	});

          
        
        $(".morelocations").bind('click',function(event){
		event.preventDefault();
                if ($.trim($("#searchTextField2").val()) != "")
                {
                    if ($("#latAux").val() != "")
                    {
                        var contador = $(".locationcounter").val();
                        contador++;
                        $(".locationcounter").val(contador) ;
                        $(".locations").html($(".locations").html() + "<p class='input'><label></label><span class='field'><input type='text' value='" + $("#searchTextField2").val() + "' id='location" + contador + "' name='location" + contador + "'></span></p>");
                        $(".locations").html($(".locations").html() + "<input type='hidden' name='lat" + contador + "' class='lat" + contador + "' id='lat" + contador + "' value='" + $("#latAux").val() + "' />");
                        $(".locations").html($(".locations").html() + "<input type='hidden' name='len" + contador + "' class='len" + contador + "' id='len" + contador + "' value='" + $("#lenAux").val() + "' />");
                        $("#searchTextField2").val("");
                        $("#latAux").val("");
                        $("#lenAux").val("");
                    }
                }
                //initialize();
        });
        
        $("#searchTextField").bind('focusout',function(event){
            GLoad();
        });
        
        $("#searchTextField").change(function() {
            GLoad();
        });
        
        $(".pac-container").live('click',function(event){
            GLoad();
        });

        $("#searchTextField").blur(function() {
            GLoad();
        });

        $("#searchTextField2").bind('focusout',function(event){
            GLoad();
        });
        
        $("#searchTextField2").change(function() {
            GLoad();
        });

        $("#searchTextField2").blur(function() {
            GLoad();
        });

        
	return;
	
	
});

</script>

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places&language=es"></script>    
    <script>
function initialize() {
  var mapOptions = {
    center: new google.maps.LatLng(-33.8688, 151.2195),
    zoom: 13,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  };
  var map = new google.maps.Map(document.getElementById('map-canvas'),
    mapOptions);

  var input = /** @type {HTMLInputElement} */(document.getElementById('searchTextField'));
  var autocomplete = new google.maps.places.Autocomplete(input);

  autocomplete.bindTo('bounds', map);

  var infowindow = new google.maps.InfoWindow();
  var marker = new google.maps.Marker({
    map: map
  });

   input = /** @type {HTMLInputElement} */(document.getElementById('searchTextField2'));
   autocomplete = new google.maps.places.Autocomplete(input);

  autocomplete.bindTo('bounds', map);

  var infowindow = new google.maps.InfoWindow();
  var marker = new google.maps.Marker({
    map: map
  });


  google.maps.event.addListener(autocomplete, 'place_changed', function() {
    infowindow.close();
    marker.setVisible(false);
    input.className = '';
    var place = autocomplete.getPlace();
    if (!place.geometry) {
      // Inform the user that the place was not found and return.
      input.className = 'notfound';
      return;
    }

    // If the place has a geometry, then present it on a map.
    if (place.geometry.viewport) {
      map.fitBounds(place.geometry.viewport);
    } else {
      map.setCenter(place.geometry.location);
      map.setZoom(17);  // Why 17? Because it looks good.
    }
    marker.setIcon(/** @type {google.maps.Icon} */({
      url: place.icon,
      size: new google.maps.Size(71, 71),
      origin: new google.maps.Point(0, 0),
      anchor: new google.maps.Point(17, 34),
      scaledSize: new google.maps.Size(35, 35)
    }));
    marker.setPosition(place.geometry.location);
    marker.setVisible(true);

    var address = '';
    if (place.address_components) {
      address = [
        (place.address_components[0] && place.address_components[0].short_name || ''),
        (place.address_components[1] && place.address_components[1].short_name || ''),
        (place.address_components[2] && place.address_components[2].short_name || '')
      ].join(' ');
    }

    infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + address);
    infowindow.open(map, marker);
  });

    GLoad();
  // Sets a listener on a radio button to change the filter type on Places
  // Autocomplete.
  function setupClickListener(id, types) {
    var radioButton = document.getElementById(id);
    google.maps.event.addDomListener(radioButton, 'click', function() {
      autocomplete.setTypes(types);
    });
  }

  setupClickListener('changetype-all', []);
  setupClickListener('changetype-establishment', ['establishment']);
  setupClickListener('changetype-geocode', ['geocode']);
}

google.maps.event.addDomListener(window, 'load', initialize);

    </script>

    <!-- AIzaSyD_Dei2f6nMzaMrBwAXFVxjuHnHz-3So4I -->
<script src="http://maps.google.com/maps?file=api&amp;v=3&amp;key=AIzaSyA60eSDixfIlHokj6GbjmqiRUN0GlBOTAM"
      type="text/javascript"></script>
      
<!--script src="http://maps.google.com/maps/api/js?sensor=false" type="text/javascript"></script-->      
    <script type="text/javascript">
   
   /*     
    var locations = [
      ['madriles', 40.4284034, -3.7149525, 1]
    ];      
      */



function GLoad() {




var geocoder;
var map;

                    $(document).ready(function(){                                                   
                var locationPrincipal =$('#searchTextField').val();

         


                var geocoder = new google.maps.Geocoder();
                geocoder.geocode({ 'address': locationPrincipal }, function (results, status) {
                if (status == google.maps.GeocoderStatus.OK) 
                {
                    var lat = results[0].geometry.location.lat().toString().substr(0, 12);
                    var len = results[0].geometry.location.lng().toString().substr(0, 12);
                    $('#lat').val(lat);
                    $('#len').val(len);

                }
                else
                {
                    if (status == "OVER_QUERY_LIMIT")
                    {
            $(document).ready(function(){                                                   
                        //setTimeout(function(){}, 201);
            });                        
                    }
                    else
                    { 
                        console.log('error: ' + status);
                    }
                }

                  pausecomp(201);
              });
              
                var locationPrincipal =$('#searchTextField2').val();

         


                var geocoder = new google.maps.Geocoder();
                geocoder.geocode({ 'address': locationPrincipal }, function (results, status) {
                if (status == google.maps.GeocoderStatus.OK) 
                {
                    var lat = results[0].geometry.location.lat().toString().substr(0, 12);
                    var len = results[0].geometry.location.lng().toString().substr(0, 12);
                    $('#latAux').val(lat);
                    $('#lenAux').val(len);

                }
                else
                {
                    if (status == "OVER_QUERY_LIMIT")
                    {
            $(document).ready(function(){                                                   
                        //setTimeout(function(){}, 201);
            });                        
                    }
                    else
                    { 
                        console.log('error: ' + status);
                    }
                }

                  //pausecomp(201);
              });
              
            });  
            
function pausecomp(ms) {
        ms += new Date().getTime();
        while (new Date() < ms){}
    } 
            
}

    </script>    
   
   
   	
   

