<div class="agenda">
    menu
	<div class="chinchetaAzul"></div>
    <?php $titulo="";
	if($this->enable_edit) {
		$titulo=$this->translate('Click to edit');
	?>
		<a class="red mbtn btnBorrar silverbox" href="<?php echo $this->agenda['hrefDelete'];?>" title="<?php  echo $this->translate('Borrar'); ?>"></a>
    <?php } ?>
	<div class="cuerpoMensaje" title="<?php echo $titulo; ?>">   
    	<textarea id="<?php echo $this->agenda['agenda_id'];?>" class="editaAgenda" style="display:none" maxlength="250"><?php echo strip_tags($this->agenda['texto']);?></textarea>
    	<span class="textoOriginal"><?php echo $this->agenda['texto'];?></span>
	</div>
</div>            