<?php echo $this->header_part; ?>

<div id="detail" class="editprofile">       
	<div id="view-profile">
		
          
            <form class="Form StaticForm" action="<?php echo $this->activatePopup; ?>" method="post" id="profileEdit">
                
                <h3 style="border-bottom:0px;padding-bottom:0px"><b><?php echo $this->translate('Apúntate a Volunttarios ');?></b></h3>
                <strong><?php echo $this->translate('"El deporte tiene el poder de cambiar el mundo; tiene el poder de inspirar; tiene el poder de unir a las personas de una manera que pocas cosas pueden lograr" Nelson Mandela.');?></strong>
                <?php echo $this->translate('En cada una de nuestras ciudades y pueblos hay personas, sobre todo niños y jóvenes, que con un poco de ayuda e inspiración se sumarían a la práctica del deporte, y con este, a sus valores de superación, compañerismo, entusiasmo, juego limpio,..., y con ello, a una vida mejor. '); ?>
                <?php echo $this->translate('Con ese objetivo, amatteur quiere ayudar a ayudar, dando la herramienta a su comunidad, para que quien quiera y pueda se sume al programa "volunttarios", que ya se encuentra en programación y estará online en las próximas semanas. '); ?>
                <?php echo $this->translate('Te podrás ofrecer voluntario para muchos tipos de acciones, y luego, en función de la solicitudes de ayuda y conversaciones que tengas con los solicitantes, tu elijes coo enfocar tus acciones, con quién, dónde..., algunas de las acciones que proponemos son'); ?>
                <h3></h3>
            
                <div class="hide">
                    <input type="hidden" name="user_id" id="user_id" value="<?php echo $this->user_id; ?>">
                </div>

                <ul>
                    <!-- Opciones -->
                    <li>
                        <label for="tc"><?php echo sprintf($this->translate('Opciones')); ?> <br class="hide" /></label>
                        <div style="display:table">
                            <div style="display:table-cell">
                                <div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option1 == '1' ? 'checked="checked"' : ''); ?> type='checkbox' id='option1' name='option1' class='option1' value="1" ><?php echo " ". sprintf($this->translate('Deportista, individual o club, da charlas a grupos, colegios...')); ?> </span>
                                </div>
                                <div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option2 == '1' ? 'checked="checked"' : ''); ?> type='checkbox' id='option2' name='option2' class='option2' value="1"><?php echo " ". sprintf($this->translate('Comparto mi experiencia de superación, charlas para grupos, colegios...')); ?> </span>
                                </div>
                                <div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option3 == '1' ? 'checked="checked"' : ''); ?> type='checkbox' id='option3' name='option3' class='option3' value="1"><?php echo " ". sprintf($this->translate('Apoyo a rehabilitación')); ?> </span>
                                </div>
                                <div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option4 == '1' ? 'checked="checked"' : ''); ?> type='checkbox' id='option4' name='option4' class='option4' value="1"><?php echo " ". sprintf($this->translate('Ayuda o entrenamiento a paralímpicos')); ?> </span>
                                </div>
                                <div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option5 == '1' ? 'checked="checked"' : ''); ?> type='checkbox' id='option5' name='option5' class='option5' value="1"><?php echo " ". sprintf($this->translate('Entrenamiento a deportista o equipo')); ?> </span>
                                </div>
                                <div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option6 == '1' ? 'checked="checked"' : ''); ?> type='checkbox' id='option6' name='option6' class='option6' value="1"><?php echo " ". sprintf($this->translate('Agrupación con otros volunttarios')); ?> </span>
                                </div>
                                <div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option7 == '1' ? 'checked="checked"' : ''); ?> type='checkbox' id='option7' name='option7' class='option7' value="1"><?php echo " ". sprintf($this->translate('Colaboración con ONG como volunttario')); ?> </span>
                                </div>
                                <div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option8 == '1' ? 'checked="checked"' : ''); ?> type='checkbox' id='option8' name='option8' class='option8' value="1"><?php echo " ". sprintf($this->translate('Participación o colaboración en eventos deportivos solidarios')); ?> </span>
                                </div>
                                <div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option9 == '1' ? 'checked="checked"' : ''); ?> type='checkbox' id='option9' name='option9' class='option9' value="1"><?php echo " ". sprintf($this->translate('Donación material usado o nuevo')); ?> </span>
                                </div>
                                <div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option10 == '1' ? 'checked="checked"' : ''); ?> type='checkbox' id='option10' name='option10' class='option10' value="1" ><?php echo " ". sprintf($this->translate('Coaching, motivación, apoyo psicológico')); ?> </span>
                                </div>
                                <div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option11 == '1' ? 'checked="checked"' : ''); ?> type='checkbox' id='option11' name='option11' class='option11' value="1" ><?php echo " ". sprintf($this->translate('Asesoría sobre salud, lesiones y nutrición en el deporte')); ?> </span>
                                </div>
                                <div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option12 == '1' ? 'checked="checked"' : ''); ?> type='checkbox' id='option12' name='option12' class='option12' value="1"><?php echo " ". sprintf($this->translate('Presto instalaciones deportivas')); ?> </span>
                                </div>
                                <div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option13 == '1' ? 'checked="checked"' : ''); ?> type='checkbox' id='option13' name='option13' class='option13' value="1"><?php echo " ". sprintf($this->translate('Patrocinio o copatrocinio equipo o deportista')); ?> </span>
                                </div>
                                <div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option14 == '1' ? 'checked="checked"' : ''); ?> type='checkbox' id='option14' name='option14' class='option14' value="1"><?php echo " ". sprintf($this->translate('Entradas o abonos para eventos deportivos')); ?> </span>
                                </div>
                                <div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option15 == '1' ? 'checked="checked"' : ''); ?> type='checkbox' id='option15' name='option15' class='option15' value="1"><?php echo " ". sprintf($this->translate('ONG ayuda a superar problemas para tomar la salida')); ?> </span>
                                </div>
                                <div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option16 == '1' ? 'checked="checked"' : ''); ?> type='checkbox' id='option16' name='option16' class='option16' value="1"><?php echo " ". sprintf($this->translate('Árbitros o jueces deportivos')); ?> </span>
                                </div>
                                <div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option17 == '1' ? 'checked="checked"' : ''); ?> type='checkbox' id='option17' name='option17' class='option17' value="1"><?php echo " ". sprintf($this->translate('Ayudo a personas mayores a hacer ejercicio')); ?> </span>
                                </div>
                                <div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option18 == '1' ? 'checked="checked"' : ''); ?> type='checkbox' id='option18' name='option18' class='option18' value="1"><?php echo " ". sprintf($this->translate('Otros (descripción en los comentarios)')); ?> </span>
                                </div>
                            </div>
                            <span style="color:red">*</span>                                                            
                        </div>
                    </li>
                    
                    <!-- State -->
                    <li>
                        <label for="id_estado_0"><?php echo $this->translate('Estado'); ?></label>
                        <div id="estadoOptions" class="Right">
                                <label for="id_estado_0"><input <?php echo ($this->estado == '1' ? 'checked="checked"' : ''); ?> type="radio" name="estado" class="estado" value="1" id="id_estado_0"> <?php echo $this->translate('Habilitar'); ?></label>
                                <label for="id_estado_1"><input <?php echo ($this->estado == '0' ? 'checked="checked"' : ''); ?> type="radio" name="estado" class="estado" value="0" id="id_estado_1"> <?php echo $this->translate('Deshabilitar'); ?></label>
                                <span style="color:red">*</span>
                        </div>
                    </li>
                    <!-- Availability -->
                    <li>
                        <label for="id_disponible"><?php echo $this->translate('Disponibilidad'); ?></label>
                        <div id="disponibleOptions" class="">
                            <label for="id_disponible_0"><input <?php echo ($this->disponible == '1' ? 'checked="checked"' : ''); ?> type="radio" name="disponible" class="disponible" value="1" id="id_disponible_0"> <?php echo $this->translate('Disponible'); ?></label>
                            <label for="id_disponible_1"><input <?php echo ($this->disponible == '0' ? 'checked="checked"' : ''); ?> type="radio" name="disponible" class="disponible" value="0" id="id_disponible_1"> <?php echo $this->translate('Ocupado'); ?></label>
                            <span style="color:red">*</span>
                        </div>
                    </li>  
                    <!-- Ubicacion -->
                    <li>
                        <label for="id_zona"><?php echo $this->translate('Zona geográfica'); ?></label>
                        <p class="input">
                            <span class="field"><input type="text" name="location" class="location" id="searchTextField" value="<?php echo $this->location; ?>" id="registration_box" placeholder="<?php echo $this->translate('Zona geográfica') ?>" style='min-width: 270px !important' autocomplete='off'/></span>
                            <span class="help_text"><?php echo $this->translate('e.g. Palo Alto, CA'); ?></span>  
                            <span style="color:red">*</span>
                            <input type="hidden" name="lat" class="lat" id="lat" value="<?php echo $this->lat;?>" />
                            <input type="hidden" name="len" class="len" id="len" value="<?php echo $this->len;?>" />
                        </p>
                        <div id="map-canvas" style="display:none !important"></div>
                    </li>
                    <!-- Deporte -->
                    <li>
                        <label for="category_id-select<?php echo ($this->is_edit ? '-edit' : ''); ?>"><?php echo $this->translate('Deporte'); ?></label>
                        <div class="Right" id='catList'>

                            <a href="" class='selectBox selectBox-dropdown' id='selectBox-Category' style='min-width: 250px !important;width: 250px; display: inline-block;'>
                                <?php if (!$this->cat_title)
                                { ?>
                                    <span class='selectBox-label' id='selectBox-label-Category' style="width: 250px;"><?php echo $this->translate('Please choose sport'); ?></span>
                                <?php } else
                                { ?>
                                    <span class='selectBox-label' id='selectBox-label-Category' style="width: 250px;"><?php echo $this->cat_title; ?></span>
                                <?php } ?>
                                <span class="selectBox-arrow" style=""></span>
                            </a>

                            <ul class='selectBox-dropdown-menu selectBox-options' id='selectBox-dropdown-menu-Category' style='display:none;overflow-x: hidden;width: 370px;'>

                                        <?php foreach ($this->categories as $category)
                                        { ?>
                                    <li  class = 'master' style='border:none !important' >
                                        <a data-id='<?php echo $category['category_id']; ?>' href="" class='' style='color:#AAA;' ><?php echo $category['title'] ?></a>
                                            <?php if ($category['subcategories'])
                                            { ?>
                                            <ul class='subcats hidden'>
                                        <?php foreach ($category['subcategories'] as $subcat)
                                        { ?>
                                                    <li style='border:none !important;padding-left:0px'>
                                                        <a data-id='<?php echo $subcat['category_id']; ?>' class='' href=""><?php echo $subcat['title'] ?></a>
                                                    </li>
                                        <?php } ?>
                                            </ul>
                                    <?php } ?>
                                    </li>
                                <?php } ?>
                            </ul>

                            <input type='hidden' id='catId' name='sport_category' class='sport_category' value = '<?php echo $this->sport_category; ?>'/>
                        </div>
                    </li>

                    <!-- Comentario -->
                    <li>
                        <div class="left w335px">
                            <p>
                                <label for="message"><?php echo $this->translate('Comment'); ?>:<br></label>
                                <textarea style="min-width: 250px !important;width: 250px !important;" name="comment" id="comment" rows="5" cols="30"><?php echo $this->comment; ?></textarea>
                            </p>
                            <p class="text_counter"></p>
                        </div>
                    <!-- Grabar -->
                    <li>
                        <div class="left w335px">
                            <p class="submit">
                                
                            <label for="required"><span style="color:red">*</span><?php echo $this->translate('Fields required'); ?><br></label>
                            <!--span style="color:red">*</span--> <?php //echo $this->translate('Fields required'); ?>                
                            &nbsp;&nbsp;<input class="red mbtn message" style="font-size:18px" type="submit" value="<?php echo $this->translate('Pinit'); ?>">
                            &nbsp;&nbsp;<input class="red mbtn message close" style="font-size:18px;width:80px" value="<?php echo $this->translate('Salir'); ?>">
                            </p>
                        </div>
                    </li>				
                </ul>
                
                <div class="clear"></div>

            </form>
    
    </div>
    
    <div class="clear"></div>    
</div>


<?php $key = str_replace('.', '', microtime(true)); ?>
<script type="text/javascript">
    $(document).ready(function(){
       
        $('.red.mbtn.message.close').click(function(){
		//history.go(-1);
                //var origen = '<?php echo $_SESSION["activate_url"]; ?>';
                var origen = '<?php echo $this->home_url; ?>';
                window.location.href=origen;
	});

/*
        $('#id_gender_male').click(function(){
            //if( $(this).is(':checked') ) alert("checked");
            alert($( ".gender:checked" ).val());
        });
        
        $('#id_gender_female').click(function(){
            alert($( ".gender:checked" ).val());
        });
            
        
	<?php if($this->successfu_edite) { ?>
	Pins.success('<?php echo $this->translate('Information is successfully changed!');?>');
	<?php } ?>
	<?php if($this->error) { ?>
	Pins.error('<?php echo $this->error;?>');
	<?php } ?>
*/        

        $('#emailpin form').unbind('submit').submit(function(){
            $('#emailpin form .submit input').after('<img src="data/images/loading_2.gif" id="loading_button" />');
            $('#emailpin form .submit input').attr('disabled', true).addClass('disabled');
            
            
            var user_id = $('#user_id').val();
            var gender = $('.gender:checked').val();
            var age = $('.age').val();
            var location = $('#searchTextField').val();            
            var sport_category = $('.sport_category').val();            
            var level = $('.level').val();            
            var activate = $('.activate:checked').val();            
            var option1 = $('.option1:checked').val();            
            var option2 = $('.option2:checked').val();            
            var option3 = $('.option3:checked').val();            
            var option4 = $('.option4:checked').val();            
            var option5 = $('.option5:checked').val();            
            var option6 = $('.option6:checked').val();            
            var option7 = $('.option7:checked').val();            
            var option8 = $('.option8:checked').val();            
            var comment = $('#comment').val();
            alert($('.option1:checked').val());
            alert($('#comment').val());
            
            
                  
            $.post('<?php echo $this->from_url; ?>', {user_id:user_id, gender : gender, age : age, location : location, sport_category : sport_category, level : level, activate : activate, option1 : option1, option2 : option2, option3 : option3, option4 : option4, option5 : option5, option6 : option6, option7 : option7, option8 : option8, comment:comment}, function(data,status){
                $('#loading_button').remove();
                $.fancybox.close();                        

            $('#emailpin form .submit input').after(kk);
            $('#emailpin .submit input').removeClass('disabled').attr('disabled', false);
			
            });
            return false;
                   
        });
	

	$("#selectBox-dropdown-menu-Level").bind('mouseleave',function(event){
                        $("#selectBox-Level").show();
                        $("#selectBox-dropdown-menu-Level").hide();

        });
          

        $("#selectBox-Level").bind('click',function(event){
            $('ul.hidden').hide();
            event.preventDefault();
            $("#selectBox-Level").hide();
            $("#selectBox-dropdown-menu-Level").show();

                if (!$("#selectBox-Age").is(":visible"))  
                    {
        		$("#selectBox-Age").show();
                	$("#selectBox-dropdown-menu-Age").hide();
                    }
                if (!$("#selectBox-Category").is(":visible"))  
                    {
        		$("#selectBox-Category").show();
                	$("#selectBox-dropdown-menu-Category").hide();
                    }


            $(".master").unbind('click').bind('click',function(event){
                event.preventDefault();

			
                var children  = $(this).find($('ul'));
                if(children.hasClass('opened')){
                    children.hide().removeClass('opened');
			
				
                }else{

                    $(".hidden").hide();
                    var self  = $(this);
                    children.addClass('opened');


                    if($(children).hasClass('hidden')){
                        try
                        {
                            console.log("OK");
                        }
                        catch(e)
                        {
                            if (window.console // check for window.console not console
                                && window.console.log)
                            {
                                window.console.log("OK");
                            }

                        }
                        children.show();
                        children.find('li a').click(function(event){
                            event.preventDefault();
                            appendElementInMain($(this));
                            $(".hidden").hide();
                        });
                    }else{
				
                        appendElementInMain(self.find($('a')));
				
                    }

                }
            });
	

            function appendElementInMain(element){
                $("#selectBox-dropdown-menu-Level").hide();
                $("#selectBox-Level").show();
                $("#selectBox-label-Level").text(element.text());
                $("#levelId").val(element.data("id"));
			
            }
        });


	$("#selectBox-dropdown-menu-Category").bind('mouseleave',function(event){
                        $("#selectBox-Category").show();
                        $("#selectBox-dropdown-menu-Category").hide();

        });
        


        $("#selectBox-Category").bind('click',function(event){
            $('ul.hidden').hide();
            event.preventDefault();
            $("#selectBox-Category").hide();
            $("#selectBox-dropdown-menu-Category").show();

                if (!$("#selectBox-Age").is(":visible"))  
                    {
        		$("#selectBox-Age").show();
                	$("#selectBox-dropdown-menu-Age").hide();
                    }
                if (!$("#selectBox-Level").is(":visible"))  
                    {
        		$("#selectBox-Level").show();
                	$("#selectBox-dropdown-menu-Level").hide();
                    }


            $(".master").unbind('click').bind('click',function(event){
                event.preventDefault();

			
                var children  = $(this).find($('ul'));
                if(children.hasClass('opened')){
                    children.hide().removeClass('opened');
			
				
                }else{

                    $(".hidden").hide();
                    var self  = $(this);
                    children.addClass('opened');


                    if($(children).hasClass('hidden')){
                        try
                        {
                            console.log("OK");
                        }
                        catch(e)
                        {
                            if (window.console // check for window.console not console
                                && window.console.log)
                            {
                                window.console.log("OK");
                            }

                        }
                        children.show();
                        children.find('li a').click(function(event){
                            event.preventDefault();
                            appendElementInMain($(this));
                            $(".hidden").hide();
                        });
                    }else{
				
                        appendElementInMain(self.find($('a')));
				
                    }

                }
            });
	

            function appendElementInMain(element){
                $("#selectBox-dropdown-menu-Category").hide();
                $("#selectBox-Category").show();
                $("#selectBox-label-Category").text(element.text());
                $("#catId").val(element.data("id"));
			
            }
        });

	$("#selectBox-dropdown-menu-Age").bind('mouseleave',function(event){
                        $("#selectBox-Age").show();
                        $("#selectBox-dropdown-menu-Age").hide();

        });

        
        $("#selectBox-Age").bind('click',function(event){
            $('ul.hidden').hide();
            event.preventDefault();
            $("#selectBox-Age").hide();
            $("#selectBox-dropdown-menu-Age").show();

                if (!$("#selectBox-Level").is(":visible"))  
                    {
        		$("#selectBox-Level").show();
                	$("#selectBox-dropdown-menu-Level").hide();
                    }
                if (!$("#selectBox-Category").is(":visible"))  
                    {
        		$("#selectBox-Category").show();
                	$("#selectBox-dropdown-menu-Category").hide();
                    }


            $(".master").unbind('click').bind('click',function(event){
                event.preventDefault();

			
                var children  = $(this).find($('ul'));
                if(children.hasClass('opened')){
                    children.hide().removeClass('opened');
			
				
                }else{

                    $(".hidden").hide();
                    var self  = $(this);
                    children.addClass('opened');


                    if($(children).hasClass('hidden')){
                        try
                        {
                            console.log("OK");
                        }
                        catch(e)
                        {
                            if (window.console // check for window.console not console
                                && window.console.log)
                            {
                                window.console.log("OK");
                            }

                        }
                        children.show();
                        children.find('li a').click(function(event){
                            event.preventDefault();
                            appendElementInMain($(this));
                            $(".hidden").hide();
                        });
                    }else{
				
                        appendElementInMain(self.find($('a')));
				
                    }

                }
            });
	

            function appendElementInMain(element){
                $("#selectBox-dropdown-menu-Age").hide();
                $("#selectBox-Age").show();
                $("#selectBox-label-Age").text(element.text());
                $("#ageId").val(element.data("id"));
			
            }
        });

        $("#searchTextField").bind('focusout',function(event){
            GLoad();
        });
        
        $("#searchTextField").change(function() {
            GLoad();
        });
        
        $(".pac-container").live('click',function(event){
            GLoad();
        });

        $("#searchTextField").blur(function() {
            GLoad();
        });

        return;
	
	
    });

</script>

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places&language=es"></script>        

    <script>
function initialize() {
  var mapOptions = {
    center: new google.maps.LatLng(-33.8688, 151.2195),
    zoom: 13,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  };
  var map = new google.maps.Map(document.getElementById('map-canvas'),
    mapOptions);

  var input = /** @type {HTMLInputElement} */(document.getElementById('searchTextField'));
  var autocomplete = new google.maps.places.Autocomplete(input);

  autocomplete.bindTo('bounds', map);

  var infowindow = new google.maps.InfoWindow();
  var marker = new google.maps.Marker({
    map: map
  });

  google.maps.event.addListener(autocomplete, 'place_changed', function() {
    infowindow.close();
    marker.setVisible(false);
    input.className = '';
    var place = autocomplete.getPlace();
    if (!place.geometry) {
      // Inform the user that the place was not found and return.
      input.className = 'notfound';
      return;
    }

    // If the place has a geometry, then present it on a map.
    if (place.geometry.viewport) {
      map.fitBounds(place.geometry.viewport);
    } else {
      map.setCenter(place.geometry.location);
      map.setZoom(17);  // Why 17? Because it looks good.
    }
    marker.setIcon(/** @type {google.maps.Icon} */({
      url: place.icon,
      size: new google.maps.Size(71, 71),
      origin: new google.maps.Point(0, 0),
      anchor: new google.maps.Point(17, 34),
      scaledSize: new google.maps.Size(35, 35)
    }));
    marker.setPosition(place.geometry.location);
    marker.setVisible(true);

    var address = '';
    if (place.address_components) {
      address = [
        (place.address_components[0] && place.address_components[0].short_name || ''),
        (place.address_components[1] && place.address_components[1].short_name || ''),
        (place.address_components[2] && place.address_components[2].short_name || '')
      ].join(' ');
    }

    infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + address);
    infowindow.open(map, marker);
  });

  GLoad();
  // Sets a listener on a radio button to change the filter type on Places
  // Autocomplete.
  function setupClickListener(id, types) {
    var radioButton = document.getElementById(id);
    google.maps.event.addDomListener(radioButton, 'click', function() {
      autocomplete.setTypes(types);
    });
  }

  setupClickListener('changetype-all', []);
  setupClickListener('changetype-establishment', ['establishment']);
  setupClickListener('changetype-geocode', ['geocode']);
}

google.maps.event.addDomListener(window, 'load', initialize);

    </script>
<!-- AIzaSyD_Dei2f6nMzaMrBwAXFVxjuHnHz-3So4I -->
<!--script src="http://maps.google.com/maps?file=api&amp;v=3&amp;key=AIzaSyA60eSDixfIlHokj6GbjmqiRUN0GlBOTAM"
      type="text/javascript"></script-->
      
<!--script src="http://maps.google.com/maps/api/js?sensor=false" type="text/javascript"></script-->      
    <script type="text/javascript">
   
   /*     
    var locations = [
      ['madriles', 40.4284034, -3.7149525, 1]
    ];      
      */



function GLoad() {




var geocoder;
var map;

                    $(document).ready(function(){                                                   
         var locationPrincipal =$('#searchTextField').val();

         


                var geocoder = new google.maps.Geocoder();
                geocoder.geocode({ 'address': locationPrincipal }, function (results, status) {
                if (status == google.maps.GeocoderStatus.OK) 
                {
                    var lat = results[0].geometry.location.lat().toString().substr(0, 12);
                    var len = results[0].geometry.location.lng().toString().substr(0, 12);
                    $('#lat').val(lat);
                    $('#len').val(len);

                }
                else
                {
                    if (status == "OVER_QUERY_LIMIT")
                    {
            $(document).ready(function(){                                                   
                        //setTimeout(function(){}, 201);
            });                        
                    }
                    else
                    { 
                        console.log('error: ' + status);
                    }
                }

                  pausecomp(201);
              });
            }); 
            
function pausecomp(ms) {
        ms += new Date().getTime();
        while (new Date() < ms){}
    } 
            
}

    </script>    
    
<?php echo $this->footer_part; ?>