<?php echo $this->header_part; ?>

<div id="detail" class="editprofile"> <!-- style="background-color:white;padding-left: 20px;padding-right: 20px"-->
   <div id="view-profile">
    <label style="font-size: 2.8em;font-weight: 300;line-height: 1em;color:#0061A5;float:left;"> 
    <?php if ($this->edited) { ?>
        <image src="data/images/editar_eventto.png"  height="53px" width="235px" >&nbsp; </strong>
    <?php } else { ?>
        <image src="data/images/anadir_eventto.png"  height="53px" width="235px" >&nbsp; </strong>
    <?php } ?>
    </label>
    <div style="padding-top: 60px">
        <?php if ($this->cancel == '1') { ?>
        <div style="width:auto;padding-top: 70px">
            <label for="evento_cancelado" style="color:red;font-size: 1.6em"><?php echo $this->translate('Este evento ha sido cancelado por: ');?></label>&nbsp;<label for="evento_cancelado" style="color:silver;font-size: 1.6em"><?php echo $this->cancelReason;?></label>
        </div>    
        <?php } ?>
                
        <form name="profileEdit" accept-charset="utf-8" method="post" action="" class="Form StaticForm" id="profileEdit">

            <input type='hidden' id='user_id' name='user_id' value="<?php echo $this->user_id;?>"/>

            <ul>

                <!-- Event Name -->
                <li>
                    <div class="Right">
                        <input type="text" id="id_eventname" value="<?php echo $this->eventname;?>" name="eventname" name="website" id="registration_box" placeholder="<?php echo $this->translate('Nombre del evento') ?>" style='min-width: 250px !important' autocomplete='off'/>
                        <span style="color:red">*</span>
                        <br/>
                        <span class="help_text"><?php echo $this->translate('Max 60 caracteres');?></span>
                    </div>
                </li>

                <div id="create-board" class="Form StaticForm" style="padding-left:0px;" >
                    <ul style="margin:0px;">

                        <!-- Deportes -->
                        <li style="border:0px">
                            <div class="Right" id='catList'>

                                 <a href="" class='selectBox selectBox-dropdown' id='selectBox-Category1' style='min-width: 232px !important;width: 232px; display: inline-block;'>
                                        <?php if(!$this->cat_title){?>
                                                 <span class='selectBox-label' id='selectBox-label-Category1' style="width: 232px;"><?php echo  $this->translate('Please choose sport');?></span>
                                        <?php }else{?>
                                                <span class='selectBox-label' id='selectBox-label-Category1' style="width: 232px;"><?php echo  $this->cat_title;?></span>
                                        <?php }?>
                                         <span class="selectBox-arrow" style=""></span>
                                 </a>

                                 <ul class='selectBox-dropdown-menu selectBox-options' id='selectBox-dropdown-menu-Category1' style='display:none;overflow-x: hidden;width: 252px;'>

                                        <?php foreach($this->categories as $category) { ?>
                                                <li  class = 'master cat1' style='border:none !important' >

                                                        <a data-id='<?php echo $category['category_id'];?>' href="" class='cats-category1' style='color:#AAA;' ><?php echo $category['title']?></a>
                                                        <?php if($category['subcategories']){?>
                                                                <ul class='subcats hidden'>
                                                                        <?php foreach($category['subcategories'] as $subcat){?>
                                                                                <li style='border:none !important;padding-left:0px'>
                                                                                        <a data-id='<?php echo $subcat['category_id']; ?>' class='' href=""><?php echo $subcat['title']?></a>
                                                                                </li>
                                                                        <?php }?>
                                                                </ul>
                                                        <?php }?>
                                                </li>
                                        <?php }?>
                                </ul>

                                <input type='hidden' id='catId1' name='sport_category' value = '<?php echo $this->sport_category;?>'/>
                                <span style="color:red">*</span>
                            </div>
                        </li>
                
                    </ul>
                </div>     
                
                <!-- Organiza -->
                <li>
                    <div class="Right">
                        <input type="text" id="id_organiza" value="<?php echo $this->organiza;?>" name="organiza" id="registration_box" placeholder="<?php echo $this->translate('Organiza') ?>" style='min-width: 250px !important' autocomplete='off'/>
                        <span style="color:red">*</span>
                    </div>
                </li>

                <!-- Location -->
                <li>
                    <div class="Right">
                        <input type="text" id="searchTextField" value="<?php echo $this->location;?>" name="location" id="registration_box" placeholder="<?php echo $this->translate('Ubicación') ?>" style='min-width: 250px !important' autocomplete='off'/>
                        <span style="color:red">*</span>
                        <br/>
                        <span class="help_text"><?php echo $this->translate('Campo obligatorio para usuario profesional (Otros)');?></span>
                    </div>
                            <input type="hidden" name="lat" class="lat" id="lat" value="<?php echo $this->lat;?>" />
                            <input type="hidden" name="len" class="len" id="len" value="<?php echo $this->len;?>" />
                    
                </li>
                <div id="map-canvas" style="display:none !important"></div>
                
                <!-- Date Time -->
                <li>
                    <div class="Right">
                        <input type="text" id="date_event" value="<?php echo $this->date_event;?>" name="date_event"  id="registration_box" placeholder="<?php echo $this->translate('Fecha y Hora') ?>" style='min-width: 250px !important' autocomplete='off'/>
                        <span style="color:red">*</span>
                    </div>
                </li>

                <!-- Website -->
                <li>
                    <div class="Right">
                        <input type="text" id="id_website" value="<?php echo $this->website;?>" name="website" id="registration_box" placeholder="<?php echo $this->translate('Web o Link relacionado') ?>" style='min-width: 250px !important' autocomplete='off'/>
                        
                    </div>
                </li>

                <!-- Image -->
                <li>
                    <div class="Right" style="padding-left: 3px">
                        <div class="current_avatar_wrapper">
                          <img src="data/images/ajax-loader.gif" class="spinner" alt="<?php echo $this->translate('Loading...');?>" style="display: none;">
                          <img style="max-width:252px" alt="<?php echo $this->translate('Foto del evento');?>" class="current_avatar floatLeft" src="<?php echo $this->avatar;?>" >
                        </div>

                        <div class="floatLeft NoInput">
                            <a class="floatLeft red mbtn change_avatar" href="#"><strong><?php echo $this->translate('Upload an Image');?></strong><span></span></a>
                            
                            <div class="clear"></div>
                        </div>
                    </div>
                </li>
                
                
                <!-- About -->
                <li>
                    <div class="Right" style="width: 260px ">                        
                        <textarea style='min-width: 250px !important;width: 250px !important' id="registration_box" placeholder="<?php echo $this->translate('Detalles. Ayúdanos a conocer más detalles sobre el evento: Datos técnicos, Inscripción, Fecha límite, etc..');?>"  autocomplete='off' name="description" cols="24" rows="3" id="id_about" ><?php echo $this->description;?></textarea>
                        <span style="color:red">*</span>
                        <div id="aboutCount" class="CharacterCount"></div>
                        <!--br/>
                        <span class="help_text"><?php echo $this->translate('Ayúdanos a conocer más detalles sobre el evento: ');?></span>
                        <br/>
                        <span class="help_text"><?php echo $this->translate('Datos técnicos, Inscripción, Fecha límite, etc..');?></span-->
                    </div>
                </li>

        
                <!-- Compartir -->
                <label for="id_compartir_seguidores"><input checked="checked" type="hidden" name="compartir" class="compartir" value="followers" id="id_compartir_seguidores"> </label>                
                <!--li>
                    <label for="id_compartir"><?php echo $this->translate('Compartir con'); ?></label>
                    <div id="compartirOptions" class="">
                        <label for="id_compartir_seguidores"><input <?php echo ($this->compartir == 'followers' ? 'checked="checked"' : ''); ?> type="radio" name="compartir" class="compartir" value="followers" id="id_compartir_seguidores"> <?php echo $this->translate('Mis Seguidores'); ?></label>
                        <label for="vacio" style="width:120px;"></label>
                        <label for="id_compartir_todos"><input <?php echo ($this->compartir == 'amatteur' ? 'checked="checked"' : ''); ?> type="radio" name="compartir" class="compartir" value="amatteur" id="id_compartir_todos"> <?php echo $this->translate('Todos'); ?></label>
                    </div>
                </li-->  

                <!-- si es alta, no se puede cancelar -->
                <?php if ($this->edited) { ?>
			
                <!-- Cancel -->
                <li>
                    <div id="genderOptions" class="Right">
                        <ul>
                                <li><label for="delete_event"><?php echo $this->translate('Evento Cancelado');?></label><label for="id_cancel_1"><input <?php echo ($this->cancel == '1' ? 'checked="checked"' : '');?> type="radio" name="delete_event" value="1" id="delete_event_1"><?php echo ($this->cancel == '1' ?  $this->translate('Si') : '');?></label></li>
                            <?php if ($this->cancel == '1' ) { ?>   
                                <li><label for="delete_event"><?php echo $this->translate('Evento Cancelado');?></label><label for="id_cancel_o"><input <?php echo ($this->cancel == '0' ? 'checked="checked"' : '');?> type="radio" name="delete_event" value="0" id="delete_event_0"><?php echo $this->translate('No'); ?></label></li>
                            <?php } ?>
                        </ul>
                        
                    </div>
                </li>
                
                <!-- Cancel Reason -->
                <li>
                    <div class="Right" id="delete">
                        <input type="text" id="delete_reason" value="<?php echo $this->cancelReason;?>" name="delete_reason"id="registration_box" placeholder="<?php echo $this->translate('Razón de la cancelación') ?>" style='min-width: 250px !important' autocomplete='off'/>
                    </div>
                </li>
                
                <?php } ?>

            </ul>

            <!-- Search events -->
            <br/>
            <div id="texto">
                <label for="black" style="width:200px;font-size: 1.8em;font-weight: 300;line-height: 1em;color:#0061A5;float:left;"><?php echo $this->translate('Ayúdanos a que no se dupliquen los eventos.');?></label>
                <label for="black" style="width:200px;color:#0061A5;float:left;"><?php echo $this->translate('Por favor, verifica que tu evento no esté ya inscrito, recuerda que puedes añadir datos a eventos ya existentes. Explora los eventos abajo, al abrirse una pestaña nueva, los datos de tu formulario no se perderán. ¡Gracias!');?></label>
            </div>

            <br/>
            <div id="contenedor" style="margin-left:50px;padding-top: 300px;">
                <?php echo $this->events;?>
            </div>
            
                
            <!-- Button -->
            <div class="Submit">
                <?php if ($this->owner) { ?>
                    <a onclick="$('#profileEdit').submit(); return false" class="red mbtn userform_submit editpage_submit" href="#"><strong><?php echo $this->translate('Guardar Evento');?></strong></a>                
                <?php } else { ?>
                    <a onclick="return false" class="red mbtn userform_submit editpage_submit disabled" href="#"><strong><?php echo $this->translate('Guardar Evento');?></strong></a>
                <?php } ?>                
            </div>
        </form>		

    </div>
            
    </div>
    
    
    <div class="clear"></div>    
</div>


<?php ob_start();?>

<script src="data/js/jquery-ui-timepicker-addon.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="data/css/jquery-ui-timepicker-addon.css"/>

<script type="text/javascript">
$(document).ready(function(){
    
    /*

        $('#date_event').datetimepicker({
            dateFormat: 'dd/mm/yy',
            controlType: 'select'
        });
*/

        $('#delete_event_0').bind('click',function(event){
           $('#delete_reason').val(''); 
        });
    

        $("#id_eventname").bind('focusout',function(event){
            $("#contenedor").html('');
            $(".Submit").css("padding-top", "300px");
            search();
        });
        
        $("#id_eventname").change(function() {
            $("#contenedor").html('');
            $(".Submit").css("padding-top", "300px");            
            search();
        });
        
        $("#id_eventname").live('click',function(event){
            $("#contenedor").html('');
            $(".Submit").css("padding-top", "300px");
            search();
        });

        $("#id_eventname").blur(function() {
            $("#contenedor").html('');
            $(".Submit").css("padding-top", "300px");
            search();
        });
        
	function posicion() {
var posicionReal = $("#profileEdit").offset();
alert("top" + posicionReal.top);
alert("height" + $("#detail").height());   

        }        
        
	function search() {
                val = $("#id_eventname").val();
		$.post('<?php echo $this->search_json;?>', {eventname: val}, function(data){
                    $("#contenedor").html(data.events);
                    $(".Submit").css("padding-top", "300px");
		},'json');
	}


	new AjaxUpload($('.StaticForm a.change_avatar'), {
		action: '<?php echo $this->form_action;?>',
		name: 'file',
		autoSubmit: true,
		responseType: 'json',
		onSubmit: function(file, extension) {
			$(".current_avatar_wrapper .spinner").show().css({opacity: 1});
			$(".current_avatar_wrapper .current_avatar").hide();
		},
		onComplete: function(file, json) {
			if (json.error) {
				Pins.error(json.error);
				$('.current_avatar_wrapper .current_avatar').show();
				$(".current_avatar_wrapper .spinner").hide().css({opacity: 0});
			} else if (json.success) {
				var image = new Image();
				image.src = json.success;
				image.onload = function(){
					$('.current_avatar_wrapper .current_avatar').attr('src', image.src).show();
					$(".current_avatar_wrapper .spinner").hide().css({opacity: 0});
				}
				image.onerror = function(){
					$('.current_avatar_wrapper .current_avatar').show();
					$(".current_avatar_wrapper .spinner").hide().css({opacity: 0});
				}
			}
		}
	});


	$('#enable_button').change(function(){
		if($(this).is(':checked')) {
			$('.StaticForm .RedButton.DeleteButton').removeClass('disabled');
		} else {
			$('.StaticForm .RedButton.DeleteButton').addClass('disabled');
		}
	}).change();

	$('a.refresh_user_image').click(function(){
		$(".current_avatar_wrapper .spinner").show().css({opacity: 1});
		$(".current_avatar_wrapper .current_avatar").hide();
		$.post('<?php echo $this->facebook_connect_avatar;?>', function(json){
			if (json.error) {
				Pins.error(json.error)
			} else if (json.success) {
				var image = new Image();
				image.src = json.success;
				image.onload = function(){
					$('.current_avatar_wrapper .current_avatar').attr('src', image.src).show();
					$(".current_avatar_wrapper .spinner").hide().css({opacity: 0});
				}
				image.onerror = function(a){
					$('.current_avatar_wrapper .current_avatar').show();
					$(".current_avatar_wrapper .spinner").hide().css({opacity: 0});
				}
			} else {
				$('.current_avatar_wrapper .current_avatar').show();
				$(".current_avatar_wrapper .spinner").hide().css({opacity: 0});
			}
		}, 'json');
	});

	<?php if($this->successfu_edite) { ?>
	Pins.success('<?php echo $this->translate('Information is successfully changed!');?>');
        setTimeout(function () {var href = '<?php echo $this->user_events;?>';
                                document.location.href=href;
                                }, 5000);
	<?php } ?>
	<?php if($this->error) { ?>
	Pins.error('<?php echo $this->error;?>');
	<?php } ?>

	$('#enable_button').click(function(){
		if($(this).is(':checked')) {
			$('#delete_user_account_confirm').removeClass('disabled').unbind('click');
		} else {
			$('#delete_user_account_confirm').addClass('disabled').unbind('click').click(function(){ return false; });
		}
	});
	
	$('#delete_user_account_confirm').unbind('click').click(function(){ return false; });
/*
	$('#id_username').checkAvailable({
		'url' : '<?php echo $this->check_username;?>',
		'holder': '.help_text.username_available'
	});
*/	
});
//--></script>
<?php $this->placeholder('inhead', ob_get_clean());?>

<script type="text/javascript">
$(document).ready(function(){

	
	var cache = {};
	$('.collaborator_name.ui-autocomplete-input').live('keyup', function(){
		var val = this.value;
		if(cache[val]) {
			autocompleteResults(cache[val]);
		} else {
			$.post('<?php echo $this->friends_href;?>', {term: val}, function(data){
				cache[val] = data.users;
				autocompleteResults(data.users);
			}, 'json');
		}
	}).after('<div class="menu_friends" style="position: absolute; display: none; margin-top: 33px;z-index:2147483647;">');
	
	function autocompleteResults(data) {

		var holder = $('.menu_friends').empty();
		if($(data).objectSize() < 1) {
			holder.hide();
			return;
		}
		holder.show(function(){
			$(document).unbind('.joauto').bind('click.joauto',function(e){
				holder.hide();
			});
		});
		$(data).each(function(i, item){
			user = $('<div class="option_friends"><img alt="'+item.label+'" src="'+item.image+'"><span>'+item.label+'</span></div>').click(function(){
				holder.hide();
				if( $('#user_fr_'+item.value+'<?php echo ($this->is_edit?'-edit':'');?>').size() > 0 ) { return; }
				$('input.collaborator_name').val('');
				$('#invite_response<?php echo ($this->is_edit?'-edit':'');?>').append('<input id="hidden_user_fr_'+item.value+'<?php echo ($this->is_edit?'-edit':'');?>" type="hidden" name="friends['+item.value+']" value="'+item.value+'" />');

				template = $('#friend-template<?php echo ($this->is_edit?'-edit':'');?>').html();
				for(e in item) {
					template = template.replace(new RegExp(RegExp.quote('{'+e+'}'), 'g'), item[e]);
				}
				
				$('#CurrentCollaborators<?php echo ($this->is_edit?'-edit':'');?>').append(template);
			}).css({'cursor': 'pointer'});
			
			holder.append(user);
		});
	}

	RegExp.quote = function(str) {
	    return (str+'').replace(/([.?*+^$[\]\\(){}|-])/g, "\\$1");
	};
		
	
});

function saveBoardData() {
	
	$.post('<?php echo $this->form_action;?>', $('#CreateBoard<?php echo ($this->is_edit?'-edit':'');?>').serialize(), function(data){
		if(data.error) {
			Pins.error(data.error);
		} else if(data.data) {
			window.location = data.data.href;
		}
	}, 'json');
	return false;
}

function deleteFriend(id) {
	$('#user_fr_'+id+'<?php echo ($this->is_edit?'-edit':'');?>').remove();
	$('#hidden_user_fr_'+id+'<?php echo ($this->is_edit?'-edit':'');?>').remove();
}


$(document).ready(function(){


	$("#selectBox-dropdown-menu-Category1").bind('mouseleave',function(event){
        		$("#selectBox-Category1").show();
                	$("#selectBox-dropdown-menu-Category1").hide();

        });
        
        

        $("#selectBox-Category1").bind('click',function(event){
            $('ul.hidden').hide();
            event.preventDefault();
            $("#selectBox-Category1").hide();
            $("#selectBox-dropdown-menu-Category1").show();

   

            $(".master").unbind('click').bind('click',function(event){
                event.preventDefault();

			
                var children  = $(this).find($('ul'));
                if(children.hasClass('opened')){
                    children.hide().removeClass('opened');
                    $(".cats-category1").bind('dblclick',function(event){
                                event.preventDefault();
                                var self  = $(this);
                            appendElementInMain(self);
                    });
			
				
                }else{

                    $(".hidden").hide();
                    var self  = $(this);
                    children.addClass('opened');


                    if($(children).hasClass('hidden')){
                        try
                        {
                            console.log("OK");
                        }
                        catch(e)
                        {
                            if (window.console // check for window.console not console
                                && window.console.log)
                            {
                                window.console.log("OK");
                            }

                        }
                        children.show();
                        children.find('li a').click(function(event){
                            event.preventDefault();
                            appendElementInMain($(this));
                            $(".hidden").hide();
                        });
                    }else{
				
                        appendElementInMain(self.find($('a')));
				
                    }

                }
            });
	

            function appendElementInMain(element){
                $("#selectBox-dropdown-menu-Category1").hide();
                $("#selectBox-Category1").show();
                $("#selectBox-label-Category1").text(element.text());
                $("#catId1").val(element.data("id"));
			
            }
        });	        

        

	
        
        $("#searchTextField").bind('focusout',function(event){
            $('.userform_submit').attr('disabled', true).addClass('disabled');        
            GLoad();
        });
        
        $("#searchTextField").change(function() {
            $('.userform_submit').attr('disabled', true).addClass('disabled');            
            GLoad();
        });
        
        $(".pac-container").live('click',function(event){
            $('.userform_submit').attr('disabled', true).addClass('disabled');            
            GLoad();
        });

        $("#searchTextField").blur(function() {
            $('.userform_submit').attr('disabled', true).addClass('disabled');            
            GLoad();
        });

        
	return;
});

</script>

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places&language=es"></script>    
    <script>
function initialize() {
  var mapOptions = {
    center: new google.maps.LatLng(-33.8688, 151.2195),
    zoom: 13,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  };
  var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

  var input = /** @type {HTMLInputElement} */(document.getElementById('searchTextField'));
  var autocomplete = new google.maps.places.Autocomplete(input);

  autocomplete.bindTo('bounds', map);
/*
  var infowindow = new google.maps.InfoWindow();
  var marker = new google.maps.Marker({
    map: map
  });

  google.maps.event.addListener(autocomplete, 'place_changed', function() {
    infowindow.close();
    marker.setVisible(false);
    input.className = '';
    var place = autocomplete.getPlace();
    if (!place.geometry) {
      // Inform the user that the place was not found and return.
      input.className = 'notfound';
      return;
    }

    // If the place has a geometry, then present it on a map.
    if (place.geometry.viewport) {
      map.fitBounds(place.geometry.viewport);
    } else {
      map.setCenter(place.geometry.location);
      map.setZoom(17);  // Why 17? Because it looks good.
    }
    marker.setIcon(/** @type {google.maps.Icon} *({
      url: place.icon,
      size: new google.maps.Size(71, 71),
      origin: new google.maps.Point(0, 0),
      anchor: new google.maps.Point(17, 34),
      scaledSize: new google.maps.Size(35, 35)
    }));
    marker.setPosition(place.geometry.location);
    marker.setVisible(true);

    var address = '';
    if (place.address_components) {
      address = [
        (place.address_components[0] && place.address_components[0].short_name || ''),
        (place.address_components[1] && place.address_components[1].short_name || ''),
        (place.address_components[2] && place.address_components[2].short_name || '')
      ].join(' ');
    }

    infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + address);
    infowindow.open(map, marker);
  });

    GLoad(); 
  // Sets a listener on a radio button to change the filter type on Places
  // Autocomplete.
  function setupClickListener(id, types) {
    var radioButton = document.getElementById(id);
    google.maps.event.addDomListener(radioButton, 'click', function() {
      autocomplete.setTypes(types);
    });
  }

  setupClickListener('changetype-all', []);
  setupClickListener('changetype-establishment', ['establishment']);
  setupClickListener('changetype-geocode', ['geocode']);
*/            
}

google.maps.event.addDomListener(window, 'load', initialize);


    </script>

<!--script src="http://maps.google.com/maps?file=api&amp;v=3&amp;key=AIzaSyA60eSDixfIlHokj6GbjmqiRUN0GlBOTAM"
      type="text/javascript"></script-->
      
    <script type="text/javascript">
   
   /*     
    var locations = [
      ['madriles', 40.4284034, -3.7149525, 1]
    ];      
      */



function GLoad() 
{
    var geocoder;
    var map;

    $(document).ready(function(){ 
                        
                                              
                var locationPrincipal =$('#searchTextField').val();

         


                var geocoder = new google.maps.Geocoder();
                geocoder.geocode({ 'address': locationPrincipal }, function (results, status) {
                if (status == google.maps.GeocoderStatus.OK) 
                {
                    var lat = results[0].geometry.location.lat().toString().substr(0, 12);
                    var len = results[0].geometry.location.lng().toString().substr(0, 12);
                    $('#lat').val(lat);
                    $('#len').val(len);

                    try
                    {
                        console.log('lat: ' + lat);
                        console.log('len: ' + len);
                    }
                    catch(e)
                    {
                        if (window.console // check for window.console not console
                            && window.console.log)
                        {
                            window.console.log('lat: ' + lat);
                            window.console.log('len: ' + len);
                        }

                    }

                }
                else
                {
                    try
                    {
                        console.log('error: ' + status);
                    }
                    catch(e)
                    {
                        if (window.console // check for window.console not console
                            && window.console.log)
                        {
                            window.console.log('error: ' + status);
                        }

                    }
                }

                cambiadisabled();
              });
              
              
    });  

    function cambiadisabled()
    {

     $(document).ready(function(){                                                   

        $('.userform_submit').attr('disabled', false).removeClass('disabled');  

     }); 
 
    }
            
    function pausecomp(ms) 
    {
        ms += new Date().getTime();
        while (new Date() < ms){}
    } 
            
}

    </script>    



<?php echo $this->footer_part; ?>