<div class="box person <?php echo ($this->key ? 'odd' : '');?>" id="<?php echo $this->event['event_id'];?>">
    
                <label style="font-size: 2.8em;
font-weight: 300;
line-height: 1em;
color:#0061A5;
float:left;"> 
                    <image src="data/images/event_calendar.png" >&nbsp;<strong><?php echo $this->translate('Evento Deportivo ');?> </strong></label>		
<br><br><br><br><br><br>

    <img width="<?php echo $this->event['popup_width'];?>" height="<?php echo $this->event['popup_height'];?>" data-original="<?php echo $this->event['popup'];?>" src="<?php echo $this->event['thumb'];?>" alt="Image" />
    <a style="background-image: url(<?php echo $this->event['avatar'];?>); filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='<?php echo $this->event['avatar'];?>',sizingMethod='scale');-ms-filter: \"progid:DXImageTransform.Microsoft.AlphaImageLoader(src='<?php echo $this->event['avatar'];?>',sizingMethod='scale')\";" class="PersonImage ImgLink" href="<?php echo $this->event['href'];?>"></a>
			<!--p class="thumb">
				<a class="PersonImage" href="<?php echo $this->event['href'];?>">
					<img style="height:110px;width:110px;" data-original="<?php echo $this->event['avatar'];?>" src="data/images/grey.gif" alt="<?php echo $this->event['fullname'];?>" />
				</a>
			</p-->

            <div class="PersonInfo">
                <div style="display:table" style="border-width: 1px;border-color: black">
                    <div style="display:table-cell">                            
                            <div style="display:table-row">
                                <div style="display:table-cell">
                                    <p class="location colorless"><?php echo $this->translate('Descripción del evento:');?> </div>
                                <div style="display:table-cell">
                                    <?php echo $this->event['eventname'];?></p>
                                </div>
                            </div>
                            <div style="display:table-row">
                                <div style="display:table-cell">
                                    <p class="location colorless"><?php echo $this->translate('Deporte:');?> </div>
                                <div style="display:table-cell">
                                    <?php echo $this->event['sport_category'];?></p>
                                </div>
                            </div>
                            <div style="display:table-row">
                                <div style="display:table-cell">
                                    <p class="location colorless"><?php echo $this->translate('Organiza:');?> </div>
                                <div style="display:table-cell">
                                    <?php echo $this->event['organiza'];?></p>
                                </div>
                            </div>
                            <div style="display:table-row">
                                <div style="display:table-cell">
                                    <p class="location colorless"><?php echo $this->translate('Ubicación');?> </div>
                                <div style="display:table-cell">
                                    <?php echo $this->event['location'];?></p>
                                </div>
                            </div>
                            <div style="display:table-row">
                                <div style="display:table-cell">
                                    <p class="location colorless"><?php echo $this->translate('Fecha');?> </div>
                                <div style="display:table-cell">
                                    <?php echo $this->event['date_event'];?></p>
                                </div>
                            </div>
                            <div style="display:table-row">                                
                                <div style="display:table-cell">
                                    <p class="location colorless"><?php echo $this->translate('Página web del evento');?> </div>
                                <div style="display:table-cell">
                                     <?php echo $this->event['website'];?></p> 
                                </div>
                            </div>
                            <div style="display:table-row">                                
                                <div style="display:table-cell">
                                    <p class="location colorless"><?php echo $this->translate('Detalles');?> </div>
                                <div style="display:table-cell">
                                     <?php echo $this->event['description'];?></p> 
                                </div>
                                
                            </div>
                            <div style="display:table-row">
                                <div style="display:table-cell">
                                    <p class="location colorless"><?php echo $this->translate('Evento publicado por: ');?> </div>
                                <div style="display:table-cell">
                                    &nbsp;<img style="height:110px;width:110px;" src="<?php echo $this->event['avataruser'];?>" alt="<?php echo $this->event['fullname'];?>"/>
                                <?php echo $this->event['fullname'];?>
                                <?php echo $this->event['description'];?>
                                </div>
                            </div>
                        </div>
			
                <!--div style="display:table-cell">&nbsp;</div>
                <div style="display:table-cell">
                    <p>
                        <img style="height:110px;width:110px;" src="<?php echo $this->event['avatar'];?>" alt="<?php echo $this->event['eventname'];?>" />
                    </p>
                </div> 
                <div style="display:table-cell">&nbsp;</div>
                <div style="display:table-cell">
                    <div style="display:table-row">
                        <a onclick="$('#profileEdit').submit(); return false" class="Button WhiteButton RedButton Button24 userform_submit editpage_submit" href="#"><strong><?php echo $this->translate('Ver');?></strong></a>
                    </div>
                    <div style="display:table-row">
                        <a onclick="$('#profileEdit').submit(); return false" class="Button WhiteButton RedButton Button24 userform_submit editpage_submit" href="#"><strong><?php echo $this->translate('Comentar');?></strong></a>
                    </div>
                </div--> 
                
        </div>                    
    </div>
</div>