<!--div class="box<?php echo $this->history_action;?>" id="<?php echo $this->event['event_id'];?>" style="width:460px;height: auto;border-width: 0px;border-color: #cccaca; border-style: solid;background-color: white">
            <div class="PersonInfo">
                <div style="display:table">
                    <div style="display:table-cell;border-color: #cccaca;border-width: 1px;border-style: solid; padding: 2px;width:390px">                            
                        <div style="display:table-row">
                                <div style="display:table-cell">
                                    <h2><?php echo $this->event['eventname'];?></h2>
                                </div>
                        </div>

                        <div style="display:table" >
                            <div style="display:table-row">
                                <div style="display:table-cell">
                                    <p class="location colorless"><?php echo $this->translate('Organiza:');?> </div>
                                <div style="display:table-cell">
                                    <?php echo $this->event['organiza'];?></p>
                                </div>
                            </div><div style="display:table-row">
                                <div style="display:table-cell">
                                    <p class="location colorless"><?php echo $this->translate('');?> </div>
                                <div style="display:table-cell">
                                    <?php echo $this->event['location'];?></p>
                                </div>
                            </div><div style="display:table-row">
                                <div style="display:table-cell">
                                    <p class="location colorless"><?php echo $this->translate('');?> </div>
                                <div style="display:table-cell">
                                    <?php echo $this->event['date_event'];?></p>
                                </div>
                            </div><div style="display:table-row">                                
                                <div style="display:table-cell">
                                    <p class="location colorless"><?php echo $this->translate('');?> </div>
                                <div style="display:table-cell">
                                     <?php echo $this->event['website'];?></p> 
                                </div>
                            </div><div style="display:table-row">
                                <div style="display:table-cell">
                                    <p class="location colorless"><?php echo $this->translate('Publicado por: ');?> </div>
                                <div style="display:table-cell">
                                    &nbsp;<a href="<?php echo $this->event['href'];?>"><?php echo $this->event['fullname'];?></a></p> 
                                </div>
                            </div>
                        </div>
			
		</div>
                <div style="display:table-cell">&nbsp;</div>
                <div style="display:table-cell">
                    <p>
                        <img style="height:110px;width:110px;" src="<?php echo $this->event['avatar'];?>" alt="<?php echo $this->event['eventname'];?>" />
                    </p>
                </div> 
                <div style="display:table-cell">&nbsp;</div>
                <div style="display:table-cell;top:10px">
                    <div style="display:table-row">
                        <a class="red mbtn" href="<?php echo $this->boxeventdetail;?>" <?php if ($this->search_add) { ?> target="_blank" <?php } ?> ><?php echo $this->translate('Ver');?></a>
                    </div>
                    <div style="display:table-row">
                        <a class="red mbtn" href="<?php echo $this->boxeventdetail;?>&comment=1" <?php if ($this->search_add) { ?> target="_blank" <?php } ?> ><?php echo $this->translate('Comentar');?></a>
                    </div>
                </div> 
                
        </div>                    
    </div>
</div-->
	<div class='pin'>
	
		<a href='/events/indexeventBoxDetail?event_id=<?php echo $this->event['event_id']; ?>'>
			<img alt='' src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==" data-original='<?php echo $this->event['avatar'];?>' width='93' height='<?php echo round( 93 / ( $this->event['width']/$this->event['height'] ) );?>'/>
		
		</a>
	

	</div>

