<div class="box<?php echo $this->history_action;?>" id="<?php echo $this->event['event_id'];?>" style="width:460px;height: auto;border-width: 0px;border-color: #cccaca; border-style: solid;background-color: white">
    <!--a style="background-image: url(<?php echo $this->event['avatar'];?>); filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='<?php echo $this->event['avatar'];?>',sizingMethod='scale');-ms-filter: \"progid:DXImageTransform.Microsoft.AlphaImageLoader(src='<?php echo $this->event['avatar'];?>',sizingMethod='scale')\";" class="PersonImage ImgLink" href="<?php echo $this->event['href'];?>"></a-->
			<!--p class="thumb">
				<a class="PersonImage" href="<?php echo $this->event['href'];?>">
					<img style="height:110px;width:110px;" data-original="<?php echo $this->event['avatar'];?>" src="data/images/grey.gif" alt="<?php echo $this->event['fullname'];?>" />
				</a>
			</p-->
            <div class="PersonInfo">
                <div style="display:table">
                    <div style="display:table-cell;border-color: #cccaca;border-width: 1px;border-style: solid; padding: 2px;width:390px">                            
                        <div style="display:table-row">
                                <div style="display:table-cell">
                                    <h2><?php echo $this->event['eventname'];?></h2>
                                </div>
                        </div>

                        <div style="display:table" >
                            <div style="display:table-row">
                                <div style="display:table-cell">
                                    <p class="location colorless"><?php echo $this->translate('Organiza:');?> </div>
                                <div style="display:table-cell">
                                    <?php echo $this->event['organiza'];?></p>
                                </div>
                            </div><div style="display:table-row">
                                <div style="display:table-cell">
                                    <p class="location colorless"><?php echo $this->translate('');?> </div>
                                <div style="display:table-cell">
                                    <?php echo $this->event['location'];?></p>
                                </div>
                            </div><div style="display:table-row">
                                <div style="display:table-cell">
                                    <p class="location colorless"><?php echo $this->translate('');?> </div>
                                <div style="display:table-cell">
                                    <?php echo $this->event['date_event'];?></p>
                                </div>
                            </div><div style="display:table-row">                                
                                <div style="display:table-cell">
                                    <p class="location colorless"><?php echo $this->translate('');?> </div>
                                <div style="display:table-cell">
                                     <?php echo $this->event['website'];?></p> 
                                </div>
                            </div><div style="display:table-row">
                                <div style="display:table-cell">
                                    <p class="location colorless"><?php echo $this->translate('Publicado por: ');?> </div>
                                <div style="display:table-cell">
                                    &nbsp;<a href="<?php echo $this->event['href'];?>"><?php echo $this->event['fullname'];?></a></p> 
                                </div>
                            </div>
                        </div>
			
		</div>
                <div style="display:table-cell">&nbsp;</div>
                <div style="display:table-cell">
                    <p>
                        <img style="height:110px;width:110px;" src="<?php echo $this->event['avatar'];?>" alt="<?php echo $this->event['eventname'];?>" />
                    </p>
                </div> 
                <div style="display:table-cell">&nbsp;</div>
                <div style="display:table-cell;top:10px">
                    <div style="display:table-row">
                        <a class="red mbtn" href="<?php echo $this->boxeventdetail;?>" <?php if ($this->search_add) { ?> target="_blank" <?php } ?> ><?php echo $this->translate('Ver');?></a>
                    </div>
                    <div style="display:table-row">
                        <a class="red mbtn" href="<?php echo $this->boxeventdetail;?>&comment=1" <?php if ($this->search_add) { ?> target="_blank" <?php } ?> ><?php echo $this->translate('Comentar');?></a>
                    </div>
                </div> 
                
        </div>                    
    </div>
</div>