<?php echo $this->header_part; ?>

    <?php  if (!$this->user_data) { ?>                    
	<div id="container" style="margin-top:-50px;margin-left: 300px;" >
    <?php } else { ?>                    
	<div id="container" style="margin-top:10px;margin-left: 300px;" >
    <?php } ?>

	            	<span class="greyselected" style="font-size: 1.8em;
font-weight: 300;
line-height: 1em;
color:#0061A5;
float:left;"> 
                            <label>
                                <div style="width:70px;float:left">
                                    <image src="data/images/event_calendar.png" >&nbsp;<strong>
                                </div>    
                                <div style="width:750px">
                                    <?php echo $this->translate('Eventos Deportivos ');?> &mdash; </strong>
                                    <span class="hilight"><?php echo $this->translate('¡Busca, Añade, Comparte! ');?></span><br/>
                                    <span style="font-size: 0.8em;"><?php echo $this->translate('Busca, publica, comparte y promociona cualquier tipo de evento deportivo; cualquier deporte, en cualquier lugar, lo podrás encontrar aquí. Una base de datos creada y moderada por la comunidad amatteur');?></span>
                                </div>
                            </label>
                        </span>

		<div id="" class="box" style="min-width: 300px;width:100px;min-height: 24px;
height: 35px;
padding: 10px 10px 12px 170px;
text-shadow: 0 1px rgba(255,255,255,0.9);
margin-top:90px;
margin-left: 150px;
clear: both;
min-width: 340px;
white-space: nowrap;
box-shadow: 0;
font-size: 1.8em;
font-weight: 300;
line-height: 1em;">
			<div class="box2">
                                <span class="selected"><a id="search" href="<?php echo $this->search_url ?>" class="red mbtn search " style="margin-top:0px;  text-decoration:none;color: white;text-shadow: 0px 1px black;" ><?php echo $this->translate('Buscar');?></a></span>
                                <?php if ($this->user_data) { ?>                    
                                <span class="selected"><a id="addEvent" href="<?php echo $this->addEvent_url ?>" class="red mbtn addEvent " style="margin-top:0px;  text-decoration:none;color: white;text-shadow: 0px 1px black;" ><?php echo $this->translate('Añadir');?></a></span>
                                <?php } else { ?> 
                                <span><a id="addEvent" onclick="addEvent()"  class="red mbtn addEvent " style="background-color:gray;margin-top:0px;  text-decoration:none;color: white;text-shadow: 0px 1px black;" ><?php echo $this->translate('Añadir');?></a></span>
                                <?php } ?>                    
        	</div>
                    
        </div>
            <div class="" style="min-width: 300px;width:100px;min-height: 24px;
height: 25px;
padding: 10px 0 12px;
text-shadow: 0 1px rgba(255,255,255,0.9);
margin-top:160px;
clear: both;
margin-left: 220px;
white-space: nowrap;
box-shadow: 0;"
                                <?php  if (!$this->user_data) { ?>                    

		<p class="input">                            
                                <span class="addtext" style="font-size: 1.3em;
font-weight: 300;
line-height: 1em;"><?php echo $this->translate('Para añadir un evento tienes que estar registrado. ');?><a id="register" href="<?php echo $this->register_url ?>" class="Button RedButton register " style="margin-top:0px;  text-decoration:none;color: white;text-shadow: 0px 1px black;" ><?php echo $this->translate('Regístrate Aquí');?></a></span>
        </p>            	
                                <?php } ?>
            </div>

		<?php echo $this->pins;?>
		
		<div class="clear"></div>
	</div>

	<?php if($this->follow_user) { ?>
	<script type="text/javascript">
	$(document).ready(function(){
		Pins.initFollow('#container .box.user .follow a');
	});
	</script>
	<?php } ?>
	
<script type="text/javascript">

    function addEvent(){
        $(document).ready(function(){

            $("#input").css({'background-color': '#ccc'});
            $('span.addtext', this).css({'color': 'red'});
            //$('span.addtext', this).css({'color': 'inherit'}).delay(2800);

        });
        
    }
    
function pausecomp(ms) {
        ms += new Date().getTime();
        while (new Date() < ms){}
    }    

</script>
<?php echo $this->footer_part; ?>