<?php echo $this->header_part; ?>
<body onLoad="GLoad();" >

    <?php  if (!$this->user_data) { ?>                    
                    <div style="margin-top:50px;margin-left:200px;position:relative;width: auto;padding: 0px">
    <?php } else { ?>                    
                    <div style="margin-top:110px;margin-left:200px;position:relative;width: auto;padding: 0px">
    <?php } ?>
    
    

                    <label style="font-size: 2.8em;
font-weight: 300;
line-height: 1em;
color:#0061A5;
float:left;"> 
                    <image src="data/images/event_calendar.png" >&nbsp;
                    <strong><?php echo $this->translate('Buscar Evento Deportivo ');?> </strong>
                    </label>		
                </div>

    
            <?php if ($this->all) { ?>
    

	<div id="panelsearch" style="padding-top: 0px ! important;width:1025px ! important; padding-left: 160px">    
            
            
            
            
    <div id="panel" style="padding-top: 5px !important">
	<form action="<?php echo $this->search_action; ?>" method="post" class="edit search StaticForm">

	<input type="hidden" name="words" id="words" value="ok" />
                <ul>

                    <!-- Deporte -->
                    <li>
                        <label for="category_id-select<?php echo ($this->is_edit ? '-edit' : ''); ?>"><?php echo $this->translate('Deporte'); ?></label>
                        <div class="Right" id='catList'>

                            <a href="" class='selectBox selectBox-dropdown' id='selectBox-Category' style='width: 352px; display: inline-block;'>
                                <?php if (!$this->cat_title)
                                { ?>
                                    <span class='selectBox-label' id='selectBox-label-Category' style="width: 352px;"><?php echo $this->translate('Please choose sport'); ?></span>
                                <?php } else
                                { ?>
                                    <span class='selectBox-label' id='selectBox-label-Category' style="width: 352px;"><?php echo $this->cat_title; ?></span>
                                <?php } ?>
                                <span class="selectBox-arrow" style=""></span>
                            </a>

                            <ul class='selectBox-dropdown-menu selectBox-options' id='selectBox-dropdown-menu-Category' style='display:none;overflow-x: hidden;width: 370px;'>

                                        <?php foreach ($this->categories as $category)
                                        { ?>
                                    <li  class = 'master cat' style='border:none !important' >
                                        <a data-id='<?php echo $category['category_id']; ?>' href="" class='cats-category' style='color:#AAA;' ><?php echo $category['title'] ?></a>
                                            <?php if ($category['subcategories'])
                                            { ?>
                                            <ul class='subcats hidden'>
                                        <?php foreach ($category['subcategories'] as $subcat)
                                        { ?>
                                                    <li style='border:none !important;padding-left:0px'>
                                                        <a data-id='<?php echo $subcat['category_id']; ?>' class='' href=""><?php echo $subcat['title'] ?></a>
                                                    </li>
                                        <?php } ?>
                                            </ul>
                                    <?php } ?>
                                    </li>
                                <?php } ?>
                            </ul>

                            <input type='hidden' id='catId' name='sport_category' class='sport_category' value = '<?php echo $this->sport_category; ?>'/>
                        </div>
                    </li>

                    <!-- Organiza -->
                    <li>
                        <div class="input" style="padding-top: 0px">
                            <label for="organiza"><?php echo $this->translate('Organiza'); ?> <br class="hide" /></label>
                            <span class="field"><input type="text" name="organiza" class="organiza" id="organiza" value="<?php echo $this->organiza; ?>" /></span>
                        </div>
                    </li>


                    <!-- Ubicacion -->
                    <li>
                        <div class="input" style="padding-top: 0px">
                            <label for="location"><?php echo $this->translate('Location activate'); ?> <br class="hide" /></label>
                            <span class="field"><input type="text" name="location" class="location" id="searchTextField" value="<?php echo $this->location; ?>" /></span>
                        </div>

                        <div id="map-canvas"></div>
                        
                    </li>

                    <!-- Fecha -->
                    <li>
                        <div class="input" style="padding-top: 0px">
                            <label for="date"><?php echo $this->translate('Fecha'); ?> <br class="hide" /></label>
                            <span class="field"><?php echo $this->translate('Desde'); ?>  <input type="text" name="date_event1" class="date_event1" id="date_event1" value="<?php echo $this->date_event1; ?>" /></span>
                            </div>
                    </li>
                    <li>    
                        <div class="input" style="padding-top: 0px">
                            <label for="date">&nbsp; <br class="hide" /></label>
                            <span class="field"><?php echo $this->translate('Hasta'); ?>  <input type="text" name="date_event2" class="date_event2" id="date_event2" value="<?php echo $this->date_event2; ?>" /></span>
                        </div>

                    </li>
                    
                    
                    <!-- Publicado -->
                    <li>
                        <label for="id_publicado_0"><?php echo $this->translate('Publicado por:'); ?></label>
                        <div id="genderOptions" class="Right">
                                <label for="id_publicado_0"><input <?php echo ($this->gender == 'followers' ? 'checked="checked"' : ''); ?> type="radio" name="compartir" class="compartir" value="followers" id="compartir"> <?php echo $this->translate('Sólo Gente que sigo'); ?></label>
                                <label for="id_publicado_1"><input <?php echo ($this->gender == 'amatteur' ? 'checked="checked"' : ''); ?> type="radio" name="compartir" class="compartir" value="amatteur" id="compartir"> <?php echo $this->translate('Comunidad Amatteur'); ?></label>
                        </div>
                    </li>
                    
                    <!-- Grabar -->
                    <li>
                        <div class="left w335px">
                            <div class="submit" style="padding-top: 0px">
                                
                            &nbsp;&nbsp;<input class="red mbtn message" style="font-size:18px;background: #00538e !important; " type="submit" name="register" value="<?php echo $this->translate('Search'); ?>">
                            &nbsp;&nbsp;<!--input class="red mbtn message close" style="font-size:18px;width:80px" value="<?php echo $this->translate('Cancel'); ?>"-->
                            </div>
                        </div>
                    </li>				
                </ul>

		<!--p class="submit"><input type="submit" value="<?php echo $this->translate('Search');?>" name="register" /></p-->
	</form>
</div>     

                <div id="mapa" style="width: 1000px; height: 400px;margin-top:210px;margin-left:40px"></div>
                <image src="data/images/ajax-loader.gif" style="width: 50px; height: 50px; margin-top:-400px;margin-left:600px" />
            
            <?php } else { ?>                            

                <?php if ($this->eventos) { ?>
                    <div id="mapa" style="width: 1000px; height: 400px;margin-top:90px;margin-left:200px"></div>
                    <image src="data/images/ajax-loader.gif" style="width: 50px; height: 50px; margin-top:-400px;margin-left:600px" />
                    <br/>
                    <label style="color:#8C7E7E;font-weight: bold;font-size: 1.2em;margin-left:550px "><?php echo sprintf($this->translate('Para detalles de resultados, por favor ver mas abajo. Gracias'));?></label>
                    <div id="container" style="margin-left:400px">
                        <?php echo $this->eventsBox;?>
                    </div>
                <?php } ?>                

            <?php } ?>                                
              

		
		<div class="clear"></div>
	</div>
	
</body>
    
   
	<?php if($this->follow_user) { ?>
	<script type="text/javascript">
	$(document).ready(function(){
		Pins.initFollow('#container .box.user .follow a');
	});
	</script>
	<?php } ?>
	<script type="text/javascript">
	$(document).ready(function(){
                <?php /*if ($this->pins) { ?>
                        $("#container").focus();
                <?php } else { ?>                        
                        $("#container1").focus();
                <?php }*/ ?>
	});
	</script>
        
<script src="data/js/jquery-ui-timepicker-addon.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="data/css/jquery-ui-timepicker-addon.css"/>

<script type="text/javascript">
$(document).ready(function(){
    
    

        $('#date_event1').datetimepicker({
            dateFormat: 'dd/mm/yy',
            controlType: 'select'
        });

        $('#date_event2').datetimepicker({
            dateFormat: 'dd/mm/yy',
            controlType: 'select'
        });

});        
</script>

<script src="http://maps.google.com/maps?file=api&amp;v=3&amp;key=AIzaSyA60eSDixfIlHokj6GbjmqiRUN0GlBOTAM"
      type="text/javascript"></script>

    <script type="text/javascript">
   
   /*     
    var locations = [
      ['madriles', 40.4284034, -3.7149525, 1]
    ];      
      */



function GLoad() 
{
    var geocoder;
    var map;



<?php if($this->eventos) { ?>;
        
        var lat = [];
        var lng = [];
        var locations = [];
        var fullname = [];
        var avatar = [];
        var href = [];
        var date_event = [];


    <?php if ($this->location) { ?>
        
         var locationPrincipal = '<?php echo ($this->location)?>';
         var i = 1;       
         var len = <?php echo count($this->eventos); ?>;
         
        <?php foreach($this->eventos as $user) { ?>
            //var location = '<?php echo ($this->location)?>';
            var location = '<?php echo $user["location"];?>';
            //if (location != "")
            {
                locations.push(location);
                fullname.push('<?php echo $user["eventname"]; ?>');
                <?php $avatar = Helper_Uploadimages::avatar($user, '_B'); ?>
                avatar.push('<?php echo $avatar['image']; ?>');
                lat.push('<?php echo $user["lat"]; ?>');
                lng.push('<?php echo $user["len"]; ?>');
                href.push('<?php echo $user["href"]; ?>');
                date_event.push('<?php echo $user["date_event"]; ?>');
                

                var geocoder = new google.maps.Geocoder();
                geocoder.geocode({ 'address': locationPrincipal }, function (results, status) {
                    if (status == google.maps.GeocoderStatus.OK) 
                    {
                        var latAux = results[0].geometry.location.lat().toString().substr(0, 12);
                        var lngAux = results[0].geometry.location.lng().toString().substr(0, 12);

                          var obj =latAux;
                          lat.push(obj);
                          var obj2 =lngAux;
                          lng.push(obj2);

                    }
                    else
                    {
                        try
                        {
                            console.log('error: ' + status);
                        }
                        catch(e)
                        {
                            if (window.console // check for window.console not console
                                && window.console.log)
                            {
                                window.log('error: ' + status);
                            }

                        }
                    }

                    if (i == len)
                    {
                        colocar();
                    }
                    i++;
                    pausecomp(201);
              });
          }
          
        <?php } ?>          



    <?php } else { ?>    
 
         var i = 1;
         var len = <?php echo count($this->eventos); ?>;
        
        <?php foreach($this->eventos as $user) { ?>
            

                locations.push('<?php echo $user["location"]; ?>');
                fullname.push('<?php echo $user["eventname"]; ?>');
                <?php $avatar = Helper_Uploadimages::avatar($user, '_B'); ?>
                avatar.push('<?php echo $avatar['image']; ?>');

                lat.push('<?php echo $user["lat"]; ?>');
                lng.push('<?php echo $user["len"]; ?>');
                href.push('<?php echo $user["href"]; ?>');
                date_event.push('<?php echo $user["date_event"]; ?>');                
        <?php } ?>
            
            colocar();
            
    <?php } ?>

    function pausecomp(ms) {
        ms += new Date().getTime();
        while (new Date() < ms){}
    } 

    function colocar()
    {

        if (lat.length == 0)
        {
            $(document).ready(function(){ 
                $('#mapa').remove();
            });
        }

        var myLatlngCenter = new google.maps.LatLng(lat[0],lng[0]);

        var mapOptions = {
          zoom: 5,
          center: myLatlngCenter,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        }

        var map = new google.maps.Map(document.getElementById('mapa'), mapOptions);

      var gm = google.maps;
      var iw = new gm.InfoWindow();
	  
      var oms = new OverlappingMarkerSpiderfier(map,
        {markersWontMove: true, markersWontHide: true});
      
	  
      var usualColor = 'F75850';
      var spiderfiedColor = 'ffee22';
      var iconWithColor = function(color) {
        return 'http://chart.googleapis.com/chart?chst=d_map_xpin_letter&chld=pin|+|' +
          color + '|000000|ffff00';
      }
	  
      var shadow = new gm.MarkerImage(
        'https://www.google.com/intl/es_ALL/mapfiles/shadow50.png',
        new gm.Size(37, 34), // size - for sprite clipping
        new gm.Point(0, 0), // origin - ditto
        new gm.Point(10, 34) // anchor - where to meet map location
      );
      
      oms.addListener('click', function(marker) {
        iw.setContent(marker.desc);
        iw.open(map, marker);
      });
      oms.addListener('spiderfy', function(markers) {
        for(var i = 0; i < markers.length; i ++) {
          markers[i].setIcon(iconWithColor(spiderfiedColor));
          markers[i].setShadow(null);
        }
        iw.close();
      });
      oms.addListener('unspiderfy', function(markers) {
        for(var i = 0; i < markers.length; i ++) {
          markers[i].setIcon(iconWithColor(usualColor));
          markers[i].setShadow(shadow);
        }
      });
      
      var bounds = new gm.LatLngBounds();
      for (var i = 0; i < locations.length; i ++) {
          
            var locationString = locations[i];
            var fullnameString = fullname[i];
            var avatarString = avatar[i];
            var hrefString = href[i];
            var dateString = date_event[i];
          
            var contentString = '<div id="contenido">'+
                '<div id="siteNotice">'+
                '</div>'+
                '<h2 id="firstHeading" class="firstHeading">' + 
                fullnameString +
                '</h2>'+
                '<div id="bodyContent">'+ 
                '<p><b>' + locationString +
                '</b></p><p>' + 
                dateString + 
                '</p>' +
                '<a href="' + hrefString + '">'+
                '<p><img src="'+ avatarString + '">' +
                '</a> ' +
                '</p>'+
                '</div>'+
                '</div>';
          
          
        var loc = new gm.LatLng(lat[i],lng[i]);
        bounds.extend(loc);
        var marker = new gm.Marker({
          position: loc,
          title: fullnameString + ", " + locationString,
          map: map,
          icon: iconWithColor(usualColor),
          shadow: shadow
        });
        marker.desc = contentString;
        oms.addMarker(marker);
      }
      map.fitBounds(bounds)

    }
    

<?php } ?> 

}

</script>        
        
<script type="text/javascript">

$(document).ready(function(){





		$('form').on('submit',function(event){
                    //showAddress(this.searchTextField.value, this.zoom.value=parseFloat(this.zoom.value));
    //$form = $(this);
    //alert('the action is: ' + $form.attr('action')); 
    

                    });

        
	$("#selectBox-dropdown-menu-Category").bind('mouseleave',function(event){
        		$("#selectBox-Category").show();
                	$("#selectBox-dropdown-menu-Category").hide();

        });
        
        

        $("#selectBox-Category").bind('click',function(event){
            $('ul.hidden').hide();
            event.preventDefault();
            $("#selectBox-Category").hide();
            $("#selectBox-dropdown-menu-Category").show();

   

            $(".master").unbind('click').bind('click',function(event){
                event.preventDefault();

			
                var children  = $(this).find($('ul'));
                if(children.hasClass('opened'))
                {
                    children.hide().removeClass('opened');
                    
                    $(".cats-category").bind('dblclick',function(event){
                                event.preventDefault();
                                var self  = $(this);
                            appendElementInMain(self);
                    });
			
				
                }
                else
                {
                    $(".hidden").hide();
                    var self  = $(this);
                    children.addClass('opened');


                    if($(children).hasClass('hidden'))
                    {
                        children.show();
                        children.find('li a').click(function(event){
                            event.preventDefault();
                            appendElementInMain($(this));
                            $(".hidden").hide();
                        });
                    }
                    else
                    {
                        appendElementInMain(self.find($('a')));
				
                    }

                }
            });
	

            function appendElementInMain(element){
                $("#selectBox-dropdown-menu-Category").hide();
                $("#selectBox-Category").show();
                $("#selectBox-label-Category").text(element.text());
                $("#catId").val(element.data("id"));
			
            }
        });

	return;
	
	
});

</script>

<script type="text/javascript">
	<?php if($this->successfu_edite) { ?>
	Pins.success('<?php echo $this->translate('Information is successfully changed!');?>');
	<?php } ?>
	<?php if($this->error) { ?>
	Pins.error('<?php echo $this->error;?>');
	<?php } ?>
</script>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places&language=es"></script>    
    <script>
function initialize() {
  var mapOptions = {
    center: new google.maps.LatLng(-33.8688, 151.2195),
    zoom: 13,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  };
  var map = new google.maps.Map(document.getElementById('map-canvas'),
    mapOptions);

  var input = /** @type {HTMLInputElement} */(document.getElementById('searchTextField'));
  var autocomplete = new google.maps.places.Autocomplete(input);


  autocomplete.bindTo('bounds', map);

  var infowindow = new google.maps.InfoWindow();
  var marker = new google.maps.Marker({
    map: map
  });
    //showAddress(this.input.value, parseFloat(15)); 
    
   input = /** @type {HTMLInputElement} */(document.getElementById('searchTextField2'));
   autocomplete = new google.maps.places.Autocomplete(input);

  autocomplete.bindTo('bounds', map);

  var infowindow = new google.maps.InfoWindow();
  var marker = new google.maps.Marker({
    map: map
  });

   input = /** @type {HTMLInputElement} */(document.getElementById('searchTextField3'));
   autocomplete = new google.maps.places.Autocomplete(input);

  autocomplete.bindTo('bounds', map);

  var infowindow = new google.maps.InfoWindow();
  var marker = new google.maps.Marker({
    map: map
  });


    
  google.maps.event.addListener(autocomplete, 'place_changed', function() {
    infowindow.close();
    marker.setVisible(false);
    input.className = '';
    var place = autocomplete.getPlace();
    if (!place.geometry) {
      // Inform the user that the place was not found and return.
      input.className = 'notfound';
      return;
    }

    // If the place has a geometry, then present it on a map.
    if (place.geometry.viewport) {
      map.fitBounds(place.geometry.viewport);
    } else {
      map.setCenter(place.geometry.location);
      map.setZoom(17);  // Why 17? Because it looks good.
    }
    marker.setIcon(/** @type {google.maps.Icon} */({
      url: place.icon,
      size: new google.maps.Size(71, 71),
      origin: new google.maps.Point(0, 0),
      anchor: new google.maps.Point(17, 34),
      scaledSize: new google.maps.Size(35, 35)
    }));
    marker.setPosition(place.geometry.location);
    marker.setVisible(true);

    var address = '';
    if (place.address_components) {
      address = [
        (place.address_components[0] && place.address_components[0].short_name || ''),
        (place.address_components[1] && place.address_components[1].short_name || ''),
        (place.address_components[2] && place.address_components[2].short_name || '')
      ].join(' ');
    }

    infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + address);
    infowindow.open(map, marker);
    

  });

  // Sets a listener on a radio button to change the filter type on Places
  // Autocomplete.
  function setupClickListener(id, types) {
    var radioButton = document.getElementById(id);
    google.maps.event.addDomListener(radioButton, 'click', function() {
      autocomplete.setTypes(types);
    });
  }

  setupClickListener('changetype-all', []);
  setupClickListener('changetype-establishment', ['establishment']);
  setupClickListener('changetype-geocode', ['geocode']);
}

google.maps.event.addDomListener(window, 'load', initialize);

    </script>
        

<?php echo $this->footer_part; ?>