<?php 
	$module = $this->getRequest()->getModule();
?>

<form name="admin_form" id="admin_form" method="post" action="">

	<div class="info_line top">
		<h3 class="fleft title">
			<img alt="" src="cms/<?php echo $module;?>/images/extensions.png">
			<?php echo $this->translate('Banners');?>
		</h3>
		
		<span id="fader" class="fleft mleft30" style="display:none;">
			<span class="msgError"><span><?php echo $this->translate('Error!');?></span><i class="error_text"></i></span>
		</span>
		
		<div class="fright mtop3">
			<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<a class="button" href="<?php echo $module;?>/banners/"><?php echo $this->translate('Cancel');?></a>
		</div>
		<div class="clear"></div>
	</div>
	
	<div class="clear"></div>

	
	<table cellspacing="0" cellpadding="0" class="formtable">
		<tbody>
			<tr>
				<td width="150"><?php echo $this->translate('Name');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
				<td>
					<input type="text" size="55" title="<?php echo $this->translate('Please enter a name');?>" value="<?php echo $this->name;?>" class="inputbox required" name="name" />
        		</td>
			</tr>
			<tr>
				<td width="150"><?php echo $this->translate('Width');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
				<td>
					<input type="text" size="55" title="<?php echo $this->translate('Please enter a width');?>" value="<?php echo $this->width;?>" class="inputbox required" name="width" />
        		</td>
			</tr>
			<tr>
				<td width="150"><?php echo $this->translate('Height');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
				<td>
					<input type="text" size="55" title="<?php echo $this->translate('Please enter a height');?>" value="<?php echo $this->height;?>" class="inputbox required" name="height" />
        		</td>
			</tr>
			<tr>
				<td width="150"><?php echo $this->translate('Position');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
				<td>
					<input type="text" size="55" title="<?php echo $this->translate('Please enter a position');?>" value="<?php echo $this->position;?>" class="inputbox required" name="position" />
        		</td>
			</tr>
			<tr>
				<td width="150"><?php echo $this->translate('Code');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
				<td>
					<textarea style="width: 400px; height: 100px;" title="<?php echo $this->translate('Please enter a code');?>" class="inputbox required" name="html"><?php echo $this->html;?></textarea>
        		</td>
			</tr>
			<tr>
				<td width="150"><?php echo $this->translate('Page');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
				<td>
					<select name="controller_set">
						<?php foreach($this->controllers AS $k=>$v) { ?>
						<?php if($k == $this->controller_set) { ?>
						<option selected="selected" value="<?php echo $k;?>"><?php echo $v;?></option>
						<?php } else { ?>
						<option value="<?php echo $k;?>"><?php echo $v;?></option>
						<?php } ?>
						<?php } ?>
					</select>
        		</td>
			</tr>
			
		</tbody>
	</table>
	
	
	<div class="info_line bottom">
		<div class="fright mtop3">
			<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<a class="button" href="<?php echo $module;?>/banners/"><?php echo $this->translate('Cancel');?></a>
		</div>
		<div class="clear"></div>
	</div>
	
</form>