<?php echo $this->header_part; ?>

	<div id="category" class="noSeparator">
		<h3><?php echo $this->category['title'];?><?php echo $this->translate(": Ranking");?></h3>
		<div class="clear"></div>
	</div>


	<div id="containerRanking" class="container.ranking">
            <div class="titleRanking">
                <h1><?php echo $this->title;?></h1>
            </div>
<!--ul id="sorting-boards"-->                
		
		<?php echo $this->pins;?>
<!--/ul-->
		
		<div class="clear"></div>
	</div>

<?php echo $this->footer_part; ?>