<?php 
	$module = $this->getRequest()->getModule();
?>

<form name="admin_form" id="admin_form" method="post" action="">

	<div class="info_line top">
		<h3 class="fleft title">
			<img alt="" src="cms/<?php echo $module;?>/images/push_pin.png">
			<?php echo $this->translate('Pins');?>
		</h3>
		
		<span id="fader" class="fleft mleft30" style="display:none;">
			<span class="msgError"><span><?php echo $this->translate('Error!');?></span><i class="error_text"></i></span>
		</span>
		
		<div class="fright mtop3">
			<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<a class="button" href="<?php echo $module;?>/pins/"><?php echo $this->translate('Cancel');?></a>
		</div>
		<div class="clear"></div>
	</div>
	
	<div class="clear"></div>

	
	<table cellspacing="0" cellpadding="0" class="formtable">
		<tbody>
			<tr>
				<td width="150"><?php echo $this->translate('Pin');?>#</td>
				<td>
					<a href="<?php echo $this->pin_href;?>" target="_blank"><?php echo $this->pin_id;?></a>
        		</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('Description');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
				<td>
					<textarea style="width: 600px; height: 150px;" title="<?php echo $this->translate('Please enter a Description');?>" class="inputbox required" name="description"><?php echo $this->description;?></textarea>
        		</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('From');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
				<td>
					<input type="text" size="85" title="<?php echo $this->translate('Please enter from');?>" value="<?php echo $this->from;?>" class="inputbox required" name="from" />
        		</td>
			</tr>
			<tr>
				<td><?php echo $this->translate('Board');?>: <img title="<?php echo $this->translate('This field is required');?>" class="tooltip" alt="<?php echo $this->translate('This field is required');?>" src="cms/<?php echo $module;?>/images/required.gif"></td>
				<td>
					<select name="board_id" class="inputbox required">
						<?php if($this->boards) { ?>
						<?php foreach($this->boards AS $board) { ?>
						<option <?php echo ($board['board_id']==$this->board_id?'selected="selected"':'');?> value="<?php echo $board['board_id'];?>"><?php echo $board['title'];?></option>
						<?php } ?>
						<?php } ?>
					</select>
        		</td>
			</tr>
			
		</tbody>
	</table>
	
	
	<div class="info_line bottom">
		<div class="fright mtop3">
			<input type="submit" value="<?php echo $this->translate('Save');?>" class="button" name="submit">
			<a class="button" href="<?php echo $module;?>/pins/"><?php echo $this->translate('Cancel');?></a>
		</div>
		<div class="clear"></div>
	</div>
	
</form>