<?php echo $this->header_part; ?>

	<div id="container" style="width:0px important!">
	
		<div id="ContextBarqSearch" class="box2" style="width:0px important!">
			<div class="box2" style="width:0px important!">
				<p>
                                <!--div id="panel">
                <p class="input"-->
                    <label><a id="morelocations" href="<?php echo $this->advanced_url ?>?id=amatteur" class="Button RedButton morelocations " style="margin-top:0px;" ><?php echo $this->translate('Amatteur');?></a></label>
                    <label><a id="morelocations" href="<?php echo $this->advanced_url ?>?id=activate" class="Button RedButton morelocations " style="margin-top:0px;" ><?php echo $this->translate('Deportistas Activados');?></a></label>
                    <label><a id="morelocations" href="<?php echo $this->advanced_url ?>?id=services" class="Button RedButton morelocations " style="margin-top:0px;" ><?php echo $this->translate('Servicios y Negocios');?></a></label>
                <!--/p>                                    
</div-->                                    		
			<?php /*foreach($this->menuSearch AS $key => $menu) { ?>
					<?php echo ($key?' ·':'');?>
					<?php if($menu['active']) { ?>
					<span class="selected"><?php echo $menu['title']?></span>
					<?php } else { ?>
					<a href="<?php echo $menu['href']?>"><?php echo $menu['title']?></a>
					<?php } ?>
					<?php } */ ?>
	            	<!--span class="greyselected"> 
	            		&mdash; <?php echo $this->translate('search results for');?><span class="hilight"><?php echo $this->query;?></span>
	            	</span-->
	        	</p>
        	</div>
        </div>
            
       <?php if (!$this->pins) { ?>
            
            <!----------------------- AMATTEUR ------------------------------->            
            <?php if ($this->advancedActive == "amatteur") { ?>
            <div id="panel">
	<form action="<?php echo $this->search_action; ?>?id=amatteur" method="post" class="edit search">
	
		<p class="input">
                        <label for="tc"><?php echo sprintf($this->translate('Buscar en Amatteur')); ?> <br class="hide" /></label>
                        <span class="field">
                        <div style="display:table">
                            <div style="display:table-cell">
                                <div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option1 == '1' ? 'checked="checked"' : ''); ?>  type='checkbox' id='option1' name='option1' class='option1' value="1" ><?php echo " ". sprintf($this->translate('Boards')); ?> </span>
                                </div><div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option2 == '1' ? 'checked="checked"' : ''); ?>  type='checkbox' id='option2' name='option2' class='option2' value="1"><?php echo " ". sprintf($this->translate('Users')); ?> </span>
                                </div><div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option3 == '1' ? 'checked="checked"' : ''); ?>  type='checkbox' id='option3' name='option3' class='option3' value="1"><?php echo " ". sprintf($this->translate('Pins')); ?> </span>
                                </div><div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option4 == '1' ? 'checked="checked"' : ''); ?>  type='checkbox' id='option4' name='option4' class='option4' value="1"><?php echo " ". sprintf($this->translate('Videos')); ?> </span>
                                </div>
                            </div>
                            <div style="display:table-cell">
                                <div style="display:table-row">
                                    &nbsp;&nbsp;&nbsp;
                                </div>
                            </div>

                            <div style="display:table-cell">
                                <div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option5 == '1' ? 'checked="checked"' : ''); ?>  type='checkbox' id='option5' name='option5' class='option5' value="1"><?php echo " ". sprintf($this->translate('Gifts')); ?> </span>
                                </div><div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option6 == '1' ? 'checked="checked"' : ''); ?>  type='checkbox' id='option6' name='option6' class='option6' value="1"><?php echo " ". sprintf($this->translate('Articles')); ?> </span>
                                </div><div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option7 == '1' ? 'checked="checked"' : ''); ?>  type='checkbox' id='option7' name='option7' class='option7' value="1"><?php echo " ". sprintf($this->translate('All')); ?> </span>
                                </div><div style="display:table-row">
                                    <!--span class="" style='text-align:left'><input type='checkbox' id='option8' name='option8' class='option8' value="1"><?php echo " ". sprintf($this->translate('Tutor begins trainee')); ?> </span-->
                                </div>
                            </div>
                        </div>
                            </span>
                </p>
                
		<p class="input">
			<label for="palabrasclave"><?php echo $this->translate('Palabras Clave');?> <br class="hide" /></label>
			<span class="field"><input type="text" name="words" id="words" value="<?php echo $this->words; ?>" /></span>
		</p>
                
		<p class="input">
			<label for="firstname"><?php echo $this->translate('First name');?> <br class="hide" /></label>
			<span class="field"><input type="text" name="firstname" id="firstname" value="<?php echo $this->firstname; ?>" /></span>
		</p>
                
                    <!-- Gender -->
		<p class="input">
                        <label for="id_gender_0"><?php echo $this->translate('Gender'); ?><br class="hide" /></label>
                        <span class="field">
                        <div id="genderOptions" class="Right">
                                <label for="id_gender_0"><input <?php echo ($this->gender == 'male' ? 'checked="checked"' : ''); ?> type="radio" name="gender" class="gender" value="male" id="id_gender_male"> <?php echo $this->translate('Male'); ?></label>
                                <label for="id_gender_1"><input <?php echo ($this->gender == 'female' ? 'checked="checked"' : ''); ?> type="radio" name="gender" class="gender" value="female" id="id_gender_female"> <?php echo $this->translate('Female'); ?></label>
                        </div>
                        </span>    
                </p>
<br/>
                    <!--  Location -->
		<p class="input">
			<label for="ubication"><?php echo $this->translate('Location');?> <br class="hide" /></label>
			<span class="field"><input type="text" name="location" id="searchTextField" value="<?php echo $this->location;?>" /></span>
		</p>
    <!--div id="panel" style="margin-left: 260px">
      <input id="searchTextField" type="text" size="50">
      <input type="radio" name="type" id="changetype-all" checked="checked">
      <label for="changetype-all">All</label>

      <input type="radio" name="type" id="changetype-establishment">
      <label for="changetype-establishment">Establishments</label>

      <input type="radio" name="type" id="changetype-geocode">
      <label for="changetype-geocode">Geocodes</lable>
    </div-->
                 <div id="map-canvas"></div>
                

       
    <div id="create-board" class="Form StaticForm" style="padding-left:0px;" >
            <ul style="margin:0px;">
                
                
                <!-- Deportes -->
                <li style="border:0px">
                    <label for="category_id-select<?php echo ($this->is_edit?'-edit':'');?>"><?php echo $this->translate('Sports');?></label>
                    <div class="Right" id='catList'>
                         
                         <a href="" class='selectBox selectBox-dropdown' id='selectBox-Category1' style='width: 352px; display: inline-block;'>
                         	<?php if(!$this->cat_title1){?>
                         		 <span class='selectBox-label' id='selectBox-label-Category1' style="width: 352px;"><?php echo  $this->translate('Please choose sport');?></span>
                         	<?php }else{?>
                         		<span class='selectBox-label' id='selectBox-label-Category1' style="width: 352px;"><?php echo  $this->cat_title1;?></span>
                         	<?php }?>
                         	 <span class="selectBox-arrow" style=""></span>
                         </a>
                         
                         <ul class='selectBox-dropdown-menu selectBox-options' id='selectBox-dropdown-menu-Category1' style='display:none;overflow-x: hidden;width: 370px;'>
                         
                        	<?php $i=0; foreach($this->categories as $category) { ?>
                        		<li  class = 'master cat1' style='border:none !important' >
                                                <?php if ($i==0) { $i=1; ?>
                                                <a data-id='<?php echo 0; ?>' href="" class='cats-category1' style='color:#AAA;' ><?php echo "Todo"; ?></a>
                                                <ul class='subcats hidden'><li style='border:none !important;padding-left:0px'></li></ul>
                                                <?php } ?>

                        			<a data-id='<?php echo $category['category_id'];?>' href="" class='cats-category1' style='color:#AAA;' ><?php echo $category['title']?></a>
                        			<?php if($category['subcategories']){?>
                        				<ul class='subcats hidden'>
                        					<?php foreach($category['subcategories'] as $subcat){?>
	                        					<li style='border:none !important;padding-left:0px'>
	                        						<a data-id='<?php echo $subcat['category_id']; ?>' class='' href=""><?php echo $subcat['title']?></a>
	                        					</li>
                        					<?php }?>
                        				</ul>
                        			<?php }?>
                        		</li>
                        	<?php }?>
                        </ul>
                        
                        <input type='hidden' id='catId1' name='sport_category_1' value = '<?php echo $this->sport_category_1;?>'/>
                      
                    </div>
                </li>

                <li style="border:0px">
                    <label for="category_id-select<?php echo ($this->is_edit?'-edit':'');?>"><?php echo $this->translate('');?></label>
                    <div class="Right" id='catList'>
                         
                         <a href="" class='selectBox selectBox-dropdown' id='selectBox-Category2' style='width: 352px; display: inline-block;'>
                         	<?php if(!$this->cat_title2){?>
                         		 <span class='selectBox-label' id='selectBox-label-Category2' style="width: 345px;"><?php echo  $this->translate('Please choose sport');?></span>
                         	<?php }else{?>
                         		<span class='selectBox-label' id='selectBox-label-Category2' style="width: 345px;"><?php echo  $this->cat_title2;?></span>
                         	<?php }?>
                         	 <span class="selectBox-arrow" style=""></span>
                         </a>
                         
                         <ul class='selectBox-dropdown-menu selectBox-options' id='selectBox-dropdown-menu-Category2' style='display:none;overflow-x: hidden;width: 370px;'>
                         
                        	<?php $i=0; foreach($this->categories as $category) { ?>
                        		<li  class = 'master cat2' style='border:none !important' >
                                                <?php if ($i==0) { $i=1; ?>
                                                <a data-id='<?php echo 0; ?>' href="" class='cats-category2' style='color:#AAA;' ><?php echo "Todo"; ?></a>
                                                <ul class='subcats hidden'><li style='border:none !important;padding-left:0px'></li></ul>
                                                <?php } ?>

                        			<a data-id='<?php echo $category['category_id'];?>' href="" class='cats-category2' style='color:#AAA;' ><?php echo $category['title']?></a>
                        			<?php if($category['subcategories']){?>
                        				<ul class='subcats hidden'>
                        					<?php foreach($category['subcategories'] as $subcat){?>
	                        					<li style='border:none !important;padding-left:0px'>
	                        						<a data-id='<?php echo $subcat['category_id']; ?>' class='' href=""><?php echo $subcat['title']?></a>
	                        					</li>
                        					<?php }?>
                        				</ul>
                        			<?php }?>
                        		</li>
                        	<?php }?>
                        </ul>
                        
                        <input type='hidden' id='catId2' name='sport_category_2' value = '<?php echo $this->sport_category_2;?>'/>
                      
                    </div>
                </li>

                                
                <li style="border:0px">
                    <label for="category_id-select<?php echo ($this->is_edit?'-edit':'');?>"><?php echo $this->translate('');?></label>
                    <div class="Right" id='catList'>
                         
                         <a href="" class='selectBox selectBox-dropdown' id='selectBox-Category3' style='width: 352px; display: inline-block;'>
                         	<?php if(!$this->cat_title3){?>
                         		 <span class='selectBox-label' id='selectBox-label-Category3' style="width: 345px;"><?php echo  $this->translate('Please choose sport');?></span>
                         	<?php }else{?>
                         		<span class='selectBox-label' id='selectBox-label-Category3' style="width: 345px;"><?php echo  $this->cat_title3;?></span>
                         	<?php } ?>
                         	 <span class="selectBox-arrow" style=""></span>
                         </a>
                         
                         <ul class='selectBox-dropdown-menu selectBox-options' id='selectBox-dropdown-menu-Category3' style='display:none;overflow-x: hidden;width: 370px;'>
                         
                        	<?php $i=0; foreach($this->categories as $category) { ?>
                        		<li  class = 'master cat3' style='border:none !important' >
                                                <?php if ($i==0) { $i=1; ?>
                                                <a data-id='<?php echo 0; ?>' href="" class='cats-category3' style='color:#AAA;' ><?php echo "Todo"; ?></a>
                                                <ul class='subcats hidden'><li style='border:none !important;padding-left:0px'></li></ul>
                                                <?php } ?>
                        			<a data-id='<?php echo $category['category_id'];?>' href="" class='cats-category3' style='color:#AAA;' ><?php echo $category['title']?></a>
                        			<?php if($category['subcategories']){?>
                        				<ul class='subcats hidden'>
                        					<?php foreach($category['subcategories'] as $subcat){?>
	                        					<li style='border:none !important;padding-left:0px'>
	                        						<a data-id='<?php echo $subcat['category_id']; ?>' class='' href=""><?php echo $subcat['title']?></a>
	                        					</li>
                        					<?php }?>
                        				</ul>
                        			<?php }?>
                        		</li>
                        	<?php }?>
                        </ul>
                        
                        <input type='hidden' id='catId3' name='sport_category_3' value = '<?php echo $this->sport_category_3;?>'/>
                      
                    </div>
                </li>

            </ul>
        </div>  
        <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
		
		<div class="hr"></div>
		<p class="submit"><input type="submit" value="<?php echo $this->translate('Search');?>" name="register" /></p>
	</form>
</div>    
            
            
            
            
            <!----------------------- ACTIVATE ------------------------------->
            <?php } else if ($this->advancedActive == "activate") { ?>
            <div id="panel">
	<form action="<?php echo $this->search_action; ?>?id=activate" method="post" class="edit search StaticForm">
	<input type="hidden" name="words" id="words" value="ok" />
                <ul>
                    <!-- Gender -->
                    <li>
                        <label for="id_gender_0"><?php echo $this->translate('Gender'); ?></label>
                        <div id="genderOptions" class="Right">
                                <label for="id_gender_0"><input <?php echo ($this->gender == 'male' ? 'checked="checked"' : ''); ?> type="radio" name="gender" class="gender" value="male" id="id_gender_male"> <?php echo $this->translate('Male'); ?></label>
                                <label for="id_gender_1"><input <?php echo ($this->gender == 'female' ? 'checked="checked"' : ''); ?> type="radio" name="gender" class="gender" value="female" id="id_gender_female"> <?php echo $this->translate('Female'); ?></label>
                        </div>
                    </li>
                    <!-- Edad -->
                    <li>
                        <label for="type_user-select<?php echo ($this->is_edit ? '-edit' : ''); ?>"><?php echo $this->translate('Age'); ?></label>
                        <div class="Right" id='catList'>
                            <a href="" class='selectBox selectBox-dropdown' id='selectBox-Age' style='width: 352px; display: inline-block;'>
                                <?php if (!$this->age_title)
                                { ?>
                                    <span class='selectBox-label' id='selectBox-label-Age' style="width: 345px;"><?php echo $this->translate('Please choose age'); ?></span>
                                <?php } else
                                { ?>
                                    <span class='selectBox-label' id='selectBox-label-Age' style="width: 345px;"><?php echo $this->age_title; ?></span>
                                <?php } ?>
                                <span class="selectBox-arrow" style=""></span>
                            </a>

                            <ul class='selectBox-dropdown-menu selectBox-options' id='selectBox-dropdown-menu-Age' style='display:none;overflow-x: hidden;width: 370px;'>

                            <?php foreach ($this->ages as $age)
                            { ?>
                                    <li  class = 'master' style='border:none !important' >
                                        <a data-id='<?php echo $age['age_id']; ?>' href="" class='' style='color:#AAA;' ><?php echo $age['age_title'] ?></a>
                                    </li>
                            <?php } ?>
                            </ul>

                            <input type='hidden' id='ageId' name='age' class='age' value = '<?php echo $this->age; ?>'/>

                        </div>
                    </li>
                    <!-- Ubicacion -->
                    <li>
                        <p class="input">
                            <label for="location"><?php echo $this->translate('Location'); ?> <br class="hide" /></label>
                            <span class="field"><input type="text" name="location" class="location" id="searchTextField" value="<?php echo $this->location; ?>" /></span>
                        </p>
                        <!--div id="panel" style="margin-left: 260px">
                          <input id="searchTextField" type="text" size="50">
                          <input type="radio" name="type" id="changetype-all" checked="checked">
                          <label for="changetype-all">All</label>
                    
                          <input type="radio" name="type" id="changetype-establishment">
                          <label for="changetype-establishment">Establishments</label>
                    
                          <input type="radio" name="type" id="changetype-geocode">
                          <label for="changetype-geocode">Geocodes</lable>
                        </div-->
                        <div id="map-canvas"></div>
                    </li>
                    <!-- Deporte -->
                    <li>
                        <label for="category_id-select<?php echo ($this->is_edit ? '-edit' : ''); ?>"><?php echo $this->translate('Sport'); ?></label>
                        <div class="Right" id='catList'>

                            <a href="" class='selectBox selectBox-dropdown' id='selectBox-Category' style='width: 352px; display: inline-block;'>
                                <?php if (!$this->cat_title)
                                { ?>
                                    <span class='selectBox-label' id='selectBox-label-Category' style="width: 352px;"><?php echo $this->translate('Please choose sport'); ?></span>
                                <?php } else
                                { ?>
                                    <span class='selectBox-label' id='selectBox-label-Category' style="width: 352px;"><?php echo $this->cat_title; ?></span>
                                <?php } ?>
                                <span class="selectBox-arrow" style=""></span>
                            </a>

                            <ul class='selectBox-dropdown-menu selectBox-options' id='selectBox-dropdown-menu-Category' style='display:none;overflow-x: hidden;width: 370px;'>

                                        <?php foreach ($this->categories as $category)
                                        { ?>
                                    <li  class = 'master' style='border:none !important' >
                                        <a data-id='<?php echo $category['category_id']; ?>' href="" class='' style='color:#AAA;' ><?php echo $category['title'] ?></a>
                                            <?php if ($category['subcategories'])
                                            { ?>
                                            <ul class='subcats hidden'>
                                        <?php foreach ($category['subcategories'] as $subcat)
                                        { ?>
                                                    <li style='border:none !important;padding-left:0px'>
                                                        <a data-id='<?php echo $subcat['category_id']; ?>' class='' href=""><?php echo $subcat['title'] ?></a>
                                                    </li>
                                        <?php } ?>
                                            </ul>
                                    <?php } ?>
                                    </li>
                                <?php } ?>
                            </ul>

                            <input type='hidden' id='catId' name='sport_category' class='sport_category' value = '<?php echo $this->sport_category; ?>'/>
                        </div>
                    </li>

                    <!-- Nivel -->
                    <li>
                        <label for="type_user-select<?php echo ($this->is_edit ? '-edit' : ''); ?>"><?php echo $this->translate('Level'); ?></label>
                        <div class="Right" id='catList'>

                            <a href="" class='selectBox selectBox-dropdown' id='selectBox-Level' style='width: 352px; display: inline-block;'>
                            <?php if (!$this->level_title)
                            { ?>
                                    <span class='selectBox-label' id='selectBox-label-Level' style="width: 345px;"><?php echo $this->translate('Please choose level'); ?></span>
                            <?php } else
                            { ?>
                                    <span class='selectBox-label' id='selectBox-label-Level' style="width: 345px;"><?php echo $this->level_title; ?></span>
                                <?php } ?>
                                <span class="selectBox-arrow" style=""></span>
                            </a>

                            <ul class='selectBox-dropdown-menu selectBox-options' id='selectBox-dropdown-menu-Level' style='display:none;overflow-x: hidden;width: 370px;'>

                            <?php foreach ($this->levels as $level)
                            { ?>
                                    <li  class = 'master' style='border:none !important' >
                                        <a data-id='<?php echo $level['level_id']; ?>' href="" class='' style='color:#AAA;' ><?php echo $level['level_title'] ?></a>
                                    </li>
                            <?php } ?>
                            </ul>

                            <input type='hidden' id='levelId' name='level' class='level' value = '<?php echo $this->level; ?>'/>
                        </div>
                    </li>
                    <!-- Opciones -->
                    <li>
                        <label for="tc"><?php echo sprintf($this->translate('Activate Options')); ?> <br class="hide" /></label>
                        <div style="display:table">
                            <div style="display:table-cell">
                                <div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option1 == '1' ? 'checked="checked"' : ''); ?>  type='checkbox' id='option1' name='option1' class='option1' value="1" ><?php echo " ". sprintf($this->translate('Practice sports together')); ?> </span>
                                </div><div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option2 == '1' ? 'checked="checked"' : ''); ?>  type='checkbox' id='option2' name='option2' class='option2' value="1"><?php echo " ". sprintf($this->translate('Organize match / tournament')); ?> </span>
                                </div><div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option3 == '1' ? 'checked="checked"' : ''); ?> type='checkbox' id='option3' name='option3' class='option3' value="1"><?php echo " ". sprintf($this->translate('Team look for sportman')); ?> </span>
                                </div><div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option4 == '1' ? 'checked="checked"' : ''); ?>  type='checkbox' id='option4' name='option4' class='option4' value="1"><?php echo " ". sprintf($this->translate('Sportman look for team')); ?> </span>
                                </div>
                            </div>
                            <div style="display:table-cell">
                                <div style="display:table-row">
                                    &nbsp;&nbsp;&nbsp;
                                </div>
                            </div>

                            <div style="display:table-cell">
                                <div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option5 == '1' ? 'checked="checked"' : ''); ?>  type='checkbox' id='option5' name='option5' class='option5' value="1"><?php echo " ". sprintf($this->translate('Look for sponsor')); ?> </span>
                                </div><div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option6 == '1' ? 'checked="checked"' : ''); ?>  type='checkbox' id='option6' name='option6' class='option6' value="1"><?php echo " ". sprintf($this->translate('Volunteer helps paraolimpics')); ?> </span>
                                </div><div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option7 == '1' ? 'checked="checked"' : ''); ?>  type='checkbox' id='option7' name='option7' class='option7' value="1"><?php echo " ". sprintf($this->translate('Trainee look for tutor')); ?> </span>
                                </div><div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option8 == '1' ? 'checked="checked"' : ''); ?>  type='checkbox' id='option8' name='option8' class='option8' value="1"><?php echo " ". sprintf($this->translate('Tutor begins trainee')); ?> </span>
                                </div>
                            </div>
                        </div>
                    </li>
                <!-- Grabar -->
                    <li>
                        <div class="left w335px">
                            <p class="submit">
                                
                            &nbsp;&nbsp;<input class="Button WhiteButton RedButton Button24 message" style="font-size:18px" type="submit" name="register" value="<?php echo $this->translate('Search'); ?>">
                            &nbsp;&nbsp;<input class="Button WhiteButton RedButton Button24 message close" style="font-size:18px;width:80px" value="<?php echo $this->translate('Cancel'); ?>">
                            </p>
                        </div>
                    </li>				
                </ul>

		<!--p class="submit"><input type="submit" value="<?php echo $this->translate('Search');?>" name="register" /></p-->
	</form>
</div>     
            
            
            
            
            
            <!----------------------------------------------- SERVICIOS Y NEGOCIOS ----------------------------------------------------------------->            
            <?php } else if ($this->advancedActive == "services") { ?>
            <div id="panel">
	<form action="<?php echo $this->search_action; ?>?id=services" method="post" class="edit search">
	
		<p class="input">
                        <!--label for="tc"><?php echo sprintf($this->translate('Activate Options')); ?> <br class="hide" /></label-->
                        <span class="field">
                        <div style="display:table">
                            <div style="display:table-cell">
                                <div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option1 == '3' ? 'checked="checked"' : ''); ?>  type='checkbox' id='option1' name='option1' class='option1' value="3" ><?php echo " ". sprintf($this->translate('Entrenador / Escuela')); ?> </span>
                                </div><div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option2 == '4' ? 'checked="checked"' : ''); ?>  type='checkbox' id='option2' name='option2' class='option2' value="4"><?php echo " ". sprintf($this->translate('Gimnasio')); ?> </span>
                                </div><div style="display:table-row">
                                    <!--span class="" style='text-align:left'><input <?php echo ($this->option3 == '1' ? 'checked="checked"' : ''); ?>  type='checkbox' id='option3' name='option3' class='option3' value="1"><?php echo " ". sprintf($this->translate('Club / Equipo')); ?> </span-->
                                </div><div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option4 == '6' ? 'checked="checked"' : ''); ?>  type='checkbox' id='option4' name='option4' class='option4' value="6"><?php echo " ". sprintf($this->translate('Medicina Deportiva / Salud')); ?> </span>
                                </div><div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option5 == '7' ? 'checked="checked"' : ''); ?>  type='checkbox' id='option5' name='option5' class='option5' value="7"><?php echo " ". sprintf($this->translate('Tienda / Negocio')); ?> </span>
                                </div>
                            </div>
                            <div style="display:table-cell">
                                <div style="display:table-row">
                                    &nbsp;&nbsp;&nbsp;
                                </div>
                            </div>

                            <div style="display:table-cell">
                                <div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option6 == '8' ? 'checked="checked"' : ''); ?>  type='checkbox' id='option6' name='option6' class='option6' value="8"><?php echo " ". sprintf($this->translate('Instalaciones')); ?> </span>
                                </div><div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option7 == '9' ? 'checked="checked"' : ''); ?>  type='checkbox' id='option7' name='option7' class='option7' value="9"><?php echo " ". sprintf($this->translate('Empresa de Aventura')); ?> </span>
                                </div><div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option8 == '10' ? 'checked="checked"' : ''); ?>  type='checkbox' id='option8' name='option8' class='option8' value="10"><?php echo " ". sprintf($this->translate('Organismo Oficial')); ?> </span>
                                </div><div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option9 == '11' ? 'checked="checked"' : ''); ?>  type='checkbox' id='option9' name='option9' class='option9' value="11"><?php echo " ". sprintf($this->translate('Medios de Comunicacion')); ?> </span>
                                </div><div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option10 == '2' ? 'checked="checked"' : ''); ?>  type='checkbox' id='option10' name='option10' class='option10' value="2"><?php echo " ". sprintf($this->translate('All')); ?> </span>
                                </div>
                            </div>
                        </div>
                            </span>
                </p>
		<p class="input">
			<label for="palabrasclave"><?php echo $this->translate('Palabras Clave');?> <br class="hide" /></label>
			<span class="field"><input type="text" name="words" id="words" value="<?php echo $this->words;?>" /></span>
		</p>
		<p class="input">
			<label for="firstname"><?php echo $this->translate('First name');?> <br class="hide" /></label>
			<span class="field"><input type="text" name="firstname" id="firstname" value="<?php echo $this->firstname;?>" /></span>
		</p>
                
                

       
    <div id="create-board" class="Form StaticForm" style="padding-left:0px;" >
            <ul style="margin:0px;">
                
                
                <!-- Deportes -->
                <li style="border:0px">
                    <label for="category_id-select<?php echo ($this->is_edit?'-edit':'');?>"><?php echo $this->translate('Sports');?></label>
                    <div class="Right" id='catList'>
                         
                         <a href="" class='selectBox selectBox-dropdown' id='selectBox-Category1' style='width: 352px; display: inline-block;'>
                         	<?php if(!$this->cat_title1){?>
                         		 <span class='selectBox-label' id='selectBox-label-Category1' style="width: 352px;"><?php echo  $this->translate('Please choose sport');?></span>
                         	<?php }else{?>
                         		<span class='selectBox-label' id='selectBox-label-Category1' style="width: 352px;"><?php echo  $this->cat_title1;?></span>
                         	<?php }?>
                         	 <span class="selectBox-arrow" style=""></span>
                         </a>
                         
                         <ul class='selectBox-dropdown-menu selectBox-options' id='selectBox-dropdown-menu-Category1' style='display:none;overflow-x: hidden;width: 370px;'>
                         
                        	<?php $i=0; foreach($this->categories as $category) { ?>
                        		<li  class = 'master cat1' style='border:none !important' >
                                                <?php if ($i==0) { $i=1; ?>
                                                <a data-id='<?php echo 0; ?>' href="" class='cats-category1' style='color:#AAA;' ><?php echo "Todo"; ?></a>
                                                <ul class='subcats hidden'><li style='border:none !important;padding-left:0px'></li></ul>
                                                <?php } ?>

                        			<a data-id='<?php echo $category['category_id'];?>' href="" class='cats-category1' style='color:#AAA;' ><?php echo $category['title']?></a>
                        			<?php if($category['subcategories']){?>
                        				<ul class='subcats hidden'>
                        					<?php foreach($category['subcategories'] as $subcat){?>
	                        					<li style='border:none !important;padding-left:0px'>
	                        						<a data-id='<?php echo $subcat['category_id']; ?>' class='' href=""><?php echo $subcat['title']?></a>
	                        					</li>
                        					<?php }?>
                        				</ul>
                        			<?php }?>
                        		</li>
                        	<?php }?>
                        </ul>
                        
                        <input type='hidden' id='catId1' name='sport_category_1' value = '<?php echo $this->sport_category_1;?>'/>
                      
                    </div>
                </li>



            </ul>
        </div>  

        <!--  Location -->
		<p class="input">
			<label for="ubication"><?php echo $this->translate('Location');?> <br class="hide" /></label>
			<span class="field"><input type="text" name="location" id="searchTextField" value="<?php echo $this->location;?>" /></span>
		</p>
    <!--div id="panel" style="margin-left: 260px">
      <input id="searchTextField" type="text" size="50">
      <input type="radio" name="type" id="changetype-all" checked="checked">
      <label for="changetype-all">All</label>

      <input type="radio" name="type" id="changetype-establishment">
      <label for="changetype-establishment">Establishments</label>

      <input type="radio" name="type" id="changetype-geocode">
      <label for="changetype-geocode">Geocodes</lable>
    </div-->
    <div id="map-canvas"></div>
    <br/>
                <!-- Grabar -->
                    <li>
                        <div class="left w335px">
                            <p class="submit">
                                
                            &nbsp;&nbsp;<input class="Button WhiteButton RedButton Button24 message" style="font-size:18px" type="submit" name="register" value="<?php echo $this->translate('Search'); ?>">
                            &nbsp;&nbsp;<input class="Button WhiteButton RedButton Button24 message close" style="font-size:18px;width:80px" value="<?php echo $this->translate('Cancel'); ?>">
                            </p>
                        </div>
                    </li>				

    
		<p class="submit"><input type="submit" value="<?php echo $this->translate('Search');?>" name="register" /></p>
	</form>
</div>                
					<?php } ?>            
            
            <?php } else { ?>
            
		<?php echo $this->pins;?>
            
            <?php } ?>
            

<script src="http://maps.google.com/maps?file=api&amp;v=2&amp;key=ABQIAAAAGAEGVZIXwwutieHF4QOL4RRpYoRN0FKJQ7RZd_AzeNEq2PLjZhR3W4-qrIA2KyJ0hRw-barmpbORVQ"
      type="text/javascript"></script>
    <script type="text/javascript">
    //<![CDATA[

	// Inicialización de variables.
    var map      = null;
    var geocoder = null;

    function load() {                                      // Abre LLAVE 1.
      if (GBrowserIsCompatible()) {						   // Abre LLAVE 2.
        map = new GMap2(document.getElementById("map"));

        map.setCenter(new GLatLng(37.567236,-1.803499), 15);
        map.addControl(new GSmallMapControl());
	   	map.addControl(new GMapTypeControl());

        geocoder = new GClientGeocoder();

        //---------------------------------//
        //   MARCADOR AL HACER CLICK
		//---------------------------------//
		GEvent.addListener(map, "click",
			function(marker, point) {
 		 		if (marker) {
               		null;
              		} else {
          			map.clearOverlays();
					var marcador = new GMarker(point);
					map.addOverlay(marcador);
					//marcador.openInfoWindowHtml("<b><br>Coordenadas:<br></b>Latitud : "+point.y+"<br>Longitud : "+point.x+"<a href=http://www.mundivideo.com/fotos_pano.htm?lat="+point.y+"&lon="+point.x+"&mapa=3 TARGET=fijo><br><br>Fotografias</a>");
					//marcador.openInfoWindowHtml("<b>Coordenadas:</b> "+point.y+","+point.x);
					document.form_mapa.coordenadas.value = point.y+","+point.x;
					}
  			}
			);
        //---------------------------------//
        //   FIN MARCADOR AL HACER CLICK
		//---------------------------------//

      } // Cierra LLAVE 1.
    }   // Cierra LLAVE 2.

    //---------------------------------//
    //           GEOCODER
	//---------------------------------//
	
    function showAddress(address, zoom) {
	
    	if (geocoder) {
        	geocoder.getLatLng(address,
          		function(point) {
            		if (!point) {
            			alert(address + " not found");
            		} else {
                                map.setCenter(point, zoom);
            			var marker = new GMarker(point);
            			map.addOverlay(marker);
            			//marker.openInfoWindowHtml("<b>"+address+"</b><br>Coordenadas:<br>Latitud : "+point.y+"<br>Longitud : "+point.x+"<a href=http://www.mundivideo.com/fotos_pano.htm?lat="+point.y+"&lon="+point.x+"&mapa=3 TARGET=fijo><br><br>Fotografias</a>");
       			     // marker.openInfoWindowHtml("<b>Coordenadas:</b> "+point.y+","+point.x);
       			      document.form_mapa.coordenadas.value = point.y + "," + point.x; 
               		}
               	}
        	);
      	}}
		
    //---------------------------------//
    //     FIN DE GEOCODER
	//---------------------------------//

    //]]>
     </script>
     <body onLoad="load();"  onunload="GUnload();">
          <form name="form_mapa" action="#" onsubmit=" showAddress(this.address.value, this.zoom.value=parseFloat(this.zoom.value)); return false">


      	<p style="font-size: 10px;font-family: verdana;font-weight: bold;">Dirección a buscar: <input type="text" name="address"  id="address" value="" style="width: 400px;font-size: 10px;font-family: verdana;font-weight: bold;" />

     	<input type="hidden" size="1" name="zoom" value=15 />
        <input type="submit" value="Ver" /></p>
        <p style="font-size: 10px;font-family: verdana;font-weight: bold;">Coordenadas: <input type="text" name="coordenadas" value="" style="width: 400px;font-size: 10px;font-family: verdana;font-weight: bold;" />
        </p>

      </form>
<div style="width: 700px; border-width: 1px; border-style: solid; border-color: #979797; padding:8px 8px 8px 8px;">
        <div id="map" style="width: 700px; height: 500px"></div>
       	</div>
</body>

            


		<div class="clear"></div>
	</div>
	
	<?php if($this->follow_user) { ?>
	<script type="text/javascript">
	$(document).ready(function(){
		Pins.initFollow('#container .box.user .follow a');
	});
	</script>
	<?php } ?>
	
<script type="text/javascript">
$(document).ready(function(){

		$('form').on('submit',function(event){
    //$form = $(this);
    //alert('the action is: ' + $form.attr('action')); 
    

                    });

	$("#selectBox-dropdown-menu-Category1").bind('mouseleave',function(event){
        		$("#selectBox-Category1").show();
                	$("#selectBox-dropdown-menu-Category1").hide();

        });


	$("#selectBox-Category1").bind('click',function(event){
		$('ul.hidden').hide();
		event.preventDefault();
		$("#selectBox-Category1").hide();
		$("#selectBox-dropdown-menu-Category1").show();
                
                if (!$("#selectBox-Category2").is(":visible"))  
                    {
        		$("#selectBox-Category2").show();
                	$("#selectBox-dropdown-menu-Category2").hide();
                    }
                if (!$("#selectBox-Category3").is(":visible"))  
                    {
        		$("#selectBox-Category3").show();
                	$("#selectBox-dropdown-menu-Category3").hide();
                    }
                if (!$("#selectBox-TypeUser").is(":visible"))  
                    {
                        $("#selectBox-TypeUser").show();
                        $("#selectBox-TypeUser-dropdown-menu").hide();
                    }
                
                /*
		$(".master").bind('click',function(event){
                    alert("o");
                            event.preventDefault();
                            var self  = $(this);
            		appendElementInMain(self.find($('a')));
				
		});
*/
		$(".cats-category1").bind('click',function(event){
                            event.preventDefault();
                            var self  = $(this);
               		appendElementInMain(self);
		});

                
		//$(".master").unbind('click').bind('click',function(event){
                $(".master.cat1").bind('mouseenter',function(event){

                        event.preventDefault();

			
			var children  = $(this).find($('ul'));
			if(children.hasClass('opened')){
				children.hide().removeClass('opened');
			
				
			}else{

			$(".hidden").hide();
			var self  = $(this);
			children.addClass('opened');


			if($(children).hasClass('hidden')){
				try
                                {
                                    console.log("OK");
                                }
                                catch(e)
                                {
                                    if (window.console // check for window.console not console
                                        && window.console.log)
                                    {
                                        window.console.log("OK");
                                    }

                                }
				children.show();
				children.find('li a').click(function(event){
						event.preventDefault();
						appendElementInMain($(this));
						$(".hidden").hide();
				});
			}else{
				
				appendElementInMain(self.find($('a')));
				
			}

			}
		});
	

		function appendElementInMain(element){
			$("#selectBox-dropdown-menu-Category1").hide();
			$("#selectBox-Category1").show();
			$("#selectBox-label-Category1").text(element.text());
			$("#catId1").val(element.data("id"));
			
			}
	});
        
	$("#selectBox-dropdown-menu-Category2").bind('mouseleave',function(event){
        		$("#selectBox-Category2").show();
                	$("#selectBox-dropdown-menu-Category2").hide();

        });
       

	$("#selectBox-Category2").bind('click',function(event){
		$('ul.hidden').hide();
		event.preventDefault();
		$("#selectBox-Category2").hide();
		$("#selectBox-dropdown-menu-Category2").show();
                
                if (!$("#selectBox-Category1").is(":visible"))  
                    {
        		$("#selectBox-Category1").show();
                	$("#selectBox-dropdown-menu-Category1").hide();
                    }
                if (!$("#selectBox-Category3").is(":visible"))  
                    {
        		$("#selectBox-Category3").show();
                	$("#selectBox-dropdown-menu-Category3").hide();
                    }
                if (!$("#selectBox-TypeUser").is(":visible"))  
                    {
                        $("#selectBox-TypeUser").show();
                        $("#selectBox-TypeUser-dropdown-menu").hide();
                    }

		$(".cats-category2").bind('click',function(event){
                            event.preventDefault();
                            var self  = $(this);
               		appendElementInMain(self);
		});

		//$(".master").unbind('click').bind('click',function(event){
                $(".master.cat2").bind('mouseenter',function(event){

			event.preventDefault();

			
			var children  = $(this).find($('ul'));
			if(children.hasClass('opened')){
				children.hide().removeClass('opened');
			
				
			}else{

			$(".hidden").hide();
			var self  = $(this);
			children.addClass('opened');


			if($(children).hasClass('hidden')){
				try
                                {
                                    console.log("OK");
                                }
                                catch(e)
                                {
                                    if (window.console // check for window.console not console
                                        && window.console.log)
                                    {
                                        window.console.log("OK");
                                    }

                                }
				children.show();
				children.find('li a').click(function(event){
						event.preventDefault();
						appendElementInMain($(this));
						$(".hidden").hide();
				});
			}else{
				
				appendElementInMain(self.find($('a')));
				
			}

			}
		});
	

		function appendElementInMain(element){
			$("#selectBox-dropdown-menu-Category2").hide();
			$("#selectBox-Category2").show();
			$("#selectBox-label-Category2").text(element.text());
			$("#catId2").val(element.data("id"));
			
			}
        });	
        
        
	$("#selectBox-dropdown-menu-Category3").bind('mouseleave',function(event){
        		$("#selectBox-Category3").show();
                	$("#selectBox-dropdown-menu-Category3").hide();

        });
        
        
        $("#selectBox-Category3").bind('click',function(event){
		$('ul.hidden').hide();
		event.preventDefault();
		$("#selectBox-Category3").hide();
		$("#selectBox-dropdown-menu-Category3").show();
                
                if (!$("#selectBox-Category2").is(":visible"))  
                    {
        		$("#selectBox-Category2").show();
                	$("#selectBox-dropdown-menu-Category2").hide();
                    }
                if (!$("#selectBox-Category1").is(":visible"))  
                    {
        		$("#selectBox-Category1").show();
                	$("#selectBox-dropdown-menu-Category1").hide();
                    }
                
                if (!$("#selectBox-TypeUser").is(":visible"))  
                    {
                        $("#selectBox-TypeUser").show();
                        $("#selectBox-TypeUser-dropdown-menu").hide();
                    }
                    
                
		$(".cats-category3").bind('click',function(event){
                            event.preventDefault();
                            var self  = $(this);
               		appendElementInMain(self);
		});

		//$(".master").unbind('click').bind('click',function(event){
                $(".master.cat3").bind('mouseenter',function(event){

			event.preventDefault();
                        

			var children  = $(this).find($('ul'));
			if(children.hasClass('opened')){
				children.hide().removeClass('opened');
				
			}else{
                            
                            

                            $(".hidden").hide();
                            var self  = $(this);
                            children.addClass('opened');

                            if($(children).hasClass('hidden')){
                                    try
                                    {
                                        console.log("Tiene hidden");
                                    }
                                    catch(e)
                                    {
                                        if (window.console // check for window.console not console
                                            && window.console.log)
                                        {
                                            window.console.log("Tiene hidden2");
                                        }

                                    }
                                    children.show();
                                    children.find('li a').click(function(event){
                                                    event.preventDefault();
                                                    appendElementInMain($(this));
                                                    $(".hidden").hide();
                                    });
                            }else{

                                    appendElementInMain(self.find($('a')));
                                    console.log("ADD");

                            }

			}
		});

		function appendElementInMain(element){
			$("#selectBox-dropdown-menu-Category3").hide();
			$("#selectBox-Category3").show();
			$("#selectBox-label-Category3").text(element.text());
			$("#catId3").val(element.data("id"));
			
			}
	});

	$("#selectBox-TypeUser-dropdown-menu").bind('mouseleave',function(event){
                        $("#selectBox-TypeUser").show();
                        $("#selectBox-TypeUser-dropdown-menu").hide();

        });

	$("#selectBox-TypeUser").bind('click',function(event){
		$('ul.hidden').hide();
		event.preventDefault();
		$("#selectBox-TypeUser").hide();
		$("#selectBox-TypeUser-dropdown-menu").show();

                if (!$("#selectBox-Category1").is(":visible"))  
                    {
        		$("#selectBox-Category1").show();
                	$("#selectBox-dropdown-menu-Category1").hide();
                    }
                if (!$("#selectBox-Category2").is(":visible"))  
                    {
        		$("#selectBox-Category2").show();
                	$("#selectBox-dropdown-menu-Category2").hide();
                    }
                if (!$("#selectBox-Category3").is(":visible"))  
                    {
        		$("#selectBox-Category3").show();
                	$("#selectBox-dropdown-menu-Category3").hide();
                    }
                    
		$(".cats-typeuser").bind('click',function(event){
                            event.preventDefault();
                            var self  = $(this);
               		appendElementInMain(self);
		});
                    
                    
		//$(".master").unbind('click').bind('click',function(event){
                $(".master.typeuser").bind('mouseenter',function(event){
			event.preventDefault();

			var children  = $(this).find($('ul'));
			if(children.hasClass('opened')){
                            
				children.hide().removeClass('opened');
				
			}else{

                            $(".hidden").hide();
                            var self  = $(this);
                            children.addClass('opened');

                            if($(children).hasClass('hidden')){
                                    try
                                    {
                                        console.log("OK");
                                    }
                                    catch(e)
                                    {
                                        if (window.console // check for window.console not console
                                            && window.console.log)
                                        {
                                            window.console.log("OK");
                                        }

                                    }
                                    children.show();
                                    children.find('li a').click(function(event){
                                                    event.preventDefault();
                                                    appendElementInMain($(this));
                                                    $(".hidden").hide();
                                    });
                            }else{
        //console.log("ADD");
                                    appendElementInMain(self.find($('a')));

                            }

			}
		});
                
		function appendElementInMain(element){
			$("#selectBox-TypeUser-dropdown-menu").hide();
			$("#selectBox-TypeUser").show();
			$("#selectBox-label-TypeUser").text(element.text());
			$("#user_typeId").val(element.data("id"));
			
			}


		
	});

	$("#selectBox-dropdown-menu-Level").bind('mouseleave',function(event){
                        $("#selectBox-Level").show();
                        $("#selectBox-dropdown-menu-Level").hide();

        });
          
        
        $("#selectBox-Level").bind('click',function(event){
            $('ul.hidden').hide();
            event.preventDefault();
            $("#selectBox-Level").hide();
            $("#selectBox-dropdown-menu-Level").show();
            
                if (!$("#selectBox-Age").is(":visible"))  
                    {
        		$("#selectBox-Age").show();
                	$("#selectBox-dropdown-menu-Age").hide();
                    }
                if (!$("#selectBox-Category").is(":visible"))  
                    {
        		$("#selectBox-Category").show();
                	$("#selectBox-dropdown-menu-Category").hide();
                    }

            $(".master").unbind('click').bind('click',function(event){
                event.preventDefault();

			
                var children  = $(this).find($('ul'));
                if(children.hasClass('opened')){
                    children.hide().removeClass('opened');
			
				
                }else{

                    $(".hidden").hide();
                    var self  = $(this);
                    children.addClass('opened');


                    if($(children).hasClass('hidden')){
                        try
                        {
                            console.log("OK");
                        }
                        catch(e)
                        {
                            if (window.console // check for window.console not console
                                && window.console.log)
                            {
                                window.console.log("OK");
                            }

                        }
                        children.show();
                        children.find('li a').click(function(event){
                            event.preventDefault();
                            appendElementInMain($(this));
                            $(".hidden").hide();
                        });
                    }else{
				
                        appendElementInMain(self.find($('a')));
				
                    }

                }
            });
	

            function appendElementInMain(element){
                $("#selectBox-dropdown-menu-Level").hide();
                $("#selectBox-Level").show();
                $("#selectBox-label-Level").text(element.text());
                $("#levelId").val(element.data("id"));
			
            }
        });
        
	$("#selectBox-dropdown-menu-Category").bind('mouseleave',function(event){
                        $("#selectBox-Category").show();
                        $("#selectBox-dropdown-menu-Category").hide();

        });
        

        $("#selectBox-Category").bind('click',function(event){
            $('ul.hidden').hide();
            event.preventDefault();
            $("#selectBox-Category").hide();
            $("#selectBox-dropdown-menu-Category").show();

                if (!$("#selectBox-Age").is(":visible"))  
                    {
        		$("#selectBox-Age").show();
                	$("#selectBox-dropdown-menu-Age").hide();
                    }
                if (!$("#selectBox-Level").is(":visible"))  
                    {
        		$("#selectBox-Level").show();
                	$("#selectBox-dropdown-menu-Level").hide();
                    }

            $(".master").unbind('click').bind('click',function(event){
                event.preventDefault();

			
                var children  = $(this).find($('ul'));
                if(children.hasClass('opened')){
                    children.hide().removeClass('opened');
			
				
                }else{

                    $(".hidden").hide();
                    var self  = $(this);
                    children.addClass('opened');


                    if($(children).hasClass('hidden')){
                        try
                        {
                            console.log("OK");
                        }
                        catch(e)
                        {
                            if (window.console // check for window.console not console
                                && window.console.log)
                            {
                                window.console.log("OK");
                            }

                        }
                        children.show();
                        children.find('li a').click(function(event){
                            event.preventDefault();
                            appendElementInMain($(this));
                            $(".hidden").hide();
                        });
                    }else{
				
                        appendElementInMain(self.find($('a')));
				
                    }

                }
            });
	

            function appendElementInMain(element){
                $("#selectBox-dropdown-menu-Category").hide();
                $("#selectBox-Category").show();
                $("#selectBox-label-Category").text(element.text());
                $("#catId").val(element.data("id"));
			
            }
        });	
        
	$("#selectBox-dropdown-menu-Age").bind('mouseleave',function(event){
                        $("#selectBox-Age").show();
                        $("#selectBox-dropdown-menu-Age").hide();

        });
        
        $("#selectBox-Age").bind('click',function(event){
            $('ul.hidden').hide();
            event.preventDefault();
            $("#selectBox-Age").hide();
            $("#selectBox-dropdown-menu-Age").show();

                if (!$("#selectBox-Level").is(":visible"))  
                    {
        		$("#selectBox-Level").show();
                	$("#selectBox-dropdown-menu-Level").hide();
                    }
                if (!$("#selectBox-Category").is(":visible"))  
                    {
        		$("#selectBox-Category").show();
                	$("#selectBox-dropdown-menu-Category").hide();
                    }

            $(".master").unbind('click').bind('click',function(event){
                event.preventDefault();

			
                var children  = $(this).find($('ul'));
                if(children.hasClass('opened')){
                    children.hide().removeClass('opened');
			
				
                }else{

                    $(".hidden").hide();
                    var self  = $(this);
                    children.addClass('opened');


                    if($(children).hasClass('hidden')){
                        try
                        {
                            console.log("OK");
                        }
                        catch(e)
                        {
                            if (window.console // check for window.console not console
                                && window.console.log)
                            {
                                window.console.log("OK");
                            }

                        }
                        children.show();
                        children.find('li a').click(function(event){
                            event.preventDefault();
                            appendElementInMain($(this));
                            $(".hidden").hide();
                        });
                    }else{
				
                        appendElementInMain(self.find($('a')));
				
                    }

                }
            });
	

            function appendElementInMain(element){
                $("#selectBox-dropdown-menu-Age").hide();
                $("#selectBox-Age").show();
                $("#selectBox-label-Age").text(element.text());
                $("#ageId").val(element.data("id"));
			
            }
        });        
        
	return;
	
	
});

</script>

    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>    
    <script>
function initialize() {
  var mapOptions = {
    center: new google.maps.LatLng(-33.8688, 151.2195),
    zoom: 13,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  };
  var map = new google.maps.Map(document.getElementById('map-canvas'),
    mapOptions);

  var input = /** @type {HTMLInputElement} */(document.getElementById('searchTextField'));
  var autocomplete = new google.maps.places.Autocomplete(input);

  autocomplete.bindTo('bounds', map);

  var infowindow = new google.maps.InfoWindow();
  var marker = new google.maps.Marker({
    map: map
  });
    showAddress(this.input.value, parseFloat(15)); 
    
   input = /** @type {HTMLInputElement} */(document.getElementById('searchTextField2'));
   autocomplete = new google.maps.places.Autocomplete(input);

  autocomplete.bindTo('bounds', map);

  var infowindow = new google.maps.InfoWindow();
  var marker = new google.maps.Marker({
    map: map
  });
    showAddress(this.input.value, parseFloat(15)); 

   input = /** @type {HTMLInputElement} */(document.getElementById('address'));
   autocomplete = new google.maps.places.Autocomplete(input);

  autocomplete.bindTo('bounds', map);

  var infowindow = new google.maps.InfoWindow();
  var marker = new google.maps.Marker({
    map: map
  });
    showAddress(this.input.value, parseFloat(15)); 

    
  google.maps.event.addListener(autocomplete, 'place_changed', function() {
    infowindow.close();
    marker.setVisible(false);
    input.className = '';
    var place = autocomplete.getPlace();
    if (!place.geometry) {
      // Inform the user that the place was not found and return.
      input.className = 'notfound';
      return;
    }

    // If the place has a geometry, then present it on a map.
    if (place.geometry.viewport) {
      map.fitBounds(place.geometry.viewport);
    } else {
      map.setCenter(place.geometry.location);
      map.setZoom(17);  // Why 17? Because it looks good.
    }
    marker.setIcon(/** @type {google.maps.Icon} */({
      url: place.icon,
      size: new google.maps.Size(71, 71),
      origin: new google.maps.Point(0, 0),
      anchor: new google.maps.Point(17, 34),
      scaledSize: new google.maps.Size(35, 35)
    }));
    marker.setPosition(place.geometry.location);
    marker.setVisible(true);

    var address = '';
    if (place.address_components) {
      address = [
        (place.address_components[0] && place.address_components[0].short_name || ''),
        (place.address_components[1] && place.address_components[1].short_name || ''),
        (place.address_components[2] && place.address_components[2].short_name || '')
      ].join(' ');
    }

    infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + address);
    infowindow.open(map, marker);
    

  });

  // Sets a listener on a radio button to change the filter type on Places
  // Autocomplete.
  function setupClickListener(id, types) {
    var radioButton = document.getElementById(id);
    google.maps.event.addDomListener(radioButton, 'click', function() {
      autocomplete.setTypes(types);
    });
  }

  setupClickListener('changetype-all', []);
  setupClickListener('changetype-establishment', ['establishment']);
  setupClickListener('changetype-geocode', ['geocode']);
}

google.maps.event.addDomListener(window, 'load', initialize);

    </script>
        

<?php //echo $this->footer_part; ?>