<?php echo $this->header_part; ?>

<div id="detail" class="editprofile">       
	<div id="view-profile">
		
          
            <form class="Form StaticForm" action="<?php echo $this->activatePopup; ?>" method="post" id="profileEdit">
                
                <h3 style="border-bottom:0px;padding-bottom:0px"><b><?php echo $this->translate('Activate');?></b></h3>
                <?php echo $this->translate('Here you can activate your profile.');?>
                <h3></h3>
            
                <div class="hide">
                    <input type="hidden" name="user_id" id="user_id" value="<?php echo $this->user_id; ?>">
                </div>

                <ul>
                    <!-- Gender -->
                    <li>
                        <label for="id_gender_0"><?php echo $this->translate('Gender'); ?></label>
                        <div id="genderOptions" class="Right">
                                <label for="id_gender_0"><input <?php echo ($this->gender == 'male' ? 'checked="checked"' : ''); ?> type="radio" name="gender" class="gender" value="male" id="id_gender_male"> <?php echo $this->translate('Male'); ?></label>
                                <label for="id_gender_1"><input <?php echo ($this->gender == 'female' ? 'checked="checked"' : ''); ?> type="radio" name="gender" class="gender" value="female" id="id_gender_female"> <?php echo $this->translate('Female'); ?></label>
                                <span style="color:red">*</span>
                        </div>
                    </li>
                    <!-- Edad -->
                    <li>
                        <label for="type_user-select<?php echo ($this->is_edit ? '-edit' : ''); ?>"><?php echo $this->translate('Age'); ?></label>
                        <div class="Right" id='catList'>
                            <a href="" class='selectBox selectBox-dropdown' id='selectBox-Age' style='width: 352px; display: inline-block;'>
                                <?php if (!$this->age_title)
                                { ?>
                                    <span class='selectBox-label' id='selectBox-label-Age' style="width: 345px;"><?php echo $this->translate('Please choose age'); ?></span>
                                <?php } else
                                { ?>
                                    <span class='selectBox-label' id='selectBox-label-Age' style="width: 345px;"><?php echo $this->age_title; ?></span>
                                <?php } ?>
                                <span class="selectBox-arrow" style=""></span>
                            </a>

                            <ul class='selectBox-dropdown-menu selectBox-options' id='selectBox-dropdown-menu-Age' style='display:none;overflow-x: hidden;width: 370px;'>

                            <?php foreach ($this->ages as $age)
                            { ?>
                                    <li  class = 'master' style='border:none !important' >
                                        <a data-id='<?php echo $age['age_id']; ?>' href="" class='' style='color:#AAA;' ><?php echo $age['age_title'] ?></a>
                                    </li>
                            <?php } ?>
                            </ul>

                            <input type='hidden' id='ageId' name='age' class='age' value = '<?php echo $this->age; ?>'/>

                        </div>
                    </li>
                    <!-- Ubicacion -->
                    <li>
                        <p class="input">
                            <label for="location"><?php echo $this->translate('Location activate'); ?> <br class="hide" /></label>
                            <span class="field"><input type="text" name="location" class="location" id="searchTextField" value="<?php echo $this->location; ?>"  /></span>
                            <span class="help_text"><?php echo $this->translate('e.g. Palo Alto, CA'); ?></span>  
                            <span style="color:red">*</span>
                            <input type="hidden" name="lat" class="lat" id="lat" value="<?php echo $this->lat;?>" />
                            <input type="hidden" name="len" class="len" id="len" value="<?php echo $this->len;?>" />
                        </p>
                        <div id="map-canvas" style="display:none !important"></div>
                    </li>
                    <!-- Deporte -->
                    <li>
                        <label for="category_id-select<?php echo ($this->is_edit ? '-edit' : ''); ?>"><?php echo $this->translate('Sport'); ?></label>
                        <div class="Right" id='catList'>

                            <a href="" class='selectBox selectBox-dropdown' id='selectBox-Category' style='width: 352px; display: inline-block;'>
                                <?php if (!$this->cat_title)
                                { ?>
                                    <span class='selectBox-label' id='selectBox-label-Category' style="width: 352px;"><?php echo $this->translate('Please choose sport'); ?></span>
                                <?php } else
                                { ?>
                                    <span class='selectBox-label' id='selectBox-label-Category' style="width: 352px;"><?php echo $this->cat_title; ?></span>
                                <?php } ?>
                                <span class="selectBox-arrow" style=""></span>
                            </a>

                            <ul class='selectBox-dropdown-menu selectBox-options' id='selectBox-dropdown-menu-Category' style='display:none;overflow-x: hidden;width: 370px;'>

                                        <?php foreach ($this->categories as $category)
                                        { ?>
                                    <li  class = 'master' style='border:none !important' >
                                        <a data-id='<?php echo $category['category_id']; ?>' href="" class='' style='color:#AAA;' ><?php echo $category['title'] ?></a>
                                            <?php if ($category['subcategories'])
                                            { ?>
                                            <ul class='subcats hidden'>
                                        <?php foreach ($category['subcategories'] as $subcat)
                                        { ?>
                                                    <li style='border:none !important;padding-left:0px'>
                                                        <a data-id='<?php echo $subcat['category_id']; ?>' class='' href=""><?php echo $subcat['title'] ?></a>
                                                    </li>
                                        <?php } ?>
                                            </ul>
                                    <?php } ?>
                                    </li>
                                <?php } ?>
                            </ul>

                            <input type='hidden' id='catId' name='sport_category' class='sport_category' value = '<?php echo $this->sport_category; ?>'/>
                            <span style="color:red">*</span>
                        </div>
                    </li>

                    <!-- Nivel -->
                    <li>
                        <label for="type_user-select<?php echo ($this->is_edit ? '-edit' : ''); ?>"><?php echo $this->translate('Level'); ?></label>
                        <div class="Right" id='catList'>

                            <a href="" class='selectBox selectBox-dropdown' id='selectBox-Level' style='width: 352px; display: inline-block;'>
                            <?php if (!$this->level_title)
                            { ?>
                                    <span class='selectBox-label' id='selectBox-label-Level' style="width: 345px;"><?php echo $this->translate('Please choose level'); ?></span>
                            <?php } else
                            { ?>
                                    <span class='selectBox-label' id='selectBox-label-Level' style="width: 345px;"><?php echo $this->level_title; ?></span>
                                <?php } ?>
                                <span class="selectBox-arrow" style=""></span>
                            </a>

                            <ul class='selectBox-dropdown-menu selectBox-options' id='selectBox-dropdown-menu-Level' style='display:none;overflow-x: hidden;width: 370px;'>

                            <?php foreach ($this->levels as $level)
                            { ?>
                                    <li  class = 'master' style='border:none !important' >
                                        <a data-id='<?php echo $level['level_id']; ?>' href="" class='' style='color:#AAA;' ><?php echo $level['level_title'] ?></a>
                                    </li>
                            <?php } ?>
                            </ul>

                            <input type='hidden' id='levelId' name='level' class='level' value = '<?php echo $this->level; ?>'/>
                            <span style="color:red">*</span>
                        </div>
                    </li>
                    <!-- Activate -->
                    <li>
                        <label for="id_activate"><?php echo $this->translate('Activate'); ?></label>
                        <div id="activateOptions" class="">
                            <label for="id_activate_0"><input <?php echo ($this->activate == '1' ? 'checked="checked"' : ''); ?> type="radio" name="activate" class="activate" value="1" id="id_activate_0"> <?php echo $this->translate('Activate'); ?></label>
                            <label for="id_activate_1"><input <?php echo ($this->activate == '0' ? 'checked="checked"' : ''); ?> type="radio" name="activate" class="activate" value="0" id="id_activate_1"> <?php echo $this->translate('Deactivate'); ?></label>
                        </div>
                    </li>  
                    <!-- Opciones -->
                    <li>
                        <label for="tc"><?php echo sprintf($this->translate('Activate Options')); ?> <br class="hide" /></label>
                        <div style="display:table">
                            <div style="display:table-cell">
                                <div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option1 == '1' ? 'checked="checked"' : ''); ?> type='checkbox' id='option1' name='option1' class='option1' value="1" ><?php echo " ". sprintf($this->translate('Practice sports together')); ?> </span>
                                </div>
                                <div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option2 == '1' ? 'checked="checked"' : ''); ?> type='checkbox' id='option2' name='option2' class='option2' value="1"><?php echo " ". sprintf($this->translate('Organize match / tournament')); ?> </span>
                                </div>
                                <div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option3 == '1' ? 'checked="checked"' : ''); ?> type='checkbox' id='option3' name='option3' class='option3' value="1"><?php echo " ". sprintf($this->translate('Team look for sportman')); ?> </span>
                                </div>
                                <div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option4 == '1' ? 'checked="checked"' : ''); ?> type='checkbox' id='option4' name='option4' class='option4' value="1"><?php echo " ". sprintf($this->translate('Sportman look for team')); ?> </span>
                                </div>
                            </div>
                            <div style="display:table-cell">
                                <div style="display:table-row">
                                    &nbsp;&nbsp;&nbsp;
                                </div>
                            </div>

                            <div style="display:table-cell">
                                <div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option5 == '1' ? 'checked="checked"' : ''); ?> type='checkbox' id='option5' name='option5' class='option5' value="1"><?php echo " ". sprintf($this->translate('Look for sponsor')); ?> </span>
                                </div>
                                <!--div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option6 == '1' ? 'checked="checked"' : ''); ?> type='checkbox' id='option6' name='option6' class='option6' value="1"><?php echo " ". sprintf($this->translate('Volunteer helps paraolimpics')); ?> </span>
                                </div-->
                                <div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option7 == '1' ? 'checked="checked"' : ''); ?> type='checkbox' id='option7' name='option7' class='option7' value="1"><?php echo " ". sprintf($this->translate('Trainee look for tutor')); ?> </span>
                                </div>
                                <div style="display:table-row">
                                    <span class="" style='text-align:left'><input <?php echo ($this->option8 == '1' ? 'checked="checked"' : ''); ?> type='checkbox' id='option8' name='option8' class='option8' value="1"><?php echo " ". sprintf($this->translate('Tutor begins trainee')); ?> </span>
                                </div>
                            </div>
                        </div>
                    </li>
                    <!-- Comentario -->
                    <li>
                        <div class="left w335px">
                            <p>
                                <label for="message"><?php echo $this->translate('Comment'); ?>:<br></label>
                                <textarea name="comment" id="comment" rows="5" cols="30"><?php echo $this->comment; ?></textarea>
                            </p>
                            <p class="text_counter"></p>
                        </div>
                <!-- Grabar -->
                                    <li>
                        <div class="left w335px">
                            <p class="submit">
                                
                                    <label for="required"><span style="color:red">*</span><?php echo $this->translate('Fields required'); ?><br></label>
                            <!--span style="color:red">*</span--> <?php //echo $this->translate('Fields required'); ?>                
                            &nbsp;&nbsp;<input class="Button WhiteButton RedButton Button24 message" style="font-size:18px" type="submit" value="<?php echo $this->translate('Pinit'); ?>" name="register" id="register" class="register">
                            &nbsp;&nbsp;<input class="Button WhiteButton RedButton Button24 message close" style="font-size:18px;width:80px" value="<?php echo $this->translate('Salir'); ?>">
                            </p>
                        </div>
                    </li>				
                </ul>
                
                <div class="clear"></div>

            </form>
    
    </div>
    
    <div class="clear"></div>    
</div>




<?php $key = str_replace('.', '', microtime(true)); ?>
<script type="text/javascript">
    $(document).ready(function(){
       
       
        $('.Button.RedButton.message.close').click(function(){
		//history.go(-1);
                var origen = '<?php echo $_SESSION["activate_url"]; ?>';
                window.location.href=origen;
	});

/*
        $('#id_gender_male').click(function(){
            //if( $(this).is(':checked') ) alert("checked");
            alert($( ".gender:checked" ).val());
        });
        
        $('#id_gender_female').click(function(){
            alert($( ".gender:checked" ).val());
        });
*/            
        
	<?php if($this->successfu_edite) { ?>
	Pins.success('<?php echo $this->translate('Information is successfully changed!');?>');
	<?php } ?>
	<?php if($this->error) { ?>
	Pins.error('<?php echo $this->error;?>');
	<?php } ?>
        

        regExPrice.addExpresionLine($('#comment').html(), true);
	
        $('#comment').jqEasyCounter({
            holder: 'p.text_counter',
            maxChars: 255,
            maxCharsWarning: 225,
            template: '{count}'
        }).bind("keydown keyup keypress focus paste",function() {
            regExPrice.addExpresionLine(this.value);
            if($.trim($('#comment').val())) {
                $('#emailpin .submit input').removeClass('disabled').attr('disabled', false);
            } 
            else 
            {
                $('#emailpin .submit input').addClass('disabled').attr('disabled', true);
            }
            regExPrice.addExpresionLine(this.value, false);
        });


        $('#emailpin form').unbind('submit').submit(function(){
            $('#emailpin form .submit input').after('<img src="data/images/loading_2.gif" id="loading_button" />');
            $('#emailpin form .submit input').attr('disabled', true).addClass('disabled');
            
            
            var user_id = $('#user_id').val();
            var gender = $('.gender:checked').val();
            var age = $('.age').val();
            var location = $('#searchTextField').val();            
            var sport_category = $('.sport_category').val();            
            var level = $('.level').val();            
            var activate = $('.activate:checked').val();            
            var option1 = $('.option1:checked').val();            
            var option2 = $('.option2:checked').val();            
            var option3 = $('.option3:checked').val();            
            var option4 = $('.option4:checked').val();            
            var option5 = $('.option5:checked').val();            
            var option6 = $('.option6:checked').val();            
            var option7 = $('.option7:checked').val();            
            var option8 = $('.option8:checked').val();            
            var comment = $('#comment').val();
            alert($('.option1:checked').val());
            alert($('#comment').val());
            
            
                  
            $.post('<?php echo $this->from_url; ?>', {user_id:user_id, gender : gender, age : age, location : location, sport_category : sport_category, level : level, activate : activate, option1 : option1, option2 : option2, option3 : option3, option4 : option4, option5 : option5, option6 : option6, option7 : option7, option8 : option8, comment:comment}, function(data,status){
                $('#loading_button').remove();
                $.fancybox.close();                        

            $('#emailpin form .submit input').after(kk);
            $('#emailpin .submit input').removeClass('disabled').attr('disabled', false);
			
            });
            return false;
                   
        });
	

	$("#selectBox-dropdown-menu-Level").bind('mouseleave',function(event){
                        $("#selectBox-Level").show();
                        $("#selectBox-dropdown-menu-Level").hide();

        });
          

        $("#selectBox-Level").bind('click',function(event){
            $('ul.hidden').hide();
            event.preventDefault();
            $("#selectBox-Level").hide();
            $("#selectBox-dropdown-menu-Level").show();

                if (!$("#selectBox-Age").is(":visible"))  
                    {
        		$("#selectBox-Age").show();
                	$("#selectBox-dropdown-menu-Age").hide();
                    }
                if (!$("#selectBox-Category").is(":visible"))  
                    {
        		$("#selectBox-Category").show();
                	$("#selectBox-dropdown-menu-Category").hide();
                    }


            $(".master").unbind('click').bind('click',function(event){
                event.preventDefault();

			
                var children  = $(this).find($('ul'));
                if(children.hasClass('opened')){
                    children.hide().removeClass('opened');
			
				
                }else{

                    $(".hidden").hide();
                    var self  = $(this);
                    children.addClass('opened');


                    if($(children).hasClass('hidden')){
                        try
                        {
                            console.log("OK");
                        }
                        catch(e)
                        {
                            if (window.console // check for window.console not console
                                && window.console.log)
                            {
                                window.console.log("OK");
                            }

                        }
                        children.show();
                        children.find('li a').click(function(event){
                            event.preventDefault();
                            appendElementInMain($(this));
                            $(".hidden").hide();
                        });
                    }else{
				
                        appendElementInMain(self.find($('a')));
				
                    }

                }
            });
	

            function appendElementInMain(element){
                $("#selectBox-dropdown-menu-Level").hide();
                $("#selectBox-Level").show();
                $("#selectBox-label-Level").text(element.text());
                $("#levelId").val(element.data("id"));
			
            }
        });


	$("#selectBox-dropdown-menu-Category").bind('mouseleave',function(event){
                        $("#selectBox-Category").show();
                        $("#selectBox-dropdown-menu-Category").hide();

        });
        


        $("#selectBox-Category").bind('click',function(event){
            $('ul.hidden').hide();
            event.preventDefault();
            $("#selectBox-Category").hide();
            $("#selectBox-dropdown-menu-Category").show();

                if (!$("#selectBox-Age").is(":visible"))  
                    {
        		$("#selectBox-Age").show();
                	$("#selectBox-dropdown-menu-Age").hide();
                    }
                if (!$("#selectBox-Level").is(":visible"))  
                    {
        		$("#selectBox-Level").show();
                	$("#selectBox-dropdown-menu-Level").hide();
                    }


            $(".master").unbind('click').bind('click',function(event){
                event.preventDefault();

			
                var children  = $(this).find($('ul'));
                if(children.hasClass('opened')){
                    children.hide().removeClass('opened');
			
				
                }else{

                    $(".hidden").hide();
                    var self  = $(this);
                    children.addClass('opened');


                    if($(children).hasClass('hidden')){
                        try
                        {
                            console.log("OK");
                        }
                        catch(e)
                        {
                            if (window.console // check for window.console not console
                                && window.console.log)
                            {
                                window.console.log("OK");
                            }

                        }
                        children.show();
                        children.find('li a').click(function(event){
                            event.preventDefault();
                            appendElementInMain($(this));
                            $(".hidden").hide();
                        });
                    }else{
				
                        appendElementInMain(self.find($('a')));
				
                    }

                }
            });
	

            function appendElementInMain(element){
                $("#selectBox-dropdown-menu-Category").hide();
                $("#selectBox-Category").show();
                $("#selectBox-label-Category").text(element.text());
                $("#catId").val(element.data("id"));
			
            }
        });

	$("#selectBox-dropdown-menu-Age").bind('mouseleave',function(event){
                        $("#selectBox-Age").show();
                        $("#selectBox-dropdown-menu-Age").hide();

        });

        
        $("#selectBox-Age").bind('click',function(event){
            $('ul.hidden').hide();
            event.preventDefault();
            $("#selectBox-Age").hide();
            $("#selectBox-dropdown-menu-Age").show();

                if (!$("#selectBox-Level").is(":visible"))  
                    {
        		$("#selectBox-Level").show();
                	$("#selectBox-dropdown-menu-Level").hide();
                    }
                if (!$("#selectBox-Category").is(":visible"))  
                    {
        		$("#selectBox-Category").show();
                	$("#selectBox-dropdown-menu-Category").hide();
                    }


            $(".master").unbind('click').bind('click',function(event){
                event.preventDefault();

			
                var children  = $(this).find($('ul'));
                if(children.hasClass('opened')){
                    children.hide().removeClass('opened');
			
				
                }else{

                    $(".hidden").hide();
                    var self  = $(this);
                    children.addClass('opened');


                    if($(children).hasClass('hidden')){
                        try
                        {
                            console.log("OK");
                        }
                        catch(e)
                        {
                            if (window.console // check for window.console not console
                                && window.console.log)
                            {
                                window.console.log("OK");
                            }

                        }
                        children.show();
                        children.find('li a').click(function(event){
                            event.preventDefault();
                            appendElementInMain($(this));
                            $(".hidden").hide();
                        });
                    }else{
				
                        appendElementInMain(self.find($('a')));
				
                    }

                }
            });
	

            function appendElementInMain(element){
                $("#selectBox-dropdown-menu-Age").hide();
                $("#selectBox-Age").show();
                $("#selectBox-label-Age").text(element.text());
                $("#ageId").val(element.data("id"));
			
            }
        });
        
        $( "#searchTextField" ).keypress(function( event ) {
            GLoad();
            if ( event.which == 13 ) {
                event.preventDefault();
            }
        });       
        
        $("#searchTextField").bind('focusin',function(event){
            $('.register').attr('disabled', true).addClass('disabled');
            GLoad();
        });
        

        $("#searchTextField").bind('focusout',function(event){
            $('.register').attr('disabled', true).addClass('disabled');
            GLoad();
        });
        
        $("#searchTextField").change(function() {
            $('.register').attr('disabled', true).addClass('disabled');
            GLoad();
        });
        
        $(".pac-container").live('click',function(event){
            $('.register').attr('disabled', true).addClass('disabled');
            GLoad();
        });

        $("#searchTextField").blur(function() {
            $('.register').attr('disabled', true).addClass('disabled');
            GLoad();
        });

        return;
	
	
    });

</script>


<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places&language=es"></script>        

    <script>
function initialize() {
  var mapOptions = {
    center: new google.maps.LatLng(-33.8688, 151.2195),
    zoom: 13,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  };
  var map = new google.maps.Map(document.getElementById('map-canvas'),
    mapOptions);

  var input = /** @type {HTMLInputElement} */(document.getElementById('searchTextField'));
  var autocomplete = new google.maps.places.Autocomplete(input);

  autocomplete.bindTo('bounds', map);

  var infowindow = new google.maps.InfoWindow();
  var marker = new google.maps.Marker({
    map: map
  });
  
   GLoad();

}

google.maps.event.addDomListener(window, 'load', initialize);

    </script>

<script type="text/javascript">
   
   /*     
    var locations = [
      ['madriles', 40.4284034, -3.7149525, 1]
    ];      
      */



function GLoad() {




var geocoder;
var map;

$(document).ready(function(){                                                   
    
    var locationPrincipal =$('#searchTextField').val(); 
    
    if (locationPrincipal != "Introduce una ubicación")
    {
    


        var geocoder = new google.maps.Geocoder();
        geocoder.geocode({ 'address': locationPrincipal }, function (results, status) {
        if (status == google.maps.GeocoderStatus.OK) 
        {
            var lat = results[0].geometry.location.lat().toString().substr(0, 12);
            var len = results[0].geometry.location.lng().toString().substr(0, 12);
            $('#lat').val(lat);
            $('#len').val(len);

        }
        else
        {
            if (status == "OVER_QUERY_LIMIT")
            {
            $(document).ready(function(){                                                   
                        //setTimeout(function(){}, 201);
            });                        
                    }
                    else
                    { 
                        console.log('error: ' + status);
                    }
                }

                  pausecomp(201);
              });
    }
}); 
            
            
function pausecomp(ms) {
        ms += new Date().getTime();
        while (new Date() < ms){}
    } 
            
}

    </script>    
    
<?php echo $this->footer_part; ?>