<div id="create_new_pin">
    <div id="content-holder">
        <div id="emailpin">
    <!--span><?php echo $this->translate('Activate. desde aquí puedes hacer mucho'); ?></span-->                    
            
<!--div id="pin" class="popuppin">
	<div class="box boxlarge">
    	<a class="closePop"></a-->
<?php if($this->error) { ?>
<script type="text/javascript">
$(document).ready(function(){
	!Pins.error('<?php echo $this->translate('Please select at least one category.');?>');
});
</script>
<?php } ?>

            <form class="Form StaticForm" action="<?php echo $this->activatePopup; ?>" method="post">
                <div class="hide">
                    <input type="hidden" name="user_id" id="user_id" value="<?php echo $this->user_id; ?>">
                </div>
                <?php echo $this->error;?>
                <ul>
                    <!-- Gender -->
                    <li>
                        <label for="id_gender_0"><?php echo $this->translate('Gender'); ?></label>
                        <div id="genderOptions" class="Right">
                                <label for="id_gender_0"><input <?php echo ($this->gender == 'male' ? 'checked="checked"' : ''); ?> type="radio" name="gender" class="gender" value="male" id="id_gender_male"> <?php echo $this->translate('Male'); ?></label>
                                <label for="id_gender_1"><input <?php echo ($this->gender == 'female' ? 'checked="checked"' : ''); ?> type="radio" name="gender" class="gender" value="female" id="id_gender_female"> <?php echo $this->translate('Female'); ?></label>
                                <span style="color:red">*</span>
                        </div>
                    </li>
                    <!-- Edad -->
                    <li style="border:0px">
                        <label for="type_user-select<?php echo ($this->is_edit ? '-edit' : ''); ?>"><?php echo $this->translate('Age'); ?></label>
                        <div class="Right" id='catList'>
                            <a href="" class='selectBox selectBox-dropdown' id='selectBox-Age' style='width: 352px; display: inline-block;'>
                                <?php if (!$this->age_title)
                                { ?>
                                    <span class='selectBox-label' id='selectBox-label-Age' style="width: 345px;"><?php echo $this->translate('Please choose age'); ?></span>
                                <?php } else
                                { ?>
                                    <span class='selectBox-label' id='selectBox-label-Age' style="width: 345px;"><?php echo $this->age_title; ?></span>
                                <?php } ?>
                                <span class="selectBox-arrow" style=""></span>
                            </a>

                            <ul class='selectBox-dropdown-menu selectBox-options' id='selectBox-dropdown-menu-Age' style='display:none;overflow-x: hidden;width: 370px;'>

                            <?php foreach ($this->ages as $age)
                            { ?>
                                    <li  class = 'master' style='border:none !important' >
                                        <a data-id='<?php echo $age['age_id']; ?>' href="" class='' style='color:#AAA;' ><?php echo $age['age_title'] ?></a>
                                    </li>
                            <?php } ?>
                            </ul>

                            <input type='hidden' id='ageId' name='age' class='age' value = '<?php echo $this->age; ?>'/>

                        </div>
                    </li>
                    <li>
                        <p class="input">
                            <label for="location"><?php echo $this->translate('Location'); ?> <br class="hide" /></label>
                            <span class="field"><input type="text" name="location" class="location" id="searchTextField" value="<?php echo $this->location; ?>" /></span>
                            <span class="help_text"><?php echo $this->translate('e.g. Palo Alto, CA'); ?></span>  
                            <span style="color:red">*</span>
                        </p>
                        <!--div id="panel" style="margin-left: 260px">
                          <input id="searchTextField" type="text" size="50">
                          <input type="radio" name="type" id="changetype-all" checked="checked">
                          <label for="changetype-all">All</label>
                    
                          <input type="radio" name="type" id="changetype-establishment">
                          <label for="changetype-establishment">Establishments</label>
                    
                          <input type="radio" name="type" id="changetype-geocode">
                          <label for="changetype-geocode">Geocodes</lable>
                        </div-->
                        <div id="map-canvas"></div>
                    </li>
                    <li style="border:0px">
                        <label for="category_id-select<?php echo ($this->is_edit ? '-edit' : ''); ?>"><?php echo $this->translate('Sport'); ?></label>
                        <div class="Right" id='catList'>

                            <a href="" class='selectBox selectBox-dropdown' id='selectBox-Category' style='width: 352px; display: inline-block;'>
                                <?php if (!$this->cat_title)
                                { ?>
                                    <span class='selectBox-label' id='selectBox-label-Category' style="width: 352px;"><?php echo $this->translate('Please choose sport'); ?></span>
                                <?php } else
                                { ?>
                                    <span class='selectBox-label' id='selectBox-label-Category' style="width: 352px;"><?php echo $this->cat_title; ?></span>
                                <?php } ?>
                                <span class="selectBox-arrow" style=""></span>
                            </a>

                            <ul class='selectBox-dropdown-menu selectBox-options' id='selectBox-dropdown-menu-Category' style='display:none;overflow-x: hidden;width: 370px;'>

                                        <?php foreach ($this->categories as $category)
                                        { ?>
                                    <li  class = 'master' style='border:none !important' >
                                        <a data-id='<?php echo $category['category_id']; ?>' href="" class='' style='color:#AAA;' ><?php echo $category['title'] ?></a>
                                            <?php if ($category['subcategories'])
                                            { ?>
                                            <ul class='subcats hidden'>
                                        <?php foreach ($category['subcategories'] as $subcat)
                                        { ?>
                                                    <li style='border:none !important;padding-left:0px'>
                                                        <a data-id='<?php echo $subcat['category_id']; ?>' class='' href=""><?php echo $subcat['title'] ?></a>
                                                    </li>
                                        <?php } ?>
                                            </ul>
                                    <?php } ?>
                                    </li>
                                <?php } ?>
                            </ul>

                            <input type='hidden' id='catId' name='sport_category' class='sport_category' value = '<?php echo $this->sport_category; ?>'/>
                            <span style="color:red">*</span>
                        </div>
                    </li>

                    <!-- Nivel -->
                    <li style="border:0px">
                        <label for="type_user-select<?php echo ($this->is_edit ? '-edit' : ''); ?>"><?php echo $this->translate('Level'); ?></label>
                        <div class="Right" id='catList'>

                            <a href="" class='selectBox selectBox-dropdown' id='selectBox-Level' style='width: 352px; display: inline-block;'>
                            <?php if (!$this->level_title)
                            { ?>
                                    <span class='selectBox-label' id='selectBox-label-Level' style="width: 345px;"><?php echo $this->translate('Please choose level'); ?></span>
                            <?php } else
                            { ?>
                                    <span class='selectBox-label' id='selectBox-label-Level' style="width: 345px;"><?php echo $this->level_title; ?></span>
                                <?php } ?>
                                <span class="selectBox-arrow" style=""></span>
                            </a>

                            <ul class='selectBox-dropdown-menu selectBox-options' id='selectBox-dropdown-menu-Level' style='display:none;overflow-x: hidden;width: 370px;'>

                            <?php foreach ($this->levels as $level)
                            { ?>
                                    <li  class = 'master' style='border:none !important' >
                                        <a data-id='<?php echo $level['level_id']; ?>' href="" class='' style='color:#AAA;' ><?php echo $level['level_title'] ?></a>
                                    </li>
                            <?php } ?>
                            </ul>

                            <input type='hidden' id='levelId' name='level' class='level' value = '<?php echo $this->level; ?>'/>
                            <span style="color:red">*</span>
                        </div>
                    </li>
                    <!-- Search Index -->
                    <li>
                        <label for="id_activate"><?php echo $this->translate('Activate'); ?></label>
                        <div id="activateOptions" class="">
                            <label for="id_activate_0"><input <?php echo ($this->user_data['activate'] == '1' ? 'checked="checked"' : ''); ?> type="radio" name="activate" class="activate" value="1" id="id_activate_0"> <?php echo $this->translate('Activate'); ?></label>
                            <label for="id_activate_1"><input <?php echo ($this->user_data['activate'] == '0' ? 'checked="checked"' : ''); ?> type="radio" name="activate" class="activate" value="0" id="id_activate_1"> <?php echo $this->translate('Deactivate'); ?></label>
                        </div>
                    </li>  
                    <li>
                        <label for="tc"><?php echo sprintf($this->translate('Activate Options')); ?> <br class="hide" /></label>
                        <div style="display:table">
                            <div style="display:table-row">
                                <div style="display:table-cell">
                                    <span class="" style='text-align:left'><input <?php echo ($this->user_data['option1'] == '0' ? 'checked="checked"' : ''); ?> type='checkbox' id='option1' class='option1'><?php echo sprintf($this->translate('Practice sports together')); ?> </span>
                                </div><div style="display:table-cell">
                                    <span class="" style='text-align:left'><input <?php echo ($this->user_data['option2'] == '0' ? 'checked="checked"' : ''); ?> type='checkbox' id='option2' class='option2'><?php echo sprintf($this->translate('Organize match / tournament')); ?> </span>
                                </div><div style="display:table-cell">
                                    <span class="" style='text-align:left'><input <?php echo ($this->user_data['option3'] == '0' ? 'checked="checked"' : ''); ?> type='checkbox' id='option3' class='option3'><?php echo sprintf($this->translate('Team look for sportman')); ?> </span>
                                </div><div style="display:table-cell">
                                    <span class="" style='text-align:left'><input <?php echo ($this->user_data['option4'] == '0' ? 'checked="checked"' : ''); ?> type='checkbox' id='option4' class='option4'><?php echo sprintf($this->translate('Sportman look for team')); ?> </span>
                                </div>
                            </div>
                            <div style="display:table-row">
                                <div style="display:table-cell">
                                    <span class="" style='text-align:left'><input <?php echo ($this->user_data['option5'] == '0' ? 'checked="checked"' : ''); ?> type='checkbox' id='option5' class='option5'><?php echo sprintf($this->translate('Look for sponsor')); ?> </span>
                                </div><div style="display:table-cell">
                                    <span class="" style='text-align:left'><input <?php echo ($this->user_data['option6'] == '0' ? 'checked="checked"' : ''); ?> type='checkbox' id='option6' class='option6'><?php echo sprintf($this->translate('Volunteer helps paraolimpics')); ?> </span>
                                </div><div style="display:table-cell">
                                    <span class="" style='text-align:left'><input <?php echo ($this->user_data['option7'] == '0' ? 'checked="checked"' : ''); ?> type='checkbox' id='option7' class='option7'><?php echo sprintf($this->translate('Trainee look for tutor')); ?> </span>
                                </div><div style="display:table-cell">
                                    <span class="" style='text-align:left'><input <?php echo ($this->user_data['option8'] == '0' ? 'checked="checked"' : ''); ?> type='checkbox' id='option8' class='option8'><?php echo sprintf($this->translate('Tutor begins trainee')); ?> </span>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="left w335px">
                            <p>
                                <label for="message"><?php echo $this->translate('Comment'); ?>:<br></label>
                                <textarea name="texto" id="texto" rows="5" cols="30"><?php echo $this->comment; ?></textarea>
                            </p>
                    </li>				<p class="text_counter"></p>
                </ul>    
                    <span style="color:red">*</span> <?php echo $this->translate('Fields required'); ?>                
                <p class="submit">
                    <input type="submit" value="<?php echo $this->translate('Pinit'); ?>">
                </p>
                    <a class="Button RedButton message close" ><?php echo $this->translate('Cancel'); ?></a>
                
                <div class="clear"></div>

                <div class="clear"></div>
            </form>
        </div>
    </div>
<!--/div-->
<!--
<script type="css/text">
#activateOptions .ui-radio .ui-icon-radio-on {
    background-color: green !important;
}
</script>
 -->   
<?php $key = str_replace('.', '', microtime(true)); ?>
<script type="text/javascript">
    $(document).ready(function(){
       
        $('.Button .RedButton .message .close').click(function(){
            alert("close");
		$.fancybox.close();
	});

/*
        $('#id_gender_male').click(function(){
            //if( $(this).is(':checked') ) alert("checked");
            alert($( ".gender:checked" ).val());
        });
        
        $('#id_gender_female').click(function(){
            alert($( ".gender:checked" ).val());
        });
*/            
        
	<?php if($this->successfu_edite) { ?>
	Pins.success('<?php echo $this->translate('Information is successfully changed!');?>');
	<?php } ?>
	<?php if($this->error) { ?>
	Pins.error('<?php echo $this->error;?>');
	<?php } ?>
        

        regExPrice.addExpresionLine($('#texto').html(), true);
	
        $('#texto').jqEasyCounter({
            holder: 'p.text_counter',
            maxChars: 255,
            maxCharsWarning: 225,
            template: '{count}'
        }).bind("keydown keyup keypress focus paste",function() {
            regExPrice.addExpresionLine(this.value);
            if($.trim($('#texto').val())) {
                $('#emailpin .submit input').removeClass('disabled').attr('disabled', false);
            } 
            else 
            {
                $('#emailpin .submit input').addClass('disabled').attr('disabled', true);
            }
            regExPrice.addExpresionLine(this.value, false);
        });


        $('#emailpin form').unbind('submit').submit(function(){
            $('#emailpin form .submit input').after('<img src="data/images/loading_2.gif" id="loading_button" />');
            $('#emailpin form .submit input').attr('disabled', true).addClass('disabled');
            
            var user_id = $('#user_id').val();
            var gender = $('.gender:checked').val();
            var age = $('.age').val();
            var location = $('#searchTextField').val();            
            var sport_category = $('.sport_category').val();            
            var level = $('.level').val();            
            var activate = $('.activate:checked').val();            
            var option1 = $('.option1:checked').val();            
            var option2 = $('.option2:checked').val();            
            var option3 = $('.option3:checked').val();            
            var option4 = $('.option4:checked').val();            
            var option5 = $('.option5:checked').val();            
            var option6 = $('.option6:checked').val();            
            var option7 = $('.option7:checked').val();            
            var option8 = $('.option8:checked').val();            
            var comment = $('#texto').val();      
            
            
                  
            $.post('<?php echo $this->from_url; ?>', {user_id:user_id, gender : gender, age : age, location : location, sport_category : sport_category, level : level, activate : activate, option1 : option1, option2 : option2, option3 : option3, option4 : option4, option5 : option5, option6 : option6, option7 : option7, option8 : option8, comment:comment}, function(data,status){
                alert(status);
	<?php if($this->successfu_edite) { ?>                
                $('#loading_button').remove();
                $.fancybox.close();                        
	<?php } ?>
            var kk = '';
	kk = '<?php echo $this->error;?>';
        alert(data);

            $('#emailpin form .submit input').after(kk);
            $('#emailpin .submit input').removeClass('disabled').attr('disabled', false);
			
            });
            return false;
                   
        });
		
    });



    $(document).ready(function(){
        $('#category_id-select<?php echo ($this->is_edit ? '-edit' : ''); ?>').selectBox({
            onOpen: function (inst) {
                try
                {
                    console.log("open", inst);
                }
                catch(e)
                {
                    if (window.console // check for window.console not console
                        && window.console.log)
                    {
                        window.console.log("open", inst);
                    }                        
                }
            },
            onClose: function (inst) {
                try
                {
                    console.log("close", inst);
                }
                catch(e)
                {
                    if (window.console // check for window.console not console
                        && window.console.log)
                    {
                        window.console.log("close", inst);
                    }                        
                }
                        
            }
        });
        $('#type_user-select<?php echo ($this->is_edit ? '-edit' : ''); ?>').selectBox({
            onOpen: function (inst) {
                try
                {
                    console.log("open", inst);
                }
                catch(e)
                {
                    if (window.console // check for window.console not console
                        && window.console.log)
                    {
                        window.console.log("open", inst);
                    }                        
                }
            },
            onClose: function (inst) {
                try
                {
                    console.log("close", inst);
                }
                catch(e)
                {
                    if (window.console // check for window.console not console
                        && window.console.log)
                    {
                        window.console.log("close", inst);
                    }                        
                }
                        
            }
        });        
        $('input.collaborator_name').clearOnFocus();

	
        var cache = {};
        $('.collaborator_name.ui-autocomplete-input').live('keyup', function(){
            var val = this.value;
            if(cache[val]) {
                autocompleteResults(cache[val]);
            } else {
                $.post('<?php echo $this->friends_href; ?>', {term: val}, function(data){
                    cache[val] = data.users;
                    autocompleteResults(data.users);
                }, 'json');
            }
        }).after('<div class="menu_friends" style="position: absolute; display: none; margin-top: 33px;z-index:2147483647;">');
	
        function autocompleteResults(data) {

            var holder = $('.menu_friends').empty();
            if($(data).objectSize() < 1) {
                holder.hide();
                return;
            }
            holder.show(function(){
                $(document).unbind('.joauto').bind('click.joauto',function(e){
                    holder.hide();
                });
            });
            $(data).each(function(i, item){
                user = $('<div class="option_friends"><img alt="'+item.label+'" src="'+item.image+'"><span>'+item.label+'</span></div>').click(function(){
                    holder.hide();
                    if( $('#user_fr_'+item.value+'<?php echo ($this->is_edit ? '-edit' : ''); ?>').size() > 0 ) { return; }
                    $('input.collaborator_name').val('');
                    $('#invite_response<?php echo ($this->is_edit ? '-edit' : ''); ?>').append('<input id="hidden_user_fr_'+item.value+'<?php echo ($this->is_edit ? '-edit' : ''); ?>" type="hidden" name="friends['+item.value+']" value="'+item.value+'" />');

                    template = $('#friend-template<?php echo ($this->is_edit ? '-edit' : ''); ?>').html();
                    for(e in item) {
                        template = template.replace(new RegExp(RegExp.quote('{'+e+'}'), 'g'), item[e]);
                    }
				
                    $('#CurrentCollaborators<?php echo ($this->is_edit ? '-edit' : ''); ?>').append(template);
                }).css({'cursor': 'pointer'});
			
                holder.append(user);
            });
        }

        RegExp.quote = function(str) {
            return (str+'').replace(/([.?*+^$[\]\\(){}|-])/g, "\\$1");
        };
		
	
    });

    function saveBoardData() {
	
        $.post('<?php echo $this->from_url; ?>', $('#CreateBoard<?php echo ($this->is_edit ? '-edit' : ''); ?>').serialize(), function(data){
            alert(data);
            if(data.error) {
                Pins.error(data.error);
            } else if(data.data) {
                window.location = data.data.href;
            }
        }, 'json');
        return false;
    }

    function deleteFriend(id) {
        $('#user_fr_'+id+'<?php echo ($this->is_edit ? '-edit' : ''); ?>').remove();
        $('#hidden_user_fr_'+id+'<?php echo ($this->is_edit ? '-edit' : ''); ?>').remove();
    }


    $(document).ready(function(){

        $("#selectBox-Level").bind('click',function(event){
            $('ul.hidden').hide();
            event.preventDefault();
            $("#selectBox-Level").hide();
            $("#selectBox-dropdown-menu-Level").show();

            $(".master").unbind('click').bind('click',function(event){
                event.preventDefault();

			
                var children  = $(this).find($('ul'));
                if(children.hasClass('opened')){
                    children.hide().removeClass('opened');
			
				
                }else{

                    $(".hidden").hide();
                    var self  = $(this);
                    children.addClass('opened');


                    if($(children).hasClass('hidden')){
                        try
                        {
                            console.log("OK");
                        }
                        catch(e)
                        {
                            if (window.console // check for window.console not console
                                && window.console.log)
                            {
                                window.console.log("OK");
                            }

                        }
                        children.show();
                        children.find('li a').click(function(event){
                            event.preventDefault();
                            appendElementInMain($(this));
                            $(".hidden").hide();
                        });
                    }else{
				
                        appendElementInMain(self.find($('a')));
				
                    }

                }
            });
	

            function appendElementInMain(element){
                $("#selectBox-dropdown-menu-Level").hide();
                $("#selectBox-Level").show();
                $("#selectBox-label-Level").text(element.text());
                $("#levelId").val(element.data("id"));
			
            }
        });

        $("#selectBox-Category").bind('click',function(event){
            $('ul.hidden').hide();
            event.preventDefault();
            $("#selectBox-Category").hide();
            $("#selectBox-dropdown-menu-Category").show();

            $(".master").unbind('click').bind('click',function(event){
                event.preventDefault();

			
                var children  = $(this).find($('ul'));
                if(children.hasClass('opened')){
                    children.hide().removeClass('opened');
			
				
                }else{

                    $(".hidden").hide();
                    var self  = $(this);
                    children.addClass('opened');


                    if($(children).hasClass('hidden')){
                        try
                        {
                            console.log("OK");
                        }
                        catch(e)
                        {
                            if (window.console // check for window.console not console
                                && window.console.log)
                            {
                                window.console.log("OK");
                            }

                        }
                        children.show();
                        children.find('li a').click(function(event){
                            event.preventDefault();
                            appendElementInMain($(this));
                            $(".hidden").hide();
                        });
                    }else{
				
                        appendElementInMain(self.find($('a')));
				
                    }

                }
            });
	

            function appendElementInMain(element){
                $("#selectBox-dropdown-menu-Category").hide();
                $("#selectBox-Category").show();
                $("#selectBox-label-Category").text(element.text());
                $("#catId").val(element.data("id"));
			
            }
        });	
        
        $("#selectBox-Age").bind('click',function(event){
            $('ul.hidden').hide();
            event.preventDefault();
            $("#selectBox-Age").hide();
            $("#selectBox-dropdown-menu-Age").show();

            $(".master").unbind('click').bind('click',function(event){
                event.preventDefault();

			
                var children  = $(this).find($('ul'));
                if(children.hasClass('opened')){
                    children.hide().removeClass('opened');
			
				
                }else{

                    $(".hidden").hide();
                    var self  = $(this);
                    children.addClass('opened');


                    if($(children).hasClass('hidden')){
                        try
                        {
                            console.log("OK");
                        }
                        catch(e)
                        {
                            if (window.console // check for window.console not console
                                && window.console.log)
                            {
                                window.console.log("OK");
                            }

                        }
                        children.show();
                        children.find('li a').click(function(event){
                            event.preventDefault();
                            appendElementInMain($(this));
                            $(".hidden").hide();
                        });
                    }else{
				
                        appendElementInMain(self.find($('a')));
				
                    }

                }
            });
	

            function appendElementInMain(element){
                $("#selectBox-dropdown-menu-Age").hide();
                $("#selectBox-Age").show();
                $("#selectBox-label-Age").text(element.text());
                $("#ageId").val(element.data("id"));
			
            }
        });

        $("#selectBox-TypeUser").bind('click',function(event){
            $('ul.hidden').hide();
            event.preventDefault();
            $("#selectBox-TypeUser").hide();
            $("#selectBox-TypeUser-dropdown-menu").show();

            $(".master").unbind('click').bind('click',function(event){
                event.preventDefault();

			
                var children  = $(this).find($('ul'));
                if(children.hasClass('opened')){
                    children.hide().removeClass('opened');
			
				
                }else{

                    $(".hidden").hide();
                    var self  = $(this);
                    children.addClass('opened');


                    if($(children).hasClass('hidden')){
                        try
                        {
                            console.log("OK");
                        }
                        catch(e)
                        {
                            if (window.console // check for window.console not console
                                && window.console.log)
                            {
                                window.console.log("OK");
                            }

                        }
                        children.show();
                        children.find('li a').click(function(event){
                            event.preventDefault();
                            appendElementInMain($(this));
                            $(".hidden").hide();
                        });
                    }else{
				
                        appendElementInMain(self.find($('a')));
				
                    }

                }
            });
	

            function appendElementInMain(element){
                $("#selectBox-TypeUser-dropdown-menu").hide();
                $("#selectBox-TypeUser").show();
                $("#selectBox-label-TypeUser").text(element.text());
                $("#user_typeId").val(element.data("id"));
			
            }

		
        });
        return;
	
	
    });

</script>

    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>    

    <script>
function initialize() {
  var mapOptions = {
    center: new google.maps.LatLng(-33.8688, 151.2195),
    zoom: 13,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  };
  var map = new google.maps.Map(document.getElementById('map-canvas'),
    mapOptions);

  var input = /** @type {HTMLInputElement} */(document.getElementById('searchTextField'));
  var autocomplete = new google.maps.places.Autocomplete(input);

  autocomplete.bindTo('bounds', map);

  var infowindow = new google.maps.InfoWindow();
  var marker = new google.maps.Marker({
    map: map
  });

  google.maps.event.addListener(autocomplete, 'place_changed', function() {
    infowindow.close();
    marker.setVisible(false);
    input.className = '';
    var place = autocomplete.getPlace();
    if (!place.geometry) {
      // Inform the user that the place was not found and return.
      input.className = 'notfound';
      return;
    }

    // If the place has a geometry, then present it on a map.
    if (place.geometry.viewport) {
      map.fitBounds(place.geometry.viewport);
    } else {
      map.setCenter(place.geometry.location);
      map.setZoom(17);  // Why 17? Because it looks good.
    }
    marker.setIcon(/** @type {google.maps.Icon} */({
      url: place.icon,
      size: new google.maps.Size(71, 71),
      origin: new google.maps.Point(0, 0),
      anchor: new google.maps.Point(17, 34),
      scaledSize: new google.maps.Size(35, 35)
    }));
    marker.setPosition(place.geometry.location);
    marker.setVisible(true);

    var address = '';
    if (place.address_components) {
      address = [
        (place.address_components[0] && place.address_components[0].short_name || ''),
        (place.address_components[1] && place.address_components[1].short_name || ''),
        (place.address_components[2] && place.address_components[2].short_name || '')
      ].join(' ');
    }

    infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + address);
    infowindow.open(map, marker);
  });

  // Sets a listener on a radio button to change the filter type on Places
  // Autocomplete.
  function setupClickListener(id, types) {
    var radioButton = document.getElementById(id);
    google.maps.event.addDomListener(radioButton, 'click', function() {
      autocomplete.setTypes(types);
    });
  }

  setupClickListener('changetype-all', []);
  setupClickListener('changetype-establishment', ['establishment']);
  setupClickListener('changetype-geocode', ['geocode']);
}

google.maps.event.addDomListener(window, 'load', initialize);

    </script>
