<div id="create_new_pin">
	<div id="content-holder">
		<div id="emailpin">
			<form action="<?php echo $this->activatePopup;?>" method="post">
				<div class="hide">
                	<input type="hidden" name="user_id" id="user_id" value="<?php echo $this->user_id;?>">
				</div>
				                <!-- Gender -->
                <li>
                    <label for="id_gender_0"><?php echo $this->translate('Gender');?></label>
                    <div id="genderOptions" class="Right">
                        <ul>
							<li><label for="id_gender_0"><input <?php echo ($this->user_data['gender'] == 'male' ? 'checked="checked"' : '');?> type="radio" name="gender" value="male" id="id_gender_0"> <?php echo $this->translate('Male');?></label></li>
							<li><label for="id_gender_1"><input <?php echo ($this->user_data['gender'] == 'female' ? 'checked="checked"' : '');?> type="radio" name="gender" value="female" id="id_gender_1"> <?php echo $this->translate('Female');?></label></li>
							<li><label for="id_gender_2"><input <?php echo ($this->user_data['gender'] == 'unspecified' ? 'checked="checked"' : '');?> type="radio" name="gender" value="unspecified" id="id_gender_2"> <?php echo $this->translate('Unspecified');?></label></li>
						</ul>
                        
                    </div>
                </li>
                <!-- Edad -->
                <li style="border:0px">
                    <label for="type_user-select<?php echo ($this->is_edit?'-edit':'');?>"><?php echo $this->translate('Age');?></label>
                    <div class="Right" id='catList'>
                         
                         <a href="" class='selectBox selectBox-dropdown' id='selectBox-TypeUser' style='width: 352px; display: inline-block;'>
                         	<?php if(!$this->usertype_title){?>
                                        <span class='selectBox-label' id='selectBox-label-TypeUser' style="width: 345px;"><?php echo  $this->translate('Please choose age');?></span>
                         	<?php }else{?>
                         		<span class='selectBox-label' id='selectBox-label-TypeUser' style="width: 345px;"><?php echo  $this->age_title;?></span>
                         	<?php } ?>
                         	 <span class="selectBox-arrow" style=""></span>
                         </a>
                         
                         <ul class='selectBox-dropdown-menu selectBox-options' id='selectBox-TypeUser-dropdown-menu' style='display:none;overflow-x: hidden;width: 370px;'>
                         
                        	<?php foreach($this->ages as $age) { ?>
                        		<li  class = 'master' style='border:none !important' >
                        			<a data-id='<?php echo $age['age_id'];?>' href="" class='' style='color:#AAA;' ><?php echo $age['age_title']?></a>
                        		</li>
                        	<?php }?>
                        </ul>
                        
                        <input type='hidden' id='ageId' name='age' value = '<?php echo $this->age_title;?>'/>

                    </div>
                </li>
            </ul>
            		<p class="input">
			<label for="ubication"><?php echo $this->translate('Location');?> <br class="hide" /></label>
			<span class="field"><input type="text" name="location" id="searchTextField" value="<?php echo $this->location;?>" /></span>
                        <span class="help_text"><?php echo $this->translate('e.g. Palo Alto, CA');?></span>                        
		</p>
    <!--div id="panel" style="margin-left: 260px">
      <input id="searchTextField" type="text" size="50">
      <input type="radio" name="type" id="changetype-all" checked="checked">
      <label for="changetype-all">All</label>

      <input type="radio" name="type" id="changetype-establishment">
      <label for="changetype-establishment">Establishments</label>

      <input type="radio" name="type" id="changetype-geocode">
      <label for="changetype-geocode">Geocodes</lable>
    </div-->
    <div id="map-canvas"></div>
                <li style="border:0px">
                    <label for="category_id-select<?php echo ($this->is_edit?'-edit':'');?>"><?php echo $this->translate('Sport');?></label>
                    <div class="Right" id='catList'>
                         
                         <a href="" class='selectBox selectBox-dropdown' id='selectBox-Category1' style='width: 352px; display: inline-block;'>
                         	<?php if(!$this->cat_title1){?>
                         		 <span class='selectBox-label' id='selectBox-label-Category1' style="width: 352px;"><?php echo  $this->translate('Please choose sport');?></span>
                         	<?php }else{?>
                         		<span class='selectBox-label' id='selectBox-label-Category1' style="width: 352px;"><?php echo  $this->cat_title1;?></span>
                         	<?php }?>
                         	 <span class="selectBox-arrow" style=""></span>
                         </a>
                         
                         <ul class='selectBox-dropdown-menu selectBox-options' id='selectBox-dropdown-menu-Category1' style='display:none;overflow-x: hidden;width: 370px;'>
                         
                        	<?php foreach($this->categories as $category) { ?>
                        		<li  class = 'master' style='border:none !important' >
                        			<a data-id='<?php echo $category['category_id'];?>' href="" class='' style='color:#AAA;' ><?php echo $category['title']?></a>
                        			<?php if($category['subcategories']){?>
                        				<ul class='subcats hidden'>
                        					<?php foreach($category['subcategories'] as $subcat){?>
	                        					<li style='border:none !important;padding-left:0px'>
	                        						<a data-id='<?php echo $subcat['category_id']; ?>' class='' href=""><?php echo $subcat['title']?></a>
	                        					</li>
                        					<?php }?>
                        				</ul>
                        			<?php }?>
                        		</li>
                        	<?php }?>
                        </ul>
                        
                        <input type='hidden' id='catId1' name='sport_category_1' value = '<?php echo $this->sport_category_1;?>'/>
                      
                    </div>
                </li>
                
                                <!-- Nivel -->
                <li style="border:0px">
                    <label for="type_user-select<?php echo ($this->is_edit?'-edit':'');?>"><?php echo $this->translate('Level');?></label>
                    <div class="Right" id='catList'>
                         
                         <a href="" class='selectBox selectBox-dropdown' id='selectBox-TypeUser' style='width: 352px; display: inline-block;'>
                         	<?php if(!$this->usertype_title){?>
                                        <span class='selectBox-label' id='selectBox-label-TypeUser' style="width: 345px;"><?php echo  $this->translate('Please choose level');?></span>
                         	<?php }else{?>
                         		<span class='selectBox-label' id='selectBox-label-TypeUser' style="width: 345px;"><?php echo  $this->level_title;?></span>
                         	<?php } ?>
                         	 <span class="selectBox-arrow" style=""></span>
                         </a>
                         
                         <ul class='selectBox-dropdown-menu selectBox-options' id='selectBox-TypeUser-dropdown-menu' style='display:none;overflow-x: hidden;width: 370px;'>
                         
                        	<?php foreach($this->levels as $level) { ?>
                        		<li  class = 'master' style='border:none !important' >
                        			<a data-id='<?php echo $level['level_id'];?>' href="" class='' style='color:#AAA;' ><?php echo $level['leve_title']?></a>
                        		</li>
                        	<?php }?>
                        </ul>
                        
                        <input type='hidden' id='levelId' name='level' value = '<?php echo $this->level_title;?>'/>

                    </div>
                </li>
                <!-- Search Index -->
                <li>
                    <label for="id_dont_search_index"><?php echo $this->translate('Hide');?></label>
                    <div class="Right NoInput">
                        <label for="id_dont_search_index" class="large">
                            <input type="checkbox" id="id_dont_search_index" name="dont_search_index" <?php echo ($this->user_data['dont_search_index'] ? 'checked="checked"' : '');?> /> <?php echo $this->translate('Hide your profile from search engines');?>
                        </label>
                    </div>
                </li>                
			<label for="tc"><?php echo sprintf($this->translate('Activate Options'));?> <br class="hide" /></label>
			<span class="" style='text-align:left'><input type='checkbox' id='tc'><?php echo sprintf($this->translate('Practice sports together'));?> </span>
                        <span class="" style='text-align:left'><input type='checkbox' id='tc'><?php echo sprintf($this->translate('Practice sports together'));?> </span>
                        <span class="" style='text-align:left'><input type='checkbox' id='tc'><?php echo sprintf($this->translate('Practice sports together'));?> </span>
                        <span class="" style='text-align:left'><input type='checkbox' id='tc'><?php echo sprintf($this->translate('Practice sports together'));?> </span>
                        <span class="" style='text-align:left'><input type='checkbox' id='tc'><?php echo sprintf($this->translate('Practice sports together'));?> </span>
                        <span class="" style='text-align:left'><input type='checkbox' id='tc'><?php echo sprintf($this->translate('Practice sports together'));?> </span>

				<div class="left w335px">
					<p>
						<label for="message"><?php echo $this->translate('Comment');?>:<br></label>
						<textarea name="texto" id="texto" rows="5" cols="30"><?php echo $this->title;?></textarea>
					</p>
					<p class="text_counter"></p>
					<p class="submit">
                    	<input class="disabled" type="submit" value="<?php echo $this->translate('Pinit');?>"></p>
					<div class="clear"></div>
				</div>
				<div class="clear"></div>
			</form>
		</div>
	</div>
</div>

<?php $key = str_replace('.','',microtime(true));?>
<script type="text/javascript">
$(document).ready(function(){

	regExPrice.addExpresionLine($('#texto').html(), true);
	
	$('#texto').jqEasyCounter({
		holder: 'p.text_counter',
		maxChars: 255,
		maxCharsWarning: 225,
		template: '{count}'
	}).bind("keydown keyup keypress focus paste",function() {
		regExPrice.addExpresionLine(this.value);
                if($.trim($('#texto').val())) {
                        $('#emailpin .submit input').removeClass('disabled').attr('disabled', false);
                } 
                else 
                {
                        $('#emailpin .submit input').addClass('disabled').attr('disabled', true);
                }
		regExPrice.addExpresionLine(this.value, false);
	});


	$('#emailpin form').unbind('submit').submit(function(){
		$('#emailpin form .submit input').after('<img src="data/images/loading_2.gif" id="loading_button" />');
		$('#emailpin form .submit input').attr('disabled', true).addClass('disabled');
                var user_id = $('#user_id').val();
                var texto = $('#texto').val();
                  
		$.post('<?php echo $this->from_url;?>', {user_id:user_id, texto:texto}, function(data,status){
			
			$('#loading_button').remove();
                        $.fancybox.close();                        
			
			
                });
		return false;
	});
		
});


</script>