<div class="box user not-popup" id="<?php echo $this->user['user_id']; ?>">

    <div class="preview">

        <p class="thumb">
            <a href="<?php echo $this->user['href']; ?>">
                <img data-original="<?php echo $this->user['avatar']; ?>" src="data/images/grey.gif" alt="<?php echo $this->user['fullname']; ?>" />
            </a>
        </p>
        <h2><a href="<?php echo $this->user['href']; ?>"><?php echo $this->user['fullname']; ?></a></h2>
        <p class="location colorless"><?php echo $this->user['location']; ?></p>
        <?php if ($this->services)
        { ?>        
        <div style="overflow:auto;color:#8c7e7e;">
            <?php echo $this->user['description']; ?>
        </div>
        <?php } ?>        
        
        <div class="follow">
            <?php if ($this->loged && !$this->user['userFollowIgnore'])
            { ?>
                    <?php if ($this->user['userIsFollow'])
                    { ?>
                    <a href="<?php echo $this->user['follow']; ?>" class="gray" style="width: auto !important">
                    <?php echo $this->translate('Unfollow'); ?>
                    </a>
                    <?php } else
                    { ?>
                    <a href="<?php echo $this->user['follow']; ?>" style="width: auto !important">
                    <?php echo $this->translate('Follow'); ?>
                    </a>
    <?php } ?>
<?php } ?>
        </div>

    </div>

</div>