<div class="box person <?php echo ($this->key ? 'odd' : '');?>" id="<?php echo $this->user['user_id'];?>" style="width:460px;height: 468px">
    <!--a style="background-image: url(<?php echo $this->user['avatar'];?>); filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='<?php echo $this->user['avatar'];?>',sizingMethod='scale');-ms-filter: \"progid:DXImageTransform.Microsoft.AlphaImageLoader(src='<?php echo $this->user['avatar'];?>',sizingMethod='scale')\";" class="PersonImage ImgLink" href="<?php echo $this->user['href'];?>"></a-->
			<!--p class="thumb">
				<a class="PersonImage" href="<?php echo $this->user['href'];?>">
					<img style="height:110px;width:110px;" data-original="<?php echo $this->user['avatar'];?>" src="data/images/grey.gif" alt="<?php echo $this->user['fullname'];?>" />
				</a>
			</p-->

		<div class="PersonInfo">
                        <div style="float: left;width: 100%;padding: 0px">
                            <div >
                                <div style="float: left;width: 35%;padding: 0px">
                                    <a style="background-image: url(<?php echo $this->user['avatar'];?>); filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='<?php echo $this->user['avatar'];?>',sizingMethod='scale');-ms-filter: \"progid:DXImageTransform.Microsoft.AlphaImageLoader(src='<?php echo $this->user['avatar'];?>',sizingMethod='scale')\";" class="PersonImage ImgLink" href="<?php echo $this->user['href'];?>"></a>
                                </div>
                                <div style="float: left;width: 30%;padding: 5px">
                                    <h2><a href="<?php echo $this->user['href'];?>"><?php echo $this->user['fullname'];?></a></h2>
                                </div>
                                <div style="float: left;width: 20%;padding: 0px">
                                    <div class="follow">
<!--------------------------------------------------------------->
    <?php if (!$this->loged) { ?>
                        <a href="users/register" style="width:95px !important;height:28px !important"><?php echo $this->translate('Regístrate para contactar'); ?></a>
    <?php } ?>


    <?php if ($this->loged) { ?>
    <?php 
			echo '<div id="divMailsHeader" style="border-bottom:0px">';
                        echo '<a id="newMail" style="width: 100px ! important; padding-top: 9px ! important; font-size: 1.2em;" href="'.$this->addMail.'?user_voluntario_name='.$this->user['fullname'].'" class="silverbox" title="'.$this->translate('Enviar mensaje').'">'.$this->translate('Nuevo mensaje').'</a>';
			echo '</div>';
    } ?>

    <script type="text/javascript">
			$(document).ready(function() 
				{
                                    /*
					$("#newMail").click(function (){
						$("#divMails").fadeOut();
					});
					$(".messagesContent").click(function (){
						$("#divMails").fadeOut();
					});
        */
					$("._5c9q").click(function (){
						if ($(this).hasClass("NOleido"))
						{
							$.post('<?php echo $this->stateMail;?>', {id:$(this).attr("id"),read:1}, function(data){
								if (data.data.unread==0)
								{
									$("#avisoMensajes").hide();
								}else
								{
									$("#avisoMensajes").html(data.data.unread);
									$("#avisoMensajes").show();
								}
							}, 'json');
							$("#mail" + $(this).attr("id")).removeClass("NOleido");
							$(this).removeClass("NOleido");
							$(this).attr("title","<?php echo $this->translate('Marcar la conversación como no leída'); ?>");
						}else
						{
							$.post('<?php echo $this->stateMail;?>', {id:$(this).attr("id"),read:0}, function(data){
								$("#avisoMensajes").html(data.data.unread);
								$("#avisoMensajes").show();
							}, 'json');
							$("#mail" + $(this).attr("id")).addClass("NOleido");
							$(this).addClass("NOleido");	
							$(this).attr("title","<?php echo $this->translate('Marcar la conversación como leída'); ?>");
											
						}
						return false;
					});
                                        /*
					$("#muestraMensajes .ados").click(function (){
						if ($("#divMails").is(":visible"))
						{
							$("#divMails").fadeOut();
						}else
						{
							$("#divMails").fadeIn();
						}
						return false;
					});
					$("#avisoMensajes").click(function (){
						if ($("#divMails").is(":visible"))
						{
							$("#divMails").fadeOut();
						}else
						{
							$("#divMails").fadeIn();
						}
						return false;
					});
                                        */
				});
	</script>


<!--------------------------------------------------------------->
			</div>
                        </div>
                        </div>
                        </div>
                        <div>
                            <div> 
                                <div style="float: left;width: 19%;padding: 5px">
                                    <p class="location colorless"><?php echo $this->translate('Opciones:');?></p>
                                </div>
                                <div style="float: left;width: 70%;padding: 5px;font-size: 1.2em;overflow-y: auto;max-height: 200px">
                                    <?php echo ($this->user['option1'] == '1' ? "&bull; ". sprintf($this->translate("Deportista, individual o club, da charlas a grupos, colegios...")) . "<br/>" : ''); ?>
                                    <?php echo ($this->user['option2'] == '1' ? "&bull; ". sprintf($this->translate("Comparto mi experiencia de superación, charlas para grupos, colegios...")) . "<br/>" : ''); ?> 
                                    <?php echo ($this->user['option3'] == '1' ? "&bull; ". sprintf($this->translate("Apoyo a rehabilitación")) . "<br/>"  : ''); ?> 
                                    <?php echo ($this->user['option4'] == '1' ? "&bull; ". sprintf($this->translate("Ayuda o entrenamiento a paralímpicos"))  . "<br/>" : ''); ?> 
                                    <?php echo ($this->user['option5'] == '1' ? "&bull; ". sprintf($this->translate("Entrenamiento a deportista o equipo"))  . "<br/>" : ''); ?> 
                                    <?php echo ($this->user['option6'] == '1' ? "&bull; ". sprintf($this->translate("Agrupación con otros volunttarios")) . "<br/>"  : ''); ?> 
                                    <?php echo ($this->user['option7'] == '1' ? "&bull; ". sprintf($this->translate("Colaboración con ONG como volunttario"))  . "<br/>" : ''); ?> 
                                    <?php echo ($this->user['option8'] == '1' ? "&bull; ". sprintf($this->translate("Participación o colaboración en eventos deportivos solidarios"))  . "<br/>"  : ''); ?> 
                                    <?php echo ($this->user['option9'] == '1' ? "&bull; ". sprintf($this->translate("Donación material usado o nuevo"))  . "<br/>"  : ''); ?>                                     
                                    <?php echo ($this->user['option10'] == '1' ? "&bull; ". sprintf($this->translate("Coaching, motivación, apoyo psicológico"))  . "<br/>" : ''); ?>
                                    <?php echo ($this->user['option11'] == '1' ? "&bull; ". sprintf($this->translate("Asesoría sobre salud, lesiones y nutrición en el deporte"))  . "<br/>" : ''); ?>
                                    <?php echo ($this->user['option12'] == '1' ? "&bull; ". sprintf($this->translate("Presto instalaciones deportivas"))  . "<br/>" : ''); ?> 
                                    <?php echo ($this->user['option13'] == '1' ? "&bull; ". sprintf($this->translate("Patrocinio o copatrocinio equipo o deportista")) . "<br/>"  : ''); ?> 
                                    <?php echo ($this->user['option14'] == '1' ? "&bull; ". sprintf($this->translate("Entradas o abonos para eventos deportivos"))  . "<br/>" : ''); ?> 
                                    <?php echo ($this->user['option15'] == '1' ? "&bull; ". sprintf($this->translate("ONG ayuda a superar problemas para tomar la salida"))  . "<br/>" : ''); ?> 
                                    <?php echo ($this->user['option16'] == '1' ? "&bull; ". sprintf($this->translate("Árbitros o jueces deportivos"))  . "<br/>" : ''); ?> 
                                    <?php echo ($this->user['option17'] == '1' ? "&bull; ". sprintf($this->translate("Ayudo a personas mayores a hacer ejercicio"))  . "<br/>" : ''); ?> 
                                    <?php echo ($this->user['option18'] == '1' ? "&bull; ". sprintf($this->translate("Otros (descripción en los comentarios)"))   . "<br/>" : ''); ?> 
                                    &nbsp;
                                </div>
                            </div>                            
                            <div>
                                <div style="float: left;width: 19%;padding: 5px">
                                    <p class="location colorless"><?php echo $this->translate('Zona geográfica:');?>&nbsp;</p>
                                </div>
                                <div style="float: left;width: 70%;padding: 5px;font-size: 1.2em;">
                                    <?php echo $this->user['location'];?>
                                </div>
                            </div>
                            <div >
                                <div style="float: left;width: 19%;padding: 5px">
                                    <p class="location colorless"><?php echo $this->translate('Deporte:');?></p>
                                </div>
                                <div style="float: left;width: 70%;padding: 5px;font-size: 1.2em;">
                                    <?php echo $this->user['sport_category'];?>&nbsp;
                                </div>
                            </div>
                            <div>
                                 <div style="float: left;width: 19%;padding: 5px;height:98px">
                                    <p class="location colorless"><?php echo $this->translate('Comentarios:');?></p>
                                </div>
                                <div style="float: left;width: 70%;padding: 5px;font-size: 1.2em;" id="divComentarios">
                                    <?php echo $this->user['comment'];?>
                                </div>
                            </div>
                        </div>
		</div>
</div>