<div id="create_new_pin">
	<div id="content-holder">
		<div id="emailpin">
			<form action="<?php echo $this->messagePopup;?>" method="post">
				<div class="hide">
                	<input type="hidden" name="message_from_id" id="message_from_id" value="<?php echo $this->message_from_id;?>">
					<input type="hidden" name="user_to" id="user_to" value="<?php echo $this->user_to;?>">
					<input type="hidden" name="user_from" id="user_from" value="<?php echo $this->user_from;?>">
					<input type="hidden" name="board_user" id="board_user" value="<?php echo $this->board_user;?>">
				</div>
				
				<div class="left w335px">
					<p>
						<label for="message"><?php echo $this->translate('Message');?>:<br></label>
						<textarea name="text_message" id="text_message" rows="5" cols="30"><?php echo $this->title;?></textarea>
                        <input type="checkbox" id="private_message" name="private_message" value="true"><?php echo $this->translate('Private message');?></input>
					</p>
					<p class="text_counter"></p>
					<p class="submit">
                    	<input class="disabled" type="submit" value="<?php echo $this->translate('Pinit');?>"></p>
					<div class="clear"></div>
				</div>
				<div class="clear"></div>
			</form>
		</div>
	</div>
</div>

<?php $key = str_replace('.','',microtime(true));?>
<script type="text/javascript">
$(document).ready(function(){

	regExPrice.addExpresionLine($('#text_message').html(), true);
	
	$('#text_message').jqEasyCounter({
		holder: 'p.text_counter',
		maxChars: 300,
		maxCharsWarning: 270,
		template: '{count}'
	}).bind("keydown keyup keypress focus paste",function() {
		regExPrice.addExpresionLine(this.value);
		var comboCarpeta=false;
		$("#board_id option:selected").each(function(){
			comboCarpeta=true
		});
                if($.trim($('#text_message').val())) {
                        $('#emailpin .submit input').removeClass('disabled').attr('disabled', false);
                } 
                else 
                {
                        $('#emailpin .submit input').addClass('disabled').attr('disabled', true);
                }
		regExPrice.addExpresionLine(this.value, false);
	});


	$('#emailpin form').unbind('submit').submit(function(){
		$('#emailpin form .submit input').after('<img src="data/images/loading_2.gif" id="loading_button" />');
		$('#emailpin form .submit input').attr('disabled', true).addClass('disabled');
                var user_to = $('#user_to').val();
                var user_from = $('#user_from').val();
                var text_message = $('#text_message').val();
				if($('#private_message').is(':checked'))
				{
					var private_message = 1; 
				}else
				{
					var private_message = 0; 
				}
                var board_user = $('#board_user').val();
                var message_from_id = $('#message_from_id').val();                
		$.post('<?php echo $this->from_url;?>', {user_to:user_to, user_from:user_from, text_message: text_message, private_message:private_message, board_user:board_user, message_from_id:message_from_id}, function(data,status){
			/*if(data.indexOf('http://') === 0) {
				window.location = data;
			} else {
				$.fancybox(data, {
					'titleFormat': function(){
			        	return '<div id="fancybox-title-over"><?php echo $this->translate('Add a Pin');?></div>';
			        },
			        titlePosition: 'over'
				});
			}
                        */
			$('#loading_button').remove();
                        $.fancybox.close();                        
			
			
                });
		return false;
	});
		
});


</script>