    <?php if($this->enable_edit) { ?>
        <div class="mensaje <?php if ($this->message['message_from_id']>0){echo "hijo";} ?>">
        	<div class="cabeceraMensaje">
            	<div class="imagen">
            		<a style="background-image: url(<?php echo $this->message['avatar'];?>)" class="PersonImageLittle ImgLink" href="<?php echo $this->message['href'];?>" title="Ver perfil"></a> 
                </div>
                <div class="nombreUsu">
                	<a class="linkHover" href="<?php echo $this->message['href'];?>" title="Ver perfil"><?php echo $this->message['fullname'];?></a>:
                </div>
            </div>
            <div class="cuerpoMensaje">
                <span class="textoOriginal"><?php echo $this->message['text_message'];?></span>
            </div>
                  
        <?php if($this->loged) { ?> 
        	 
        		<a class="btnBorrar silverboxMessage" href="<?php echo $this->message['hrefDelete'];?>" title="<?php  echo $this->translate('Borrar'); ?>"></a>   
            <?php if($this->message['message_from_id']==0)
				//Sólo pintamos el reply si es un mensaje principal
			{ ?>
            	<a class="btnReply silverboxMessage" href="<?php echo $this->message['hrefResponder'];?>" title="<?php  echo $this->translate('Responder'); ?>"></a>
            <?php } ?> 
    	<?php } ?>   
        </div>          
    <?php } else { ?>	
    	 <?php if(($this->message['private_message'] == 0) || ($this->message['from_user_id']==JO_Session::get('user[user_id]'))) { ?>  
            <div class="mensaje <?php if ($this->message['message_from_id']>0){echo "hijo";} ?>">
                <div class="cabeceraMensaje">
                    <div class="imagen">
                        <a style="background-image: url(<?php echo $this->message['avatar'];?>)" class="PersonImageLittle ImgLink" href="<?php echo $this->message['href'];?>" title="Ver perfil"></a> 
                    </div>
                    <div class="nombreUsu">
                        <a class="linkHover" href="<?php echo $this->message['href'];?>" title="Ver perfil"><?php echo $this->message['fullname'];?></a>:
                    </div>
                </div>
                <div class="cuerpoMensaje">
                    <span class="textoOriginal"><?php echo $this->message['text_message'];?></span>
                </div>
                      
            <?php if($this->loged) { ?>  
                 <?php if ($this->message['from_user_id']==JO_Session::get('user[user_id]')) { ?>
                <a class="btnBorrar silverboxMessage" href="<?php echo $this->message['hrefDelete'];?>" title="<?php  echo $this->translate('Borrar'); ?>"></a>   
                <?php } ?>
                <?php if($this->message['message_from_id']==0)
                    //Sólo pintamos el reply si es un mensaje principal
                { ?>
                    <a class="btnReply silverboxMessage" href="<?php echo $this->message['hrefResponder'];?>" title="<?php  echo $this->translate('Responder'); ?>"></a>
                <?php } ?>
            <?php } ?>   
            </div>
         <?php } ?> 
    <?php } ?>    
