<?php echo $this->header_part; ?>

<div id="panel">
	<h3 class="maintitle"><?php echo $this->translate('Complete your registration');?></h3>
	
	<?php if($this->error) { ?>
	<div class="error-box">
		<?php echo $this->error;?>
	</div>
	<?php } ?>
	
	
	<form action="" method="post" class="edit">
	
		<?php if(JO_Registry::get('enable_free_registration')) { ?>
		<div class="social_buttons register">
			<?php if($this->fb_register) { ?>
	        <div class="inset">
	            <a class="fb login_button" href="<?php echo $this->fb_register;?>">
	                <span class="logo_wrapper"><span class="logo"></span></span>
	                <span><?php echo $this->translate('Register with Facebook');?></span>
	            </a>
	        </div>
	        <?php } ?>
	        <?php /*if($this->instagram_register) { ?>
	        <div class="inset">
	            <a class="is login_button" href="<?php echo $this->instagram_register;?>">
	                <span class="logo_wrapper"><span class="logo"></span></span>
	                <span><?php echo $this->translate('Register with Instagram');?></span>
	            </a>
	        </div>
	        <?php }*/ ?>
	        <div class="clear"></div>
	    </div>
		<?php } ?>
	
		<p class="input">
			<label for="email"><?php echo $this->translate('Email');?> <br class="hide" /></label>
			<span class="field"><input type="text" name="email" id="email" value="<?php echo $this->email;?>" /></span>
			<span class="addtext"><?php echo $this->translate('Not shown publicly');?></span>
		</p>
		<p class="input">
			<label for="firstname"><?php echo $this->translate('First name');?> <br class="hide" /></label>
			<span class="field"><input type="text" name="firstname" id="firstname" value="<?php echo $this->firstname;?>" /></span>
                        <span class="addtext"><?php echo $this->translate('En caso de empresa, nombre de la misma');?></span>
		</p>
		<!--p class="input">
			<label for="lastname"><?php echo $this->translate('Last name');?> <br class="hide" /></label>
			<span class="field"><input type="text" name="lastname" id="lastname" value="<?php echo $this->lastname;?>" /></span>
		</p-->
                <input type="hidden" name="lastname" id="lastname" value="" />
		<p class="input">
			<label for="username"><?php echo $this->translate('Username');?> <br class="hide" /></label>
			<span class="field"><input type="text" name="username" id="username" value="<?php echo $this->username;?>" /></span>
			<span class="addtext"><?php echo $this->baseUrl;?>username</span>
		</p>
		<div class="hr"></div>
       
    <div id="create-board" class="Form StaticForm" style="padding-left:0px;" >
            <ul style="margin:0px;">
                
                <!-- Tipo Usuario -->
                <li style="border:0px">
                    <label for="type_user-select<?php echo ($this->is_edit?'-edit':'');?>"><?php echo $this->translate('User Type');?></label>
                    <div class="Right" id='catList'>
                         
                         <a href="" class='selectBox selectBox-dropdown' id='selectBox-TypeUser' style='width: 352px; display: inline-block;'>
                         	<?php if(!$this->usertype_title){?>
                                        <span class='selectBox-label' id='selectBox-label-TypeUser' style="width: 345px;"><?php echo  $this->translate('Please choose user type');?></span>
                         	<?php }else{?>
                         		<span class='selectBox-label' id='selectBox-label-TypeUser' style="width: 345px;"><?php echo  $this->usertype_title;?></span>
                         	<?php } ?>
                         	 <span class="selectBox-arrow" style=""></span>
                         </a>
                         
                         <ul class='selectBox-dropdown-menu selectBox-options' id='selectBox-TypeUser-dropdown-menu' style='display:none;overflow-x: hidden;width: 370px;'>
                         
                        	<?php foreach($this->user_types as $user_type) { ?>
                        		<li  class = 'master typeuser' style='border:none !important' >
                        			<a data-id='<?php echo $user_type['user_type_id'];?>' href="" class='cats-typeuser' style='color:#AAA;' ><?php echo $user_type['title']?></a>
                        			<?php if($user_type['subuser_types']){?>
                        				<ul class='subcats hidden'>
                        					<?php foreach($user_type['subuser_types'] as $subuser_type){?>
	                        					<li style='border:none !important;padding-left:0px'>
	                        						<a data-id='<?php echo $subuser_type['user_type_id']; ?>' class='' href=""><?php echo $subuser_type['title']; ?></a>
	                        					</li>
                        					<?php }?>
                        				</ul>
                        			<?php }?>
                        		</li>
                        	<?php }?>
                        </ul>
                        
                        <input type='hidden' id='user_typeId' name='type_user' value = '<?php echo $this->type_user;?>'/>

                    </div>
                </li>
                
                <!-- Deportes -->
                
                <li style="border:0px">
                    <label for="category_id-select<?php echo ($this->is_edit?'-edit':'');?>"><?php echo $this->translate('My Sports');?></label>
                    <div class="Right" id='catList'>
                        <a id="moresports" onclick="deportes()"  class="Button RedButton moresports " style="margin-top:0px;" ><?php echo $this->translate('Seleccionar ...');?></a>
                        <br/><br/>
                        <div id="divSports" name="divSports" >
                        	<?php foreach($this->user_sports as $user_sport) {  ?>
                                <?php  echo trim($user_sport); ?><br/>
                                <?php     } ?>
                            
                            <input id="sports" class="sports" name="sports" type="hidden" value="<?php foreach($this->user_sports as $user_sport) {  echo trim($user_sport); break; } ?>" />
                        </div>
                    </div>
                    <span class="addtext" style="float:right"><?php echo $this->translate('Elegir por lo menos un deporte o categoría');?></span>                    
                </li>
                
                <!--li style="border:0px">
                    <label for="category_id-select<?php echo ($this->is_edit?'-edit':'');?>"><?php echo $this->translate('My Sports');?></label>
                    <div class="Right" id='catList'>
                         
                         <a href="" class='selectBox selectBox-dropdown' id='selectBox-Category1' style='width: 352px; display: inline-block;'>
                         	<?php if(!$this->cat_title1){?>
                         		 <span class='selectBox-label' id='selectBox-label-Category1' style="width: 352px;"><?php echo  $this->translate('Please choose sport');?></span>
                         	<?php }else{?>
                         		<span class='selectBox-label' id='selectBox-label-Category1' style="width: 352px;"><?php echo  $this->cat_title1;?></span>
                         	<?php }?>
                         	 <span class="selectBox-arrow" style=""></span>
                         </a>
                         
                         <ul class='selectBox-dropdown-menu selectBox-options' id='selectBox-dropdown-menu-Category1' style='display:none;overflow-x: hidden;width: 370px;'>
                         
                        	<?php $i=0; foreach($this->categories as $category) { ?>
                        		<li  class = 'master cat1' style='border:none !important' >
                                                <?php if ($i==0) { $i=1; ?>
                                                <a data-id='<?php echo 1; ?>' href="" class='cats-category1' style='color:#AAA;' ><?php echo "Todo"; ?></a>
                                                <ul class='subcats hidden'><li style='border:none !important;padding-left:0px'></li></ul>
                                                <?php } ?>

                        			<a data-id='<?php echo $category['category_id'];?>' href="" class='cats-category1' style='color:#AAA;' ><?php echo $category['title']?></a>
                        			<?php if($category['subcategories']){?>
                        				<ul class='subcats hidden'>
                        					<?php foreach($category['subcategories'] as $subcat){?>
	                        					<li style='border:none !important;padding-left:0px'>
	                        						<a data-id='<?php echo $subcat['category_id']; ?>' class='' href=""><?php echo $subcat['title']?></a>
	                        					</li>
                        					<?php }?>
                        				</ul>
                        			<?php }?>
                        		</li>
                        	<?php }?>
                        </ul>
                        
                        <input type='hidden' id='catId1' name='sport_category_1' value = '<?php echo $this->sport_category_1;?>'/>
                      
                    </div>
                    <span class="addtext" style="float:right"><?php echo $this->translate('Elegir por lo menos un deporte o categoría');?></span>
                </li>

                <li style="border:0px">
                    <label for="category_id-select<?php echo ($this->is_edit?'-edit':'');?>"><?php echo $this->translate('');?></label>
                    <div class="Right" id='catList'>
                         
                         <a href="" class='selectBox selectBox-dropdown' id='selectBox-Category2' style='width: 352px; display: inline-block;'>
                         	<?php if(!$this->cat_title2){?>
                         		 <span class='selectBox-label' id='selectBox-label-Category2' style="width: 345px;"><?php echo  $this->translate('Please choose sport');?></span>
                         	<?php }else{?>
                         		<span class='selectBox-label' id='selectBox-label-Category2' style="width: 345px;"><?php echo  $this->cat_title2;?></span>
                         	<?php }?>
                         	 <span class="selectBox-arrow" style=""></span>
                         </a>
                         
                         <ul class='selectBox-dropdown-menu selectBox-options' id='selectBox-dropdown-menu-Category2' style='display:none;overflow-x: hidden;width: 370px;'>
                         
                        	<?php $i=0; foreach($this->categories as $category) { ?>
                        		<li  class = 'master cat2' style='border:none !important' >
                                                <?php if ($i==0) { $i=1; ?>
                                                <a data-id='<?php echo 1; ?>' href="" class='cats-category2' style='color:#AAA;' ><?php echo "Todo"; ?></a>
                                                <ul class='subcats hidden'><li style='border:none !important;padding-left:0px'></li></ul>
                                                <?php } ?>

                        			<a data-id='<?php echo $category['category_id'];?>' href="" class='cats-category2' style='color:#AAA;' ><?php echo $category['title']?></a>
                        			<?php if($category['subcategories']){?>
                        				<ul class='subcats hidden'>
                        					<?php foreach($category['subcategories'] as $subcat){?>
	                        					<li style='border:none !important;padding-left:0px'>
	                        						<a data-id='<?php echo $subcat['category_id']; ?>' class='' href=""><?php echo $subcat['title']?></a>
	                        					</li>
                        					<?php }?>
                        				</ul>
                        			<?php }?>
                        		</li>
                        	<?php }?>
                        </ul>
                        
                        <input type='hidden' id='catId2' name='sport_category_2' value = '<?php echo $this->sport_category_2;?>'/>
                      
                    </div>
                </li>

                                
                <li style="border:0px">
                    <label for="category_id-select<?php echo ($this->is_edit?'-edit':'');?>"><?php echo $this->translate('');?></label>
                    <div class="Right" id='catList'>
                         
                         <a href="" class='selectBox selectBox-dropdown' id='selectBox-Category3' style='width: 352px; display: inline-block;'>
                         	<?php if(!$this->cat_title3){?>
                         		 <span class='selectBox-label' id='selectBox-label-Category3' style="width: 345px;"><?php echo  $this->translate('Please choose sport');?></span>
                         	<?php }else{?>
                         		<span class='selectBox-label' id='selectBox-label-Category3' style="width: 345px;"><?php echo  $this->cat_title3;?></span>
                         	<?php } ?>
                         	 <span class="selectBox-arrow" style=""></span>
                         </a>
                         
                         <ul class='selectBox-dropdown-menu selectBox-options' id='selectBox-dropdown-menu-Category3' style='display:none;overflow-x: hidden;width: 370px;'>
                         
                        	<?php $i=0; foreach($this->categories as $category) { ?>
                        		<li  class = 'master cat3' style='border:none !important' >
                                                <?php if ($i==0) { $i=1; ?>
                                                <a data-id='<?php echo 1; ?>' href="" class='cats-category3' style='color:#AAA;' ><?php echo "Todo"; ?></a>
                                                <ul class='subcats hidden'><li style='border:none !important;padding-left:0px'></li></ul>
                                                <?php } ?>
                        			<a data-id='<?php echo $category['category_id'];?>' href="" class='cats-category3' style='color:#AAA;' ><?php echo $category['title']?></a>
                        			<?php if($category['subcategories']){?>
                        				<ul class='subcats hidden'>
                        					<?php foreach($category['subcategories'] as $subcat){?>
	                        					<li style='border:none !important;padding-left:0px'>
	                        						<a data-id='<?php echo $subcat['category_id']; ?>' class='' href=""><?php echo $subcat['title']?></a>
	                        					</li>
                        					<?php }?>
                        				</ul>
                        			<?php }?>
                        		</li>
                        	<?php }?>
                        </ul>
                        
                        <input type='hidden' id='catId3' name='sport_category_3' value = '<?php echo $this->sport_category_3;?>'/>
                      
                    </div>
                </li-->

            </ul>
        </div>  
        <!--br/><br/><br/--><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
        <!--  Location -->
		<p class="input">
			<label for="ubication"><?php echo $this->translate('Location');?> <br class="hide" /></label>
			<span class="field"><input type="text" name="location" class="location" id="searchTextField" value="<?php echo $this->location;?>" /></span>
                        <span class="addtext"><?php echo $this->translate('Campo obligatorio para los usuario profesional (Otros)');?></span>
                        <br/><br/><br/><br/><br/><br/><br/>
                            <input type="hidden" name="lat" class="lat" id="lat" />
                            <input type="hidden" name="len" class="len" id="len" />
                        </p>
                        <div id="map-canvas" style="display:none !important"></div>
                <!-- More Location -->
                <p class="input">
                    <input type='hidden' id="locationcounter" name="locationcounter"  class="locationcounter" value="<?php echo $this->locationcounter; ?>"/>
                    <label><?php echo $this->translate('Añadir ubicación');?>&nbsp;<a id="morelocations" href="" class="Button RedButton morelocations " style="margin-top:0px;" ><?php echo $this->translate('Añadir');?></a></label>
                    
                    <span class="field"><input type="text" id="searchTextField2" value="" name="locationAux" class="locationAux"></span>
                    <span class="addtext" style="float:left"><?php echo $this->translate('Pulsa añadir después de buscar la ubicación');?></span>  
                    <br/><br/><br/><br/><br/><br/><br/>        
                    <input type="hidden" name="latAux" class="latAux" id="latAux" />
                    <input type="hidden" name="lenAux" class="lenAux" id="lenAux" />
                    
                </p>

                    <span class="locations ">
                        <?php $i=0; foreach($this->user_location as $users_location) { ?>
                        <?php $i++; ?>
                            <p class="input"><label></label><span class="field"><input type='text' value='<?php echo $users_location; ?>' name='<?php echo "location".$i; ?>'></span></p>
                        <?php } ?>
                    </span>
    
		<p class="input">
			<label for="password"><?php echo $this->translate('Password');?> <br class="hide" /></label>
			<span class="field"><input type="password" name="password" id="password" value="<?php echo $this->password;?>" /></span>
		</p>
		<p class="input">
			<label for="password2"><?php echo $this->translate('Confirm password');?> <br class="hide" /></label>
			<span class="field"><input type="password" name="password2" id="password2" value="<?php echo $this->password2;?>" /></span>
		</p>
		<div class="hr"></div>
		
			<label for="tc"><?php echo sprintf($this->translate('I agree with the %s terms and conditions %s'),"<a href='' class='tcLink'>","</a>");?> <br class="hide" /></label>
			<span class="" style='text-align:left'><input type='checkbox' id='tc'></span>
		
		<div class="hr"></div>
		<p class="submit"><input type="submit" value="<?php echo $this->translate('Save Profile');?>" name="register" /></p>
	</form>
</div>

<script type='text/javascript'>
	$(document).ready(function(){
		$('form').on('submit',function(event){
			if(!$('#tc').is(':checked')){
				event.preventDefault();
				$("#tc").parent().append("<br/><p class='warn' style='color:red'><?php echo $this->translate('Please agree with terms and conditions')?></p>")
			}
		});	

		$("#tc").click(function(){
			if($(this).is(':checked')){
				$(".warn").remove();
			}
		});
                $("#moresports").click(function(){
                    var locationcounter = $('#locationcounter').val();
                    var locations = '&locationcounter='+ $('#locationcounter').val();
                    var k = 0;
                    for(var i = 1; i <= locationcounter; i++)
                    {
                        if ($.trim($('#location' + i).val()) != "")
                        {
                            k++;
                            locations += '&location'+ k + '='+ $('#location' + i).val();
                        }
                    }                    
                    window.location.href = '<?php echo $this->deportes;?>?email=' + $('#email').val() + 
                        '&firstname=' + $('#firstname').val() + '&username=' + $('#username').val() + 
                        /*'&password=' + $('#password').val() + '&password2=' + $('#password2').val() + */
                        '&location=' + $('.location').val() + '&type_user=' + $('#user_typeId').val() + 
                        locations;
                });
	
	});
</script>
    


                
<script type="text/javascript">
$(document).ready(function(){
	$('#category_id-select<?php echo ($this->is_edit?'-edit':'');?>').selectBox({
		onOpen: function (inst) {
                    try
                    {
			console.log("open", inst);
                    }
                    catch(e)
                    {
                        if (window.console // check for window.console not console
                            && window.console.log)
                        {
                            window.console.log("open", inst);
                        }                        
                    }
		},
		onClose: function (inst) {
                    try
                    {
			console.log("close", inst);
                    }
                    catch(e)
                    {
                        if (window.console // check for window.console not console
                            && window.console.log)
                        {
                            window.console.log("close", inst);
                        }                        
                    }
                        
		}
	});
	$('#type_user-select<?php echo ($this->is_edit?'-edit':'');?>').selectBox({
		onOpen: function (inst) {
                    try
                    {
			console.log("open", inst);
                    }
                    catch(e)
                    {
                        if (window.console // check for window.console not console
                            && window.console.log)
                        {
                            window.console.log("open", inst);
                        }                        
                    }
		},
		onClose: function (inst) {
                    try
                    {
			console.log("close", inst);
                    }
                    catch(e)
                    {
                        if (window.console // check for window.console not console
                            && window.console.log)
                        {
                            window.console.log("close", inst);
                        }                        
                    }
                        
		}
	});        
	$('input.collaborator_name').clearOnFocus();

	
	var cache = {};
	$('.collaborator_name.ui-autocomplete-input').live('keyup', function(){
		var val = this.value;
		if(cache[val]) {
			autocompleteResults(cache[val]);
		} else {
			$.post('<?php echo $this->friends_href;?>', {term: val}, function(data){
				cache[val] = data.users;
				autocompleteResults(data.users);
			}, 'json');
		}
	}).after('<div class="menu_friends" style="position: absolute; display: none; margin-top: 33px;z-index:2147483647;">');
	
	function autocompleteResults(data) {

		var holder = $('.menu_friends').empty();
		if($(data).objectSize() < 1) {
			holder.hide();
			return;
		}
		holder.show(function(){
			$(document).unbind('.joauto').bind('click.joauto',function(e){
				holder.hide();
			});
		});
		$(data).each(function(i, item){
			user = $('<div class="option_friends"><img alt="'+item.label+'" src="'+item.image+'"><span>'+item.label+'</span></div>').click(function(){
				holder.hide();
				if( $('#user_fr_'+item.value+'<?php echo ($this->is_edit?'-edit':'');?>').size() > 0 ) { return; }
				$('input.collaborator_name').val('');
				$('#invite_response<?php echo ($this->is_edit?'-edit':'');?>').append('<input id="hidden_user_fr_'+item.value+'<?php echo ($this->is_edit?'-edit':'');?>" type="hidden" name="friends['+item.value+']" value="'+item.value+'" />');

				template = $('#friend-template<?php echo ($this->is_edit?'-edit':'');?>').html();
				for(e in item) {
					template = template.replace(new RegExp(RegExp.quote('{'+e+'}'), 'g'), item[e]);
				}
				
				$('#CurrentCollaborators<?php echo ($this->is_edit?'-edit':'');?>').append(template);
			}).css({'cursor': 'pointer'});
			
			holder.append(user);
		});
	}

	RegExp.quote = function(str) {
	    return (str+'').replace(/([.?*+^$[\]\\(){}|-])/g, "\\$1");
	};
		
	
});

function saveBoardData() {
	
	$.post('<?php echo $this->form_action;?>', $('#CreateBoard<?php echo ($this->is_edit?'-edit':'');?>').serialize(), function(data){
		if(data.error) {
			Pins.error(data.error);
		} else if(data.data) {
			window.location = data.data.href;
		}
	}, 'json');
	return false;
}

function deleteFriend(id) {
	$('#user_fr_'+id+'<?php echo ($this->is_edit?'-edit':'');?>').remove();
	$('#hidden_user_fr_'+id+'<?php echo ($this->is_edit?'-edit':'');?>').remove();
}


$(document).ready(function(){
    /*
	$(".selectBox.selectBox-dropdown").bind('click',function(event){
		$('ul.hidden').hide();
		event.preventDefault();
		$(".selectBox.selectBox-dropdown").hide();
		$(".selectBox-dropdown-menu.selectBox-options").show();

		$(".master").unbind('click').bind('click',function(event){
			event.preventDefault();

			
			var children  = $(this).find($('ul'));
			if(children.hasClass('opened')){
				children.hide().removeClass('opened');
			
				
			}else{

			$(".hidden").hide();
			var self  = $(this);
			children.addClass('opened');


			if($(children).hasClass('hidden')){
				try
                                {
                                    console.log("OK");
                                }
                                catch(e)
                                {
                                    if (window.console // check for window.console not console
                                        && window.console.log)
                                    {
                                        window.console.log("OK");
                                    }

                                }
				children.show();
				children.find('li a').click(function(event){
						event.preventDefault();
						appendElementInMain($(this));
						$(".hidden").hide();
				});
			}else{
				
				appendElementInMain(self.find($('a')));
				
			}

			}
		});
	

		function appendElementInMain(element){
			$(".selectBox-dropdown-menu.selectBox-options").hide();
			$(".selectBox.selectBox-dropdown").show();
			$(".selectBox-label").text(element.text());
			$("#catId").val(element.data("id"));
			
			}

		
	});

	$("#selectBox-Category1").bind('click',function(event){
		$('ul.hidden').hide();
		event.preventDefault();
		$("#selectBox-Category1").hide();
		$("#selectBox-dropdown-menu-Category1").show();

		$(".master").unbind('click').bind('click',function(event){
			event.preventDefault();

			
			var children  = $(this).find($('ul'));
			if(children.hasClass('opened')){
				children.hide().removeClass('opened');
			
				
			}else{

			$(".hidden").hide();
			var self  = $(this);
			children.addClass('opened');


			if($(children).hasClass('hidden')){
				try
                                {
                                    console.log("OK");
                                }
                                catch(e)
                                {
                                    if (window.console // check for window.console not console
                                        && window.console.log)
                                    {
                                        window.console.log("OK");
                                    }

                                }
				children.show();
				children.find('li a').click(function(event){
						event.preventDefault();
						appendElementInMain($(this));
						$(".hidden").hide();
				});
			}else{
				
				appendElementInMain(self.find($('a')));
				
			}

			}
		});
	

		function appendElementInMain(element){
			$("#selectBox-dropdown-menu-Category1").hide();
			$("#selectBox-Category1").show();
			$("#selectBox-label-Category1").text(element.text());
			$("#catId1").val(element.data("id"));
			
			}
	});

	$("#selectBox-Category2").bind('click',function(event){
		$('ul.hidden').hide();
		event.preventDefault();
		$("#selectBox-Category2").hide();
		$("#selectBox-dropdown-menu-Category2").show();

		$(".master").unbind('click').bind('click',function(event){
			event.preventDefault();

			
			var children  = $(this).find($('ul'));
			if(children.hasClass('opened')){
				children.hide().removeClass('opened');
			
				
			}else{

			$(".hidden").hide();
			var self  = $(this);
			children.addClass('opened');


			if($(children).hasClass('hidden')){
				try
                                {
                                    console.log("OK");
                                }
                                catch(e)
                                {
                                    if (window.console // check for window.console not console
                                        && window.console.log)
                                    {
                                        window.console.log("OK");
                                    }

                                }
				children.show();
				children.find('li a').click(function(event){
						event.preventDefault();
						appendElementInMain($(this));
						$(".hidden").hide();
				});
			}else{
				
				appendElementInMain(self.find($('a')));
				
			}

			}
		});
	

		function appendElementInMain(element){
			$("#selectBox-dropdown-menu-Category2").hide();
			$("#selectBox-Category2").show();
			$("#selectBox-label-Category2").text(element.text());
			$("#catId2").val(element.data("id"));
			
			}
        });	
        
        $("#selectBox-Category3").bind('click',function(event){
		$('ul.hidden').hide();
		event.preventDefault();
		$("#selectBox-Category3").hide();
		$("#selectBox-dropdown-menu-Category3").show();

		$(".master").unbind('click').bind('click',function(event){
			event.preventDefault();

			
			var children  = $(this).find($('ul'));
			if(children.hasClass('opened')){
				children.hide().removeClass('opened');
			
				
			}else{

			$(".hidden").hide();
			var self  = $(this);
			children.addClass('opened');


			if($(children).hasClass('hidden')){
				try
                                {
                                    console.log("OK");
                                }
                                catch(e)
                                {
                                    if (window.console // check for window.console not console
                                        && window.console.log)
                                    {
                                        window.console.log("OK");
                                    }

                                }
				children.show();
				children.find('li a').click(function(event){
						event.preventDefault();
						appendElementInMain($(this));
						$(".hidden").hide();
				});
			}else{
				
				appendElementInMain(self.find($('a')));
				
			}

			}
		});
	

		function appendElementInMain(element){
			$("#selectBox-dropdown-menu-Category3").hide();
			$("#selectBox-Category3").show();
			$("#selectBox-label-Category3").text(element.text());
			$("#catId3").val(element.data("id"));
			
			}
	});

	$("#selectBox-TypeUser").bind('click',function(event){
		$('ul.hidden').hide();
		event.preventDefault();
		$("#selectBox-TypeUser").hide();
		$("#selectBox-TypeUser-dropdown-menu").show();

		$(".master").unbind('click').bind('click',function(event){
			event.preventDefault();

			
			var children  = $(this).find($('ul'));
			if(children.hasClass('opened')){
				children.hide().removeClass('opened');
			
				
			}else{

			$(".hidden").hide();
			var self  = $(this);
			children.addClass('opened');


			if($(children).hasClass('hidden')){
				try
                                {
                                    console.log("OK");
                                }
                                catch(e)
                                {
                                    if (window.console // check for window.console not console
                                        && window.console.log)
                                    {
                                        window.console.log("OK");
                                    }

                                }
				children.show();
				children.find('li a').click(function(event){
						event.preventDefault();
						appendElementInMain($(this));
						$(".hidden").hide();
				});
			}else{
				
				appendElementInMain(self.find($('a')));
				
			}

			}
		});
	

		function appendElementInMain(element){
			$("#selectBox-TypeUser-dropdown-menu").hide();
			$("#selectBox-TypeUser").show();
			$("#selectBox-label-TypeUser").text(element.text());
			$("#user_typeId").val(element.data("id"));
			
			}

		
	});
        */
	$("#selectBox-dropdown-menu-Category1").bind('mouseleave',function(event){
        		$("#selectBox-Category1").show();
                	$("#selectBox-dropdown-menu-Category1").hide();

        });


	$("#selectBox-Category1").bind('click',function(event){
		$('ul.hidden').hide();
		event.preventDefault();
		$("#selectBox-Category1").hide();
		$("#selectBox-dropdown-menu-Category1").show();
                
                if (!$("#selectBox-Category2").is(":visible"))  
                    {
        		$("#selectBox-Category2").show();
                	$("#selectBox-dropdown-menu-Category2").hide();
                    }
                if (!$("#selectBox-Category3").is(":visible"))  
                    {
        		$("#selectBox-Category3").show();
                	$("#selectBox-dropdown-menu-Category3").hide();
                    }
                if (!$("#selectBox-TypeUser").is(":visible"))  
                    {
                        $("#selectBox-TypeUser").show();
                        $("#selectBox-TypeUser-dropdown-menu").hide();
                    }
                
                /*
		$(".master").bind('click',function(event){
                    alert("o");
                            event.preventDefault();
                            var self  = $(this);
            		appendElementInMain(self.find($('a')));
				
		});
*/
		$(".cats-category1").bind('click',function(event){
                            event.preventDefault();
                            var self  = $(this);
               		appendElementInMain(self);
		});

                
		//$(".master").unbind('click').bind('click',function(event){
                $(".master.cat1").bind('mouseenter',function(event){

                        event.preventDefault();

			
			var children  = $(this).find($('ul'));
			if(children.hasClass('opened')){
				children.hide().removeClass('opened');
			
				
			}else{

			$(".hidden").hide();
			var self  = $(this);
			children.addClass('opened');


			if($(children).hasClass('hidden')){
				try
                                {
                                    console.log("OK");
                                }
                                catch(e)
                                {
                                    if (window.console // check for window.console not console
                                        && window.console.log)
                                    {
                                        window.console.log("OK");
                                    }

                                }
				children.show();
				children.find('li a').click(function(event){
						event.preventDefault();
						appendElementInMain($(this));
						$(".hidden").hide();
				});
			}else{
				
				appendElementInMain(self.find($('a')));
				
			}

			}
		});
	

		function appendElementInMain(element){
			$("#selectBox-dropdown-menu-Category1").hide();
			$("#selectBox-Category1").show();
			$("#selectBox-label-Category1").text(element.text());
			$("#catId1").val(element.data("id"));
			
			}
	});
        
	$("#selectBox-dropdown-menu-Category2").bind('mouseleave',function(event){
        		$("#selectBox-Category2").show();
                	$("#selectBox-dropdown-menu-Category2").hide();

        });
       

	$("#selectBox-Category2").bind('click',function(event){
		$('ul.hidden').hide();
		event.preventDefault();
		$("#selectBox-Category2").hide();
		$("#selectBox-dropdown-menu-Category2").show();
                
                if (!$("#selectBox-Category1").is(":visible"))  
                    {
        		$("#selectBox-Category1").show();
                	$("#selectBox-dropdown-menu-Category1").hide();
                    }
                if (!$("#selectBox-Category3").is(":visible"))  
                    {
        		$("#selectBox-Category3").show();
                	$("#selectBox-dropdown-menu-Category3").hide();
                    }
                if (!$("#selectBox-TypeUser").is(":visible"))  
                    {
                        $("#selectBox-TypeUser").show();
                        $("#selectBox-TypeUser-dropdown-menu").hide();
                    }

		$(".cats-category2").bind('click',function(event){
                            event.preventDefault();
                            var self  = $(this);
               		appendElementInMain(self);
		});

		//$(".master").unbind('click').bind('click',function(event){
                $(".master.cat2").bind('mouseenter',function(event){

			event.preventDefault();

			
			var children  = $(this).find($('ul'));
			if(children.hasClass('opened')){
				children.hide().removeClass('opened');
			
				
			}else{

			$(".hidden").hide();
			var self  = $(this);
			children.addClass('opened');


			if($(children).hasClass('hidden')){
				try
                                {
                                    console.log("OK");
                                }
                                catch(e)
                                {
                                    if (window.console // check for window.console not console
                                        && window.console.log)
                                    {
                                        window.console.log("OK");
                                    }

                                }
				children.show();
				children.find('li a').click(function(event){
						event.preventDefault();
						appendElementInMain($(this));
						$(".hidden").hide();
				});
			}else{
				
				appendElementInMain(self.find($('a')));
				
			}

			}
		});
	

		function appendElementInMain(element){
			$("#selectBox-dropdown-menu-Category2").hide();
			$("#selectBox-Category2").show();
			$("#selectBox-label-Category2").text(element.text());
			$("#catId2").val(element.data("id"));
			
			}
        });	
        
        
	$("#selectBox-dropdown-menu-Category3").bind('mouseleave',function(event){
        		$("#selectBox-Category3").show();
                	$("#selectBox-dropdown-menu-Category3").hide();

        });
        
        
        $("#selectBox-Category3").bind('click',function(event){
		$('ul.hidden').hide();
		event.preventDefault();
		$("#selectBox-Category3").hide();
		$("#selectBox-dropdown-menu-Category3").show();
                
                if (!$("#selectBox-Category2").is(":visible"))  
                    {
        		$("#selectBox-Category2").show();
                	$("#selectBox-dropdown-menu-Category2").hide();
                    }
                if (!$("#selectBox-Category1").is(":visible"))  
                    {
        		$("#selectBox-Category1").show();
                	$("#selectBox-dropdown-menu-Category1").hide();
                    }
                
                if (!$("#selectBox-TypeUser").is(":visible"))  
                    {
                        $("#selectBox-TypeUser").show();
                        $("#selectBox-TypeUser-dropdown-menu").hide();
                    }
                    
                
		$(".cats-category3").bind('click',function(event){
                            event.preventDefault();
                            var self  = $(this);
               		appendElementInMain(self);
		});

		//$(".master").unbind('click').bind('click',function(event){
                $(".master.cat3").bind('mouseenter',function(event){

			event.preventDefault();
                        

			var children  = $(this).find($('ul'));
			if(children.hasClass('opened')){
				children.hide().removeClass('opened');
				
			}else{
                            
                            

                            $(".hidden").hide();
                            var self  = $(this);
                            children.addClass('opened');

                            if($(children).hasClass('hidden')){
                                    try
                                    {
                                        console.log("Tiene hidden");
                                    }
                                    catch(e)
                                    {
                                        if (window.console // check for window.console not console
                                            && window.console.log)
                                        {
                                            window.console.log("Tiene hidden2");
                                        }

                                    }
                                    children.show();
                                    children.find('li a').click(function(event){
                                                    event.preventDefault();
                                                    appendElementInMain($(this));
                                                    $(".hidden").hide();
                                    });
                            }else{

                                    appendElementInMain(self.find($('a')));
                                    console.log("ADD");

                            }

			}
		});

		function appendElementInMain(element){
			$("#selectBox-dropdown-menu-Category3").hide();
			$("#selectBox-Category3").show();
			$("#selectBox-label-Category3").text(element.text());
			$("#catId3").val(element.data("id"));
			
			}
	});

	$("#selectBox-TypeUser-dropdown-menu").bind('mouseleave',function(event){
                        $("#selectBox-TypeUser").show();
                        $("#selectBox-TypeUser-dropdown-menu").hide();

        });

	$("#selectBox-TypeUser").bind('click',function(event){
		$('ul.hidden').hide();
		event.preventDefault();
		$("#selectBox-TypeUser").hide();
		$("#selectBox-TypeUser-dropdown-menu").show();

                if (!$("#selectBox-Category1").is(":visible"))  
                    {
        		$("#selectBox-Category1").show();
                	$("#selectBox-dropdown-menu-Category1").hide();
                    }
                if (!$("#selectBox-Category2").is(":visible"))  
                    {
        		$("#selectBox-Category2").show();
                	$("#selectBox-dropdown-menu-Category2").hide();
                    }
                if (!$("#selectBox-Category3").is(":visible"))  
                    {
        		$("#selectBox-Category3").show();
                	$("#selectBox-dropdown-menu-Category3").hide();
                    }
                    
		$(".cats-typeuser").bind('click',function(event){
                            event.preventDefault();
                            var self  = $(this);
               		appendElementInMain(self);
		});
                    
                    
		//$(".master").unbind('click').bind('click',function(event){
                $(".master.typeuser").bind('mouseenter',function(event){
			event.preventDefault();

			var children  = $(this).find($('ul'));
			if(children.hasClass('opened')){
                            
				children.hide().removeClass('opened');
				
			}else{

                            $(".hidden").hide();
                            var self  = $(this);
                            children.addClass('opened');

                            if($(children).hasClass('hidden')){
                                    try
                                    {
                                        console.log("OK");
                                    }
                                    catch(e)
                                    {
                                        if (window.console // check for window.console not console
                                            && window.console.log)
                                        {
                                            window.console.log("OK");
                                        }

                                    }
                                    children.show();
                                    children.find('li a').click(function(event){
                                                    event.preventDefault();
                                                    appendElementInMain($(this));
                                                    $(".hidden").hide();
                                    });
                            }else{
        //console.log("ADD");
                                    appendElementInMain(self.find($('a')));

                            }

			}
		});
                
		function appendElementInMain(element){
			$("#selectBox-TypeUser-dropdown-menu").hide();
			$("#selectBox-TypeUser").show();
			$("#selectBox-label-TypeUser").text(element.text());
			$("#user_typeId").val(element.data("id"));
			
			}


		
	});

          
        
        $(".morelocations").bind('click',function(event){
		event.preventDefault();
                if ($("#latAux").val() != "")
                {
                    var contador = $(".locationcounter").val();
                    contador++;
                    $(".locationcounter").val(contador) ;
                    $(".locations").html($(".locations").html() + "<p class='input'><label></label><span class='field'><input type='text' value='" + $("#searchTextField2").val() + "' id='location" + contador + "' name='location" + contador + "'></span></p>");
                    $(".locations").html($(".locations").html() + "<input type='hidden' name='lat" + contador + "' class='lat" + contador + "' id='lat" + contador + "' value='" + $("#latAux").val() + "' />");
                    $(".locations").html($(".locations").html() + "<input type='hidden' name='len" + contador + "' class='len" + contador + "' id='len" + contador + "' value='" + $("#lenAux").val() + "' />");
                    $("#searchTextField2").val("");
                    $("#latAux").val("");
                    $("#lenAux").val("");
                    }
                //initialize();
        });
        
        $("#searchTextField").bind('focusout',function(event){
            GLoad();
        });
        
        $("#searchTextField").change(function() {
            GLoad();
        });
        
        $(".pac-container").live('click',function(event){
            GLoad();
        });

        $("#searchTextField").blur(function() {
            GLoad();
        });

        $("#searchTextField2").bind('focusout',function(event){
            GLoad();
        });
        
        $("#searchTextField2").change(function() {
            GLoad();
        });

        $("#searchTextField2").blur(function() {
            GLoad();
        });

        
	return;
	
	
});

</script>

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places&language=es"></script>    
    <script>
function initialize() {
  var mapOptions = {
    center: new google.maps.LatLng(-33.8688, 151.2195),
    zoom: 13,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  };
  var map = new google.maps.Map(document.getElementById('map-canvas'),
    mapOptions);

  var input = /** @type {HTMLInputElement} */(document.getElementById('searchTextField'));
  var autocomplete = new google.maps.places.Autocomplete(input);

  autocomplete.bindTo('bounds', map);

  var infowindow = new google.maps.InfoWindow();
  var marker = new google.maps.Marker({
    map: map
  });

   input = /** @type {HTMLInputElement} */(document.getElementById('searchTextField2'));
   autocomplete = new google.maps.places.Autocomplete(input);

  autocomplete.bindTo('bounds', map);

  var infowindow = new google.maps.InfoWindow();
  var marker = new google.maps.Marker({
    map: map
  });


  google.maps.event.addListener(autocomplete, 'place_changed', function() {
    infowindow.close();
    marker.setVisible(false);
    input.className = '';
    var place = autocomplete.getPlace();
    if (!place.geometry) {
      // Inform the user that the place was not found and return.
      input.className = 'notfound';
      return;
    }

    // If the place has a geometry, then present it on a map.
    if (place.geometry.viewport) {
      map.fitBounds(place.geometry.viewport);
    } else {
      map.setCenter(place.geometry.location);
      map.setZoom(17);  // Why 17? Because it looks good.
    }
    marker.setIcon(/** @type {google.maps.Icon} */({
      url: place.icon,
      size: new google.maps.Size(71, 71),
      origin: new google.maps.Point(0, 0),
      anchor: new google.maps.Point(17, 34),
      scaledSize: new google.maps.Size(35, 35)
    }));
    marker.setPosition(place.geometry.location);
    marker.setVisible(true);

    var address = '';
    if (place.address_components) {
      address = [
        (place.address_components[0] && place.address_components[0].short_name || ''),
        (place.address_components[1] && place.address_components[1].short_name || ''),
        (place.address_components[2] && place.address_components[2].short_name || '')
      ].join(' ');
    }

    infowindow.setContent('<div><strong>' + place.name + '</strong><br>' + address);
    infowindow.open(map, marker);
  });

    GLoad();
  // Sets a listener on a radio button to change the filter type on Places
  // Autocomplete.
  function setupClickListener(id, types) {
    var radioButton = document.getElementById(id);
    google.maps.event.addDomListener(radioButton, 'click', function() {
      autocomplete.setTypes(types);
    });
  }

  setupClickListener('changetype-all', []);
  setupClickListener('changetype-establishment', ['establishment']);
  setupClickListener('changetype-geocode', ['geocode']);
}

google.maps.event.addDomListener(window, 'load', initialize);

    </script>

    <!-- AIzaSyD_Dei2f6nMzaMrBwAXFVxjuHnHz-3So4I -->
<script src="http://maps.google.com/maps?file=api&amp;v=3&amp;key=AIzaSyA60eSDixfIlHokj6GbjmqiRUN0GlBOTAM"
      type="text/javascript"></script>
      
<!--script src="http://maps.google.com/maps/api/js?sensor=false" type="text/javascript"></script-->      
    <script type="text/javascript">
   
   /*     
    var locations = [
      ['madriles', 40.4284034, -3.7149525, 1]
    ];      
      */



function GLoad() {




var geocoder;
var map;

                    $(document).ready(function(){                                                   
                var locationPrincipal =$('#searchTextField').val();

         


                var geocoder = new google.maps.Geocoder();
                geocoder.geocode({ 'address': locationPrincipal }, function (results, status) {
                if (status == google.maps.GeocoderStatus.OK) 
                {
                    var lat = results[0].geometry.location.lat().toString().substr(0, 12);
                    var len = results[0].geometry.location.lng().toString().substr(0, 12);
                    $('#lat').val(lat);
                    $('#len').val(len);

                }
                else
                {
                    if (status == "OVER_QUERY_LIMIT")
                    {
            $(document).ready(function(){                                                   
                        //setTimeout(function(){}, 201);
            });                        
                    }
                    else
                    { 
                        console.log('error: ' + status);
                    }
                }

                  pausecomp(201);
              });
              
                var locationPrincipal =$('#searchTextField2').val();

         


                var geocoder = new google.maps.Geocoder();
                geocoder.geocode({ 'address': locationPrincipal }, function (results, status) {
                if (status == google.maps.GeocoderStatus.OK) 
                {
                    var lat = results[0].geometry.location.lat().toString().substr(0, 12);
                    var len = results[0].geometry.location.lng().toString().substr(0, 12);
                    $('#latAux').val(lat);
                    $('#lenAux').val(len);

                }
                else
                {
                    if (status == "OVER_QUERY_LIMIT")
                    {
            $(document).ready(function(){                                                   
                        //setTimeout(function(){}, 201);
            });                        
                    }
                    else
                    { 
                        console.log('error: ' + status);
                    }
                }

                  //pausecomp(201);
              });
              
            });  
            
function pausecomp(ms) {
        ms += new Date().getTime();
        while (new Date() < ms){}
    } 
            
}

    </script>    

<?php echo $this->footer_part; ?>