<?php echo $this->header_part; ?>

<div id="create_new_pin">
	<div id="content-holder">
		<div id="emailpin" style="padding-top: 70px;padding-left: 200px">
			<form action="<?php echo $this->agendaPopup;?>" method="post" style="background-color: white;width: 1135px">
				<div class="hide">
                                    <input type="hidden" name="user_id" id="user_id" value="<?php echo $this->user_id;?>">
				</div>
                                <img style="width: 335px; height: 260px; float: left;padding-left: 10px" src="data/images/equipott.png"  />                            
				<div class="left w335px" style="font-weight: bold;font-size: 1.2em; padding: 10px; width: 415px">
                                        <img style="width: 395px; float: left" src="data/images/volunttarios_h.png"  />
					<p>
                                            <?php if (!$this->user_id) { ?>                    
                                                <div id="conocenos" style="width: 415px;height: 30px"><center><label for="message"><?php echo $this->translate('Para apuntarte como voluntario, necesitas registrarte en amatteur, únete, es gratis');?></label></center></div><br/>
                                            <?php } else { ?>                                                                
                                                <div id="conocenos" style="width: 415px"><center><label for="message"><?php echo $this->translate('Bienvenido a volunttarios, ¿qué deseas hacer?');?></label></center></div><br/>
                                            <?php } ?>                                                                
                                            <div id="conocenos" style="width: 415px;padding-bottom: 10px"><center><a id='videoTrigger' class="" href=''><?php echo $this->translate('Ver vídeo de introducción');?></a></center></div><br>
					</p>
                                        <br/>
                                        <div class="box2" style="height: 125px">
                                            
                                                <span class="selected"><a id="search" href="<?php echo $this->search_url ?>" class="Button RedButton search " style="font-weight: bold;font-size: 1.2em;width: 160px;height: 20px;padding-top: 12px; margin-top:0px;  text-decoration:none;color: white;text-shadow: 0px 1px black;" ><?php echo $this->translate('Buscar Voluntarios');?></a></span>
                                                <?php if ($this->user_id) { ?>                    
                                                <span class="selected"><a id="apuntate" href="<?php echo $this->apuntate_loged_url ?>" class="Button RedButton apuntate " style="float:right; font-weight: bold;font-size: 1.2em;width: 160px;height: 20px;padding-top: 12px; margin-top:0px;  text-decoration:none;color: white;text-shadow: 0px 1px black;" ><?php  if($this->estado) {echo $this->translate('Edita tu disponibilidad');} else {echo $this->translate('Apúntate');}?></a></span>
                                                <?php } else { ?>
                                                <span class="selected"><a id="apuntate" href="<?php echo $this->apuntate_nologed_url ?>"  class="Button RedButton apuntate " style="float:right; font-weight: bold;font-size: 1.2em;width: 160px;height: 20px;padding-top: 12px; margin-top:0px;  text-decoration:none;color: white;text-shadow: 0px 1px black;" ><?php echo $this->translate('Registrate');?></a></span>
                                                <?php } ?>                    
                                        </div>
					<div class="clear"></div>
				</div>
                                <img style="width: 335px;height: 260px;" src="data/images/manostt.png"  />
				<div class="clear"></div>
			</form>
		</div>
	</div>
</div>

<script type='text/javascript'>
    <?php if ($this->user_id) { ?>
        getVideoImage();
    <?php } ?>                    
</script>


<?php $key = str_replace('.','',microtime(true));?>
<script type="text/javascript">
$(document).ready(function(){

/*
	$('#emailpin form').unbind('submit').submit(function(){
		$('#emailpin form .submit input').after('<img src="data/images/loading_2.gif" id="loading_button" />');
		$('#emailpin form .submit input').attr('disabled', true).addClass('disabled');
                var user_id = $('#user_id').val();
                var texto = $('#texto').val();
                  
		$.post('<?php echo $this->from_url;?>', {user_id:user_id, texto:texto}, function(data,status){
			
			$('#loading_button').remove();
                        $.fancybox.close();                        
			
			
                });
		return false;
	});
*/		
});


</script>