<?php //if (!isset($_SESSION['token'])) //<?php if(!JO_Session::get('token')) 
{
    echo $this->header_part; 
}    
?>

<?php ob_start();?>
<script type="text/javascript">
function Modal_show_delete() {
	$("#PinEdit").hide();
	$("#Modal_show_delete").fadeIn();
}
function Modal_hide_delete() {
	$("#Modal_show_delete").hide();
	$("#PinEdit").fadeIn();
}
</script>

<?php $this->placeholder('inhead', ob_get_clean()); ?>



<div id="detail">

	<div id="view-profile">		

		<div class="FixedContainer">

        <div id="PinEditPreview">
        	<div class="imageholder">
	            <a href="<?php echo $this->pin_info['href'];?>">
	            	<img src="<?php echo $this->pin_info['thumb'];?>" alt="" />
	            	<span class="price" <?php echo ($this->pin_info['gift'] ? 'style="display:block;"' : '');?>><?php echo $this->pin_info['price_formated'];?></span>
	            </a>
            </div>
            <p id="postDescription"><?php echo $this->pin_info['description'];?></p>
        </div>

        <form accept-charset="utf-8" method="POST" action="" class="Form StaticForm PinEdit" id="PinEdit">
			
			<div class="hide">
				<input type="hidden" name="price" value="<?php echo $this->pin_info['price_formated'];?>" />
			</div>
			
            <!--<div class="ButtonHeading">
                <h3><?php //echo $this->translate('Edit Pin');?></h3>
            </div>-->

            <ul>
                <li>
                    <label><?php echo $this->translate('Description');?></label>
                    <div class="Right">
                        <div class="editable_shadow pin_edit" id="ta_holder">
                            <textarea class="expand autocomplete_desc" cols="20" id="message" name="description" rows="2"><?php echo $this->pin_info['description'];?></textarea>
                        </div>
                        <span class="CharacterCount colorless hidden">500</span>
                    </div>
                </li>
                <li>
                    <label for="id_link"><?php echo $this->translate('Link');?></label>
                    <div class="Right">
                        <input type="text" id="id_link" value="<?php echo $this->pin_info['from'];?>" name="from"><br />
                        <?php if ($this->pin_info['is_article']) { ?>
                            <input type="checkbox" id="is_article" name="is_article" value="true" checked="checked"><?php echo $this->translate('Image vinculate to an article');?></input>
                        <?php } else {?>
                            <input type="checkbox" id="is_article" name="is_article" value="true"><?php echo $this->translate('Image vinculate to an article');?></input>
                        <?php } ?>
                    </div>
                </li>
                <li class="doubleborder">
                    <label for="id_board"><?php echo $this->translate('Board');?></label>
                    <div class="Right">
                        <select id="board_id" name="board_id">
							<?php foreach($this->boards AS $board) { ?>
							<?php if($this->pin_info['board_id'] == $board['board_id']) { ?>
							<option selected="selected" value="<?php echo $board['board_id'];?>"><?php echo $board['title'];?></option>
							<?php } else {?>
							<option value="<?php echo $board['board_id'];?>"><?php echo $board['title'];?></option>
							<?php } ?>
							<?php } ?>
						</select>
                        
                    </div>
                </li>
            </ul>

            <div class="Submit">
                <p>
                <a onclick="$('#PinEdit').submit(); return false" class="comment_btn white mbtn" href="#">
                        <strong><?php echo $this->translate('Save Pin');?></strong>
                    </a>
                <a onclick="Modal_show_delete(); return false" class="comment_btn white mbtn" id="delete" href="#"><strong><?php echo $this->translate('Delete Pin');?></strong></a>
                    
                </p>
            </div>

        </form>
        <div class="hide" id="Modal_show_delete">
            <div id="modal-delete-board-confirm">
                <p><?php echo $this->translate('Are you sure you want to permanently delete this pin?')?></p>
                <div class="buttons">
                    <a onclick="Modal_hide_delete(); return false" class="comment_btn white mbtn" href="#"><strong><?php echo $this->translate('Cancel');?></strong></a>&nbsp;&nbsp;&nbsp;
                    <a class="comment_btn white mbtn" href="<?php echo $this->pin_delete;?>"><strong><?php echo $this->translate('Delete Pin')?></strong></a>
                </div>
                <div class="clear"></div>
            </div>
        </div>

    </div>
	
	</div>
	<div class="clear"></div>	
</div>

<?php //if (!isset($_SESSION['token'])) //<?php if(!JO_Session::get('token')) 
{
    echo $this->footer_part;
}    
?>
