<?php //if (!isset($_SESSION['token'])) //<?php if(!JO_Session::get('token')) 
{
    echo $this->header_part; 
}    
?>

		<div class="pinboard closeup">
                <div class='pin' data-id='<?php echo $this->pin['pin_id'] ?>'>
                    <!-- Pinner element -->
                    <div class="banner">
                        <table class="pinner">
  
  
  <tbody><tr>
    <td class="pinner_image">
      <a href="<?php echo $this->author['profile'] ?>" ontouchstart="">
        <img src="<?php echo  $this->author['avatar'] ?>" alt="Picture of <?php echo $this->author['fullname'] ?>">
      </a>
    </td>
    <td class="pinner_name">
        <a href="<?php echo $this->author['profile'] ?>" class="name link" ontouchstart="">
           <?php echo $this->author['fullname'] ?>
        </a>
    </td>
    <td class='right'>
						
						<a href='<?php echo $this->pin['onto_href'] ?>' class='board link'>
						
								<?php echo $this->pin['board']; ?>
						</a>
					</td>
  </tr>
</tbody></table>

                        <div class="stitching">
                            <div class="stitch"></div>
                            <div class="stitch white"></div>
                        </div>
                    </div>

                    <a href="http://handsomenclassy.tumblr.com/page/7">
                        <div class="image">
                            <?php if($this->pin['is_video']) { ?>
                                <img src="data/images/VideoIndicator.png" alt="Video" class="video" />
                            <?php } ?>
                            <?php if($this->pin['is_article']){ ?>
                                <img src="data/images/ico_arti.png"  class="article" alt="Articulo" style="display:block;float:right;"  />
                            <?php } ?>
                            <a href='<?php echo $this->pin['from'] ?>' target='_blank' >
                                <!--img  class='notLoadedImg' alt='' data-src='../data/images/white_dim.png' src='<?php //echo 'uploads'.$this->pin['image'];?>' /-->
                                <img  class='notLoadedImg' alt='' src='../data_mobile/images/white_dim.png' data-src='<?php echo $this->pin['popup'];?>' style='width:100%' />
								
                            </a>
                        </div>
                    </a>

                   
                    <span class="pin_description">
                        <?php echo Helper_Pin::descriptionFix($this->pin['description']); ?>
                    </span>

                    <span class="pin_source">
                        
                           <!--  decide wether to type pinned or repinned by checkin for the user_via array. if its empty it is pinned and not  repinned-->
							<?php if($this->pin['user_via'] == ''): ?>
								<?php echo $this->translate('Pinned')." ".$this->author['fullname'] ?> <?php echo sprintf($this->translate('%d %s ago'),$this->pin['date_dif']['value'], $this->translate($this->pin['date_dif']['key']));?>
							
							<!-- if it is not empty it means it is repinned -->
							<?php else: ?>
								<?php echo $this->translate('Repinned')." ".sprintf($this->translate('%d %s ago'),$this->pin['date_dif']['value'], $this->translate($this->pin['date_dif']['key']))." ".$this->translate('via')." ".$this->pin['user_via']['fullname'] ?>
							<?php endif; ?>
					                        
                    </span>
                    <div class='pin_stats'>
						<div class='pin_likes' style='display: block'>
							 <div class='icon'></div>
							 <span>
							 		<?php echo count($this->pin['likes']); ?>
							 </span>
						</div>
						<div class="pin_repins" style="display: block;">
				                    <div class="icon"></div>
				                    <span>
				                        <?php echo count($this->pin['repins']); ?>
				                    </span>
				        </div>
				          
				   
					</div>
                    
                    		<?php if($this->loged): ?>
							<div style='text-align: center;width: 100%;padding-bottom:10px' >
		    				<a class="comment_btn white mbtn" id='commentButton' title="" ontouchstart="commentPin(event)" ><strong><?php echo $this->translate('Comment');?></strong><span></span></a>
		    			    <a href='<?php echo $this->pin['url_like'] ?>' ontouchstart='likePin(event)' class="white mbtn like_btn" data-liked='<?php echo $this->pin['liked'] ?>'> 
		           				<strong>
		           				 	<?php if($this->pin['liked']  == 0)
		           				 		  {
		           				 			echo $this->translate('Like');
		           				 		  }
										  else
										  {
										  	echo $this->translate("Unlike");
										  }
		           				 	?>
		           				</strong>
		           				<span></span>
		    			    </a>
		    			 
		    				<a class="repin_btn white mbtn" href="<?php echo $this->pin['url_repin'] ?>" title="" ontouchstart="repin(event)"><strong><?php echo $this->translate('Repin');?></strong><span></span></a>
                            <?php if($this->pin['edit']){?>
                                <a href='<?php echo  $this->pin['edit'];?>' class='edit_btn white mbtn' title="<?php echo $this->translate('Edit');?>">
                                	<strong><?php echo $this->translate("Edit"); ?></strong>
                                </a>
							<?php }?>
							</div>
							<?php endif; ?>
				                     	
                     	
                    
         
                    <div class='pin_comments <?php if($this->pin['latest_comments'] > 0) echo "filled" ?>' style='display:block'>
                    	<div class='inner'>
						<?php if($this->pin['latest_comments'] > 0): ?>
								<table>
									<tbody>
							<?php foreach($this->pin['latest_comments'] as $comm): ?>
									<tr>
										<td class="closeup_commenter">
											<a class='link' href='<?php echo $comm['user']['username'] ?>'>
												<!--img src='<?php //echo 'uploads'.$comm['user']['avatar']?>'/-->
                                                                                                <img src='<?php echo $comm['user']['avatar']?>'/>
											</a>
										</td>
										<td>
											<p>
												<a class='link' href='<?php echo   $comm['user']['username']?>>'/>
													<?php echo $comm['user']['fullname'] ?>
												</a>
											</p>
											<p>
												<span>
													<?php echo $comm['comment'] ?>
												</span>
											</p> 
										</td>
									</tr>
							<?php endforeach; ?>
									</tbody>
								</table>
						<?php endif; ?>
					</div>
					</div>
                  

					
					 <div class="board">
                        <a class="tappable_link" href="/lbh3/it-will-be-mine-oh-yes/">
                            <div class="tappable">
                              <a class="board_link" href="<?php echo $this->pin['onto_board2']['0']['href'] ?>">
								<div style="width: 80%;">
									<span>
										<?php echo $this->pin['board'] ?>
									</span>
						
                                    <div class="board_images" style="min-height: 30px">
                                        <?php foreach($this->pin['onto_board2'] as $img): ?>
                                            <img src='<?php echo $img['thumb'] ?>'/>
                                        <?php endforeach; ?>		
                                    </div>
								</div>
					 		<div style="float: right;width: 20%;margin-bottom: -20%;">
        			 <img src="../data_mobile/images/arrow.png" height="14px" style="float: right;margin-top: -45px">
    				 </div>
						</a>
	
                     </div>
                        </a>
					</div>
                
                </div> <!-- End Pin-->
         	</div>

<?php //if (!isset($_SESSION['token'])) //<?php if(!JO_Session::get('token')) 
{
    echo $this->footer_part;
}    
?>


