
<?php if($this->getRequest()->getController() == 'index' && $this->getRequest()->getAction() == 'index') : ?>
		
<div class='pin' data-id='<?php echo $this->pin['pin_id'] ?>'>
	
	<table class='pinner'>
			<tbody>
				<tr>
					<td class="pinner_image">
				
						<a href='<?php echo $this->author['profile'] ?>'>
							<img src='<?php echo $this->author['avatar']; ?>' alt='Picture of <?php echo $this->author['fullname'] ?>'/>
						</a>
					</td>
					<td class='pinner_name'>
						<a href='<?php echo $this->author['profile'] ?>' class='name_link'>
							<?php echo $this->author['fullname'] ?>
						</a>
					</td>
					<td class='right'>
						
						<a href='<?php echo $this->pin['onto_href'] ?>' class='board link'>
								
								<?php echo $this->pin['board']; ?>
							
						</a>
					</td>
				</tr>
			</tbody>
	</table>
	<div class='image' style='background:#D9D9D9 !important'>
					<?php if($this->pin['is_video']) { ?>
					<img src="data/images/VideoIndicator.png" alt="Video" class="video" />
					<?php } ?>
		
		<a href='<?php echo $this->pin['from'] ?>' target='_blank' class='pinImg' >
				<img  class='notLoadedImg' alt='' src='../data_mobile/images/white_dim.png' data-src='<?php echo $this->pin['popup'];?>' style='width:100%' />
		</a>
	</div>
	<p class='pin_description'>
		<?php echo Helper_Pin::descriptionFix($this->pin['description']); ?>
	</p>
	<p class='pin_source'>
		<!--  decide wether to type pinned or repinned by checkin for the user_via array. if its empty it is pinned and not  repinned-->
		<?php if($this->pin['user_via'] == ''): ?>
			<?php echo $this->translate('Pinned by')?> <span class='pin_method'><a class='link' href='<?php echo $this->author['profile']?>'> <?php echo $this->author['fullname'] ?> </a></span> <?php echo sprintf($this->translate('%d %s ago'),$this->pin['date_dif']['value'], $this->translate($this->pin['date_dif']['key']));?>
		
		<!-- if it is not empty it means it is repinned -->
		<?php else: ?>
			
			<?php echo $this->translate('Repinned')." ".sprintf($this->translate('%d %s ago'),$this->pin['date_dif']['value'], $this->translate($this->pin['date_dif']['key']))." ".$this->translate('via')." <span class='pin_method'><a class='link' href='".$this->author['profile']."'>".$this->pin['user_via']['fullname']."</a></span>" ?>
		<?php endif; ?>
	</p>
	
		
	<div class='pin_comments' style='display:block'>
		<div class='inner' style='margin: -10px'>
		<?php if($this->pin['comments'] > 0): ?>
		<table>
			<tbody>
				<tr>
					<td class='icon'></td>
						<td class='comment_text'>
							<?php foreach($this->pin['latest_comments'] as $comm): ?>
				
								<p>
									<a class='link' href=''>
										<?php echo $comm['user']['fullname'] ?>
									</a>
									<span>
										<?php echo $comm['comment']; ?>
									</span>
								</p>
					
			   				<?php endforeach; ?>
						</td>
				</tr>
			</tbody>
		</table>
			<?php endif; ?>
		</div>
	</div>

	<div class='pin_stats'>
		
		<div class='pin_likes' style='display: block'>
			
			 <div class='likeIcon <?php if($this->pin['likes'] > 0) echo "icon"?>'></div>
			 <span>
			 	<?php if($this->pin['likes'] > 0): ?>
			 	<?php  echo $this->pin['likes']." ".$this->translate('Likes');  ?>
			 	<?php endif; ?>
			 </span>
			
		</div>
		
		<div class="pin_repins" style="display: block;">
                    <div class="repinIcon <?php if($this->pin['repins'] > 0) echo 'icon'; ?>"></div>
                    <span>
                        <?php 
                        if($this->pin['repins'] > 0){
                       echo $this->pin['repins']." ".$this->translate('Repins'); 
						}
                        ?>
                    </span>
        </div>
          
   
	</div>
			
			<?php if($this->loged): //if($_SESSION['pintastic']['user']['user_id'] !== 0): ?>
							<div style='text-align: center;width: 100%;padding-bottom:10px' >
    				<a class="comment_btn white mbtn" title=""  ><strong><?php echo $this->translate('Comment');?></strong><span></span></a>
    			    <a href='<?php echo $this->pin['url_like'] ?>' class="white mbtn like_btn" data-liked='<?php echo $this->pin['liked'] ?>'> 
           				<strong>
           				 	<?php if($this->pin['liked']  == 0)
           				 		  {
           				 			echo $this->translate('Like');
           				 		  }
								  else
								  {
								  	echo $this->translate("Unlike");
								  }
           				 	?>
           				</strong>
           				<span></span>
    			    </a>
    			 
    				<a class="repin_btn white mbtn" href="<?php echo $this->pin['url_repin'] ?>" title=""><strong>Guardar</strong><span></span></a>
			     </div>
			<?php endif; ?>
	
	</div>



<?php endif; ?>







<?php echo "CONTROLLER " . $this->getRequest()->getController() ?>

<!-- if the controller is users and esto no estaba hecho -->

<?php if(         $this->getRequest()->getController() == 'users'
		  ) : ?>


<div class="box<?php echo $this->history_action;?>" id="<?php echo ($this->history_id ? $this->history_id . '_' : '');?><?php echo $this->pin['pin_id'];?>">

		<?php if($this->pin['vip']) { ?>
		<strong class="vipContainer">
			<strong class="vip"><?php echo $this->translate('VIP');?></strong>
		</strong>
		<?php } ?>
		<div class="preview">
			<div class='pinAuthor'>
					<p class="avatar">
						<a href="<?php echo $this->author['profile'];?>">
							<img src="<?php echo $this->author['avatar'];?>?<?php echo $this->image_no_cache;?>" alt="<?php echo $this->author['fullname'];?>" />
						</a>
					</p>
					
		
					<p class="message">
						<a href="<?php echo $this->author['profile'];?>"><?php echo $this->author['fullname'];?></a> 
						<?php if($this->via) { ?>
						<?php echo $this->translate('via');?> 
						<a href="<?php echo $this->via['profile'];?>"><?php echo $this->via['fullname'];?></a> 
						<?php } ?>
						<?php echo $this->translate('onto');?> 
						<a href="<?php echo $this->pin['onto_href'];?>"><?php echo $this->pin['board'];?></a>
					</p>
					<div class="clear"></div>
			</div>
			<!--  <p class="icons">
			<a href="<?php echo $this->pin['url_repin'];?>" class="repin<?php echo (!$this->loged ? ' login' : ' silverbox');?>" title="<?php echo $this->translate('Repin');?>"><span><?php echo $this->translate('Repin');?></span></a> 
			<?php if($this->pin['edit']) { ?>
			<a href="<?php echo $this->pin['edit'];?>" class="edit login" title="<?php echo $this->translate('Edit');?>"><span><?php echo $this->translate('Edit');?></span></a> 
			<?php } else { ?>
			<a href="<?php echo $this->pin['url_like'];?>" class="like<?php echo (!$this->loged ? ' login' : ($this->pin['liked'] ? ' disabled' : '') );?>" title="<?php echo ($this->pin['liked']?$this->translate('Unlike'):$this->translate('Like'));?>"><span><?php echo ($this->pin['liked']?$this->translate('Unlike'):$this->translate('Like'));?></span></a> 
			<?php } ?>
			<a href="<?php echo $this->pin['url_comment'];?>" class="comment<?php echo (!$this->loged ? ' login' : '');?>" title="<?php echo $this->translate('Comment');?>"><span><?php echo $this->translate('Comment');?></span></a>
			</p>-->
			
			
				<ul class='c_icons_small'>
					<li>
						<a href='<?php echo $this->pin['url_repin'];?>' class='repin <?php echo (!$this->loged ? ' login' : ' silverbox');?>' title="<?php echo $this->translate('Repin');?>">
							<span  class='anim repinIcon'></span>
							<span class='text'><?php echo strtoupper($this->translate('Repin'));?></span>
							<span class='roundedImage'></span>
						</a>
					</li>
					<li>
						<?php if($this->pin['edit']){?>
						<a href='<?php echo  $this->pin['edit'];?>' class='edit login <?php echo (!$this->loged ? ' login' : '');?>' title="<?php echo $this->translate('Edit');?>">
							<span  class='anim editIcon'></span>
							<span class='text'><?php echo strtoupper($this->translate('Edit'));?></span>
							<span class='roundedImage'></span>
						</a>
						<?php }else{?>
						<a href='<?php echo  $this->pin['url_like'];?>' class="like<?php echo (!$this->loged ? ' login' : ($this->pin['liked'] ? ' disabled' : '') );?>"  title="<?php echo ($this->pin['liked']?$this->translate('Unlike'):$this->translate('Like'));?>">
							<span  class='anim likeIcon'></span>
							<span class='text'><?php echo strtoupper($this->pin['liked']?$this->translate('Unlike'):$this->translate('Like'));?></span>
							<span class='roundedImage'></span>
						</a>
						<?php }?>
					</li>
					<li>
						<a href='<?php echo  $this->pin['comment'];?>' class="comment<?php echo (!$this->loged ? ' login' : '');?>" title="<?php echo $this->translate('Comment');?>">
							<span  class='anim commentIcon'></span>
							<span class='text'><?php echo strtoupper($this->translate('Comment'));?></span>
							<span class='roundedImage'></span>
						</a>
					</li>
				</ul>
		
			<?php if($this->set_activity_title) {?>
			<h4 class="title">
				<span class="icon-holder"></span>
				<?php echo $this->set_activity_title;?>
				<span><?php echo sprintf($this->translate('%d %s ago'), $this->date_dif['value'], $this->translate($this->date_dif['key']));?></span>
			</h4>
			<?php } ?>
			

                    
			<p class="thumb">
				<a href="<?php echo $this->pin['href'];?>">
					<?php if($this->pin['gift']) { ?>
					<strong class="PriceContainer">
						<strong class="price"><?php echo $this->pin['price_formated'];?></strong>
					</strong>
					<?php } ?>
					<?php if($this->pin['is_video']) { ?>
					<img src="data/images/VideoIndicator.png" alt="Video" class="video" />
					<?php } ?>
                                        <?php if($this->pin['is_article']) { ?>
                                          <img src="data/images/article.png"  class="article" alt="Articulo" style="display:block;float:right;" width="30px" height="30px" />
                                        <?php } ?>
					<img style="margin-left:<?php echo ( (194-$this->pin['thumb_width']) / 2 );?>px;width:<?php echo $this->pin['thumb_width'];?>px;height:<?php echo $this->pin['thumb_height'];?>px;" width="<?php echo $this->pin['thumb_width'];?>" height="<?php echo $this->pin['thumb_height'];?>" data-original="<?php echo $this->pin['thumb'];?>" src="data/images/grey.gif" alt="Image" />
				</a>
			</p>
			<h4><?php   echo Helper_Pin::descriptionFix($this->pin['description']);?></h4>
			<p class="stats">
				<span class="likes">
				<?php if($this->pin['likes']) { ?>
					<?php echo sprintf( $this->translate('%d like' . ($this->pin['likes'] == 1 ? '' : 's')), $this->pin['likes'] );?> 
				<?php } ?>
				</span> &nbsp; 
				<span class="comments">
				<?php if($this->pin['comments']) { ?>
					<?php echo sprintf( $this->translate('%d comment' . ($this->pin['comments'] == 1 ? '' : 's')), $this->pin['comments'] );?>
				<?php } ?>
				</span> &nbsp; 
				<span class="repins">
				<?php if($this->pin['repins']) { ?>
					<?php echo sprintf( $this->translate('%d repin' . ($this->pin['repins'] == 1 ? '' : 's')), $this->pin['repins'] );?>
				<?php } ?>
				</span>
			</p>
		</div>
		<div class="comments">
			<ul>
				<!-- <li class="creator-pin">
				
				</li> -->
				<?php if($this->pin['latest_comments']) { ?>
				<?php foreach($this->pin['latest_comments'] AS $crow => $comment) { ?>
				<li<?php echo ($crow == ( count($this->pin['latest_comments']) - 1) ? ' class="last"' : '' );?>>
					<p class="avatar"><a href="<?php echo $comment['user']['profile'];?>"><img src="<?php echo $comment['user']['avatar'];?>?<?php echo $this->image_no_cache;?>" alt="<?php echo $comment['user']['fullname'];?>" /></a></p>
					<p class="message"><a href="<?php echo $comment['user']['profile'];?>"><?php echo $comment['user']['fullname'];?></a> <?php echo $comment['comment'];?></p>
					<div class="clear"></div>
					<?php if($comment['delete']) { ?>
					<a href="<?php echo $comment['delete'];?>" class="delete" title="<?php echo $this->translate('Delete Comment');?>">X</a>
					<?php } ?>
				</li>
				<?php } ?>
				<?php } ?>
				
				<?php if($this->profile_self) { ?>
				<li class="addComment">
					<p class="avatar">
						<a href="<?php echo $this->profile_self;?>">
							<img src="<?php echo $this->author_self;?>?<?php echo $this->image_no_cache;?>" alt="" />
						</a>
					</p>
					<form action="<?php echo $this->pin['url_comment'];?>" method="post" class="comment-form">
						<textarea name="write_comment"></textarea>
						<input class="comment-button" type="submit" value="<?php echo $this->translate('comment');?>" />
						<div class="clear"></div>
					</form>
				</li>
				<?php } ?>
				
			</ul>
			<div class="clear"></div>
			<?php if($this->pin['comments'] > 5) { ?>
			<p class="all"><a href="<?php echo $this->pin['href'];?>"><?php echo sprintf($this->translate('All %d comments...'), $this->pin['comments']);?></a></p>	
			<?php } ?>
		</div>

</div>

<?php endif; ?>

<!-- if the controller is catgegory and action is index -->

<?php if( $this->getRequest()->getController() == 'category' || 
	      $this->getRequest()->getController() == 'popular'  ||
		  $this->getRequest()->getController() == 'gifts' 	 ||
		  $this->getRequest()->getController() == 'all' 	 ||
		  $this->getRequest()->getController() == 'boards'   ||
                  $this->getRequest()->getController() == 'users'
		 
		  ) : ?>



<div class='pin' data-id='<?php echo $this->pin['pin_id'] ?>'>
	
	<table class='pinner'>
			<tbody>
				<tr>
					<td class="pinner_image">
					<!--	<pre>
						<?php 
						//var_dump($this->pin); 
						?>
					</pre> --> 
						<a href='<?php echo $this->author['profile'] ?>'>
							<img src='<?php echo $this->author['avatar']; ?>' alt='Picture of <?php echo $this->author['fullname'] ?>'/>
						</a>
					</td>
					<td class='pinner_name'>
						<a href='<?php echo $this->author['profile'] ?>' class='name_link'>
							<?php echo $this->author['fullname'] ?>
						</a>
					</td>
					<td class='right'>
						
						<a href='<?php echo $this->pin['onto_href'] ?>' class='board link' style='overflow: hidden'>
						
								<?php echo $this->pin['board']; ?>
						</a>
					</td>
				</tr>
			</tbody>
	</table>
	<div class='image' style='background:#D9D9D9 !important'>
			
		<a href='<?php echo $this->pin['from'] ?>' target='_blank' >
			<img  class='notLoadedImg' alt='' src='../data_mobile/images/white_dim.png' data-src='<?php echo $this->pin['popup'];?>' style='width:100%' />
		</a>

	</div>
	<p class='pin_description'>
		<?php echo Helper_Pin::descriptionFix($this->pin['description']); ?>
	</p>
	<p class='pin_source'>
		<!--  decide wether to type pinned or repinned by checkin for the user_via array. if its empty it is pinned and not  repinned-->
		<?php if($this->pin['user_via'] == ''): ?>
			<?php echo $this->translate('Pinned by')?> <span class='pin_method'><a class='link' href='<?php echo $this->author['profile']?>'> <?php echo $this->author['fullname'] ?> </a></span> <?php echo sprintf($this->translate('%d %s ago'),$this->pin['date_dif']['value'], $this->translate($this->pin['date_dif']['key']));?>
		
		<!-- if it is not empty it means it is repinned -->
		<?php else: ?>
			
			<?php echo $this->translate('Repinned')." ".sprintf($this->translate('%d %s ago'),$this->pin['date_dif']['value'], $this->translate($this->pin['date_dif']['key']))." ".$this->translate('via')." <span class='pin_method'><a class='link' href='".$this->author['profile']."'>".$this->pin['user_via']['fullname']."</a></span>" ?>
		<?php endif; ?>
	</p>
	
		
	<div class='pin_comments' style='display:block'>
		<?php if($this->pin['comments'] > 0): ?>
		<table>
			<tbody>
				<tr>
					<td class='icon'></td>
						<td class='comment_text'>
							<?php foreach($this->pin['latest_comments'] as $comm): ?>
				
								<p>
									<a class='link' href=''>
										<?php echo $comm['user']['fullname'] ?>
									</a>
									<span>
										<?php echo $comm['comment']; ?>
									</span>
								</p>
					
			   				<?php endforeach; ?>
						</td>
				</tr>
			</tbody>
		</table>
			<?php endif; ?>
	</div>

	<div class='pin_stats'>
		
		<div class='pin_likes' style='display: block'>
			
			 <div class='likeIcon <?php if($this->pin['likes'] > 0) echo "icon"?>'></div>
			 <span>
			 	<?php if($this->pin['likes'] > 0): ?>
			 	<?php echo $this->pin['likes']." ".$this->translate("Likes"); ?>
			 	<?php endif; ?>
			 </span>
			
		</div>
		
		<div class="pin_repins" style="display: block;">
                    <div class="repinIcon <?php if($this->pin['repins'] > 0) echo 'icon'; ?>"></div>
                    <span>
                        <?php 
                        if($this->pin['repins'] > 0){
                        echo $this->pin['repins']." ".$this->translate('Repins'); 
						}
                        ?>
                    </span>
        </div>
          
   
	</div>
			
			<?php if($this->loged)://if($_SESSION['pintastic']['user']['user_id'] !== 0): ?>
							<div style='text-align: center;width: 100%;padding-bottom:10px' >
    				<a class="comment_btn white mbtn"  title="" ontouchstart="commentPin(event)" ><strong><?php echo $this->translate('Comment');?></strong><span></span></a>
    			    <a href='<?php echo $this->pin['url_like'] ?>'  ontouchstart='likePin(event)' class="white mbtn like_btn" data-liked='<?php echo $this->pin['liked'] ?>'> 
           				<strong>
           				 	<?php if($this->pin['liked']  == 0)
           				 		  {
           				 			echo $this->translate('Like');
           				 		  }
								  else
								  {
								  	echo $this->translate("Unlike");
								  }
           				 	?>
           				</strong>
           				<span></span>
    			    </a>
    			 
    				<a class="repin_btn white mbtn" href="<?php echo $this->pin['url_repin'] ?>" title="" ontouchstart="repin(event)"><strong>Repin</strong><span></span></a>
			     </div>
			<?php endif; ?>
	
	</div>
<?php endif; ?>



<!-- if the controller is user and action is pins -->

<?php if($this->getRequest()->getAction() == 'pins' ||
	   $this->getRequest()->getController() == 'search' 

) : ?>
	
	
	<div class='pin'>
	
		<a href='/pin/<?php echo $this->pin['pin_id']; ?>'>
			<img alt='' src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==" data-original='<?php echo $this->pin['thumb'];?>' width='93' height='<?php echo round( 93 / ( $this->pin['thumb_width']/$this->pin['thumb_height'] ) );?>'/>
		
		</a>
	

	</div>
<?php endif; ?>

