<div id="wrapper">
	<div id="container">
		<div id="content" style="width: auto;">
		
			<div class="news-full">
				<h4><a href="<?php echo $this->full_url;?>" onclick="target='_top'"><?php echo $this->page['title']; ?></a></h4>
				
				<div class="textbox">
					<?php echo $this->page['description']; ?>
				</div>
				<div class="clear"></div>
			</div>
			
			<div class="clear"></div>
			
		</div>
		<div class="clear"></div>
	</div>
</div>