<?php if (!isset($_SESSION['token'])) //<?php if(!JO_Session::get('token')) 
{
    echo $this->header_part; 
}    
?>


<div id="detail">

		<div class="no_account_page">
	        <a href="./">
	        	<img src="data/images/error_Downtime_icon.png" class="fade">
	        </a>
	        <h1 class="fade"><?php echo $this->translate('Sorry!');?></h1>
	        <?php echo $this->translate('Sorry, your Twitter account is not associated with any account.');?>
	        <br /><br />
	        <?php echo $this->translate('If you have an account, try logging in with your email and password. Or, please request an invite to create an account.');?>
	        <?php if($this->page_login_trouble) { ?>
	        <br /><br />
	        <?php echo $this->translate('Having trouble?');?> <a href="<?php echo $this->page_login_trouble['href'];?>"><?php echo $this->translate('Read more here.');?></a>
	    	<?php } ?>
	    </div>

</div>
    
<?php if (!isset($_SESSION['token'])) //<?php if(!JO_Session::get('token')) 
{
    echo $this->footer_part;
}    
?>
