<?php //if (!isset($_SESSION['token'])) //<?php if(!JO_Session::get('token')) 
{
    echo $this->header_part; 
}    

$masonry = true;
?>
<script type="text/javascript" src='data_mobile/js/infscroll.js?<?php echo rand(1,999); ?>'></script>
<script type="text/javascript" src='data_mobile/js/jquery.masonry.min.js'></script>
<script type="text/javascript">	
		$(document).ready(function(){
			if ($('#container').width()>768)
			{
				$('#container').masonry({
					itemSelector : '.pin'
				  });
				  
				$(window).bind('deviceorientation', function() { $('#container').masonry('reload'); });
				$(window).bind('MozOrientation', function() { $('#container').masonry('reload'); });
				$(window).bind('load', function() { $('#container').masonry('reload'); }); 
			}
		});	 
		lazyLoad();
		infScroll();
</script>
<!-- here we put the variables for the users pinboards -->



	<div id="container">
		

		<?php echo $this->pins;?>
		
		
		<div class="clear"></div>
	</div>
	
<?php //if (!isset($_SESSION['token'])) //<?php if(!JO_Session::get('token')) 
{
    echo $this->footer_part;
}    
?>
